import React, { useEffect, useState } from 'react';
import { learningRequest as request, exportLearningCsv } from '../services/lifelong';
import { useSubscription } from '../hooks/useSubscription';
import './lifelong.css';

export default function CompetencyManagement({ session }) {
  const { hasAdminAccess } = useSubscription(session);
  const [members,setMembers]=useState([]); const [assignments,setAssignments]=useState([]); const [items,setItems]=useState([]); const [institutions,setInstitutions]=useState([]);
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
  const [assign,setAssign]=useState({institution:'',user:'',item:'',due:''}); const [member,setMember]=useState({institution:'',email:'',role:'staff'});
  const [evidence,setEvidence]=useState({}); const [feedback,setFeedback]=useState({}); const [expiry,setExpiry]=useState({});
  async function load() {
    const [m,a,i]=await Promise.all([request(db=>db.from('competency_memberships').select('*')),request(db=>db.from('competency_assignments').select('*').order('due_on')),request(db=>db.from('learning_items').select('id,title').eq('kind','competency').eq('status','published'))]);setMembers(m);setAssignments(a);setItems(i);
    if(hasAdminAccess) setInstitutions(await request(db=>db.from('institution_accounts').select('id,name')));
  }
  useEffect(()=>{load().catch(e=>setError(e.message));},[hasAdminAccess]);
  async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice('Saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  const canAssess=(id)=>hasAdminAccess||members.some(m=>m.user_id===session.user.id&&m.institution_id===id&&['manager','assessor'].includes(m.role));
  const orgs=hasAdminAccess?institutions:[...new Set(members.filter(m=>m.user_id===session.user.id&&canAssess(m.institution_id)).map(m=>m.institution_id))].map(id=>({id,name:`Institution ${id.slice(0,8)}`}));
  const today=new Date().toISOString().slice(0,10);
  return <section className="content-band lifelong"><h2>Hospital Competency Management</h2><p>Submit evidence, receive assessor feedback and track reassessment dates. Do not include patient-identifying information.</p>
    {error&&<p className="lf-error" role="alert">{error}</p>}{notice&&<p role="status" className="lf-notice">{notice}</p>}
    <div className="lf-stats"><article><span>Assignments</span><strong>{assignments.length}</strong></article><article><span>Awaiting assessment</span><strong>{assignments.filter(a=>a.status==='submitted').length}</strong></article><article><span>Current competencies</span><strong>{assignments.filter(a=>a.status==='competent'&&a.expires_on>=today).length}</strong></article><article><span>Overdue / expired</span><strong>{assignments.filter(a=>a.status==='competent'?a.expires_on<today:a.due_on<today).length}</strong></article></div>
    {!!orgs.length&&<form className="lf-panel lf-form" onSubmit={e=>{e.preventDefault();act(()=>request(db=>db.rpc('assign_competency',{p_institution:assign.institution,p_user:assign.user,p_item:assign.item,p_due:assign.due})));}}><h3>Assign a competency</h3><label>Institution<select required value={assign.institution} onChange={e=>setAssign({...assign,institution:e.target.value,user:''})}><option value="">Select institution</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Staff member<select required value={assign.user} onChange={e=>setAssign({...assign,user:e.target.value})}><option value="">Select staff member</option>{members.filter(m=>m.institution_id===assign.institution).map(m=><option key={m.user_id} value={m.user_id}>{m.display_name}</option>)}</select></label><label>Competency<select required value={assign.item} onChange={e=>setAssign({...assign,item:e.target.value})}><option value="">Select competency</option>{items.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label><label>Due date<input required type="date" min={today} value={assign.due} onChange={e=>setAssign({...assign,due:e.target.value})}/></label><button disabled={busy} className="primary-btn">Assign</button></form>}
    <button className="ghost-btn" onClick={()=>exportLearningCsv('competency-report.csv',[['Staff','Competency','Status','Due','Expiry','Assessor feedback'],...assignments.map(a=>[members.find(m=>m.user_id===a.user_id&&m.institution_id===a.institution_id)?.display_name||a.user_id,a.title,a.status,a.due_on,a.expires_on,a.feedback])])}>Export visible competency report</button>
    {!assignments.length&&<p className="lf-panel">No competencies assigned yet.</p>}
    {assignments.map(a=><article className="lf-panel" key={a.id}><span className="eyebrow">{a.status.replaceAll('_',' ')} · Due {a.due_on}</span><h3>{a.title}</h3><p>{members.find(m=>m.user_id===a.user_id&&m.institution_id===a.institution_id)?.display_name||'Staff member'} · Content version {a.item_version}</p><details><summary>Assessment criteria</summary><p className="lf-prose">{a.criteria_snapshot}</p></details><p className="lf-prose">Evidence: {a.evidence||'Not submitted'}</p>{a.feedback&&<p className="lf-notice">Assessor feedback: {a.feedback}<br/>Reassessment: {a.expires_on||'Not yet competent'}</p>}
      {a.user_id===session.user.id&&a.status!=='competent'&&<form onSubmit={e=>{e.preventDefault();act(()=>request(db=>db.rpc('submit_competency_evidence',{p_assignment:a.id,p_evidence:evidence[a.id]||a.evidence})));}}><label>Your evidence<textarea minLength={10} maxLength={12000} required value={evidence[a.id]??a.evidence} onChange={e=>setEvidence({...evidence,[a.id]:e.target.value})}/></label><button disabled={busy} className="primary-btn">Submit for assessment</button></form>}
      {canAssess(a.institution_id)&&a.user_id!==session.user.id&&a.status==='submitted'&&<div><label>Assessment findings<textarea value={feedback[a.id]||''} onChange={e=>setFeedback({...feedback,[a.id]:e.target.value})}/></label><label>Reassessment date<input type="date" min={today} value={expiry[a.id]||''} onChange={e=>setExpiry({...expiry,[a.id]:e.target.value})}/></label><div className="lf-toolbar">{[true,false].map(pass=><button key={String(pass)} disabled={busy} className="primary-btn" onClick={()=>act(()=>request(db=>db.rpc('assess_competency',{p_assignment:a.id,p_pass:pass,p_feedback:feedback[a.id]||'',p_expiry:expiry[a.id]||null})))}>{pass?'Sign off as competent':'Needs development'}</button>)}</div></div>}
    </article>)}
    {hasAdminAccess&&<form className="lf-panel lf-form" onSubmit={e=>{e.preventDefault();act(()=>request(db=>db.rpc('add_competency_member',{p_institution:member.institution,p_email:member.email,p_role:member.role})));}}><h3>Manage institution membership</h3><label>Institution<select required value={member.institution} onChange={e=>setMember({...member,institution:e.target.value})}><option value="">Select institution</option>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>Registered email<input required type="email" value={member.email} onChange={e=>setMember({...member,email:e.target.value})}/></label><label>Role<select value={member.role} onChange={e=>setMember({...member,role:e.target.value})}>{['staff','assessor','manager'].map(r=><option key={r}>{r}</option>)}</select></label><button disabled={busy} className="primary-btn">Save membership</button></form>}
  </section>;
}
