import React, { useEffect, useState } from 'react';
import { learningRequest as request } from '../services/lifelong';
import './lifelong.css';

export default function ProfessionalCV({ session }) {
  const [draft,setDraft]=useState({name:session.user.user_metadata?.full_name||'',contact:'',summary:'',experience:'',education:'',skills:''});
  const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [busy,setBusy]=useState(false);
  useEffect(()=>{request(db=>db.from('learning_profiles').select('cv').eq('user_id',session.user.id).maybeSingle()).then(p=>{if(p?.cv)setDraft(d=>({...d,...p.cv}));}).catch(e=>setError(e.message));},[session.user.id]);
  async function save(){setBusy(true);setSaved(false);setError('');try{await request(db=>db.from('learning_profiles').upsert({user_id:session.user.id,cv:draft}));setSaved(true);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section className="content-band lifelong"><h2>Professional CV</h2><p>Create a CV from your own experience and education. Review it before sharing.</p>{error&&<p role="alert" className="lf-error">{error}</p>}{saved&&<p role="status">CV saved.</p>}<form className="lf-panel lf-form" onSubmit={e=>{e.preventDefault();save();}}>{Object.entries({name:'Full name',contact:'Contact details',summary:'Professional summary',experience:'Work experience',education:'Education and qualifications',skills:'Skills and certifications'}).map(([key,label])=><label key={key}>{label}<textarea value={draft[key]} onChange={e=>{setDraft({...draft,[key]:e.target.value});setSaved(false);}}/></label>)}<button disabled={busy} className="primary-btn">Save CV</button><button type="button" className="ghost-btn" onClick={()=>window.print()}>Print / Save PDF</button></form><article id="professional-cv-print" className="lf-panel"><h1>{draft.name}</h1><p className="lf-prose">{draft.contact}</p>{Object.entries({summary:'Profile',experience:'Experience',education:'Education',skills:'Skills and certifications'}).filter(([key])=>draft[key]).map(([key,label])=><section key={key}><h2>{label}</h2><p className="lf-prose">{draft[key]}</p></section>)}</article><style>{`@media print { body * { visibility:hidden; } #professional-cv-print, #professional-cv-print * { visibility:visible; } #professional-cv-print { position:absolute; left:0; top:0; width:100%; margin:0; border:0; } }`}</style></section>;
}
