-- Safe seed Yingoh NCLEX question bank, part 4.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with cirrhosis is confused and has asterixis (flapping tremor). Which diet modification is indicated?', '[{"id":"a","text":"High-protein diet to support liver regeneration"},{"id":"b","text":"Low-protein diet to reduce ammonia production"},{"id":"c","text":"High-fat diet to provide dense calories"},{"id":"d","text":"High-sodium diet to combat ascites"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Hepatic encephalopathy: confusion and asterixis result from elevated ammonia from protein metabolism. Limit dietary protein to reduce ammonia production. Lactulose and rifaximin are also used. Sodium restriction (not increase) manages ascites.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with cirrhosis is confused and has asterixis (flapping tremor). Which diet modification is indicated?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A patient with acute pancreatitis is admitted. Which nursing interventions are appropriate? (Select all that apply)', '[{"id":"a","text":"NPO status initially to rest the pancreas"},{"id":"b","text":"IV fluid resuscitation"},{"id":"c","text":"Administer proton pump inhibitors"},{"id":"d","text":"Semi-Fowler''s or fetal position for comfort"},{"id":"e","text":"Encourage high-fat oral nutrition to restore weight"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Acute pancreatitis: NPO rests the pancreas, IV fluids prevent hypovolemia and necrosis, positioning (fetal or forward lean) relieves pain. PPIs are used for peptic ulcer disease not pancreatitis. High-fat foods worsen pancreatitis by stimulating pancreatic enzymes.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with acute pancreatitis is admitted. Which nursing interventions are appropriate? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with a spinal cord injury at T4 suddenly develops a pounding headache, diaphoresis above the injury, and blood pressure of 218/114. What condition does the nurse suspect?', '[{"id":"a","text":"Hypertensive urgency from fluid overload"},{"id":"b","text":"Autonomic dysreflexia"},{"id":"c","text":"Neurogenic shock"},{"id":"d","text":"Spinal shock"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Autonomic dysreflexia is a life-threatening emergency in SCI at T6 or above. Triggers (full bladder, pressure ulcer) cause massive sympathetic response: severe hypertension, pounding headache, diaphoresis above lesion, bradycardia. Sit patient upright and remove the trigger immediately.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with a spinal cord injury at T4 suddenly develops a pounding headache, diaphoresis above the injury, and blood pressure of 218/114. What condition does the nurse suspect?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with deep vein thrombosis has a warm, swollen, painful right calf. Which action should the nurse avoid?', '[{"id":"a","text":"Elevating the affected extremity"},{"id":"b","text":"Massaging the affected leg to improve circulation"},{"id":"c","text":"Monitoring for signs of pulmonary embolism"},{"id":"d","text":"Administering anticoagulant therapy as ordered"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'NEVER massage a limb with suspected DVT — this can dislodge the clot, causing a pulmonary embolism. Elevation, anticoagulation, and monitoring for PE (dyspnea, chest pain, SpO2 drop) are appropriate interventions.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with deep vein thrombosis has a warm, swollen, painful right calf. Which action should the nurse avoid?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with a closed head injury has a GCS score of 8. What does this indicate?', '[{"id":"a","text":"Mild traumatic brain injury"},{"id":"b","text":"Normal neurological status"},{"id":"c","text":"Severe traumatic brain injury"},{"id":"d","text":"Moderate traumatic brain injury requiring monitoring"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Glasgow Coma Scale: 13–15 = mild TBI, 9–12 = moderate, ≤8 = severe TBI. GCS ≤8 typically indicates need for airway protection (intubation). The GCS evaluates eye opening, verbal, and motor responses (max 15, min 3).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with a closed head injury has a GCS score of 8. What does this indicate?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A patient is diagnosed with syndrome of inappropriate antidiuretic hormone (SIADH). Which findings does the nurse expect? (Select all that apply)', '[{"id":"a","text":"Serum sodium of 118 mEq/L"},{"id":"b","text":"Decreased urine output with concentrated urine"},{"id":"c","text":"Peripheral edema and hypertension"},{"id":"d","text":"Confusion and headache"},{"id":"e","text":"Increased serum osmolality"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'SIADH: excess ADH causes water retention → dilutional hyponatremia (low Na+), concentrated urine (high urine osmolality), decreased serum osmolality. CNS symptoms (confusion, headache, seizures) from cerebral edema. No peripheral edema because fluid stays intracellular.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is diagnosed with syndrome of inappropriate antidiuretic hormone (SIADH). Which findings does the nurse expect? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient post-thyroidectomy reports tingling around the mouth and carpopedal spasms. Which action is the nurse''s priority?', '[{"id":"a","text":"Administer IV calcium gluconate as ordered"},{"id":"b","text":"Apply oxygen via nasal cannula"},{"id":"c","text":"Draw a serum magnesium level"},{"id":"d","text":"Encourage the patient to breathe into a paper bag"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Post-thyroidectomy hypocalcemia occurs when the parathyroid glands are inadvertently removed or damaged (parathyroid glands regulate calcium). Tingling and carpopedal spasms (positive Trousseau''s sign) indicate hypocalcemia — treat with IV calcium gluconate.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient post-thyroidectomy reports tingling around the mouth and carpopedal spasms. Which action is the nurse''s priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A nurse is caring for a patient with a chest tube. The fluid in the water-seal chamber is fluctuating (tidaling) with respirations. What does this indicate?', '[{"id":"a","text":"A clot in the chest tube"},{"id":"b","text":"The system is functioning properly"},{"id":"c","text":"The lung has fully re-expanded"},{"id":"d","text":"Subcutaneous emphysema is developing"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Tidaling (fluid rising with inspiration, falling with expiration) in the water-seal chamber is NORMAL and indicates the chest tube is patent and functioning. Tidaling stops when the lung fully re-expands or if the tube is kinked/blocked.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with a chest tube. The fluid in the water-seal chamber is fluctuating (tidaling) with respirations. What does this indicate?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with Addison''s disease is admitted with vomiting, hypotension, and severe fatigue. What is the priority intervention?', '[{"id":"a","text":"Oral hydrocortisone replacement"},{"id":"b","text":"IV hydrocortisone and isotonic saline"},{"id":"c","text":"Blood transfusion for hypovolemia"},{"id":"d","text":"Restrict fluids to prevent hyponatremia"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Addisonian crisis (acute adrenal insufficiency) is life-threatening. Priority: IV glucocorticoid (hydrocortisone) replacement and aggressive IV isotonic saline (0.9% NaCl) for sodium and volume replacement. Oral corticosteroids cannot be absorbed during vomiting crisis.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with Addison''s disease is admitted with vomiting, hypotension, and severe fatigue. What is the priority intervention?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A patient is admitted with acute kidney injury (AKI). Which findings indicate the oliguric phase? (Select all that apply)', '[{"id":"a","text":"Urine output <400 mL/day"},{"id":"b","text":"Rising BUN and creatinine"},{"id":"c","text":"Hyperkalemia"},{"id":"d","text":"Polyuria of 3–5 L/day"},{"id":"e","text":"Metabolic acidosis"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Oliguric phase of AKI: <400 mL urine/day, rising BUN/creatinine (uremia), hyperkalemia (kidney can''t excrete K+), and metabolic acidosis (kidney can''t excrete H+). Polyuria (3–5 L/day) occurs in the diuretic phase that follows recovery.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is admitted with acute kidney injury (AKI). Which findings indicate the oliguric phase? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with a burns covering 30% TBSA is in the emergent phase. Using the Parkland Formula, how much fluid should be given in the first 8 hours? (Patient weighs 70 kg)', '[{"id":"a","text":"2,100 mL"},{"id":"b","text":"4,200 mL"},{"id":"c","text":"8,400 mL"},{"id":"d","text":"1,050 mL"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Parkland Formula: 4 mL × kg × %TBSA = 4 × 70 × 30 = 8,400 mL total in 24 hrs. Give half (4,200 mL) in the first 8 hours, and the remaining 4,200 mL over the next 16 hours. Count from time of burn, not admission.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with a burns covering 30% TBSA is in the emergent phase. Using the Parkland Formula, how much fluid should be given in the first 8 hours? (Patient weighs 70 kg)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A nurse is caring for a patient with increased intracranial pressure. Which position is most appropriate?', '[{"id":"a","text":"Trendelenburg position"},{"id":"b","text":"Head of bed elevated 30 degrees, neck in neutral alignment"},{"id":"c","text":"Prone position to reduce venous pooling"},{"id":"d","text":"Head of bed flat to maintain cerebral perfusion"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'HOB 30° promotes venous drainage from the brain, reducing ICP. Keep neck neutral (no flexion or rotation) to prevent jugular vein compression. Trendelenburg and flat positions increase ICP by impeding venous outflow.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with increased intracranial pressure. Which position is most appropriate?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with type 1 diabetes develops diaphoresis, trembling, and a blood glucose of 48 mg/dL. The patient is conscious and able to swallow. What is the priority action?', '[{"id":"a","text":"Administer 1 mg glucagon intramuscularly"},{"id":"b","text":"Give 15 grams of fast-acting carbohydrates orally"},{"id":"c","text":"Administer 50 mL of D50W IV"},{"id":"d","text":"Call the provider and wait for orders"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Rule of 15: give 15g fast carbs (4 oz juice, glucose tablets) → wait 15 min → recheck glucose. For a conscious patient who can swallow, oral carbs are first-line. IV D50 and IM glucagon are for unconscious patients who cannot swallow.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with type 1 diabetes develops diaphoresis, trembling, and a blood glucose of 48 mg/dL. The patient is conscious and able to swallow. What is the priority action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A patient has a hemoglobin of 7.2 g/dL and is receiving a packed red blood cell transfusion. Which findings require the nurse to stop the transfusion immediately? (Select all that apply)', '[{"id":"a","text":"Temperature increase of 1.5°C"},{"id":"b","text":"Low back pain and chills within 15 minutes of starting"},{"id":"c","text":"Mild urticaria (hives) localized to the arm"},{"id":"d","text":"New-onset dyspnea and oxygen saturation drop to 88%"},{"id":"e","text":"Slight redness at the IV site"}]'::jsonb, '{"ids":["b","d"]}'::jsonb, 'Stop transfusion for: low back pain + chills (hemolytic reaction — medical emergency), dyspnea + SpO2 drop (TRALI or TACO). Mild fever or urticaria = slow or stop, give antipyretics/diphenhydramine, may resume. Local IV site redness needs site care but not transfusion stoppage.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient has a hemoglobin of 7.2 g/dL and is receiving a packed red blood cell transfusion. Which findings require the nurse to stop the transfusion immediately? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient with schizophrenia states, "The TV is sending me special messages." This is an example of:', '[{"id":"a","text":"Hallucination"},{"id":"b","text":"Delusion of reference"},{"id":"c","text":"Thought broadcasting"},{"id":"d","text":"Negative symptom"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A delusion of reference is the false belief that ordinary events have special personal meaning directed at the individual. Hallucinations are sensory perceptions without stimuli. Thought broadcasting is the belief others can hear your thoughts.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with schizophrenia states, "The TV is sending me special messages." This is an example of:');
