-- Safe seed Yingoh NCLEX question bank, part 12.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'mcq', 'A 58-year-old is admitted following a fall. CT scan shows a subdural hematoma. The patient was alert on arrival but is now difficult to arouse, with unequal pupils and declining GCS. What is the priority intervention?', '[{"id":"a","text":"Reposition the patient and reassess in 30 minutes"},{"id":"b","text":"Activate a rapid response/code and prepare for emergent neurosurgical intervention"},{"id":"c","text":"Administer IV morphine for pain and recheck pupils"},{"id":"d","text":"Perform a 12-lead ECG to rule out cardiac cause"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A patient deteriorating from alert to unarousable with unequal pupils and declining GCS is exhibiting signs of transtentorial herniation — a neurosurgical emergency. Immediate: call rapid response/neurosurgery, elevate HOB 30°, administer osmotic therapy (mannitol or hypertonic saline) if ordered, prepare for emergency craniotomy.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 58-year-old is admitted following a fall. CT scan shows a subdural hematoma. The patient was alert on arrival but is now difficult to arouse, with unequal pupils and declining GCS. What is the priority intervention?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient receives an overdose of acetaminophen 8 hours ago and denies symptoms. Which laboratory value is most important to monitor?', '[{"id":"a","text":"Serum creatinine"},{"id":"b","text":"Serum acetaminophen level and liver function tests"},{"id":"c","text":"CBC and platelet count"},{"id":"d","text":"Serum glucose"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Acetaminophen overdose causes hepatotoxicity that peaks at 72–96 hours — the patient is asymptomatic early. Monitor: acetaminophen level (Rumack-Matthew nomogram determines N-acetylcysteine [NAC] need), and AST/ALT every 24 hours. NAC is most effective when given <8–10 hours post-ingestion but can still help later.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient receives an overdose of acetaminophen 8 hours ago and denies symptoms. Which laboratory value is most important to monitor?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with benign prostatic hyperplasia (BPH) is in acute urinary retention. Which is the first intervention?', '[{"id":"a","text":"Encourage the patient to drink 3 L of fluid to stimulate voiding"},{"id":"b","text":"Apply a warm compress to the suprapubic area and attempt voiding"},{"id":"c","text":"Insert a urinary catheter to relieve bladder distension"},{"id":"d","text":"Administer an alpha-blocker and wait 2 hours"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Acute urinary retention with a distended, painful bladder requires immediate catheterization to relieve obstruction and prevent bladder/kidney damage. Up to 1,000 mL may be drained initially (some facilities drain 500 mL, clamp, then continue to prevent hypotension from rapid decompression). Warm compresses and fluids are NOT sufficient for acute retention.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with benign prostatic hyperplasia (BPH) is in acute urinary retention. Which is the first intervention?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient with schizophrenia is experiencing command hallucinations telling them to hurt a named co-worker. What is the nurse''s legal and ethical obligation?', '[{"id":"a","text":"Maintain confidentiality — the hallucinations are part of the illness"},{"id":"b","text":"Warn the identified co-worker and notify the appropriate authorities (Tarasoff duty to protect)"},{"id":"c","text":"Increase antipsychotic medications without provider order"},{"id":"d","text":"Document the hallucinations and monitor without action"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Tarasoff v. Regents (duty to protect): when a patient makes a credible, specific threat against an identifiable third party, clinicians have a legal and ethical duty to warn the potential victim and authorities. Confidentiality is overridden by the duty to protect. This must be reported to the treatment team immediately.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with schizophrenia is experiencing command hallucinations telling them to hurt a named co-worker. What is the nurse''s legal and ethical obligation?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A 4-year-old is prescribed amoxicillin 250 mg every 8 hours. The available suspension is 125 mg/5 mL. How many mL should the nurse administer per dose?', '[{"id":"a","text":"5 mL"},{"id":"b","text":"10 mL"},{"id":"c","text":"15 mL"},{"id":"d","text":"2.5 mL"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Desired/Available × Volume: 250 mg ÷ 125 mg × 5 mL = 10 mL. Always use weight-based dosing verification and a calibrated oral syringe for pediatric liquid medications. Never use household teaspoons (1 tsp ≈ 5 mL but measurement is imprecise).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 4-year-old is prescribed amoxicillin 250 mg every 8 hours. The available suspension is 125 mg/5 mL. How many mL should the nurse administer per dose?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A patient who is Rh-negative delivers an Rh-positive baby. Which medication should the nurse administer within 72 hours?', '[{"id":"a","text":"Betamethasone (to mature fetal lungs for the next pregnancy)"},{"id":"b","text":"RhoGAM (Rh immune globulin)"},{"id":"c","text":"Anti-D immunoglobulin is only needed if the mother has already been sensitized"},{"id":"d","text":"Vitamin K to prevent bleeding"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Rh-negative mother + Rh-positive fetus = risk of maternal sensitization from fetal blood mixing. RhoGAM (Rh immune globulin) must be given within 72 hours of delivery to prevent maternal antibody formation. Without it, subsequent Rh-positive pregnancies risk hemolytic disease of the fetus/newborn.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient who is Rh-negative delivers an Rh-positive baby. Which medication should the nurse administer within 72 hours?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse correctly identifies a patient using two identifiers before administering medication. The identifiers checked are:', '[{"id":"a","text":"Room number and bed assignment"},{"id":"b","text":"Patient name and date of birth (or MRN)"},{"id":"c","text":"Patient name and diagnosis"},{"id":"d","text":"Patient name and nurse assignment"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'The Joint Commission requires two patient identifiers before procedures, medication, blood products, or specimen collection. Approved identifiers: name, DOB, MRN. Room number is NOT a patient identifier — patient transfers make it unreliable. Using room/bed number as an identifier is a common wrong-patient error source.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse correctly identifies a patient using two identifiers before administering medication. The identifiers checked are:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse suspects that a patient is experiencing elder abuse at home. Which action is required?', '[{"id":"a","text":"Ask the family member accompanying the patient if abuse is occurring"},{"id":"b","text":"Document suspicions in the chart and let the provider decide"},{"id":"c","text":"Report the suspicion to adult protective services (APS) per state mandated reporter law"},{"id":"d","text":"Discuss findings with the interdisciplinary team at next week''s meeting"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Nurses are mandated reporters in all U.S. states. Suspected elder abuse, neglect, or exploitation MUST be reported to Adult Protective Services (APS) — the nurse does not need proof, only reasonable suspicion. Reports should be made promptly; waiting for a team meeting may allow continued harm. Questioning the suspected abuser can escalate danger.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse suspects that a patient is experiencing elder abuse at home. Which action is required?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'sata', 'A nurse is caring for a patient post-cardiac catheterization via the radial artery approach. Which assessments are essential? (Select all that apply)', '[{"id":"a","text":"Radial pulse distal to the access site"},{"id":"b","text":"Capillary refill and color of the hand"},{"id":"c","text":"Femoral groin site for hematoma"},{"id":"d","text":"Patient reports of hand numbness or tingling"},{"id":"e","text":"TR Band (hemostatic band) pressure and bleeding at wrist site"}]'::jsonb, '{"ids":["a","b","d","e"]}'::jsonb, 'Radial access: assess the distal radial pulse, color/warmth/capillary refill of hand (ischemia risk), sensory symptoms (numbness = nerve/arterial compromise), and the TR Band for bleeding/hematoma at the wrist. The femoral groin site is NOT relevant for radial access — that applies to femoral approach.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient post-cardiac catheterization via the radial artery approach. Which assessments are essential? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient is prescribed transdermal nitroglycerin patches for angina prophylaxis. Which instruction prevents tolerance?', '[{"id":"a","text":"Apply a new patch every 12 hours without removing the old one"},{"id":"b","text":"Remove the patch for 10–12 hours each day (nitrate-free interval)"},{"id":"c","text":"Use the same skin site each time for consistent absorption"},{"id":"d","text":"Apply the patch to the chest only for cardiac benefit"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Continuous nitrate exposure causes tolerance within 24 hours. A nitrate-free interval of 10–12 hours (typically overnight) prevents tolerance. Rotate application sites (avoid distal extremities, skin folds, hairy areas). Wash hands after applying and avoid the nitroglycerin during the patch-free period if angina occurs.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is prescribed transdermal nitroglycerin patches for angina prophylaxis. Which instruction prevents tolerance?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with myasthenia gravis is in crisis. Which finding helps the nurse differentiate myasthenic crisis from cholinergic crisis?', '[{"id":"a","text":"Both crises present identically — only Tensilon test can differentiate"},{"id":"b","text":"Cholinergic crisis includes SLUDGE symptoms (salivation, lacrimation, urination, defecation, GI cramping, emesis)"},{"id":"c","text":"Myasthenic crisis presents with dry mucous membranes and constipation"},{"id":"d","text":"Cholinergic crisis responds to anticholinesterase medications"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Myasthenic crisis: too little acetylcholine effect (needs more pyridostigmine). Cholinergic crisis: too much acetylcholine (excess pyridostigmine → SLUDGE symptoms). The Tensilon (edrophonium) test differentiates: if symptoms improve = myasthenic; if worsen = cholinergic. Cholinergic crisis requires holding pyridostigmine and giving atropine.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with myasthenia gravis is in crisis. Which finding helps the nurse differentiate myasthenic crisis from cholinergic crisis?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A nurse is caring for a patient in acute respiratory distress syndrome (ARDS) on mechanical ventilation. Which lung-protective strategies are used? (Select all that apply)', '[{"id":"a","text":"Low tidal volume ventilation (4–6 mL/kg ideal body weight)"},{"id":"b","text":"High PEEP to recruit alveoli"},{"id":"c","text":"FiO2 as high as needed to maintain SpO2 >95%"},{"id":"d","text":"Prone positioning for severe ARDS"},{"id":"e","text":"Permissive hypercapnia (allowing PaCO2 to rise modestly)"}]'::jsonb, '{"ids":["a","b","d","e"]}'::jsonb, 'ARDS lung-protective ventilation (ARDSnet): low tidal volume (4–6 mL/kg IBW) prevents volutrauma, high PEEP keeps alveoli open, prone positioning (>12 hours/day) improves V/Q matching, permissive hypercapnia is accepted to allow low tidal volumes. Minimize FiO2 (target SpO2 88–95%) to prevent O2 toxicity.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient in acute respiratory distress syndrome (ARDS) on mechanical ventilation. Which lung-protective strategies are used? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'sata', 'A patient is on a 1:1 safety watch for suicidal ideation. Which environmental modifications are essential? (Select all that apply)', '[{"id":"a","text":"Remove sharps, cords, and belts from the patient''s environment"},{"id":"b","text":"Search belongings for contraband upon admission"},{"id":"c","text":"Allow the patient to keep their cell phone for distress calls"},{"id":"d","text":"Use tamper-resistant fixtures and breakaway shower bars"},{"id":"e","text":"Use paper or foam cups instead of glass or ceramic"}]'::jsonb, '{"ids":["a","b","d","e"]}'::jsonb, 'Environmental safety for suicidal patients: remove ligature risks (cords, belts, shoelaces), sharps, glass objects; tamper-resistant environmental features; paper/foam products. Cell phones pose a risk (cords, ability to access means, stressful content). All belongings are searched on admission to a psychiatric unit.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is on a 1:1 safety watch for suicidal ideation. Which environmental modifications are essential? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'sata', 'A nurse is preventing hospital-acquired pressure injuries in a bedridden patient. Which interventions are evidence-based? (Select all that apply)', '[{"id":"a","text":"Reposition the patient every 2 hours"},{"id":"b","text":"Massage bony prominences vigorously to increase circulation"},{"id":"c","text":"Use a pressure-redistribution mattress"},{"id":"d","text":"Keep skin clean and dry, apply moisture barrier cream"},{"id":"e","text":"Use heel lift boots or pillows to float heels off the bed"}]'::jsonb, '{"ids":["a","c","d","e"]}'::jsonb, 'Evidence-based pressure injury prevention: reposition every 2 hours, pressure-redistribution support surface, moisture management (brief hygiene), heel offloading. Do NOT massage bony prominences — this disrupts already-compromised tissue and increases injury risk. The Braden Scale guides risk assessment.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preventing hospital-acquired pressure injuries in a bedridden patient. Which interventions are evidence-based? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient is receiving continuous enteral tube feeding. The residual volume is 350 mL. What action should the nurse take?', '[{"id":"a","text":"Continue the feeding at the current rate"},{"id":"b","text":"Discard the residual and continue the feeding"},{"id":"c","text":"Hold the feeding, return the residual, and notify the provider or follow the protocol"},{"id":"d","text":"Increase the feeding rate to compensate for the residual"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'A gastric residual >200–250 mL (per most facility protocols) indicates impaired gastric emptying. Hold the feeding, return the residual (to prevent electrolyte loss), and assess for aspiration risk. Notify the provider. Follow facility protocol — thresholds vary. Never increase the rate with a large residual.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is receiving continuous enteral tube feeding. The residual volume is 350 mL. What action should the nurse take?');
