-- Batch 10: maternal, newborn, pediatric, and lifespan promotion catalog.
select public.seed_structured_concept(
  'expansion-batch-10', slug, topic, condition, cue, action, teaching,
  danger, wrong1, wrong2, wrong3, 'Health Promotion and Maintenance'
)
from (values
('first-prenatal','Maternal and Newborn','the first prenatal visit','a client presents after a positive pregnancy test','Obtain history, dating, risks, medicines, labs, psychosocial needs, and preventive counseling','Begin prenatal care early and review every medicine and supplement','Ectopic warning symptoms with syncope and unilateral pain','Delay care until fetal movement','Stop prescribed medicine without review','Use alcohol for nausea'),
('gestational-weight','Maternal and Newborn','healthy gestational weight gain','a pregnant client asks for one universal weight target','Use prepregnancy BMI and clinical factors to individualize nutrition and gain goals','Choose nutrient-dense foods and regular activity as approved rather than dieting','Persistent vomiting with weight loss and dehydration','Use severe calorie restriction','Double all portions automatically','Take weight-loss medicine'),
('prenatal-exercise','Maternal and Newborn','exercise during uncomplicated pregnancy','an active pregnant client requests guidance','Encourage moderate activity with hydration and condition-specific precautions','Stop and seek advice for bleeding, fluid leakage, chest pain, dizziness, or contractions','Exercise triggers bleeding and painful regular contractions','Exercise through severe symptoms','Use high-fall-risk activity','Become overheated and dehydrated'),
('gestational-diabetes-screen','Maternal and Newborn','gestational diabetes screening','a pregnant client has elevated screening glucose','Complete diagnostic evaluation and use nutrition, monitoring, activity, and medicine as indicated','Glucose control reduces maternal and fetal complications and requires postpartum follow-up','Persistent severe hyperglycemia with ketones and vomiting','Skip monitoring when asymptomatic','Eliminate all carbohydrates','Miss postpartum diabetes screening'),
('group-b-strep','Maternal and Newborn','group B streptococcus prevention','a late-pregnancy culture is positive','Document the result and give indicated intrapartum antibiotics','A positive screen usually requires antibiotics during labor rather than treatment weeks beforehand','Labor begins and the positive result is not communicated','Use leftover oral antibiotics','Assume cesarean plans eliminate all review','Hide the result from the birth team'),
('fetal-movement','Maternal and Newborn','fetal movement awareness','a pregnant client perceives a marked decrease from the usual pattern','Follow the instructed movement assessment and contact maternity care promptly','Know the baby’s usual pattern and report a significant decrease rather than waiting days','No movement is perceived with bleeding or pain','Wait until the next appointment','Drink alcohol to stimulate movement','Use a home Doppler to replace evaluation'),
('labor-birth-plan','Maternal and Newborn','shared birth planning','a client presents preferences for labor and birth','Review preferences, safety contingencies, consent, coping, support, and newborn care','A birth plan communicates preferences but may change when maternal or fetal safety requires','The client is coerced into an intervention without urgent need or informed consent','Guarantee every requested outcome','Dismiss all preferences','Withhold changing clinical information'),
('postpartum-followup','Maternal and Newborn','postpartum preventive follow-up','a client has hypertension and mood risk after discharge','Arrange timely physical and mental-health follow-up and review warning signs, contraception, and chronic disease','Postpartum care is an ongoing process; seek help for severe headache, chest pain, dyspnea, bleeding, or harmful thoughts','Severe headache with vision change and blood pressure 170/112','Wait six weeks despite danger signs','Stop pressure medicine independently','Ignore intrusive harm thoughts'),
('newborn-temperature','Maternal and Newborn','newborn thermoregulation','a healthy newborn is wet and cooling after birth','Dry immediately, provide skin-to-skin warmth, cover the head, and monitor temperature and glucose risk','Use skin-to-skin and appropriate clothing and avoid overheating or unsafe heat sources','Persistent hypothermia with lethargy and poor feeding','Use an unattended heating pad','Bathe immediately before warming','Leave wet linens in place'),
('newborn-cord','Maternal and Newborn','umbilical-cord care','parents ask how to care for the drying stump','Keep it clean and dry and observe for infection or bleeding','Fold the diaper below the stump and report spreading redness, pus, fever, or persistent bleeding','Redness spreads onto the abdomen with fever','Cover with a tight moist dressing','Apply unapproved substances','Pull the stump off'),
('breastfeeding-latch','Maternal and Newborn','effective breastfeeding latch','a parent has nipple pain and the newborn transfers little milk','Observe a feed and correct positioning, deep latch, frequency, and swallowing','Feed on cues and seek help for persistent pain, poor output, lethargy, or inadequate gain','The newborn is difficult to wake and has very few wet diapers','Limit feeds to a rigid short schedule','Accept cracked bleeding nipples as normal','Give water instead of feeding'),
('formula-safety','Maternal and Newborn','safe infant-formula preparation','a caregiver uses powdered formula','Use safe water, exact dilution, clean preparation, and storage and discard rules','Never dilute to stretch formula and discard leftovers from a used bottle','The infant is lethargic after repeatedly over-diluted feeds','Add extra water','Microwave bottles','Save a partially consumed bottle all day'),
('newborn-bathing','Maternal and Newborn','safe newborn bathing','parents prepare the first baths at home','Use a warm draft-free space, shallow water, constant hand support, and cord guidance','Test water temperature and never leave the infant alone even briefly','The infant is left unsupported in water','Leave to answer the phone','Use very hot water','Place the tub on an unstable surface'),
('infant-crying','Pediatrics','coping with infant crying','an exhausted caregiver feels overwhelmed by persistent crying','Assess infant needs and safety and teach placing the infant safely in the crib while the caregiver takes a brief break','Never shake an infant; seek help for illness signs or when coping is failing','The caregiver states an intent to shake or harm the infant','Shake to stop crying','Place the infant prone on a sofa','Use unapproved sedating medicine'),
('tummy-time','Pediatrics','supervised tummy time','parents ask how to support infant motor development','Encourage awake supervised prone play while maintaining supine sleep','Use short frequent sessions when alert and stop if distress or breathing difficulty occurs','The infant is left prone unattended for sleep','Use tummy time during sleep','Place on a soft pillow unattended','Continue despite respiratory distress'),
('introducing-solids','Pediatrics','introduction of complementary foods','an infant shows developmental readiness for solids','Introduce age-appropriate textures one at a time while continuing breast milk or formula','Avoid choking hazards and honey in the first year and watch for allergic reactions','Wheezing and facial swelling after a new food','Give whole nuts','Put cereal in a bottle routinely','Give honey before age one'),
('toddler-discipline','Pediatrics','developmentally appropriate toddler discipline','caregivers report frequent tantrums','Use predictable routines, brief clear limits, redirection, praise, and safe consistent consequences','Offer limited choices and remain calm while protecting the child during tantrums','Tantrums include loss of consciousness or serious self-injury','Use physical punishment','Give long abstract lectures','Reward every tantrum'),
('toilet-readiness','Pediatrics','toilet-learning readiness','a two-year-old family feels pressured to train','Assess readiness signs and use a positive routine without punishment','Readiness varies; praise attempts and expect temporary setbacks','Painful urination, severe constipation, or regression with other illness signs','Punish accidents','Restrict fluid','Force prolonged sitting'),
('pediatric-dental','Pediatrics','early-childhood dental prevention','a toddler sleeps with a bottle of sweet liquid','Establish dental care, fluoride guidance, twice-daily brushing, and elimination of bedtime sugar exposure','Use water only if a bedtime bottle is unavoidable and never share utensils that spread bacteria','Facial swelling with fever and dental pain','Dip pacifier in sugar','Use juice throughout the night','Delay dental care until school age'),
('school-bullying','Pediatrics','bullying prevention and response','a school-age child reports repeated threats and avoidance','Assess immediate safety and emotional impact and coordinate a documented school and family response','Tell a trusted adult, preserve evidence, and seek help for threats or self-harm thoughts','The child has a suicide plan after escalating online harassment','Tell the child to fight back','Arrange direct unsupervised confrontation','Dismiss it as normal teasing'),
('adolescent-sleep','Pediatrics','adolescent sleep health','a teen sleeps five hours and uses devices overnight','Assess schedule, mood, substances, apnea symptoms, and create consistent sleep and device limits','Use a regular wake time, reduce late caffeine, and keep devices out of the sleep space','Falling asleep while driving or suicidal depression','Use energy drinks at night','Drive when severely sleepy','Take another person’s sedative'),
('sports-concussion','Pediatrics','concussion safety','an athlete has headache and confusion after impact','Remove from play immediately and arrange medical assessment and graduated return','No same-day return after suspected concussion; report worsening headache, vomiting, weakness, or confusion','Declining consciousness with repeated vomiting','Return when headache briefly improves','Leave the athlete alone','Use alcohol for sleep'),
('pediatric-sun','Pediatrics','sun and heat protection for children','a family plans prolonged outdoor activity','Use shade, protective clothing, age-appropriate sunscreen, hydration, and heat breaks','Reapply sunscreen and stop activity for dizziness, confusion, or heat illness signs','Confusion with hot skin and collapse','Leave an infant in a parked vehicle','Use tanning beds','Continue sports through heat symptoms'),
('teen-substance','Pediatrics','adolescent substance-use prevention','a teen reports vaping and occasional pills from friends','Use confidential validated screening, assess overdose and mental-health risk, and offer treatment support','Never take unidentified pills and use emergency help and naloxone when opioid exposure is possible','Slow breathing and unresponsiveness after an unknown pill','Punish disclosure','Assume vaping is harmless','Drive after substance use'),
('young-adult-transition','Health Promotion','transition from pediatric to adult care','a young adult with chronic disease relies entirely on parents','Build skills in medicines, appointments, insurance, emergency planning, and self-advocacy','Maintain an updated health summary and know when and how to seek urgent care','Essential treatment stops because no adult clinician or supply plan exists','Transfer without records','Wait for a crisis','Hide the diagnosis from the new team'),
('midlife-screening','Health Promotion','midlife preventive assessment','an adult has several modifiable cardiovascular and cancer risks','Use age, anatomy, family history, and risk to plan screening and prevention through shared decisions','Know personal numbers and report new symptoms rather than waiting for screening','New exertional chest pressure is scheduled only as routine screening','Order tests without discussing harms','Ignore family history','Use screening to evaluate an emergency'),
('healthy-aging','Health Promotion','healthy aging','an older adult wants to preserve independence','Assess mobility, cognition, mood, vision, hearing, nutrition, medicines, vaccines, and social connection','Strength, balance, meaningful activity, sleep, and preventive care support independence','Rapid functional decline with delirium and falls','Assume decline is normal aging','Stop activity','Use sedatives for every sleep complaint')
) as c(slug,topic,condition,cue,action,teaching,danger,wrong1,wrong2,wrong3);

-- Retained for subsequent held batches.
