-- Batch 03: 90 draft questions from 30 concepts in underrepresented blueprint areas.
-- Requires the structured seed function created by Batch 02.

-- Management of Care (6 concepts / 18 questions)
select public.seed_structured_concept('expansion-batch-03','informed-consent','Leadership and Delegation','valid informed consent','a client who signed after receiving a sedative says the procedure was never explained','Stop preparation and notify the provider because consent may not be informed or voluntary','The provider explains risks, benefits, and alternatives; the nurse witnesses the voluntary signature and verifies understanding','The client asks basic questions and cannot describe the procedure after signing','Ask a family member to sign without legal authority','Explain the surgical risks independently in place of the provider','Proceed because a signature is present in the chart','Management of Care');
select public.seed_structured_concept('expansion-batch-03','acuity-assignment','Leadership and Delegation','safe assignment by acuity','one nurse is newly licensed and several clients have rapidly changing conditions','Assign stable predictable clients to the new nurse and retain unstable clients with experienced staff','Assignments should match client stability, staff competency, and available supervision','A new nurse is assigned two unstable clients requiring simultaneous titrated infusions','Divide clients only by room number','Give the newest nurse the sickest client for experience','Ignore competency when staffing is limited','Management of Care');
select public.seed_structured_concept('expansion-batch-03','telephone-order','Leadership and Delegation','a telephone medication order','an urgent order received while the provider is off site','Write the complete order, read it back, and obtain required authentication','Expect the nurse to read back names, doses, routes, frequencies, and indications clearly','An order containing an unsafe dose that the provider refuses to clarify','Ask another nurse to guess an unclear dose','Document the order from memory after the call','Administer before reading the order back','Management of Care');
select public.seed_structured_concept('expansion-batch-03','advance-directive','Leadership and Delegation','an advance directive','a competent client requests care different from the family’s wishes','Honor the client’s informed choices and notify the team of the documented directive','Discuss goals early and provide copies of advance-directive documents to the healthcare team','Treatment begins that directly conflicts with the valid directive','Allow the oldest relative to override the client','Withhold information to prevent family conflict','Assume a do-not-resuscitate order prohibits all treatment','Management of Care');
select public.seed_structured_concept('expansion-batch-03','discharge-reconciliation','Leadership and Delegation','medication reconciliation at discharge','multiple changed prescriptions and duplicate brand and generic medicines','Compare every medication list, resolve discrepancies, and provide one understandable final schedule','Use the final reconciled list and discard outdated lists to prevent duplicate dosing','Two prescriptions contain the same drug under different names at full doses','Tell the client to choose whichever list seems newest','Keep discontinued medicines mixed with active medicines','Skip reconciliation because the pharmacy will correct errors','Management of Care');
select public.seed_structured_concept('expansion-batch-03','ethical-refusal','Leadership and Delegation','a conscientious objection to assigned care','a nurse objects to a procedure but the client needs timely lawful care','Notify leadership early and ensure qualified alternative care without abandoning the client','Personal beliefs do not permit delaying, coercing, or abandoning a client','The nurse leaves immediately without arranging coverage','Attempt to shame the client into changing the decision','Alter the schedule secretly to prevent the procedure','Refuse emergency stabilization while debating beliefs','Management of Care');

-- Safety and Infection Prevention and Control (6 / 18)
select public.seed_structured_concept('expansion-batch-03','measles-precautions','Safety and Infection Control','suspected measles','fever, cough, conjunctivitis, Koplik spots, and a spreading rash','Place the client in an airborne infection isolation room and use a fit-tested respirator','Call before arrival, mask the client for transport, and avoid exposing susceptible people','A susceptible pregnant staff member is assigned to enter the room','Use droplet precautions alone','Leave the isolation-room door open','Transport the unmasked client through a crowded hallway','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-03','varicella-precautions','Safety and Infection Control','disseminated varicella','fever with widespread vesicles in different stages','Use airborne and contact precautions in an appropriate isolation room','Avoid susceptible contacts until lesions have crusted and follow exposure guidance','New respiratory distress in an immunocompromised client with varicella','Use standard precautions alone','Assign nonimmune pregnant personnel','Cover lesions but discontinue airborne precautions immediately','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-03','pertussis-precautions','Safety and Infection Control','suspected pertussis','paroxysmal cough, inspiratory whoop, and post-tussive vomiting','Initiate droplet precautions and administer prescribed antimicrobial therapy','Close contacts may require prophylaxis and vaccination status should be reviewed','Apnea and cyanosis during coughing in an infant','Use airborne isolation as the only measure','Delay precautions until culture confirmation','Allow an unmasked symptomatic visitor into the nursery','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-03','central-line-infection','Safety and Infection Control','central-line infection prevention','a client receiving therapy through a nontunneled central venous catheter','Use hand hygiene, chlorhexidine skin antisepsis, sterile access technique, and daily necessity review','Keep the dressing clean and dry and report redness, drainage, fever, or line damage','Purulent drainage with fever and rigors during infusion','Palpate the site after antisepsis with bare fingers','Reuse contaminated access caps','Keep an unnecessary line for convenient blood draws','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-03','urinary-catheter-cauti','Safety and Infection Control','catheter-associated urinary infection prevention','an indwelling catheter with no continuing indication','Remove the catheter promptly and maintain a closed unobstructed system until removal','Keep the bag below bladder level and avoid disconnecting the closed system','Fever with suprapubic pain and new cloudy urine','Place the drainage bag on the bed','Disconnect tubing daily for routine cleaning','Irrigate routinely without an indication','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-03','sharps-disposal','Safety and Infection Control','safe sharps handling','a used hollow-bore needle after venipuncture','Activate the safety device and place it directly into an approved sharps container','Never bend or recap used needles except when a specific procedure requires an approved one-hand technique','An overfilled sharps container with needles protruding','Carry the uncapped needle to another room','Push contents down by hand','Discard the needle in ordinary waste','Safety and Infection Prevention and Control');

-- Health Promotion and Maintenance (6 / 18)
select public.seed_structured_concept('expansion-batch-03','preconception-folate','Health Promotion','preconception folic-acid counseling','a client planning pregnancy who previously had a fetus with a neural-tube defect','Refer for individualized high-dose folic-acid guidance before conception','Begin folic acid before conception because the neural tube closes early in pregnancy','The client plans to wait until the second trimester to begin supplementation','Replace folate with vitamin A supplements','Stop all fortified foods','Assume diet alone always meets high-risk needs','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-03','infant-safe-sleep','Health Promotion','safe infant sleep','parents preparing a sleep space for a healthy newborn','Place the infant supine on a firm flat surface with no loose bedding','Room-share without bed-sharing and keep pillows, bumpers, and toys out of the sleep space','The caregiver places the infant prone on a sofa to sleep','Use a weighted blanket','Position the infant with a sleep wedge','Let the infant sleep in an inclined car seat overnight','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-03','development-18-month','Health Promotion','18-month developmental surveillance','a toddler attending a well-child visit','Assess language, mobility, social interaction, hearing, and autism-related development using recommended screening','Read, talk, and play daily and report loss of previously acquired skills','The toddler loses words and no longer makes eye contact','Compare the child only with an older sibling','Delay evaluation of regression until school age','Use screen time instead of interactive play','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-03','adolescent-confidentiality','Health Promotion','adolescent confidential care','an adolescent requests private discussion about sexual health','Explain confidentiality and its safety limits, then provide private developmentally appropriate assessment','Private visits support honest preventive care, but imminent safety threats must be shared','The adolescent reports an immediate plan for self-harm and requests secrecy','Promise absolute secrecy before assessment','Discuss sensitive answers in a crowded waiting room','Exclude the adolescent from all decisions','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-03','older-adult-fall-screen','Health Promotion','community fall prevention','an older adult reports two falls and takes several sedating medicines','Assess gait, vision, orthostatic pressure, footwear, home hazards, and medications','Use strength and balance exercise, adequate lighting, and medication review to reduce falls','New syncope with injury and persistent neurologic change','Limit all activity to prevent future falls','Use loose rugs for cushioning','Take sedating medicines before walking','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-03','vaccine-anaphylaxis-prep','Health Promotion','safe immunization practice','a clinic administering routine vaccines','Screen for contraindications, give the correct product and route, and maintain emergency anaphylaxis supplies','Expected mild soreness differs from breathing difficulty or facial swelling, which requires emergency care','Wheezing and hypotension minutes after vaccination','Give vaccines without checking identity','Use the same needle for multiple clients','Send the client away immediately during an active reaction','Health Promotion and Maintenance');

-- Basic Care and Comfort (6 / 18)
select public.seed_structured_concept('expansion-batch-03','dysphagia-feeding','Fundamentals','safe feeding with dysphagia','a post-stroke client with a prescribed texture-modified diet','Sit the client upright, use the prescribed consistency, and allow slow small bites','Remain upright after meals and report coughing, wet voice, or food pocketing','A wet voice with oxygen desaturation during the meal','Offer thin water to clear coughing','Feed rapidly while the client is reclined','Mix food textures without swallowing guidance','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-03','ostomy-care','Fundamentals','new colostomy care','a moist red stoma with liquid output after surgery','Measure the stoma, protect peristomal skin, and fit the barrier closely without constriction','A healthy stoma is moist and red; empty the pouch before it becomes heavy','A dusky black stoma with absent output and increasing pain','Clean the stoma vigorously with alcohol','Cut the barrier much larger than the stoma','Treat persistent skin breakdown as expected','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-03','opioid-constipation','Fundamentals','opioid-related constipation prevention','a client beginning scheduled opioid therapy','Start prescribed bowel prevention with fluids, mobility, fiber when appropriate, and stimulant therapy','Do not wait several days for severe constipation before using the prescribed bowel plan','Abdominal distention with vomiting and absent bowel sounds','Use an antidiarrheal every day','Restrict fluids without a medical reason','Stop all movement to conserve energy','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-03','nonpharm-pain','Fundamentals','multimodal pain management','a stable client with postoperative pain despite scheduled medication','Reassess pain and combine prescribed analgesia with positioning, splinting, relaxation, or cold as appropriate','Use pain medicine before activity and combine it with safe non-drug methods','Sudden severe pain out of proportion with a tense swollen limb','Tell the client pain is unavoidable','Withhold analgesia until pain reaches maximum intensity','Apply heat over an acutely bleeding site','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-03','sleep-hygiene','Fundamentals','sleep promotion in the hospital','a stable client unable to sleep because of noise and repeated interruptions','Cluster appropriate care, reduce noise and light, and support the client’s usual bedtime routine','Keep a consistent schedule and limit late caffeine, heavy meals, and screen exposure','New nighttime agitation with hypoxemia and acute confusion','Offer caffeine with evening medicines','Wake the client for nonessential tasks hourly','Use sedatives before assessing reversible causes','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-03','immobility-rom','Fundamentals','complication prevention during immobility','a bedbound client with weakness but stable vital signs','Reposition, perform prescribed range of motion, protect skin, and promote pulmonary hygiene','Participate in gradual mobility and ankle exercises as directed and report calf pain or breathlessness','A warm swollen unilateral calf with sudden dyspnea','Place pillows directly behind flexed knees continuously','Massage a painful swollen calf','Maintain one position to conserve strength','Basic Care and Comfort');

-- Psychosocial Integrity (6 / 18)
select public.seed_structured_concept('expansion-batch-03','complicated-grief','Mental Health','possible prolonged grief disorder','persistent disabling yearning and inability to function long after a death','Assess safety, functioning, culture, supports, and need for grief-focused treatment','Grief varies, but persistent inability to function or thoughts of self-harm require professional help','A stated wish to die in order to reunite with the deceased','Tell the client to remove every reminder immediately','Set a fixed deadline for completing grief','Avoid discussing the deceased under all circumstances','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-03','intimate-partner-violence','Mental Health','intimate partner violence','injuries with a controlling partner who answers every question','Interview the client alone, assess immediate danger, document objectively, and offer resources','A personalized safety plan can include emergency contacts, documents, medicines, and a safe destination','The partner threatens to kill the client and has access to a weapon','Confront the partner while the client is present','Insist the client leave immediately as a condition of care','Document judgmental conclusions instead of findings','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-03','auditory-hallucinations','Mental Health','command auditory hallucinations','a client says voices are ordering harm to another person','Ask what the voices say, assess intent and means, ensure safety, and reduce stimulation','Use coping methods such as talking with staff or listening to music and report harmful commands immediately','The client has obtained a weapon and intends to obey the voice','Agree that the voices are real','Challenge the client aggressively to stop pretending','Leave the client alone with access to hazards','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-03','ocd-rituals','Mental Health','obsessive-compulsive disorder','time-consuming handwashing rituals causing skin injury','Acknowledge anxiety, protect the skin, set collaborative limits, and support evidence-based therapy','Exposure and response prevention works gradually; do not stop rituals abruptly without support','The client uses caustic chemicals and has open bleeding wounds','Punish ritual behavior','Join every ritual to prevent anxiety','Demand immediate permanent cessation','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-03','major-depression','Mental Health','major depressive disorder','hopelessness, insomnia, withdrawal, and poor intake','Assess suicide risk directly, support basic needs, and use brief achievable activities','Antidepressants may take time; report worsening agitation or suicidal thoughts promptly','New energy with a specific suicide plan and collected medications','Use cheerful commands to overcome depression','Leave all medicines at the bedside','Interpret withdrawal as manipulation','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-03','dementia-sundowning','Mental Health','dementia with sundowning','late-day agitation and wandering in an unfamiliar setting','Assess unmet needs, reduce evening stimulation, use familiar cues, and maintain safety','Use consistent routines, daylight activity, identification, and secured safe wandering areas','A sudden change from baseline with fever and reduced attention','Use physical restraints as the first response','Argue repeatedly about incorrect beliefs','Change caregivers and rooms each evening','Psychosocial Integrity');

-- Retained temporarily for subsequent held expansion batches.
