-- Seed Yingoh NCLEX question bank, part 1.
-- Inserts only prompts that do not already exist, so it is safe to rerun.

insert into public.questions (
  topic,
  question_type,
  prompt,
  choices,
  correct_answer,
  rationale,
  strategy,
  client_need,
  clinical_judgment,
  status
)
select *
from (values
  ('Pharmacology', 'mcq', 'A nurse is administering metformin to a patient with type 2 diabetes. Which laboratory finding should the nurse report to the provider immediately before giving this medication?', '[{"id":"a","text":"Blood glucose of 180 mg/dL"},{"id":"b","text":"Serum creatinine of 2.8 mg/dL"},{"id":"c","text":"HbA1c of 7.2%"},{"id":"d","text":"Blood pressure of 130/82 mmHg"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Metformin is contraindicated with significant renal impairment (creatinine >1.4 mg/dL in women, >1.5 in men) due to the risk of lactic acidosis. A creatinine of 2.8 mg/dL requires holding the medication and notifying the provider.', '', '', '', 'published'),
  ('Safety and Infection Control', 'sata', 'A nurse is caring for a patient with Clostridioides difficile (C. diff) colitis. Which actions are appropriate? (Select all that apply)', '[{"id":"a","text":"Wear gloves when entering the room"},{"id":"b","text":"Use alcohol-based hand rub after removing gloves"},{"id":"c","text":"Wear a gown when entering the room"},{"id":"d","text":"Wash hands with soap and water"},{"id":"e","text":"Place patient in a negative pressure room"},{"id":"f","text":"Wear an N95 respirator"}]'::jsonb, '{"ids":["a","c","d"]}'::jsonb, 'C. diff requires contact precautions: gown and gloves. Alcohol-based hand rubs do NOT kill C. diff spores — soap and water is required. Negative pressure rooms and N95s are for airborne precautions, not C. diff.', '', '', '', 'published'),
  ('Maternal and Newborn', 'mcq', 'A nurse calculates an APGAR score at 5 minutes. The newborn has HR 110/min, slow irregular respirations, some extremity flexion, grimace to stimulation, and acrocyanosis. What is the APGAR score?', '[{"id":"a","text":"4"},{"id":"b","text":"5"},{"id":"c","text":"6"},{"id":"d","text":"7"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'HR >100 = 2, Respiratory slow/irregular = 1, Muscle tone some flexion = 1, Reflex grimace = 1, Color acrocyanosis = 0. Total = 5. Scores 4–6 indicate moderate depression requiring stimulation.', '', '', '', 'published'),
  ('NGN Case Studies', 'sata', 'A nurse assesses a patient 12 hours post-abdominal surgery: T 38.9°C, HR 102, BP 118/76, SpO2 95%, urine output 20 mL over 2 hours. Which findings require immediate intervention? (Select all that apply)', '[{"id":"a","text":"Temperature 38.9°C"},{"id":"b","text":"Heart rate 102"},{"id":"c","text":"Urine output 20 mL over 2 hours"},{"id":"d","text":"SpO2 95%"},{"id":"e","text":"Respiratory rate 22"},{"id":"f","text":"Blood pressure 118/76"}]'::jsonb, '{"ids":["a","c"]}'::jsonb, 'Post-op day 0–1 fever (atelectasis) requires incentive spirometry and deep breathing. Urine output 20 mL/2 hr = 10 mL/hr — below the 30 mL/hr minimum, indicating oliguria. Other values are acceptable post-operatively.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A nurse is preparing to administer digoxin. Which finding should cause the nurse to withhold the medication and contact the provider?', '[{"id":"a","text":"Apical pulse of 56 beats per minute"},{"id":"b","text":"Blood pressure of 118/72 mmHg"},{"id":"c","text":"Serum potassium of 4.1 mEq/L"},{"id":"d","text":"Serum digoxin level of 0.8 ng/mL"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Withhold digoxin if apical pulse <60 bpm and notify the provider. Digoxin is a negative chronotrope; giving it with a rate of 56 could cause dangerous bradycardia or heart block.', '', '', '', 'published'),
  ('Medical-Surgical', 'sata', 'A nurse is caring for a patient with diabetic ketoacidosis (DKA). Which clinical findings are consistent with this diagnosis? (Select all that apply)', '[{"id":"a","text":"Kussmaul respirations"},{"id":"b","text":"Blood glucose 520 mg/dL"},{"id":"c","text":"Fruity breath odor"},{"id":"d","text":"Bradycardia"},{"id":"e","text":"Polyuria and polydipsia"},{"id":"f","text":"Diaphoresis and pallor"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'DKA: Kussmaul respirations (compensation for metabolic acidosis), hyperglycemia >250 mg/dL, fruity/acetone breath (ketones), polyuria and polydipsia. Bradycardia and diaphoresis/pallor are not DKA findings.', '', '', '', 'published'),
  ('Mental Health', 'mcq', 'A patient is prescribed lithium carbonate for bipolar disorder. Which serum level indicates toxicity requiring immediate intervention?', '[{"id":"a","text":"0.6 mEq/L"},{"id":"b","text":"0.9 mEq/L"},{"id":"c","text":"1.2 mEq/L"},{"id":"d","text":"2.1 mEq/L"}]'::jsonb, '{"ids":["d"]}'::jsonb, 'Therapeutic lithium range is 0.6–1.2 mEq/L. Levels >1.5 indicate toxicity; >2.0 is severe toxicity requiring emergency treatment including IV fluids and possible hemodialysis.', '', '', '', 'published'),
  ('Pediatrics', 'mcq', 'A nurse is assessing an 18-month-old child. Which developmental milestone should the nurse expect?', '[{"id":"a","text":"Speaking in 4–5 word sentences"},{"id":"b","text":"Walking up stairs with alternating feet"},{"id":"c","text":"Using a spoon and cup with some spilling"},{"id":"d","text":"Drawing a circle"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'At 18 months, toddlers use a spoon and cup with some spilling. Four-to-five word sentences, stair-climbing with alternating feet, and drawing circles are ~3-year milestones.', '', '', '', 'published'),
  ('Medical-Surgical', 'sata', 'A nurse teaches a patient prescribed warfarin. Which foods should be eaten in consistent amounts because they may decrease warfarin effectiveness? (Select all that apply)', '[{"id":"a","text":"Spinach"},{"id":"b","text":"Kale"},{"id":"c","text":"Grapefruit"},{"id":"d","text":"Broccoli"},{"id":"e","text":"Bananas"},{"id":"f","text":"Brussels sprouts"}]'::jsonb, '{"ids":["a","b","d","f"]}'::jsonb, 'Vitamin K antagonizes warfarin. High vitamin K foods include spinach, kale, broccoli, and Brussels sprouts. Patients should eat these consistently, not avoid them, to maintain stable INR.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A nurse is administering morphine sulfate IV post-operatively. Which equipment must be at the bedside before administering?', '[{"id":"a","text":"Blood pressure cuff and stethoscope"},{"id":"b","text":"Naloxone and resuscitation equipment"},{"id":"c","text":"Blood glucose monitor"},{"id":"d","text":"IV calcium gluconate"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Before administering opioids, naloxone (Narcan) and resuscitation equipment must be at bedside. Opioids can cause respiratory depression; naloxone is the required antidote.', '', '', '', 'published'),
  ('Safety and Infection Control', 'mcq', 'A nurse is preparing to administer blood. Which action is the priority to prevent a transfusion reaction?', '[{"id":"a","text":"Prime IV tubing with normal saline"},{"id":"b","text":"Verify the blood product with another nurse at the bedside"},{"id":"c","text":"Check vital signs 15 minutes after starting"},{"id":"d","text":"Obtain IV access with an 18-gauge catheter"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Two licensed nurses must verify blood type, unit number, expiration date, and patient ID at bedside before transfusion. This is the priority action to prevent hemolytic transfusion reactions.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient has a serum potassium of 2.8 mEq/L. Which assessment finding is most consistent with this result?', '[{"id":"a","text":"Muscle weakness and leg cramps"},{"id":"b","text":"Peaked T waves on ECG"},{"id":"c","text":"Bradycardia"},{"id":"d","text":"Paresthesias of the face"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Hypokalemia (<3.5 mEq/L) causes muscle weakness, cramps, and fatigue. Peaked T waves and bradycardia are hyperkalemia signs. Facial paresthesias are associated with hypocalcemia.', '', '', '', 'published'),
  ('NGN Case Studies', 'sata', 'A nurse reviews orders for a patient with acute heart failure. Which orders should be clarified before implementing? (Select all that apply)', '[{"id":"a","text":"0.9% NaCl 500 mL IV bolus over 1 hour"},{"id":"b","text":"Furosemide 40 mg IV push"},{"id":"c","text":"Restrict fluids to 1500 mL/day"},{"id":"d","text":"Morphine sulfate 2 mg IV PRN for air hunger"},{"id":"e","text":"High sodium diet"},{"id":"f","text":"Daily weights"}]'::jsonb, '{"ids":["a","e"]}'::jsonb, 'IV saline bolus worsens fluid overload and pulmonary edema in acute HF. A high sodium diet exacerbates fluid retention. Furosemide, fluid restriction, morphine for dyspnea, and daily weights are all appropriate HF interventions.', '', '', '', 'published'),
  ('Maternal and Newborn', 'sata', 'A nurse assesses a patient in active labor. Which findings require immediate intervention? (Select all that apply)', '[{"id":"a","text":"Fetal heart rate of 90 bpm for 3 minutes"},{"id":"b","text":"Contractions every 3–4 minutes lasting 50 seconds"},{"id":"c","text":"Late decelerations on the fetal monitor"},{"id":"d","text":"Maternal blood pressure of 158/106 mmHg"},{"id":"e","text":"Cervical dilation of 7 cm"},{"id":"f","text":"Clear amniotic fluid"}]'::jsonb, '{"ids":["a","c","d"]}'::jsonb, 'Fetal bradycardia <110 bpm for >3 min requires repositioning, O2, and provider notification. Late decelerations indicate uteroplacental insufficiency. BP 158/106 meets severe hypertension in pregnancy criteria — magnesium sulfate and provider notification required.', '', '', '', 'published'),
  ('Leadership and Management', 'mcq', 'A charge nurse is making shift assignments. Which patient should be assigned to the most experienced RN?', '[{"id":"a","text":"Patient with COPD requiring chest physiotherapy"},{"id":"b","text":"Patient with new colostomy requiring discharge teaching"},{"id":"c","text":"Patient with septic shock receiving vasopressors"},{"id":"d","text":"Patient with type 2 diabetes preparing for discharge"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Match patient acuity to nurse competency. Septic shock with vasopressors requires complex hemodynamic monitoring, medication titration, and critical thinking — the most demanding assignment.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A nurse assesses a patient 24 hours post-thyroidectomy. Which finding requires the most immediate action?', '[{"id":"a","text":"Serum calcium 7.2 mg/dL with positive Trousseau sign"},{"id":"b","text":"Hoarseness when speaking"},{"id":"c","text":"Incision pain rated 5/10"},{"id":"d","text":"Temperature of 37.8°C"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Post-thyroidectomy hypocalcemia from parathyroid damage can progress to tetany, laryngospasm, and seizures. Calcium 7.2 mg/dL with positive Trousseau sign requires immediate IV calcium gluconate.', '', '', '', 'published'),
  ('Mental Health', 'sata', 'A patient is admitted after a suicide attempt. Which nursing interventions are appropriate? (Select all that apply)', '[{"id":"a","text":"Remove all potentially harmful items from the environment"},{"id":"b","text":"Maintain 1:1 supervision at all times"},{"id":"c","text":"Ask the patient directly about suicidal ideation"},{"id":"d","text":"Avoid discussing the attempt to prevent distress"},{"id":"e","text":"Establish a therapeutic nurse–patient relationship"},{"id":"f","text":"Document the patient''s statements and behaviors"}]'::jsonb, '{"ids":["a","b","c","e","f"]}'::jsonb, 'Suicide precautions include environmental safety, 1:1 supervision, and direct assessment — asking directly does NOT increase risk. Therapeutic relationship and thorough documentation are essential. Avoiding discussion (D) is incorrect.', '', '', '', 'published'),
  ('Pharmacology', 'sata', 'A nurse is preparing to administer heparin subcutaneously. Which actions should the nurse take? (Select all that apply)', '[{"id":"a","text":"Verify the aPTT before administration"},{"id":"b","text":"Administer in the abdomen, rotating sites"},{"id":"c","text":"Massage the injection site after administration"},{"id":"d","text":"Have protamine sulfate available as an antidote"},{"id":"e","text":"Use a 1-inch 21-gauge needle"},{"id":"f","text":"Monitor platelet count for HIT"}]'::jsonb, '{"ids":["a","b","d","f"]}'::jsonb, 'Monitor aPTT; rotate abdominal sites; keep protamine sulfate available; monitor platelets for HIT (day 5–10). Do NOT massage (causes bruising). Use 5/8-inch, 25–27 gauge needle for subcutaneous injection.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with a bowel obstruction has an NG tube on low intermittent suction. Labs: Na 138, K 2.9, Cl 88, HCO3 32. Which acid-base imbalance is present?', '[{"id":"a","text":"Metabolic acidosis"},{"id":"b","text":"Metabolic alkalosis"},{"id":"c","text":"Respiratory acidosis"},{"id":"d","text":"Respiratory alkalosis"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'NG suction removes gastric HCl, causing loss of H+ and Cl−. Result: elevated HCO3 (32), low Cl (88), and hypokalemia (2.9). This is metabolic alkalosis.', '', '', '', 'published'),
  ('Leadership and Management', 'sata', 'A nurse is delegating tasks to unlicensed assistive personnel (UAP). Which tasks can be safely delegated? (Select all that apply)', '[{"id":"a","text":"Measuring and recording urinary output"},{"id":"b","text":"Assessing a patient who reports increased pain"},{"id":"c","text":"Obtaining vital signs on a stable patient"},{"id":"d","text":"Teaching a patient how to use an incentive spirometer"},{"id":"e","text":"Reporting urine output of 20 mL/hr to the nurse"},{"id":"f","text":"Ambulating a post-stroke patient independently"}]'::jsonb, '{"ids":["a","c","e"]}'::jsonb, 'UAPs can measure and record I&O, obtain vital signs on stable patients, and report objective measurements. Assessment, teaching, and ambulating post-stroke patients require nursing judgment and cannot be delegated.', '', '', '', 'published'),
  ('NGN Case Studies', 'bow_tie', 'A 68-year-old client is admitted to the ICU with a 3-day history of productive cough, fever of 39.2°C, and confusion. Oxygen saturation is 88% on room air. BP is 88/54 mmHg. The client''s family reports he lives alone and has type 2 diabetes and COPD. ABGs: pH 7.28, PaCO2 52, HCO3 22. WBC 22,000. Chest X-ray shows bilateral infiltrates.', '[]'::jsonb, '{"ids":[]}'::jsonb, 'This client meets criteria for septic shock secondary to pneumonia with concurrent respiratory acidosis and hypoxemia. Priority actions: administer supplemental oxygen and position HOB 30–45°, initiate broad-spectrum antibiotics within the first hour, and establish IV access for fluid resuscitation. Key parameters to monitor: oxygen saturation and ABGs (respiratory status), blood pressure and MAP (hemodynamic stability), and blood cultures (source identification). Avoid vasopressors before adequate fluid resuscitation.', '', '', '', 'published'),
  ('NGN Case Studies', 'matrix', 'A nurse is caring for a 54-year-old client admitted for acute decompensated heart failure. Vitals: BP 156/98, HR 108, RR 26, SpO₂ 90%, temp 37.1°C. The client has 3+ pitting edema in bilateral lower extremities, JVD, and audible crackles bilaterally. Orders include: IV furosemide 40 mg, continuous cardiac monitoring, daily weights, sodium restriction 2g/day, and supplemental oxygen. For each nursing intervention, indicate whether it is Indicated, Contraindicated, or Not Applicable.', '[]'::jsonb, '{"ids":[]}'::jsonb, 'In acute decompensated HF: IV furosemide reduces fluid overload (Indicated); positioning HOB 45° reduces preload and improves oxygenation (Indicated); daily weights monitor fluid status (Indicated). Encouraging oral fluid intake worsens fluid overload (Contraindicated). Sodium restriction is already ordered and would be managed by dietary team, not a direct nursing intervention in this context (Not Applicable as a nursing action; it is a dietary order). Ambulating in the acute decompensated phase with SpO₂ 90% is Contraindicated.', '', '', '', 'published'),
  ('NGN Case Studies', 'ordered_response', 'A nurse receives a shift report on a client who had an emergency appendectomy 6 hours ago. On assessment, the nurse notes sudden onset of tachycardia (HR 128), diaphoresis, abdominal rigidity, and temperature 38.9°C. The client states the pain has changed from 4/10 to 9/10 and feels "different." Place the following nursing actions in the correct order of priority (1 = first action, 5 = last action).', '[{"id":"a","text":"Notify the surgeon immediately of assessment findings"},{"id":"b","text":"Assess the client''s airway, breathing, and circulation"},{"id":"c","text":"Obtain vital signs and oxygen saturation"},{"id":"d","text":"Prepare the client for potential return to the OR"},{"id":"e","text":"Document all findings and interventions in the medical record"}]'::jsonb, '{"ids":[],"order":["b","c","a","d","e"]}'::jsonb, 'Use the nursing process and ABCs. First: assess ABCs (B) — immediate threat identification. Second: obtain full vital signs and SpO₂ to quantify deterioration (C). Third: notify the surgeon with complete SBAR — these findings suggest peritonitis from anastomotic leak (A). Fourth: prepare client for surgical intervention which may be imminent (D). Finally: document all findings and the chain of communication (E).', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A nurse is administering warfarin. Which laboratory value should be monitored to evaluate therapeutic effectiveness?', '[{"id":"a","text":"aPTT"},{"id":"b","text":"PT/INR"},{"id":"c","text":"Platelet count"},{"id":"d","text":"Bleeding time"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Warfarin (a vitamin K antagonist) effectiveness is monitored with PT/INR. Therapeutic INR for most indications is 2.0–3.0. aPTT monitors heparin therapy.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A patient is receiving IV vancomycin. The nurse notices flushing, erythema, and hypotension developing during the infusion. What is the priority action?', '[{"id":"a","text":"Administer diphenhydramine IV push"},{"id":"b","text":"Stop the infusion and notify the provider"},{"id":"c","text":"Slow the infusion rate and monitor"},{"id":"d","text":"Obtain a vancomycin trough level"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Red Man Syndrome is a rate-related reaction to vancomycin, not a true allergy. Slowing the infusion rate (over 60–90 min) resolves symptoms. It is not an IgE-mediated hypersensitivity reaction requiring stopping the drug.', '', '', '', 'published'),
  ('Pharmacology', 'sata', 'A nurse is teaching a patient newly prescribed atorvastatin. Which instructions should be included? (Select all that apply)', '[{"id":"a","text":"Report unexplained muscle pain or weakness"},{"id":"b","text":"Avoid grapefruit juice"},{"id":"c","text":"Take the medication in the morning for best effect"},{"id":"d","text":"Monitor LFTs periodically"},{"id":"e","text":"Expect a rash during the first week"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Statins can cause myopathy/rhabdomyolysis (report muscle pain). Grapefruit inhibits CYP3A4 increasing statin levels. Liver function should be monitored. Statins are given at any time of day (not only morning). A rash is not expected.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A nurse is preparing to give morphine 4 mg IV to a post-op patient. Respirations are 10/min. What should the nurse do first?', '[{"id":"a","text":"Give the medication as prescribed — pain increases respiratory rate"},{"id":"b","text":"Withhold the medication and notify the provider"},{"id":"c","text":"Give half the dose and reassess in 15 minutes"},{"id":"d","text":"Administer oxygen before giving morphine"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Opioids are withheld when respirations are <12/min due to the risk of respiratory depression. The nurse should hold the dose and notify the provider immediately. Naloxone (Narcan) should be available.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'Which electrolyte imbalance increases a patient''s risk of digoxin toxicity?', '[{"id":"a","text":"Hypernatremia"},{"id":"b","text":"Hypokalemia"},{"id":"c","text":"Hypermagnesemia"},{"id":"d","text":"Hypercalcemia"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Hypokalemia potentiates digoxin toxicity because potassium and digoxin compete for the same receptor (Na-K ATPase pump). Low potassium increases digoxin binding and effect. Monitor and maintain K+ 3.5–5.0 mEq/L.', '', '', '', 'published'),
  ('Pharmacology', 'sata', 'A nurse is caring for a patient receiving heparin infusion. Which findings indicate possible heparin-induced thrombocytopenia (HIT)? (Select all that apply)', '[{"id":"a","text":"Platelet count dropped from 280,000 to 90,000 on day 8 of therapy"},{"id":"b","text":"New thrombus formation despite heparin therapy"},{"id":"c","text":"aPTT supratherapeutic at 130 seconds"},{"id":"d","text":"Skin necrosis at heparin injection sites"},{"id":"e","text":"Serum potassium of 3.2 mEq/L"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'HIT: >50% platelet drop on days 5–14, paradoxical new clotting, and skin necrosis at injection sites. Supratherapeutic aPTT reflects dosing, not HIT. Hypokalemia is unrelated. If HIT suspected, stop heparin immediately.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A patient with a penicillin allergy (hives) is prescribed cefazolin. What is the most appropriate nursing action?', '[{"id":"a","text":"Administer as prescribed — cephalosporins are unrelated to penicillin"},{"id":"b","text":"Hold the medication and verify the order with the provider"},{"id":"c","text":"Give a test dose and observe for 30 minutes"},{"id":"d","text":"Substitute oral amoxicillin instead"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'There is a small but real cross-reactivity between penicillins and cephalosporins (~1–2%). A penicillin allergy warrants clarification before administering a cephalosporin. The nurse should hold and verify. Amoxicillin is also a penicillin.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A nurse is administering IV potassium chloride 40 mEq. Which action is most important?', '[{"id":"a","text":"Administer by IV push over 2 minutes"},{"id":"b","text":"Dilute and infuse no faster than 10 mEq/hour peripherally"},{"id":"c","text":"Add to a 50 mL bag and give over 15 minutes"},{"id":"d","text":"Give orally instead to reduce cardiac risk"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'IV potassium must NEVER be given as a bolus — this causes fatal cardiac dysrhythmias. Maximum peripheral rate is 10 mEq/hr; central line max is 20 mEq/hr. Always dilute and monitor cardiac rhythm.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A patient on isoniazid (INH) for tuberculosis reports numbness and tingling in the feet. Which supplement should the nurse anticipate administering?', '[{"id":"a","text":"Vitamin C"},{"id":"b","text":"Pyridoxine (Vitamin B6)"},{"id":"c","text":"Folate"},{"id":"d","text":"Vitamin D"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'INH causes peripheral neuropathy by interfering with pyridoxine (B6) metabolism. Vitamin B6 supplementation is given prophylactically or to treat neuropathy in patients on INH, especially malnourished patients and the elderly.', '', '', '', 'published'),
  ('Pharmacology', 'sata', 'A nurse is reviewing medications for a patient prescribed MAOIs. Which substances should the patient avoid? (Select all that apply)', '[{"id":"a","text":"Aged cheeses"},{"id":"b","text":"Red wine"},{"id":"c","text":"Pseudoephedrine"},{"id":"d","text":"Fresh fruits"},{"id":"e","text":"Meperidine"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'MAOIs + tyramine-rich foods (aged cheese, red wine) → hypertensive crisis. MAOIs + sympathomimetics (pseudoephedrine) → hypertensive crisis. MAOIs + meperidine (Demerol) → serotonin syndrome or hyperpyrexic coma. Fresh fruits are safe.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A nurse is giving furosemide 40 mg IV. Which assessment finding requires immediate follow-up after administration?', '[{"id":"a","text":"Urine output 200 mL in the first hour"},{"id":"b","text":"Blood pressure decreased from 158/92 to 138/84"},{"id":"c","text":"Serum potassium dropped from 3.8 to 2.9 mEq/L"},{"id":"d","text":"Weight decreased by 0.5 kg"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Furosemide is a loop diuretic that wastes potassium. A drop to 2.9 mEq/L indicates hypokalemia (normal 3.5–5.0), which risks dangerous dysrhythmias. Potassium replacement should be initiated and the provider notified.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A patient taking methotrexate for rheumatoid arthritis calls to report mouth sores and a temperature of 38.6°C. What is the priority nursing response?', '[{"id":"a","text":"Advise the patient to use salt water rinses and monitor temperature"},{"id":"b","text":"Instruct the patient to go to the emergency department immediately"},{"id":"c","text":"Tell the patient to skip the next methotrexate dose"},{"id":"d","text":"Recommend acetaminophen and call back if temperature exceeds 39°C"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Methotrexate is an immunosuppressant. Fever with mucositis in an immunocompromised patient is a medical emergency — signs of severe bone marrow suppression and infection. The patient needs immediate evaluation and CBC.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'Which antidote should a nurse have available when administering IV magnesium sulfate?', '[{"id":"a","text":"Naloxone (Narcan)"},{"id":"b","text":"Protamine sulfate"},{"id":"c","text":"Calcium gluconate"},{"id":"d","text":"Flumazenil"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Calcium gluconate is the antidote for magnesium toxicity. Magnesium sulfate toxicity presents with absent reflexes, respiratory depression, and cardiac arrest. Calcium antagonizes magnesium''s CNS and neuromuscular effects.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A patient prescribed spironolactone asks what foods to limit. What should the nurse teach?', '[{"id":"a","text":"High-sodium foods"},{"id":"b","text":"High-potassium foods such as bananas and oranges"},{"id":"c","text":"High-fat foods"},{"id":"d","text":"Dairy products"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Spironolactone is a potassium-sparing diuretic. It retains potassium, so patients should limit high-potassium foods to prevent hyperkalemia (K+ >5.0 mEq/L), which causes dangerous dysrhythmias.', '', '', '', 'published'),
  ('Pharmacology', 'sata', 'A nurse is reviewing a patient''s medication list before administering the morning dose. Which medications require the nurse to take an apical pulse for one full minute before administration? (Select all that apply)', '[{"id":"a","text":"Digoxin"},{"id":"b","text":"Metoprolol"},{"id":"c","text":"Diltiazem"},{"id":"d","text":"Amlodipine"},{"id":"e","text":"Lisinopril"}]'::jsonb, '{"ids":["a","b","c"]}'::jsonb, 'Digoxin (cardiac glycoside), metoprolol (beta-blocker), and diltiazem (calcium channel blocker) all reduce heart rate — hold if apical pulse <60 bpm. Amlodipine (CCB) primarily reduces BP, not HR. Lisinopril (ACE inhibitor) does not significantly affect HR.', '', '', '', 'published'),
  ('Pharmacology', 'mcq', 'A nurse is preparing insulin. The order reads: "Regular insulin 10 units and NPH insulin 20 units subcutaneously." What is the correct preparation sequence?', '[{"id":"a","text":"Draw NPH first, then regular"},{"id":"b","text":"Draw regular first, then NPH"},{"id":"c","text":"Mix both in separate syringes and give two injections"},{"id":"d","text":"The order does not matter"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Memory aid: "Clear before cloudy." Regular insulin is clear; draw it first to prevent contaminating the regular vial with NPH (which is cloudy/modified). NPH contamination changes the action profile of regular insulin.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with chronic kidney disease has a serum potassium of 6.2 mEq/L and peaked T waves on ECG. Which intervention is the highest priority?', '[{"id":"a","text":"Administer sodium polystyrene sulfonate (Kayexalate) by mouth"},{"id":"b","text":"Prepare for emergent hemodialysis"},{"id":"c","text":"Administer IV calcium gluconate"},{"id":"d","text":"Start a low-potassium diet"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Peaked T waves with K+ 6.2 mEq/L indicates cardiac danger. IV calcium gluconate is given first to stabilize the cardiac membrane (does not lower K+ but prevents fatal arrhythmias). Then insulin/dextrose, Kayexalate, or dialysis to actually remove potassium.', '', '', '', 'published'),
  ('Medical-Surgical', 'sata', 'A nurse is caring for a patient with a pulmonary embolism (PE). Which findings are consistent with this diagnosis? (Select all that apply)', '[{"id":"a","text":"Sudden onset dyspnea"},{"id":"b","text":"Pleuritic chest pain"},{"id":"c","text":"Hemoptysis"},{"id":"d","text":"Bradycardia"},{"id":"e","text":"SpO2 88%"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Classic PE triad: dyspnea, pleuritic chest pain, hemoptysis. Hypoxia (low SpO2) and tachycardia (not bradycardia) are expected. Bradycardia is not a PE finding — the compensatory response is tachycardia.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient returns from cardiac catheterization via the right femoral artery. Which assessment finding requires immediate action?', '[{"id":"a","text":"Pedal pulse 2+ in right foot"},{"id":"b","text":"Small bruise at insertion site"},{"id":"c","text":"Right groin hematoma expanding rapidly"},{"id":"d","text":"Patient reports needing to void"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'A rapidly expanding hematoma at the femoral access site indicates arterial bleeding — a vascular emergency. Apply firm manual pressure and notify the provider immediately. The patient may need emergent intervention.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with COPD is admitted with exacerbation. ABGs show pH 7.32, PaCO2 58, PaO2 62, HCO3 26. Which interpretation is correct?', '[{"id":"a","text":"Respiratory alkalosis"},{"id":"b","text":"Metabolic acidosis"},{"id":"c","text":"Respiratory acidosis, partially compensated"},{"id":"d","text":"Metabolic alkalosis"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'pH 7.32 (acidosis), PaCO2 58 (elevated → respiratory cause), HCO3 26 (slightly elevated → renal compensation). This is respiratory acidosis with partial metabolic compensation — classic COPD exacerbation with CO2 retention.', '', '', '', 'published'),
  ('Medical-Surgical', 'sata', 'A nurse is caring for a patient following a total hip replacement. Which actions help prevent hip dislocation? (Select all that apply)', '[{"id":"a","text":"Keep an abduction pillow between legs"},{"id":"b","text":"Avoid hip flexion beyond 90 degrees"},{"id":"c","text":"Encourage the patient to cross their legs when sitting"},{"id":"d","text":"Use a raised toilet seat"},{"id":"e","text":"Avoid internal rotation of the operative leg"}]'::jsonb, '{"ids":["a","b","d","e"]}'::jsonb, 'Hip dislocation precautions: abduction pillow to keep hips apart, no flexion >90°, use raised toilet seat, avoid internal rotation and adduction. Crossing legs causes adduction and internal rotation — strictly prohibited.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with a nasogastric tube connected to low intermittent suction develops muscle cramps and positive Chvostek''s sign. Which electrolyte imbalance should the nurse suspect?', '[{"id":"a","text":"Hyperkalemia"},{"id":"b","text":"Hypocalcemia"},{"id":"c","text":"Hypernatremia"},{"id":"d","text":"Hypomagnesemia"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Chvostek''s sign (facial twitching when tapping facial nerve) and Trousseau''s sign indicate hypocalcemia. NG suction removes gastric acid (HCl), causing metabolic alkalosis, which decreases ionized calcium. Monitor calcium levels.', '', '', '', 'published')
) as seed(topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
where not exists (
  select 1
  from public.questions q
  where q.prompt = seed.prompt
);
