-- Safe seed Yingoh NCLEX question bank, part 15.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Respiratory', 'mcq', 'A client 30 minutes post-thoracentesis reports sudden sharp chest pain and dyspnea. Breath sounds are absent on the right. The nurse''s first action is to:', '[{"id":"a","text":"Administer the prescribed analgesic"},{"id":"b","text":"Position the client on the affected side"},{"id":"c","text":"Notify the provider immediately"},{"id":"d","text":"Encourage slow deep breathing"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Absent breath sounds + chest pain + dyspnea after thoracentesis = pneumothorax. Life-threatening complication. Notify the provider immediately for chest tube.', 'Post-thoracic procedure + absent breath sounds + dyspnea = pneumothorax until proven otherwise. Always notify provider first — this is an emergency.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client 30 minutes post-thoracentesis reports sudden sharp chest pain and dyspnea. Breath sounds are absent on the right. The nurse''s first action is to:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Renal and Urinary', 'mcq', 'A client with CKD has K⁺ 6.4 mEq/L and peaked T waves on the monitor. The nurse implements which intervention first?', '[{"id":"a","text":"Restrict dietary potassium"},{"id":"b","text":"Administer sodium polystyrene sulfonate orally"},{"id":"c","text":"Administer IV calcium gluconate as prescribed"},{"id":"d","text":"Prepare the client for hemodialysis"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Hyperkalemia with cardiac changes needs immediate cardiac membrane stabilization. IV calcium gluconate acts within minutes. Kayexalate removes K⁺ slowly (hours). Dialysis is definitive but not the immediate first step.', 'Hyperkalemia + cardiac changes = cardiac emergency. Stabilize the heart first with calcium gluconate, THEN remove potassium. Stabilize → eliminate.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with CKD has K⁺ 6.4 mEq/L and peaked T waves on the monitor. The nurse implements which intervention first?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Renal and Urinary', 'sata', 'A client is 2 days post-kidney transplant. Which findings require the nurse to notify the provider? Select all that apply.', '[{"id":"a","text":"Urine output 200 mL/hr"},{"id":"b","text":"Creatinine rising from 1.1 to 3.4 mg/dL"},{"id":"c","text":"Temperature 37.2°C (99°F)"},{"id":"d","text":"Graft site tenderness and swelling"},{"id":"e","text":"WBC 11,000/mm³ on tacrolimus"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Polyuria, rising creatinine, and graft tenderness signal acute rejection or ATN. Low-grade fever is expected post-op. Mild WBC elevation on immunosuppressants is expected.', 'Post-transplant "3 Cs": Creatinine rising, Clinical graft changes, output Changes (high or low). Any = notify provider. Low-grade fever and mild WBC elevation = expected.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client is 2 days post-kidney transplant. Which findings require the nurse to notify the provider? Select all that apply.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Endocrine', 'mcq', 'A client with type 1 diabetes is unresponsive with BG 38 mg/dL. An IV is in place. The nurse''s priority intervention is:', '[{"id":"a","text":"Give 4 oz of orange juice orally"},{"id":"b","text":"Administer 50 mL of 50% dextrose IV"},{"id":"c","text":"Administer glucagon 1 mg IM"},{"id":"d","text":"Recheck BG in 15 minutes"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Unresponsive + IV access + severe hypoglycemia = D50W IV (works in 1–3 min). Oral juice is contraindicated when unconscious — aspiration risk. Glucagon IM only when no IV access available.', 'Unresponsive + IV = D50W first. Conscious + no IV = oral glucose. No IV access at all = glucagon IM. IV route is always fastest in a hypoglycemic emergency.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with type 1 diabetes is unresponsive with BG 38 mg/dL. An IV is in place. The nurse''s priority intervention is:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Endocrine', 'sata', 'A client is admitted in diabetic ketoacidosis. Which findings does the nurse expect? Select all that apply.', '[{"id":"a","text":"Blood glucose > 300 mg/dL"},{"id":"b","text":"Kussmaul respirations"},{"id":"c","text":"Fruity acetone breath"},{"id":"d","text":"Serum pH of 7.48"},{"id":"e","text":"Positive urine ketones"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'DKA: hyperglycemia, metabolic acidosis (pH < 7.35), ketonuria, Kussmaul respirations (resp compensation), fruity breath. pH 7.48 = alkalosis — contradicts DKA acidosis.', 'DKA = High glucose + Low pH + Ketones + Kussmaul breathing. Eliminate pH 7.48 — DKA causes acidosis (low pH), never alkalosis.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client is admitted in diabetic ketoacidosis. Which findings does the nurse expect? Select all that apply.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Endocrine', 'mcq', 'A client is newly prescribed levothyroxine. Which instruction does the nurse provide?', '[{"id":"a","text":"Take with a glass of milk for better absorption"},{"id":"b","text":"Take at bedtime to minimize side effects"},{"id":"c","text":"Take on an empty stomach 30–60 minutes before breakfast"},{"id":"d","text":"Discontinue if you experience palpitations"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Levothyroxine absorption is best on an empty stomach 30–60 min before breakfast. Calcium (milk), antacids, and iron block absorption. Palpitations during titration = contact provider, do not self-discontinue.', 'Empty stomach + morning + 30–60 min before food = best levothyroxine absorption. Calcium and iron block it. Never instruct a client to self-discontinue any medication.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client is newly prescribed levothyroxine. Which instruction does the nurse provide?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Gastrointestinal', 'mcq', 'A client 2 days post-colostomy says "I should irrigate my colostomy every day to control output." The nurse recognizes this statement indicates:', '[{"id":"a","text":"Correct understanding of colostomy care"},{"id":"b","text":"A need for further teaching"},{"id":"c","text":"An appropriate long-term goal"},{"id":"d","text":"Standard discharge instruction"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Daily colostomy irrigation is NOT universally required and is not standard teaching. It is an optional technique for sigmoid colostomies. Standard teaching: empty at 1/3–1/2 full, skin care, avoid gas-producing foods.', 'Negative event query: "further teaching" = select the incorrect statement. Daily irrigation is not standard. This is a frequent NCLEX wrong-answer trap — do not confuse irrigation with routine pouch emptying.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client 2 days post-colostomy says "I should irrigate my colostomy every day to control output." The nurse recognizes this statement indicates:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Gastrointestinal', 'sata', 'A client has acute pancreatitis. Which interventions are appropriate? Select all that apply.', '[{"id":"a","text":"Keep the client NPO during the acute phase"},{"id":"b","text":"Administer IV opioid analgesics as prescribed"},{"id":"c","text":"Place the client in high-Fowler''s position"},{"id":"d","text":"Monitor serum amylase and lipase"},{"id":"e","text":"Encourage a high-fat diet to rest the pancreas"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Pancreatitis: NPO (rests pancreas), IV opioids for pain, monitor amylase/lipase. High-fat diet stimulates enzymes — contraindicated. Semi-Fowler''s with knees flexed for comfort, not high-Fowler''s.', 'REST the pancreas: NPO + pain control + monitor markers. High fat = stimulates enzyme secretion = worse. Eliminate both high fat and high-Fowler''s.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client has acute pancreatitis. Which interventions are appropriate? Select all that apply.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Neurological', 'mcq', 'A client with elevated ICP has BP 182/50 mmHg, HR 44 bpm, and irregular respirations. The nurse recognizes:', '[{"id":"a","text":"Orthostatic hypotension"},{"id":"b","text":"Cushing''s triad"},{"id":"c","text":"Autonomic dysreflexia"},{"id":"d","text":"Neurogenic shock"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Cushing''s triad = late severe ICP sign: hypertension with wide pulse pressure + bradycardia + irregular respirations. Signals impending brain herniation — medical emergency.', 'Cushing''s triad = Hypertension + Bradycardia + Irregular respirations in a neuro client. Wide pulse pressure is the vascular signature. Memorize this cluster — it is the most tested neuro vital sign pattern.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with elevated ICP has BP 182/50 mmHg, HR 44 bpm, and irregular respirations. The nurse recognizes:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Neurological', 'mcq', 'A client presents with sudden right-sided weakness, facial droop, and slurred speech with onset 45 minutes ago. The nurse''s priority action is:', '[{"id":"a","text":"Obtain an ECG"},{"id":"b","text":"Keep NPO and notify the stroke team"},{"id":"c","text":"Administer aspirin 325 mg immediately"},{"id":"d","text":"Prepare for cardiac catheterization"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Stroke symptoms within 4.5 hours = tPA window. Activate stroke team and get CT immediately. NPO for swallowing safety. Never give aspirin until CT rules out hemorrhagic stroke — aspirin in hemorrhagic stroke is fatal.', 'FAST within 4.5 hours = stroke team + CT first. No aspirin until hemorrhage is excluded. Time is brain — every minute = 1.9 million neurons lost.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client presents with sudden right-sided weakness, facial droop, and slurred speech with onset 45 minutes ago. The nurse''s priority action is:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Neurological', 'sata', 'A client has a tonic-clonic seizure. Which post-ictal nursing actions are appropriate? Select all that apply.', '[{"id":"a","text":"Position the client laterally"},{"id":"b","text":"Insert an oral airway during active seizing"},{"id":"c","text":"Assess for post-ictal confusion and fatigue"},{"id":"d","text":"Document seizure duration and characteristics"},{"id":"e","text":"Restrain the client''s movements"}]'::jsonb, '{"ids":["a","c","d"]}'::jsonb, 'Post-seizure: lateral position (prevents aspiration), assess post-ictal state, document details. Never insert anything into mouth (injury risk). Never restrain (increases injury).', 'Seizure nursing = Protect, Position lateral, Document. Two classic wrong-answer traps: inserting oral airway and restraining. Both cause harm. Nothing goes in the mouth.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client has a tonic-clonic seizure. Which post-ictal nursing actions are appropriate? Select all that apply.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Musculoskeletal', 'mcq', 'A client 6 hours post-hip replacement reports right foot pain, numbness, pallor, and capillary refill of 4 seconds. The nurse''s first action is to:', '[{"id":"a","text":"Elevate the right leg above heart level"},{"id":"b","text":"Apply a warm compress"},{"id":"c","text":"Notify the provider immediately"},{"id":"d","text":"Administer PRN pain medication"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'The 6 Ps post-orthopedic surgery (pain, pallor, paresthesia + prolonged capillary refill) = neurovascular compromise/compartment syndrome. Medical emergency — notify provider immediately. Elevation worsens arterial perfusion.', '6 Ps: Pain, Pallor, Pulselessness, Paresthesia, Paralysis, Poikilothermia. Any combination post-orthopedic = notify STAT. Pain medication alone treats the symptom while the limb is dying.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client 6 hours post-hip replacement reports right foot pain, numbness, pallor, and capillary refill of 4 seconds. The nurse''s first action is to:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Fluids and Electrolytes', 'mcq', 'A client receiving IV fluids has Na⁺ 128 mEq/L with headache and confusion. The nurse identifies:', '[{"id":"a","text":"Hypernatremia"},{"id":"b","text":"Hyponatremia"},{"id":"c","text":"Hyperkalemia"},{"id":"d","text":"Hypomagnesemia"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Normal Na⁺ = 135–145 mEq/L. Na⁺ 128 = hyponatremia. Low Na⁺ → water shifts into cells → cerebral edema → neurological symptoms: headache, confusion, nausea, seizures.', '128 < 135 = low sodium = hyponatremia. Low Na⁺ → water into brain cells → brain swells → neuro symptoms. Direct knowledge question — know the normal sodium range.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client receiving IV fluids has Na⁺ 128 mEq/L with headache and confusion. The nurse identifies:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Fluids and Electrolytes', 'sata', 'A client has K⁺ 2.8 mEq/L. Which manifestations does the nurse expect? Select all that apply.', '[{"id":"a","text":"Muscle weakness and fatigue"},{"id":"b","text":"Peaked T waves on ECG"},{"id":"c","text":"Hypoactive bowel sounds"},{"id":"d","text":"Flat or inverted T waves on ECG"},{"id":"e","text":"U waves on ECG"}]'::jsonb, '{"ids":["a","c","d","e"]}'::jsonb, 'Hypokalemia (K⁺ < 3.5): muscle weakness, hypoactive bowel/ileus, flat/inverted T waves, U waves. Peaked T waves = HYPERKALEMIA.', 'HyperK = Peaked T waves. HypoK = Flat T + U waves. Peaked T is the wrong-answer trap here — eliminate it.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client has K⁺ 2.8 mEq/L. Which manifestations does the nurse expect? Select all that apply.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Complex Care', 'mcq', 'A nurse has 4 assigned clients. Which client is assessed first?', '[{"id":"a","text":"Client with COPD requesting pain medication for chronic back pain"},{"id":"b","text":"Post-appendectomy day 2 asking for a bedpan"},{"id":"c","text":"Client with chest pain radiating to the left arm and diaphoresis"},{"id":"d","text":"Diabetic client reporting hunger before breakfast"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Chest pain + left arm radiation + diaphoresis = potential MI = life-threatening emergency. The other clients have non-life-threatening, stable needs.', 'Priority = ABC. Ask: "Who could die in the next few minutes?" Chest pain + radiation + diaphoresis = possible MI = first. Apply this decision rule every time.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse has 4 assigned clients. Which client is assessed first?');
