-- Batch 04: 72 draft questions across the three highest-weight clinical categories.
-- Requires the structured seed function created by Batch 02.

-- Pharmacological and Parenteral Therapies
select public.seed_structured_concept('expansion-batch-04','tpa-alteplase','Pharmacology','alteplase therapy for acute ischemic stroke','an eligible client within the treatment window after hemorrhage has been excluded','Verify eligibility, blood pressure, timing, and bleeding risks before administration','Report severe headache, vomiting, bleeding, or sudden neurologic worsening immediately','Sudden severe headache with acute hypertension during infusion','Give an IM injection after treatment','Insert invasive lines immediately after infusion','Administer when intracranial bleeding is suspected','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-04','nitroglycerin','Pharmacology','sublingual nitroglycerin for angina','chest pressure in a client with a current prescription','Stop activity, sit down, take the prescribed dose, and activate emergency care when pain persists','Keep tablets protected from heat and replace them by the labeled expiration date','Severe hypotension after recent phosphodiesterase-5 inhibitor use','Stand while taking the medicine','Swallow sublingual tablets whole','Take sildenafil together to improve circulation','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-04','beta-blocker','Pharmacology','beta-blocker therapy','metoprolol prescribed after myocardial infarction','Check heart rate and blood pressure and use ordered hold parameters','Do not stop abruptly and report fainting, wheezing, or marked bradycardia','Heart rate 42/min with dizziness','Double the dose after a missed tablet','Stop suddenly when blood pressure improves','Use extra doses for acute chest pain','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-04','spironolactone','Pharmacology','spironolactone therapy','heart failure with potassium-sparing diuretic treatment','Monitor potassium, renal function, blood pressure, and fluid status','Avoid potassium salt substitutes and report weakness or palpitations','Potassium 6.1 mEq/L with peaked T waves','Take potassium supplements routinely','Use NSAIDs daily without consultation','Increase high-potassium foods after renal decline','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-04','levothyroxine','Pharmacology','levothyroxine replacement','new treatment for primary hypothyroidism','Give consistently on an empty stomach and monitor thyroid response','Take it at the same time apart from iron or calcium and expect long-term therapy','Chest pain and new rapid irregular pulse after a dose increase','Stop when energy improves','Take with calcium at the same moment','Change brands repeatedly without monitoring','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-04','rifampin','Pharmacology','rifampin therapy','multidrug treatment for active tuberculosis','Review liver function, interactions, adherence, and companion medications','Orange body fluids are expected, but jaundice, severe nausea, or missed doses require follow-up','Jaundice with dark urine and right-upper-quadrant pain','Use hormonal contraception as the only method without discussion','Stop companion tuberculosis drugs','Skip doses whenever secretions turn orange','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-04','tacrolimus','Pharmacology','tacrolimus after organ transplant','immunosuppression requiring trough monitoring','Monitor trough level, renal function, potassium, glucose, and infection signs','Avoid grapefruit and report fever, reduced urine, tremor, or medication changes','Rising creatinine with potassium 6.0 mEq/L','Receive live vaccines without approval','Take grapefruit juice with each dose','Stop medication when feeling well','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-04','epidural-opioid','Pharmacology','epidural opioid analgesia','postoperative analgesia through an epidural catheter','Monitor respiratory rate, sedation, blood pressure, pain, and catheter site','Call before walking and report itching, weakness, numbness, or breathing difficulty','Respirations 7/min with increasing sedation','Apply an unapproved heating pad over the catheter','Ambulate alone immediately','Give additional sedatives without reassessment','Pharmacological and Parenteral Therapies');

-- Reduction of Risk Potential
select public.seed_structured_concept('expansion-batch-04','post-thyroidectomy','Medical-Surgical','post-thyroidectomy complications','a client several hours after thyroid surgery','Keep airway equipment available and assess voice, breathing, neck swelling, and calcium signs','Support the neck and report breathing difficulty, tingling, cramping, or rapidly increasing swelling','Stridor with tense neck swelling','Place the client flat without neck support','Encourage forceful coughing repeatedly','Delay reporting new tingling until morning','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-04','post-carotid','Medical-Surgical','post-carotid endarterectomy care','a client returning from carotid surgery','Monitor neurologic status, airway, neck swelling, and blood pressure closely','Report severe headache, weakness, speech change, or neck swelling immediately','New aphasia with unilateral weakness','Flex the neck sharply','Allow uncontrolled severe hypertension','Massage the surgical neck','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-04','lumbar-puncture','Medical-Surgical','complications after lumbar puncture','a client after cerebrospinal-fluid sampling','Monitor neurologic status, puncture site, and prescribed positioning and hydration','Report persistent severe headache, fever, drainage, weakness, or confusion','Decreasing consciousness with new focal weakness','Encourage immediate strenuous exercise','Ignore clear drainage from the site','Give anticoagulants without reviewing orders','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-04','liver-biopsy','Medical-Surgical','post-liver-biopsy hemorrhage risk','a client returning from percutaneous liver biopsy','Position as prescribed on the right side and monitor vital signs, pain, and bleeding','Avoid heavy lifting and report dizziness, increasing abdominal pain, or bleeding','Tachycardia, hypotension, and increasing right-upper-quadrant pain','Place on the left side immediately','Encourage coughing without support','Give an anticoagulant before reassessment','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-04','bronchoscopy-recovery','Medical-Surgical','recovery after bronchoscopy','a client with topical airway anesthesia after the procedure','Keep NPO until gag and swallow reflexes return and monitor breathing and bleeding','Do not eat or drink until swallowing sensation returns and report breathing difficulty or substantial blood','Stridor with increasing respiratory distress','Offer water immediately to test comfort','Give solid food while the throat is numb','Treat large-volume hemoptysis as expected','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-04','pacemaker-malfunction','Medical-Surgical','pacemaker malfunction','a paced client with dizziness and pacing spikes not followed by QRS complexes','Assess the client, verify connections, notify the provider, and prepare backup pacing','Check the pulse, keep follow-up appointments, and report dizziness, syncope, or persistent hiccups','Syncope with failure to capture on the monitor','Place a magnet routinely over the device','Ignore dizziness when spikes are visible','Allow strong magnets directly over the generator','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-04','cast-neurovascular','Medical-Surgical','neurovascular compromise under a cast','increasing pain, numbness, pallor, and delayed capillary refill','Perform urgent neurovascular assessment and notify the provider immediately','Elevate as directed and report increasing pain, tightness, numbness, coolness, or color change','Inability to move digits with worsening pain despite medication','Insert objects under the cast to scratch','Cover a damp cast with plastic','Wait for complete pulse loss before reporting','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-04','tracheostomy-obstruction','Medical-Surgical','tracheostomy obstruction','sudden distress, noisy breathing, and inability to pass a suction catheter','Call for help, remove the inner cannula if applicable, suction, and prepare emergency airway equipment','Humidify as directed and report thick secretions, difficult suctioning, or breathing distress','Cyanosis with absent airflow through the tube','Force the suction catheter repeatedly','Leave the obturator unavailable','Cover the tracheostomy opening tightly','Reduction of Risk Potential');

-- Physiological Adaptation
select public.seed_structured_concept('expansion-batch-04','septic-shock','Emergency and Critical Care','septic shock','suspected infection, lactate elevation, hypotension, and altered perfusion','Obtain cultures promptly, begin prescribed broad-spectrum antibiotics and fluids, and reassess perfusion','Seek early care for infection with confusion, breathing difficulty, mottled skin, or very low urine output','Persistent hypotension and rising lactate after initial fluids','Delay antibiotics until every culture is final','Give only hypotonic oral fluids','Ignore falling urine output','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-04','anaphylactic-shock','Emergency and Critical Care','anaphylaxis','wheezing, urticaria, facial swelling, and hypotension after medication','Give intramuscular epinephrine promptly and support airway and circulation','Carry prescribed epinephrine, use it immediately for systemic symptoms, and call emergency services','Increasing stridor with rapidly falling blood pressure','Give an oral antihistamine as the only first treatment','Make the client walk to improve circulation','Delay epinephrine until a rash spreads','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-04','neurogenic-shock','Emergency and Critical Care','neurogenic shock after spinal injury','hypotension, bradycardia, warm skin, and impaired temperature regulation','Maintain spinal alignment, support blood pressure, and treat bradycardia as prescribed','Prevent pressure injury and report dizziness, breathing change, or temperature problems','Worsening hypotension with bradycardia and respiratory weakness','Place the client upright without support','Apply direct high heat to numb skin','Assume warm skin excludes shock','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-04','acute-chest-syndrome','Medical-Surgical','acute chest syndrome','sickle cell disease with fever, chest pain, infiltrate, and hypoxemia','Give oxygen, analgesia, antibiotics and supportive therapy as prescribed and prepare escalation','Seek emergency care for fever, chest pain, cough, or breathing difficulty','Rapidly increasing oxygen requirement with multilobar infiltrates','Restrict fluids completely','Delay antibiotics until sputum culture results','Use cold exposure to reduce pain','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-04','myasthenic-crisis','Medical-Surgical','myasthenic crisis','rapidly worsening bulbar weakness, weak cough, and respiratory fatigue','Assess respiratory strength, protect the airway, and prepare ventilatory support','Take medicines on schedule and report infection, swallowing difficulty, or increasing weakness','Declining vital capacity with inability to handle secretions','Give food before swallowing assessment','Administer sedatives for distress','Delay respiratory measurements until cyanosis','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-04','adrenal-crisis','Medical-Surgical','acute adrenal crisis','vomiting, severe hypotension, hyponatremia, hyperkalemia, and hypoglycemia','Give prescribed IV hydrocortisone, isotonic fluid, and glucose support promptly','Never stop steroids abruptly and use prescribed stress dosing during illness','Refractory hypotension with worsening altered consciousness','Restrict sodium and fluid','Withhold steroid until cortisol results return','Encourage strenuous activity','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-04','malignant-hyperthermia','Emergency and Critical Care','malignant hyperthermia','rapid carbon-dioxide rise, muscle rigidity, tachycardia, and hyperthermia during anesthesia','Stop triggering agents, give dantrolene, cool the client, and treat complications','Tell anesthesia teams about personal or family reactions and consider medical-alert identification','Generalized rigidity with rapidly rising end-tidal carbon dioxide','Continue the anesthetic at a lower dose','Use antipyretics as the only treatment','Delay dantrolene until genetic confirmation','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-04','tumor-lysis','Medical-Surgical','tumor lysis syndrome','recent chemotherapy with hyperkalemia, hyperphosphatemia, hypocalcemia, and rising uric acid','Begin prescribed hydration, cardiac monitoring, and uric-acid and electrolyte management','Maintain prescribed hydration and report weakness, cramping, reduced urine, or palpitations','Peaked T waves with oliguria and rising creatinine','Give potassium supplements','Restrict fluids without an indication','Delay laboratory monitoring for several days','Physiological Adaptation');

-- Retained for the next held batch.
