-- Batch 07: 288 drafts; broader specialty and lifespan coverage.

-- Management of Care
select public.seed_structured_concept('expansion-batch-07','case-management','Leadership and Delegation','complex discharge case management','a client has new disability, housing insecurity, and several specialty appointments','Identify barriers early and coordinate an interdisciplinary plan with one accountable transition pathway','Keep one current medication and appointment plan and contact the care coordinator when barriers arise','The client is discharged without essential equipment or a safe destination','Give disconnected referrals without follow-up','Assume the family can provide all care','Wait until discharge day to assess barriers','Management of Care');
select public.seed_structured_concept('expansion-batch-07','interfacility-transfer','Leadership and Delegation','safe interfacility transfer','an unstable client requires a higher level of care','Stabilize within capability, confirm acceptance, send essential records, and use appropriately equipped transport','Provide the receiving team with current condition, treatments, allergies, risks, and pending results','The client deteriorates during transport that lacks required monitoring','Send before a receiving clinician accepts','Use private transport for an unstable client','Omit recent medication administration','Management of Care');
select public.seed_structured_concept('expansion-batch-07','delegate-intake-output','Leadership and Delegation','delegating intake and output','a stable client requires strict fluid-balance measurement','Specify what to measure and when to report and validate unexpected totals','Record all oral, enteral, IV, urine, drain, and emesis amounts as instructed','Urine output is 15 mL/hr and is not reported','Ask assistive personnel to prescribe fluids','Estimate unmeasured output as normal','Discard drainage before measurement','Management of Care');
select public.seed_structured_concept('expansion-batch-07','decision-capacity','Leadership and Delegation','decision-making capacity','a client with fluctuating cognition refuses a high-risk procedure','Assess decision-specific understanding, appreciation, reasoning, and ability to communicate a choice','Capacity can fluctuate and is evaluated for the specific decision rather than assumed from diagnosis','A confused client cannot explain consequences but consent is obtained without evaluation','Assume all dementia removes capacity','Use orientation alone as the full assessment','Let convenience determine the surrogate','Management of Care');
select public.seed_structured_concept('expansion-batch-07','restraint-order','Leadership and Delegation','legal restraint management','a client remains immediately dangerous after alternatives fail','Obtain the required order, use the least restrictive option, monitor continuously as indicated, and discontinue early','Restraints require ongoing assessment, basic care, documentation, and repeated attempts at release','A restraint continues after danger resolves without reassessment','Use a standing PRN restraint order','Apply for punishment','Renew automatically without evaluation','Management of Care');
select public.seed_structured_concept('expansion-batch-07','incident-command','Leadership and Delegation','hospital incident command','a mass-casualty event overwhelms normal operations','Follow incident command roles, communicate through designated channels, and conserve critical resources','Report to the assigned role and avoid self-deployment outside the coordinated response','Conflicting unverified instructions cause evacuation into danger','Bypass command to create a separate plan','Share unconfirmed information publicly','Use scarce resources without tracking','Management of Care');

-- Safety and Infection Prevention and Control
select public.seed_structured_concept('expansion-batch-07','hand-hygiene-moments','Safety and Infection Control','healthcare hand hygiene','a nurse moves between contaminated and clean care tasks','Perform hand hygiene before clean contact and after body-fluid, client, glove, or environmental exposure','Gloves do not replace hand hygiene and must be changed between dirty and clean tasks','The nurse moves from perineal care to a central-line dressing with unchanged gloves','Wash gloves instead of changing them','Use one pair for two clients','Skip hygiene after touching bed rails','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-07','disseminated-zoster','Safety and Infection Control','disseminated herpes zoster','an immunocompromised client has widespread vesicular lesions','Use airborne and contact precautions and cover lesions during essential transport','Avoid susceptible contacts until lesions crust and follow exposure guidance','A nonimmune pregnant worker enters without protection','Use droplet precautions alone','Leave lesions uncovered in common areas','Assign susceptible personnel','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-07','rsv-contact','Safety and Infection Control','RSV transmission prevention','an infant has copious respiratory secretions and bronchiolitis','Use contact precautions and standard precautions with dedicated equipment','Clean hands and high-touch objects and keep symptomatic visitors away from vulnerable infants','Shared suction equipment is used without disinfection','Use only airborne precautions','Share toys without cleaning','Keep contaminated gloves between tasks','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-07','cjd-instruments','Safety and Infection Control','possible prion contamination','reusable neurosurgical instruments contact high-risk tissue','Quarantine instruments and follow the specialized prion decontamination or disposal protocol','Standard routine processing may be insufficient for instruments exposed to high-risk prion tissue','Potentially contaminated instruments return to routine circulation','Use ordinary surface wipes only','Mix instruments with the general set','Ignore tissue-risk classification','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-07','hazardous-drug-ppe','Safety and Infection Control','hazardous-drug handling','a nurse prepares and administers antineoplastic medicine','Use designated engineering controls, chemotherapy-rated PPE, and closed-system practices when required','Handle body fluids and contaminated waste with prescribed hazardous-drug precautions','A drug splash reaches an unprotected eye','Use a surgical mask as the only protection','Crush hazardous tablets in open air','Discard contaminated tubing in regular waste','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-07','suspicious-powder','Safety and Infection Control','a suspicious powder exposure','an unknown powder spills from a package in a clinic','Isolate the area, avoid disturbing material, notify emergency authorities, and follow decontamination guidance','Do not shake, smell, clean, or transport an unknown suspicious substance','Staff sweep the powder and develop respiratory symptoms','Use a household vacuum','Carry the package through the building','Ask unprotected staff to inspect closely','Safety and Infection Prevention and Control');

-- Health Promotion and Maintenance
select public.seed_structured_concept('expansion-batch-07','menopause-health','Health Promotion','menopause health promotion','a client reports hot flashes and asks about long-term health','Assess symptoms and individualized bone, cardiovascular, sexual, sleep, and cancer risks','Use layered clothing, regular activity, sleep support, and shared decision-making for treatment options','Postmenopausal bleeding occurs after months without menses','Treat all bleeding as expected','Use unregulated hormones without review','Stop preventive screening','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-07','puberty-education','Health Promotion','puberty education','a preadolescent asks about body and emotional changes','Provide accurate inclusive anticipatory guidance about growth, hygiene, menstruation, erections, mood, consent, and privacy','Body changes occur at different times; ask a trusted adult or clinician about concerns','The child reports unwanted sexual contact and fear of going home','Use shame-based language','Promise secrecy for abuse','Compare development critically with peers','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-07','newborn-screening','Maternal and Newborn','newborn screening','parents ask why an apparently healthy infant needs tests','Explain metabolic, hearing, and critical-heart screening and ensure timely collection and follow-up','A normal appearance does not exclude screened conditions; repeat testing may be required','A critical screen result is not communicated or followed','Delay all screening until symptoms appear','Assume one inadequate sample is final','Skip hearing follow-up after a refer result','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-07','oral-health','Health Promotion','preventive oral health','an adult has gum bleeding and irregular dental care','Assess oral habits and access and encourage fluoride, brushing, interdental cleaning, and dental evaluation','Persistent sores, lumps, bleeding, pain, or swallowing difficulty need professional assessment','A nonhealing oral ulcer with neck swelling and weight loss','Use tobacco for tooth pain','Stop brushing bleeding gums entirely','Place aspirin directly on oral tissue','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-07','exercise-prescription','Health Promotion','safe exercise initiation','a sedentary adult with chronic disease wants to become active','Assess symptoms and risks and build gradual aerobic, strength, balance, and flexibility activity','Start slowly, warm up, hydrate as appropriate, and stop for chest pain, faintness, or severe breathlessness','Exertional chest pressure with syncope','Begin maximal intensity immediately','Exercise through severe symptoms','Ignore prescribed limitations','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-07','travel-health','Health Promotion','international travel preparation','a client plans travel to a region with infectious and environmental risks','Review itinerary early for vaccines, malaria prevention, food, water, injury, and chronic-medicine planning','Carry medicines in labeled containers and use destination-specific bite and food precautions','Fever and confusion develop after return from a malaria-risk area','Wait until departure day for vaccines','Drink untreated water','Pack essential medicine only in checked luggage','Health Promotion and Maintenance');

-- Psychosocial Integrity
select public.seed_structured_concept('expansion-batch-07','somatic-symptoms','Mental Health','somatic symptom disorder','distressing physical symptoms persist despite repeated reassuring tests','Validate suffering, assess new changes, and coordinate consistent visits focused on function and coping','Use one care team and avoid repeated unplanned testing while still reporting genuinely new warning signs','New focal weakness and speech change is dismissed as somatic','Tell the client symptoms are imaginary','Order duplicate invasive tests automatically','Avoid all physical assessment','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-07','dissociation','Mental Health','acute dissociation','a trauma survivor feels unreal and disconnected from surroundings','Ensure safety and use calm grounding through present sensory cues and orientation','Practice grounding skills and seek help when episodes impair safety or functioning','The client becomes unresponsive near traffic during an episode','Force detailed trauma recall immediately','Use unexpected touch','Argue that the experience is impossible','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-07','alcohol-screening','Mental Health','unhealthy alcohol use screening','an adult minimizes drinking despite injuries and missed work','Use a validated screen, assess withdrawal risk, and offer nonjudgmental brief intervention and treatment','Be honest about amount and timing because abrupt cessation after heavy use may require medical support','The client stops heavy use and develops hallucinations and a seizure','Use moral confrontation','Recommend abrupt unsupervised cessation despite prior withdrawal seizures','Ignore interactions with sedatives','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-07','elder-maltreatment','Mental Health','suspected elder maltreatment','an older adult has unexplained injuries and a fearful caregiver interaction','Interview privately, assess immediate safety and capacity, document findings, and follow reporting law','Keep emergency contacts and seek help for threats, neglect, exploitation, or withheld necessities','The caregiver prevents urgent treatment and threatens the client','Confront the caregiver before securing safety','Promise absolute secrecy','Attribute injuries to age without assessment','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-07','acute-crisis','Mental Health','an acute situational crisis','a client is overwhelmed after sudden loss and cannot identify a next step','Assess safety and supports, define the immediate problem, and create one achievable short-term plan','Use trusted supports and emergency resources when coping fails or safety concerns emerge','The client states there is no reason to live and has access to a firearm','Explore distant childhood before current safety','Offer many complex decisions','Leave the client isolated','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-07','sleepwalking-safety','Mental Health','sleepwalking','a child repeatedly walks through the home while asleep','Protect the environment, secure exits and stairs, and assess triggers and injury risk','Use regular sleep, reduce deprivation, and gently guide rather than abruptly frighten the child','The child exits the house near a roadway during an episode','Lock the child alone in a room','Shake and shout during episodes','Place obstacles around the bed','Psychosocial Integrity');

-- Basic Care and Comfort
select public.seed_structured_concept('expansion-batch-07','renal-diet-comfort','Fundamentals','nutrition with advanced kidney disease','a client has poor appetite, hyperkalemia, and prescribed dietary limits','Coordinate individualized protein, sodium, potassium, phosphorus, fluid, and calorie needs with renal nutrition services','Use the prescribed food plan and ask before using salt substitutes or supplements','Progressive weakness and palpitations with potassium 6.2 mEq/L','Use potassium salt substitute freely','Follow a generic high-protein diet without review','Drink unlimited fluid despite restriction','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-07','aspiration-position','Fundamentals','aspiration-risk positioning','a drowsy client is receiving oral care and secretion management','Use side-lying or upright positioning as condition permits and keep suction available','Remain upright for oral intake and stop if coughing or wet voice occurs','Gurgling, cyanosis, and sudden oxygen decline','Place flat supine during feeding','Pour fluids into the mouth','Continue intake through coughing','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-07','denture-care','Fundamentals','denture and oral-tissue care','an older adult has loose dentures and irritated gums','Remove and clean dentures, inspect mucosa, and store safely in labeled solution','Remove dentures at night as advised and report persistent sores or poor fit','A nonhealing ulcer beneath a denture with weight loss','Use hot water that warps dentures','Wrap dentures in tissue on a meal tray','Wear painful loose dentures continuously','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-07','fecal-impaction','Fundamentals','fecal impaction','an immobile client has rectal pressure and liquid stool seepage','Assess for impaction and use prescribed removal and bowel-regimen measures','Report persistent constipation, seepage, pain, vomiting, or inability to pass stool','Bradycardia and syncope during digital removal','Give bulk fiber during complete obstruction','Perform digital removal without an order or monitoring','Ignore liquid seepage as diarrhea','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-07','cold-therapy','Fundamentals','safe cold therapy','a client has an acute soft-tissue injury and intact circulation','Wrap the cold source, limit application time, and reassess skin, pain, and circulation','Stop cold for numbness, pallor, blistering, or worsening pain','Mottled insensate skin under the cold pack','Apply ice directly for an hour','Use over impaired sensation without checks','Sleep on the cold pack','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-07','body-mechanics','Fundamentals','safe client handling','a dependent client requires repositioning in bed','Use mobility assessment, friction-reducing devices, sufficient staff, and mechanical lift when indicated','Follow transfer instructions and avoid pulling on staff or unstable furniture','A manual lift is attempted despite equipment indicating a full mechanical lift','Twist while lifting','Pull the client by the arms','Ask one small caregiver to lift alone','Basic Care and Comfort');

-- Pharmacological and Parenteral Therapies
select public.seed_structured_concept('expansion-batch-07','theophylline','Pharmacology','theophylline therapy','a client with chronic lung disease develops nausea and tremor','Hold as indicated, obtain a serum level, and review interacting medicines and smoking changes','Keep caffeine and smoking habits consistent and report vomiting, tremor, palpitations, or seizures','Ventricular dysrhythmia with a markedly elevated level','Double the dose during wheezing','Consume large caffeine amounts','Ignore vomiting as expected','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-07','valproate','Pharmacology','valproate therapy','treatment for seizures or bipolar disorder','Monitor liver function, blood counts, pregnancy risk, pancreatitis signs, and level when indicated','Use effective pregnancy planning and report severe abdominal pain, jaundice, bruising, or lethargy','Severe epigastric pain with vomiting and elevated lipase','Stop abruptly after one missed period','Use during pregnancy without specialist review','Ignore unusual bleeding','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-07','lamotrigine','Pharmacology','lamotrigine therapy','a client recently started dose titration','Titrate slowly and stop and seek urgent evaluation for concerning rash or mucosal lesions','Follow the titration exactly and report any new rash, blister, fever, or mouth sore','Blistering rash with facial swelling and oral lesions','Restart at the full dose after a long interruption','Increase rapidly for faster effect','Cover a new rash and continue','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-07','allopurinol','Pharmacology','allopurinol therapy','urate-lowering treatment for recurrent gout','Review renal function and interactions and stop for serious rash or hypersensitivity signs','Take consistently with prescribed hydration and understand it does not treat immediate attack pain','Rash, fever, facial swelling, and liver injury','Double the dose during an acute flare','Continue through a blistering rash','Use with interacting azathioprine without adjustment','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-07','epoetin','Pharmacology','epoetin alfa therapy','anemia of chronic kidney disease treated with an erythropoiesis-stimulating agent','Verify hemoglobin, iron status, blood pressure, and thrombosis risk before dosing','Keep laboratory and blood-pressure checks and report chest pain, severe headache, or unilateral swelling','Rapid hemoglobin rise with severe hypertension and neurologic symptoms','Give for uncontrolled hypertension','Target a normal high hemoglobin routinely','Skip iron evaluation','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-07','filgrastim','Pharmacology','filgrastim therapy','chemotherapy-related neutropenia','Monitor absolute neutrophil count, timing, bone pain, and splenic or respiratory symptoms','Report left-upper-abdominal or shoulder pain, severe breathing difficulty, or allergic symptoms','Left-upper-quadrant pain with hypotension','Give too close to cytotoxic chemotherapy against protocol','Ignore respiratory distress','Shake the prefilled syringe vigorously','Pharmacological and Parenteral Therapies');

-- Reduction of Risk Potential
select public.seed_structured_concept('expansion-batch-07','aaa-repair','Medical-Surgical','complications after abdominal aortic aneurysm repair','a client requires close perfusion and graft surveillance','Monitor hemodynamics, distal pulses, urine output, abdomen, and signs of bleeding or ischemia','Report sudden abdominal or back pain, cool legs, faintness, or reduced urine immediately','Loss of femoral pulses with severe abdominal pain and hypotension','Encourage immediate heavy lifting','Ignore declining urine output','Massage a cool pulseless leg','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-07','cabg-postop','Medical-Surgical','early complications after coronary bypass surgery','a client has mediastinal tubes, pacing wires, and invasive monitoring','Monitor hemodynamics, rhythm, drainage, perfusion, lungs, and signs of tamponade','Use sternal precautions and report chest clicking, fever, drainage, palpitations, or worsening breathlessness','Abrupt cessation of chest drainage with hypotension and rising venous pressure','Milk tubes aggressively without policy','Use arms to push from a chair','Ignore new atrial fibrillation','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-07','craniotomy-postop','Medical-Surgical','post-craniotomy neurologic deterioration','a client returns after intracranial surgery','Perform frequent neurologic and airway assessment while maintaining ordered head alignment and seizure precautions','Report worsening headache, vomiting, weakness, confusion, seizure, or clear drainage immediately','New unequal pupils with decreasing consciousness','Flex the neck sharply','Place flat despite increased-pressure risk','Delay reporting a seizure','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-07','nephrectomy-postop','Medical-Surgical','complications after nephrectomy','a client has one remaining kidney after surgery','Monitor urine output, renal function, bleeding, respiratory status, and flank incision','Protect kidney health and report reduced urine, fever, increasing pain, or wound drainage','Oliguria with rising creatinine and hypotension','Give nephrotoxic medicine without review','Ignore low urine because one kidney was removed','Encourage dehydration','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-07','amputation-postop','Medical-Surgical','post-amputation complications','a client has residual-limb pain and immobility risk','Assess bleeding, perfusion, positioning, contracture prevention, pain, and phantom sensation','Use prescribed positioning and exercises and report wound change or uncontrolled pain','Rapidly saturating dressing with hypotension','Keep the hip flexed continuously','Place a pillow under the residual limb long term','Dismiss phantom pain as imaginary','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-07','thoracentesis','Medical-Surgical','complications after thoracentesis','a client develops symptoms after pleural-fluid removal','Monitor breathing, oxygenation, puncture site, and signs of pneumothorax or re-expansion edema','Report sudden chest pain, dyspnea, persistent cough, or bleeding immediately','Sudden unilateral absent breath sounds with hypoxemia','Position flat on the puncture side without assessment','Ignore severe coughing and pink sputum','Encourage strenuous activity immediately','Reduction of Risk Potential');

-- Physiological Adaptation
select public.seed_structured_concept('expansion-batch-07','afib-rvr','Emergency and Critical Care','atrial fibrillation with rapid ventricular response','an irregular rate of 170/min with chest pain and hypotension','Prepare immediate synchronized cardioversion while supporting airway and circulation','Take rate-control and anticoagulant medicines exactly as directed and report syncope, chest pain, or stroke signs','Hypotension and altered consciousness with persistent rapid rhythm','Delay treatment for routine laboratory results','Encourage walking','Use unsynchronized shock for a perfusing rhythm','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-07','hypertensive-emergency','Emergency and Critical Care','hypertensive emergency','severe blood pressure elevation with pulmonary edema and neurologic change','Begin controlled IV blood-pressure reduction with continuous organ-perfusion monitoring','Take medicines consistently and seek emergency care for severe pressure with chest pain, breathlessness, or neurologic symptoms','New seizure and acute pulmonary edema','Lower pressure to normal instantly','Give unmonitored oral doses repeatedly','Delay evaluation because hypertension is often silent','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-07','subarachnoid-hemorrhage','Emergency and Critical Care','subarachnoid hemorrhage','a sudden worst-ever headache, vomiting, neck stiffness, and altered consciousness','Activate neurologic emergency care, protect the airway, and prepare urgent imaging and aneurysm management','Seek emergency help for an abrupt maximal-intensity headache or new neurologic deficit','Declining consciousness with a fixed pupil','Give anticoagulant before imaging','Encourage straining','Delay evaluation if pain improves','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-07','spinal-shock','Emergency and Critical Care','spinal shock after acute cord injury','flaccid paralysis and absent reflexes below the injury with hypotension','Maintain spinal alignment, support ventilation and perfusion, and monitor neurologic return','Prevent skin and respiratory complications and report new breathing difficulty immediately','Progressive respiratory weakness with high cervical injury','Sit upright without stabilization','Use unassisted transfers','Assume absent reflexes prove permanent prognosis','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-07','upper-airway-obstruction','Emergency and Critical Care','acute upper-airway obstruction','inspiratory stridor, retractions, inability to speak, and decreasing air movement','Call emergency support, provide oxygen, and prepare immediate airway intervention','Seek emergency care for stridor, drooling, inability to speak, or blue color','A quiet chest with worsening drowsiness','Inspect deeply with unprepared equipment','Force oral fluids','Leave the client supine and alone','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-07','acute-liver-failure','Medical-Surgical','acute liver failure','jaundice, coagulopathy, hypoglycemia, confusion, and rapidly rising enzymes','Transfer for intensive liver support, monitor glucose and neurologic status, and treat the cause','Avoid unapproved medicines and seek care for jaundice, confusion, bleeding, or severe vomiting','Worsening encephalopathy with hypoglycemia and cerebral-edema signs','Give sedatives for agitation without assessment','Administer hepatotoxic medicine','Delay transplant-center consultation','Physiological Adaptation');

-- Retained for subsequent held batches.
