-- Seed Yingoh NCLEX question bank, part 2.
-- Inserts only prompts that do not already exist, so it is safe to rerun.

insert into public.questions (
  topic,
  question_type,
  prompt,
  choices,
  correct_answer,
  rationale,
  strategy,
  client_need,
  clinical_judgment,
  status
)
select *
from (values
  ('Medical-Surgical', 'mcq', 'A patient with cirrhosis is confused and has asterixis (flapping tremor). Which diet modification is indicated?', '[{"id":"a","text":"High-protein diet to support liver regeneration"},{"id":"b","text":"Low-protein diet to reduce ammonia production"},{"id":"c","text":"High-fat diet to provide dense calories"},{"id":"d","text":"High-sodium diet to combat ascites"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Hepatic encephalopathy: confusion and asterixis result from elevated ammonia from protein metabolism. Limit dietary protein to reduce ammonia production. Lactulose and rifaximin are also used. Sodium restriction (not increase) manages ascites.', '', '', '', 'published'),
  ('Medical-Surgical', 'sata', 'A patient with acute pancreatitis is admitted. Which nursing interventions are appropriate? (Select all that apply)', '[{"id":"a","text":"NPO status initially to rest the pancreas"},{"id":"b","text":"IV fluid resuscitation"},{"id":"c","text":"Administer proton pump inhibitors"},{"id":"d","text":"Semi-Fowler''s or fetal position for comfort"},{"id":"e","text":"Encourage high-fat oral nutrition to restore weight"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Acute pancreatitis: NPO rests the pancreas, IV fluids prevent hypovolemia and necrosis, positioning (fetal or forward lean) relieves pain. PPIs are used for peptic ulcer disease not pancreatitis. High-fat foods worsen pancreatitis by stimulating pancreatic enzymes.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with a spinal cord injury at T4 suddenly develops a pounding headache, diaphoresis above the injury, and blood pressure of 218/114. What condition does the nurse suspect?', '[{"id":"a","text":"Hypertensive urgency from fluid overload"},{"id":"b","text":"Autonomic dysreflexia"},{"id":"c","text":"Neurogenic shock"},{"id":"d","text":"Spinal shock"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Autonomic dysreflexia is a life-threatening emergency in SCI at T6 or above. Triggers (full bladder, pressure ulcer) cause massive sympathetic response: severe hypertension, pounding headache, diaphoresis above lesion, bradycardia. Sit patient upright and remove the trigger immediately.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with deep vein thrombosis has a warm, swollen, painful right calf. Which action should the nurse avoid?', '[{"id":"a","text":"Elevating the affected extremity"},{"id":"b","text":"Massaging the affected leg to improve circulation"},{"id":"c","text":"Monitoring for signs of pulmonary embolism"},{"id":"d","text":"Administering anticoagulant therapy as ordered"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'NEVER massage a limb with suspected DVT — this can dislodge the clot, causing a pulmonary embolism. Elevation, anticoagulation, and monitoring for PE (dyspnea, chest pain, SpO2 drop) are appropriate interventions.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with a closed head injury has a GCS score of 8. What does this indicate?', '[{"id":"a","text":"Mild traumatic brain injury"},{"id":"b","text":"Normal neurological status"},{"id":"c","text":"Severe traumatic brain injury"},{"id":"d","text":"Moderate traumatic brain injury requiring monitoring"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Glasgow Coma Scale: 13–15 = mild TBI, 9–12 = moderate, ≤8 = severe TBI. GCS ≤8 typically indicates need for airway protection (intubation). The GCS evaluates eye opening, verbal, and motor responses (max 15, min 3).', '', '', '', 'published'),
  ('Medical-Surgical', 'sata', 'A patient is diagnosed with syndrome of inappropriate antidiuretic hormone (SIADH). Which findings does the nurse expect? (Select all that apply)', '[{"id":"a","text":"Serum sodium of 118 mEq/L"},{"id":"b","text":"Decreased urine output with concentrated urine"},{"id":"c","text":"Peripheral edema and hypertension"},{"id":"d","text":"Confusion and headache"},{"id":"e","text":"Increased serum osmolality"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'SIADH: excess ADH causes water retention → dilutional hyponatremia (low Na+), concentrated urine (high urine osmolality), decreased serum osmolality. CNS symptoms (confusion, headache, seizures) from cerebral edema. No peripheral edema because fluid stays intracellular.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient post-thyroidectomy reports tingling around the mouth and carpopedal spasms. Which action is the nurse''s priority?', '[{"id":"a","text":"Administer IV calcium gluconate as ordered"},{"id":"b","text":"Apply oxygen via nasal cannula"},{"id":"c","text":"Draw a serum magnesium level"},{"id":"d","text":"Encourage the patient to breathe into a paper bag"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Post-thyroidectomy hypocalcemia occurs when the parathyroid glands are inadvertently removed or damaged (parathyroid glands regulate calcium). Tingling and carpopedal spasms (positive Trousseau''s sign) indicate hypocalcemia — treat with IV calcium gluconate.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A nurse is caring for a patient with a chest tube. The fluid in the water-seal chamber is fluctuating (tidaling) with respirations. What does this indicate?', '[{"id":"a","text":"A clot in the chest tube"},{"id":"b","text":"The system is functioning properly"},{"id":"c","text":"The lung has fully re-expanded"},{"id":"d","text":"Subcutaneous emphysema is developing"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Tidaling (fluid rising with inspiration, falling with expiration) in the water-seal chamber is NORMAL and indicates the chest tube is patent and functioning. Tidaling stops when the lung fully re-expands or if the tube is kinked/blocked.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with Addison''s disease is admitted with vomiting, hypotension, and severe fatigue. What is the priority intervention?', '[{"id":"a","text":"Oral hydrocortisone replacement"},{"id":"b","text":"IV hydrocortisone and isotonic saline"},{"id":"c","text":"Blood transfusion for hypovolemia"},{"id":"d","text":"Restrict fluids to prevent hyponatremia"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Addisonian crisis (acute adrenal insufficiency) is life-threatening. Priority: IV glucocorticoid (hydrocortisone) replacement and aggressive IV isotonic saline (0.9% NaCl) for sodium and volume replacement. Oral corticosteroids cannot be absorbed during vomiting crisis.', '', '', '', 'published'),
  ('Medical-Surgical', 'sata', 'A patient is admitted with acute kidney injury (AKI). Which findings indicate the oliguric phase? (Select all that apply)', '[{"id":"a","text":"Urine output <400 mL/day"},{"id":"b","text":"Rising BUN and creatinine"},{"id":"c","text":"Hyperkalemia"},{"id":"d","text":"Polyuria of 3–5 L/day"},{"id":"e","text":"Metabolic acidosis"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Oliguric phase of AKI: <400 mL urine/day, rising BUN/creatinine (uremia), hyperkalemia (kidney can''t excrete K+), and metabolic acidosis (kidney can''t excrete H+). Polyuria (3–5 L/day) occurs in the diuretic phase that follows recovery.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with a burns covering 30% TBSA is in the emergent phase. Using the Parkland Formula, how much fluid should be given in the first 8 hours? (Patient weighs 70 kg)', '[{"id":"a","text":"2,100 mL"},{"id":"b","text":"4,200 mL"},{"id":"c","text":"8,400 mL"},{"id":"d","text":"1,050 mL"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Parkland Formula: 4 mL × kg × %TBSA = 4 × 70 × 30 = 8,400 mL total in 24 hrs. Give half (4,200 mL) in the first 8 hours, and the remaining 4,200 mL over the next 16 hours. Count from time of burn, not admission.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A nurse is caring for a patient with increased intracranial pressure. Which position is most appropriate?', '[{"id":"a","text":"Trendelenburg position"},{"id":"b","text":"Head of bed elevated 30 degrees, neck in neutral alignment"},{"id":"c","text":"Prone position to reduce venous pooling"},{"id":"d","text":"Head of bed flat to maintain cerebral perfusion"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'HOB 30° promotes venous drainage from the brain, reducing ICP. Keep neck neutral (no flexion or rotation) to prevent jugular vein compression. Trendelenburg and flat positions increase ICP by impeding venous outflow.', '', '', '', 'published'),
  ('Medical-Surgical', 'mcq', 'A patient with type 1 diabetes develops diaphoresis, trembling, and a blood glucose of 48 mg/dL. The patient is conscious and able to swallow. What is the priority action?', '[{"id":"a","text":"Administer 1 mg glucagon intramuscularly"},{"id":"b","text":"Give 15 grams of fast-acting carbohydrates orally"},{"id":"c","text":"Administer 50 mL of D50W IV"},{"id":"d","text":"Call the provider and wait for orders"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Rule of 15: give 15g fast carbs (4 oz juice, glucose tablets) → wait 15 min → recheck glucose. For a conscious patient who can swallow, oral carbs are first-line. IV D50 and IM glucagon are for unconscious patients who cannot swallow.', '', '', '', 'published'),
  ('Medical-Surgical', 'sata', 'A patient has a hemoglobin of 7.2 g/dL and is receiving a packed red blood cell transfusion. Which findings require the nurse to stop the transfusion immediately? (Select all that apply)', '[{"id":"a","text":"Temperature increase of 1.5°C"},{"id":"b","text":"Low back pain and chills within 15 minutes of starting"},{"id":"c","text":"Mild urticaria (hives) localized to the arm"},{"id":"d","text":"New-onset dyspnea and oxygen saturation drop to 88%"},{"id":"e","text":"Slight redness at the IV site"}]'::jsonb, '{"ids":["b","d"]}'::jsonb, 'Stop transfusion for: low back pain + chills (hemolytic reaction — medical emergency), dyspnea + SpO2 drop (TRALI or TACO). Mild fever or urticaria = slow or stop, give antipyretics/diphenhydramine, may resume. Local IV site redness needs site care but not transfusion stoppage.', '', '', '', 'published'),
  ('Mental Health', 'mcq', 'A patient with schizophrenia states, "The TV is sending me special messages." This is an example of:', '[{"id":"a","text":"Hallucination"},{"id":"b","text":"Delusion of reference"},{"id":"c","text":"Thought broadcasting"},{"id":"d","text":"Negative symptom"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A delusion of reference is the false belief that ordinary events have special personal meaning directed at the individual. Hallucinations are sensory perceptions without stimuli. Thought broadcasting is the belief others can hear your thoughts.', '', '', '', 'published'),
  ('Mental Health', 'mcq', 'A patient threatens to leave the hospital against medical advice. The nurse restrains the patient without consent. This constitutes:', '[{"id":"a","text":"Battery"},{"id":"b","text":"False imprisonment"},{"id":"c","text":"Negligence"},{"id":"d","text":"Malpractice"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'False imprisonment is unlawful restraint or restriction of a person''s freedom of movement without consent or legal justification. Patients who are competent and have decision-making capacity have the right to leave AMA. The nurse should document the AMA discussion.', '', '', '', 'published'),
  ('Mental Health', 'sata', 'A nurse is assessing suicide risk. Which factors significantly increase risk? (Select all that apply)', '[{"id":"a","text":"Previous suicide attempt"},{"id":"b","text":"Access to lethal means such as firearms"},{"id":"c","text":"Strong religious beliefs against suicide"},{"id":"d","text":"Recent significant loss or humiliation"},{"id":"e","text":"Stated desire for revenge"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Highest risk factors: prior attempt (strongest predictor), access to means (especially firearms), recent loss/humiliation. Strong religious beliefs and social support are protective factors that reduce risk. Expressed desire for revenge alone is insufficient for elevated risk categorization.', '', '', '', 'published'),
  ('Mental Health', 'mcq', 'A patient in the manic phase of bipolar disorder refuses to eat because "eating takes too much time." What is the most therapeutic nursing response?', '[{"id":"a","text":"Sit with the patient during structured mealtimes and encourage eating"},{"id":"b","text":"Offer high-calorie finger foods and snacks the patient can eat while moving"},{"id":"c","text":"Restrict activities until the patient agrees to sit and eat a full meal"},{"id":"d","text":"Notify the provider that the patient is refusing meals"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Manic patients are hyperactive and cannot sit still for meals. Provide portable, high-calorie finger foods (sandwiches, crackers, fruit) so they can eat while moving. This meets nutritional needs within the patient''s behavioral capacity during mania.', '', '', '', 'published'),
  ('Mental Health', 'mcq', 'A patient prescribed clozapine (Clozaril) requires monitoring for which serious adverse effect?', '[{"id":"a","text":"QT prolongation"},{"id":"b","text":"Agranulocytosis"},{"id":"c","text":"Tardive dyskinesia"},{"id":"d","text":"Neuroleptic malignant syndrome"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Clozapine has a BLACK BOX WARNING for agranulocytosis (life-threatening drop in WBC/neutrophils). Weekly then bi-weekly ANC monitoring is mandatory. The drug is only available through a restricted REMS program. Hold if ANC <1500.', '', '', '', 'published'),
  ('Mental Health', 'mcq', 'A patient experiencing alcohol withdrawal on day 2 develops tremors, diaphoresis, and a seizure. Which medication does the nurse anticipate?', '[{"id":"a","text":"Haloperidol (Haldol)"},{"id":"b","text":"Lorazepam (Ativan)"},{"id":"c","text":"Naltrexone (Vivitrol)"},{"id":"d","text":"Disulfiram (Antabuse)"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Benzodiazepines (lorazepam, diazepam) are first-line for alcohol withdrawal seizures and delirium tremens. They cross-react with GABA receptors to prevent CNS hyperexcitability. CIWA-Ar protocol guides dosing. Haloperidol lowers seizure threshold.', '', '', '', 'published'),
  ('Mental Health', 'sata', 'A nurse is applying therapeutic communication with a patient who is grieving. Which responses are therapeutic? (Select all that apply)', '[{"id":"a","text":"\"I understand exactly how you feel.\""},{"id":"b","text":"\"Tell me what you''re experiencing right now.\""},{"id":"c","text":"\"This must be a very difficult time for you.\""},{"id":"d","text":"\"Everything happens for a reason.\""},{"id":"e","text":"Sitting silently with the patient for several minutes"}]'::jsonb, '{"ids":["b","c","e"]}'::jsonb, 'Therapeutic: open-ended questions, empathy, and therapeutic silence. Non-therapeutic: "I know how you feel" (impossible to know another''s experience — blocks communication) and clichés like "everything happens for a reason" (minimizes feelings).', '', '', '', 'published'),
  ('Mental Health', 'mcq', 'A patient with anorexia nervosa has a BMI of 15.2 and serum potassium of 2.8 mEq/L. What is the priority concern?', '[{"id":"a","text":"Cardiac dysrhythmias from electrolyte imbalance"},{"id":"b","text":"Impaired body image and self-esteem"},{"id":"c","text":"Risk of refeeding syndrome from rapid nutritional replacement"},{"id":"d","text":"Social isolation related to disordered eating behaviors"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'With K+ 2.8 mEq/L, the priority is physiologic safety — hypokalemia causes life-threatening cardiac dysrhythmias including ventricular fibrillation. The body can only address psychosocial needs once the patient is medically stabilized.', '', '', '', 'published'),
  ('Mental Health', 'mcq', 'A patient with PTSD wakes up screaming and is disoriented. What is the nurse''s therapeutic response?', '[{"id":"a","text":"\"You''re safe. I''m your nurse. You''re in the hospital.\""},{"id":"b","text":"\"Calm down. It was just a dream.\""},{"id":"c","text":"Leave the room to give the patient space"},{"id":"d","text":"Ask the patient to describe the nightmare in detail"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'During a PTSD nightmare/flashback, orient the patient with calm, simple statements about safety and present reality. "You''re safe, you''re in the hospital" grounds the patient. Dismissing the experience or leaving is non-therapeutic; detail-seeking during acute distress is re-traumatizing.', '', '', '', 'published'),
  ('Mental Health', 'mcq', 'A patient receiving an SSRI for 10 days reports feeling more energetic and has made end-of-life phone calls to family. What is the priority nursing concern?', '[{"id":"a","text":"The SSRI is working — energy returning is a positive sign"},{"id":"b","text":"The patient may be at increased risk for suicide"},{"id":"c","text":"The SSRI needs to be increased as the patient still seems sad"},{"id":"d","text":"Teach the patient it takes 4–6 weeks for full effect"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'SSRIs restore energy before improving mood — patients may now have enough motivation to act on suicidal thoughts. "End-of-life" calls (saying goodbye) and increased energy in the first 2 weeks = HIGH RISK for suicide. Perform a complete safety assessment immediately.', '', '', '', 'published'),
  ('Maternal and Newborn', 'mcq', 'A nurse is monitoring a patient in active labor. Which fetal heart rate pattern requires immediate intervention?', '[{"id":"a","text":"Early decelerations beginning and ending with contractions"},{"id":"b","text":"Accelerations with fetal movement"},{"id":"c","text":"Late decelerations occurring after each contraction"},{"id":"d","text":"Variable decelerations that resolve quickly"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Late decelerations (FHR drops after the peak of a contraction and recovers late) indicate uteroplacental insufficiency — fetal hypoxia. Immediate actions: left lateral position, O2 via mask, IV fluids, stop oxytocin, notify provider. Early decelerations are benign (head compression). Accelerations are reassuring.', '', '', '', 'published'),
  ('Maternal and Newborn', 'sata', 'A nurse is caring for a patient at 38 weeks gestation with severe preeclampsia (BP 168/112). Which interventions are priority? (Select all that apply)', '[{"id":"a","text":"Administer magnesium sulfate IV as ordered"},{"id":"b","text":"Maintain a quiet, low-stimulation environment"},{"id":"c","text":"Monitor reflexes, LOC, and respiratory rate hourly"},{"id":"d","text":"Encourage ambulation in the hallway to lower BP"},{"id":"e","text":"Keep calcium gluconate at bedside"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Severe preeclampsia: mag sulfate prevents seizures (eclampsia), low-stimulation prevents seizure triggers, close monitoring of mag toxicity signs (absent reflexes, RR <12, LOC), calcium gluconate is the mag sulfate antidote. Ambulation is contraindicated — bedrest.', '', '', '', 'published'),
  ('Maternal and Newborn', 'mcq', 'A breastfeeding mother asks the nurse when her milk will "come in" after birth. What is the most accurate response?', '[{"id":"a","text":"Within 2–4 hours of delivery"},{"id":"b","text":"Day 3–5 postpartum"},{"id":"c","text":"At 2 weeks postpartum"},{"id":"d","text":"Only after the placenta is delivered"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Colostrum (thick, yellow, antibody-rich) is produced for the first 2–3 days. Mature breast milk transitions in at 3–5 days postpartum. Teach the mother this is normal and that colostrum alone adequately nourishes the newborn in the first days.', '', '', '', 'published'),
  ('Maternal and Newborn', 'mcq', 'A nurse assesses a postpartum patient 1 hour after delivery and finds the fundus boggy and displaced to the right. What is the priority action?', '[{"id":"a","text":"Document and continue monitoring"},{"id":"b","text":"Have the patient void and then reassess the fundus"},{"id":"c","text":"Perform firm uterine massage immediately"},{"id":"d","text":"Administer oxytocin (Pitocin) as ordered"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A full bladder displaces the uterus (usually to the right) and prevents proper contraction, causing uterine atony and bleeding. First: have the patient void or catheterize, then reassess. A boggy fundus = uterine atony = risk of postpartum hemorrhage.', '', '', '', 'published'),
  ('Maternal and Newborn', 'mcq', 'A newborn is born at 35 weeks gestation. Which finding is most expected compared to a term newborn?', '[{"id":"a","text":"Strong suck and swallow reflex"},{"id":"b","text":"Lanugo covering most of the body"},{"id":"c","text":"Abundant vernix only in skin folds"},{"id":"d","text":"Well-developed plantar creases"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Lanugo (fine hair covering) is abundant in preterm infants and diminishes as gestation advances. At 35 weeks: poor suck/swallow (weak), abundant lanugo, decreased vernix (it builds up then decreases), and few plantar creases (those develop in the 3rd trimester).', '', '', '', 'published'),
  ('Maternal and Newborn', 'sata', 'A nurse is caring for a newborn receiving phototherapy for jaundice. Which interventions are appropriate? (Select all that apply)', '[{"id":"a","text":"Cover the newborn''s eyes with opaque shields"},{"id":"b","text":"Remove eye shields during feedings for bonding"},{"id":"c","text":"Monitor temperature frequently"},{"id":"d","text":"Apply lotion to skin to prevent drying"},{"id":"e","text":"Increase feeding frequency to promote bilirubin excretion"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Phototherapy: opaque eye shields protect retinas, remove during feedings for parent bonding, frequent temp monitoring (lights cause hyperthermia/hypothermia), frequent feedings promote GI transit and bilirubin excretion. Do NOT apply lotions — increases risk of burns under lights.', '', '', '', 'published'),
  ('Maternal and Newborn', 'mcq', 'A patient at 32 weeks gestation reports sudden, painless, bright red vaginal bleeding. Which condition does the nurse suspect?', '[{"id":"a","text":"Placental abruption"},{"id":"b","text":"Placenta previa"},{"id":"c","text":"Preterm labor"},{"id":"d","text":"Ruptured uterus"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Placenta previa: painless, bright red bleeding (placenta covers the cervical os, bleeds as cervix dilates). Placental abruption: sudden, painful, dark red bleeding. NEVER perform a vaginal exam in placenta previa — can cause massive hemorrhage. Immediate bedrest and notify provider.', '', '', '', 'published'),
  ('Maternal and Newborn', 'mcq', 'A nurse notices a newborn has a bluish-purple bruise-like discoloration on the lower back and buttocks. What is this finding?', '[{"id":"a","text":"Sign of child abuse requiring immediate reporting"},{"id":"b","text":"Mongolian spot — a normal finding in darker-skinned newborns"},{"id":"c","text":"Hemangioma requiring dermatology consultation"},{"id":"d","text":"Port-wine stain associated with Sturge-Weber syndrome"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Mongolian spots (congenital dermal melanocytosis) are blue-gray pigmented areas on the sacral/lumbar region, common in Asian, Hispanic, Native American, and Black newborns. They are benign and typically fade by school age. Important to document to prevent later confusion with bruising.', '', '', '', 'published'),
  ('Pediatrics', 'mcq', 'A nurse is caring for a 4-year-old post-tonsillectomy. Which assessment finding requires immediate action?', '[{"id":"a","text":"Reports throat pain rated 5/10"},{"id":"b","text":"Frequent swallowing and restlessness"},{"id":"c","text":"Refuses to drink cold fluids"},{"id":"d","text":"Low-grade temperature of 37.8°C"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Frequent swallowing in a post-tonsillectomy child is a classic early sign of hemorrhage — the child is swallowing blood. Assess the throat immediately. This is a surgical emergency. Throat pain, fluid refusal, and low-grade fever are expected post-tonsillectomy findings.', '', '', '', 'published'),
  ('Pediatrics', 'sata', 'A nurse is educating parents on preventing sudden infant death syndrome (SIDS). Which recommendations should be included? (Select all that apply)', '[{"id":"a","text":"Place baby on their back to sleep"},{"id":"b","text":"Use a firm, flat sleep surface"},{"id":"c","text":"Keep the sleep area free of soft objects and loose bedding"},{"id":"d","text":"Allow the baby to sleep in the parents'' bed for warmth"},{"id":"e","text":"Offer a pacifier at sleep time after breastfeeding is established"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Safe sleep (AAP): back to sleep, firm flat surface, no soft objects/bedding. Pacifier use reduces SIDS risk — offer after breastfeeding is established (3–4 weeks). Bed-sharing (co-sleeping) increases SIDS risk significantly and is NOT recommended.', '', '', '', 'published'),
  ('Pediatrics', 'mcq', 'A 2-year-old is brought to the ED with inspiratory stridor, a barking cough, and low-grade fever. Which condition is most likely?', '[{"id":"a","text":"Epiglottitis"},{"id":"b","text":"Croup (laryngotracheobronchitis)"},{"id":"c","text":"Bronchiolitis"},{"id":"d","text":"Asthma"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Croup: barking/seal-like cough, inspiratory stridor, low-grade fever in children 6 months–3 years, often worsens at night. Epiglottitis: "tripod position," drooling, high fever, NO barking cough — do not examine throat. Bronchiolitis: expiratory wheezing, RSV, <2 years.', '', '', '', 'published'),
  ('Pediatrics', 'mcq', 'The parent of a 9-month-old asks when to introduce solid foods. The nurse''s best response is:', '[{"id":"a","text":"\"Start solids at 4 months to help the baby sleep longer.\""},{"id":"b","text":"\"Solids should be introduced between 4–6 months, and your baby appears ready.\""},{"id":"c","text":"\"Wait until 12 months to reduce allergy risk.\""},{"id":"d","text":"\"Single-grain iron-fortified cereals are introduced around 6 months with developmental readiness signs.\""}]'::jsonb, '{"ids":["d"]}'::jsonb, 'AAP recommends introducing solid foods around 6 months with signs of readiness: sitting with support, good head control, interest in food, loss of tongue-thrust reflex. Iron-fortified single-grain cereals and pureed vegetables/fruits are appropriate first foods.', '', '', '', 'published'),
  ('Pediatrics', 'mcq', 'A 6-year-old with acute asthma exacerbation has SpO2 of 91%, is using accessory muscles, and speaks in short phrases. What is the priority intervention?', '[{"id":"a","text":"Administer a short-acting beta2 agonist (albuterol) via nebulizer"},{"id":"b","text":"Obtain a chest X-ray to rule out pneumonia"},{"id":"c","text":"Apply supplemental oxygen and complete full nursing assessment"},{"id":"d","text":"Administer oral corticosteroids"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Priority in acute asthma: bronchodilator first (albuterol via nebulizer/MDI) to reverse bronchoconstriction. SpO2 91% with accessory muscle use and limited speech indicates moderate-severe exacerbation. Oxygen, corticosteroids follow, but bronchodilation is the urgent intervention.', '', '', '', 'published'),
  ('Pediatrics', 'sata', 'A nurse suspects child abuse in a 3-year-old admitted with multiple bruises. Which findings increase this suspicion? (Select all that apply)', '[{"id":"a","text":"Bruises in various stages of healing"},{"id":"b","text":"Bruises on the shins and knees of an ambulatory child"},{"id":"c","text":"Patterned bruising (shape of belt buckle, cord)"},{"id":"d","text":"Inconsistent story between caregiver and child"},{"id":"e","text":"Bruising over bony prominences"}]'::jsonb, '{"ids":["a","c","d"]}'::jsonb, 'Red flags for abuse: bruises in multiple healing stages (different-colored), patterned injuries (burns, bite marks, belt shapes), inconsistent history. Bruises on shins/knees and bony prominences are normal in active toddlers. Mandated reporters must report ALL suspected abuse.', '', '', '', 'published'),
  ('Pediatrics', 'mcq', 'A 7-year-old with type 1 diabetes has a blood glucose of 380 mg/dL, is vomiting, and has Kussmaul breathing. What is the priority nursing action?', '[{"id":"a","text":"Give a rapidly absorbed carbohydrate snack"},{"id":"b","text":"Establish IV access and prepare for IV insulin and fluids"},{"id":"c","text":"Administer glucagon IM"},{"id":"d","text":"Place in Trendelenburg to increase cerebral perfusion"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'DKA in a child: hyperglycemia + vomiting + Kussmaul breathing (metabolic acidosis compensation) = pediatric emergency. IV access for fluid resuscitation (normal saline) and continuous IV insulin are priorities. Oral carbs worsen hyperglycemia; glucagon treats hypoglycemia.', '', '', '', 'published'),
  ('Pediatrics', 'mcq', 'A 12-month-old has not yet said "mama" or "dada" specifically. What is the nurse''s response?', '[{"id":"a","text":"Reassure the parents this is within normal limits"},{"id":"b","text":"Refer for developmental evaluation — should have 2–4 words by 12 months"},{"id":"c","text":"Recommend speech therapy immediately"},{"id":"d","text":"Advise recheck at 15 months if no words develop"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'By 12 months, children should have 2–4 meaningful words (not just babbling). Absence of these words is a developmental red flag. Early referral for evaluation is preferred — early speech therapy intervention has the best outcomes. Do not wait until 15 months.', '', '', '', 'published'),
  ('Safety and Infection Control', 'mcq', 'A nurse is preparing to insert a urinary catheter. Which action best prevents catheter-associated urinary tract infections (CAUTI)?', '[{"id":"a","text":"Change the catheter every 7 days"},{"id":"b","text":"Use strict sterile technique during insertion"},{"id":"c","text":"Irrigate the catheter daily with normal saline"},{"id":"d","text":"Apply antibiotic ointment to the urethral meatus daily"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Strict sterile technique during catheter insertion is the most effective CAUTI prevention strategy. Also: use smallest gauge catheter, remove as soon as possible, maintain closed drainage system, keep bag below bladder. Routine catheter changes, irrigation, and meatal ointment are not evidence-based for CAUTI prevention.', '', '', '', 'published'),
  ('Safety and Infection Control', 'sata', 'A patient is placed on neutropenic precautions after chemotherapy. Which actions are appropriate? (Select all that apply)', '[{"id":"a","text":"Provide a low-microbial (neutropenic) diet avoiding raw fruits and vegetables"},{"id":"b","text":"Place patient in a private room with positive-pressure air flow"},{"id":"c","text":"Restrict all visitors"},{"id":"d","text":"Monitor temperature every 4 hours"},{"id":"e","text":"Perform meticulous hand hygiene before entering room"}]'::jsonb, '{"ids":["a","b","d","e"]}'::jsonb, 'Neutropenic precautions: low-microbial diet, positive-pressure private room (protects patient FROM environment), frequent temperature monitoring (fever = infection emergency in neutropenic patient), meticulous hand hygiene. Visitors are restricted (no ill visitors) but not eliminated entirely.', '', '', '', 'published'),
  ('Safety and Infection Control', 'mcq', 'A nurse sustains a needlestick from a patient with unknown HIV status. What is the priority action?', '[{"id":"a","text":"Complete an incident report and see occupational health within 72 hours"},{"id":"b","text":"Immediately wash the site thoroughly with soap and water, then report to employee health"},{"id":"c","text":"Squeeze the wound to expel blood and apply antiseptic"},{"id":"d","text":"Begin prophylactic antibiotics immediately"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Immediate action after needlestick: wash site with soap and water thoroughly. Then report immediately to employee health for exposure assessment, testing of source patient (if available), and decision on post-exposure prophylaxis (PEP) — must start within 72 hours of exposure for HIV. Do NOT squeeze wound (increases tissue trauma).', '', '', '', 'published'),
  ('Safety and Infection Control', 'mcq', 'A patient with active pulmonary tuberculosis (TB) requires which type of precautions?', '[{"id":"a","text":"Contact precautions: gown and gloves"},{"id":"b","text":"Droplet precautions: surgical mask within 3 feet"},{"id":"c","text":"Airborne precautions: negative-pressure room and N95 respirator"},{"id":"d","text":"Standard precautions only"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'TB is transmitted via airborne droplet nuclei (<5 microns) that remain suspended in air. Requires: negative-pressure isolation room, N95 (not surgical mask) for all who enter, door kept closed. Patient transport: have patient wear surgical mask. Standard masks do NOT filter TB particles.', '', '', '', 'published'),
  ('Safety and Infection Control', 'sata', 'A nurse is preparing to change a central line dressing using the CLABSI bundle. Which interventions are included? (Select all that apply)', '[{"id":"a","text":"Hand hygiene before the procedure"},{"id":"b","text":"Use chlorhexidine gluconate for skin antisepsis"},{"id":"c","text":"Use sterile technique with mask, gown, and sterile gloves"},{"id":"d","text":"Change tubing every 24 hours"},{"id":"e","text":"Daily assessment of whether the central line is still needed"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'CLABSI bundle: hand hygiene, maximal sterile barrier precautions, chlorhexidine (CHG) skin antisepsis, optimal site selection, daily review of line necessity. Standard IV tubing is changed every 72–96 hours (not 24h). Lipid tubing changes every 24 hours.', '', '', '', 'published')
) as seed(topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
where not exists (
  select 1
  from public.questions q
  where q.prompt = seed.prompt
);
