-- Safe seed Yingoh NCLEX question bank, part 10.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'sata', 'A nurse is performing the "five rights" of medication administration. What are they? (Select all that apply)', '[{"id":"a","text":"Right patient"},{"id":"b","text":"Right medication"},{"id":"c","text":"Right dose"},{"id":"d","text":"Right route"},{"id":"e","text":"Right time"}]'::jsonb, '{"ids":["a","b","c","d","e"]}'::jsonb, 'The Five Rights: right patient (2 identifiers), right drug, right dose, right route, right time. Extended rights include: right documentation, right reason, and right response. Using 2 patient identifiers (name + DOB or MRN) prevents wrong-patient errors — the most preventable medication error.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is performing the "five rights" of medication administration. What are they? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'Which hand hygiene method is most effective against Clostridium difficile spores?', '[{"id":"a","text":"Alcohol-based hand rub for 20 seconds"},{"id":"b","text":"Soap and water for at least 20 seconds"},{"id":"c","text":"Antiseptic wipes"},{"id":"d","text":"Either method is equally effective"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'C. diff produces spores that are NOT killed by alcohol-based hand sanitizers. Soap and water (physical scrubbing for ≥20 seconds) is required to mechanically remove spores. This is one of the key reasons for special precautions: hand washing, not just sanitizer, when caring for C. diff patients.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'Which hand hygiene method is most effective against Clostridium difficile spores?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse is caring for a patient with varicella (chickenpox). Which type of isolation is required?', '[{"id":"a","text":"Contact precautions only"},{"id":"b","text":"Droplet precautions only"},{"id":"c","text":"Airborne AND contact precautions"},{"id":"d","text":"Standard precautions only"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Varicella (chickenpox) requires BOTH airborne precautions (negative pressure room, N95) AND contact precautions (gown and gloves) because it spreads via airborne droplet nuclei AND direct contact with vesicle fluid. Shingles (herpes zoster) is contact only unless disseminated.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with varicella (chickenpox). Which type of isolation is required?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse is restraining a patient for the first time due to combative behavior. Which action must the nurse take?', '[{"id":"a","text":"Apply wrist restraints and check every 2 hours"},{"id":"b","text":"Obtain a provider order, document behavior justifying restraint, and reassess every 2 hours"},{"id":"c","text":"Obtain consent from the patient before applying restraints"},{"id":"d","text":"Use a jacket restraint for maximum security"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Restraint requirements: provider order (must be time-limited), document the behavior and all alternatives tried, reassess every 2 hours (circulation, sensation, range of motion), offer alternatives (reduce stimulation, redirect, toileting). Least restrictive method first. Jacket/vest restraints increase asphyxiation risk.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is restraining a patient for the first time due to combative behavior. Which action must the nurse take?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse witnesses a colleague charting a blood pressure that was never taken. The nurse''s legal and ethical obligation is to:', '[{"id":"a","text":"Confront the colleague privately and ask them to correct the chart"},{"id":"b","text":"Report the incident through the facility''s chain of command"},{"id":"c","text":"Document the observation in the patient''s chart"},{"id":"d","text":"Ignore it — it is not the nurse''s responsibility"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Falsifying medical records is fraud and a criminal offense. The nurse has an ethical and legal obligation to report through proper channels (charge nurse, supervisor, risk management). This protects patient safety and maintains professional standards. Ignoring it makes the witness complicit. Documenting in the patient''s chart is inappropriate.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse witnesses a colleague charting a blood pressure that was never taken. The nurse''s legal and ethical obligation is to:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse is caring for a patient who is Jehovah''s Witness and refuses a blood transfusion despite critical anemia. The nurse understands that:', '[{"id":"a","text":"The family can override the patient''s decision if the patient is in danger"},{"id":"b","text":"The hospital has the right to get a court order if the patient is a danger to themselves"},{"id":"c","text":"A competent adult patient has the right to refuse treatment, including life-saving blood transfusions"},{"id":"d","text":"The nurse should administer the transfusion while the patient is asleep to save their life"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Informed refusal: a competent adult has the absolute right to refuse any treatment, including life-saving interventions, based on religious or personal beliefs. Administering blood without consent is assault/battery. The nurse ensures the patient understands the consequences, documents informed refusal, and notifies the provider. Family cannot override a competent adult.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient who is Jehovah''s Witness and refuses a blood transfusion despite critical anemia. The nurse understands that:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'sata', 'A nurse is caring for 5 patients. Which tasks can be safely delegated to a licensed practical nurse (LPN/LVN)? (Select all that apply)', '[{"id":"a","text":"Administering a scheduled oral medication to a stable patient"},{"id":"b","text":"Performing the initial nursing assessment on a newly admitted patient"},{"id":"c","text":"Changing a wound dressing on a chronic, stable wound"},{"id":"d","text":"Teaching a patient about a new insulin injection technique"},{"id":"e","text":"Administering an IV push medication on a stable patient (per state law and facility policy)"}]'::jsonb, '{"ids":["a","c","e"]}'::jsonb, 'LPNs/LVNs: can administer scheduled medications to stable patients, change dressings, collect specimens, monitor IV infusions (facility specific). Cannot: perform initial admission assessments (RN-only scope), develop care plans, or perform patient teaching independently (they reinforce RN teaching). IV push depends on state law.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for 5 patients. Which tasks can be safely delegated to a licensed practical nurse (LPN/LVN)? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A patient care situation deteriorates rapidly. Which communication tool provides the most structured and efficient handoff?', '[{"id":"a","text":"SBAR"},{"id":"b","text":"Narrative nursing note"},{"id":"c","text":"Shift end-of-shift report"},{"id":"d","text":"Informal verbal update"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'SBAR (Situation-Background-Assessment-Recommendation) provides a standardized, concise communication format for urgent clinical situations. Studies show SBAR reduces communication errors, improves response time, and creates a common language between nurses and physicians during handoffs and emergencies.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient care situation deteriorates rapidly. Which communication tool provides the most structured and efficient handoff?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse is using the "I PASS the BATON" handoff tool. What does the "A" stand for?', '[{"id":"a","text":"Allergies"},{"id":"b","text":"Assessment and actions taken"},{"id":"c","text":"Anticipated orders"},{"id":"d","text":"Admission diagnosis"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'I PASS the BATON: Introduction, Patient, Assessment, Situation, Safety (allergies, alerts) — the BATON portion: Background, Actions, Timing, Ownership, Next. "A" = Allergies and alerts (code status, fall risk, isolation). This Joint Commission-endorsed tool standardizes handoffs to prevent information loss.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is using the "I PASS the BATON" handoff tool. What does the "A" stand for?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'sata', 'A 72-year-old with COPD, heart failure, and type 2 diabetes is admitted with worsening dyspnea. SpO2 82%, RR 28, HR 112, BP 158/96, bilateral crackles, 3+ pitting edema. Which nursing actions are priority? (Select all that apply)', '[{"id":"a","text":"Position in high Fowler''s to ease breathing"},{"id":"b","text":"Apply oxygen at 2 L/min via nasal cannula targeting SpO2 88–92%"},{"id":"c","text":"Administer furosemide IV as ordered for fluid overload"},{"id":"d","text":"Apply 100% non-rebreather mask at 15 L/min"},{"id":"e","text":"Notify provider and prepare for possible BiPAP"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'COPD + HF: HOB elevation (reduce preload, improve lung expansion), low-flow O2 targeting 88–92% (COPD hypoxic drive), IV diuresis for fluid overload (bilateral crackles, 3+ edema), and provider notification for escalation including BiPAP. High-flow 100% O2 (non-rebreather) risks respiratory failure in COPD by eliminating hypoxic drive.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 72-year-old with COPD, heart failure, and type 2 diabetes is admitted with worsening dyspnea. SpO2 82%, RR 28, HR 112, BP 158/96, bilateral crackles, 3+ pitting edema. Which nursing actions are priority? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'mcq', 'A nurse is caring for a patient 2 days post-ischemic stroke. The patient has left-sided weakness and dysphagia. The patient is hungry and wants to eat. What is the priority nursing action?', '[{"id":"a","text":"Provide a regular diet with thin liquids as ordered"},{"id":"b","text":"Complete a swallowing screen before any oral intake"},{"id":"c","text":"Give the patient soft foods and encourage self-feeding with the right hand"},{"id":"d","text":"Insert an NG tube for enteral feeding immediately"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Dysphagia after stroke significantly increases aspiration pneumonia risk (leading preventable complication). Conduct a bedside swallowing screen (e.g., 3-oz water test) before any oral intake. Refer to speech-language pathology for formal evaluation. Do not feed orally without swallow screen clearance.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient 2 days post-ischemic stroke. The patient has left-sided weakness and dysphagia. The patient is hungry and wants to eat. What is the priority nursing action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'sata', 'A nurse reviews labs for a patient with chronic liver failure: Na 128, K 5.8, Creatinine 3.2, ammonia 98, INR 3.1, albumin 1.8, bilirubin 8.4. Which conditions do these values indicate? (Select all that apply)', '[{"id":"a","text":"Hyponatremia"},{"id":"b","text":"Hepatic encephalopathy risk"},{"id":"c","text":"Impaired coagulation"},{"id":"d","text":"Hyperkalemia requiring immediate intervention"},{"id":"e","text":"Acute kidney injury"}]'::jsonb, '{"ids":["a","b","c","d","e"]}'::jsonb, 'All values are abnormal: Na 128 = hyponatremia (dilutional), K 5.8 = hyperkalemia (cardiac risk — K >6 requires immediate treatment), creatinine 3.2 = AKI (hepatorenal syndrome), ammonia 98 = encephalopathy risk, INR 3.1 = coagulopathy, albumin 1.8 = severe malnutrition and edema risk, bilirubin 8.4 = cholestasis/hepatocellular failure.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse reviews labs for a patient with chronic liver failure: Na 128, K 5.8, Creatinine 3.2, ammonia 98, INR 3.1, albumin 1.8, bilirubin 8.4. Which conditions do these values indicate? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'mcq', 'A 45-year-old male with no PMH presents with 2 hours of crushing substernal chest pain radiating to the left jaw and arm, diaphoresis, and nausea. 12-lead ECG shows ST elevation in leads II, III, and aVF. This pattern indicates:', '[{"id":"a","text":"Anterior STEMI — left anterior descending artery occlusion"},{"id":"b","text":"Inferior STEMI — right coronary artery occlusion"},{"id":"c","text":"Lateral STEMI — circumflex artery occlusion"},{"id":"d","text":"Unstable angina — admit for monitoring"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Inferior STEMI: ST elevation in leads II, III, aVF → right coronary artery territory. Anterior STEMI = V1–V4 (LAD). Lateral STEMI = I, aVL, V5–V6 (circumflex). This patient needs immediate activation of the cath lab (door-to-balloon <90 min). Also assess for RV involvement (right-sided ECG leads).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 45-year-old male with no PMH presents with 2 hours of crushing substernal chest pain radiating to the left jaw and arm, diaphoresis, and nausea. 12-lead ECG shows ST elevation in leads II, III, and aVF. This pattern indicates:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'sata', 'A nurse receives a patient in anaphylaxis after a bee sting. Which interventions are performed simultaneously? (Select all that apply)', '[{"id":"a","text":"Administer epinephrine 0.3 mg IM to the outer thigh"},{"id":"b","text":"Apply oxygen via non-rebreather mask"},{"id":"c","text":"Establish large-bore IV access and begin IV fluids"},{"id":"d","text":"Administer IV diphenhydramine as definitive treatment"},{"id":"e","text":"Place patient supine with legs elevated (unless dyspneic)"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Anaphylaxis: epinephrine IM (lateral thigh) is first-line — do not delay. Simultaneously: high-flow O2, IV access + fluids for hypotension, supine with legs elevated to increase venous return (sit up if airway compromised). Diphenhydramine and corticosteroids are ADJUNCTS, not first-line — they are too slow to prevent laryngeal edema.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse receives a patient in anaphylaxis after a bee sting. Which interventions are performed simultaneously? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient with type 2 diabetes is started on insulin glargine (Lantus). Which statement indicates the patient needs additional teaching?', '[{"id":"a","text":"\"I will give this injection at the same time each day.\""},{"id":"b","text":"\"I should not mix this insulin with other insulins in the same syringe.\""},{"id":"c","text":"\"I can use this insulin for hypoglycemic episodes because it works quickly.\""},{"id":"d","text":"\"I should rotate injection sites to prevent lipodystrophy.\""}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Insulin glargine (Lantus) is a long-acting basal insulin with no peak — it cannot treat acute hypoglycemia. Short-acting (regular) or rapid-acting (lispro, aspart) insulin is used for hyperglycemia correction. Glargine should NOT be mixed with other insulins (pH incompatibility).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with type 2 diabetes is started on insulin glargine (Lantus). Which statement indicates the patient needs additional teaching?');
