-- Safe seed Yingoh NCLEX question bank, part 16.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Complex Care', 'mcq', 'A client in septic shock is on norepinephrine. Which finding best indicates treatment is working?', '[{"id":"a","text":"Serum lactate falling from 6.2 to 2.1 mmol/L"},{"id":"b","text":"Temperature falling from 39.8°C to 37.1°C"},{"id":"c","text":"HR falling from 118 to 98 bpm"},{"id":"d","text":"WBC falling from 22,000 to 14,000/mm³"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Falling serum lactate = gold standard for improving tissue perfusion in septic shock. Lactate rises during anaerobic metabolism. Falling lactate = cells are receiving oxygen = perfusion is restored.', 'Septic shock goal = restore tissue perfusion. Lactate is the direct cellular oxygen marker. Temperature and WBC reflect infection control, not perfusion. Falling lactate = treatment working.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client in septic shock is on norepinephrine. Which finding best indicates treatment is working?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Oncology and Hematology', 'mcq', 'A client on chemotherapy has an ANC of 450/mm³. The nursing priority is to:', '[{"id":"a","text":"Administer a platelet transfusion"},{"id":"b","text":"Initiate neutropenic precautions and monitor for infection"},{"id":"c","text":"Restrict all visitors from the room"},{"id":"d","text":"Place the client on contact precautions"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'ANC < 500/mm³ = severe neutropenia = highest infection risk. Neutropenic precautions protect the immunocompromised client from the environment (reverse isolation). Platelets address thrombocytopenia. Not all visitors restricted — healthy visitors with good hand hygiene may visit.', 'ANC < 500 = neutropenic precautions. These protect the client FROM pathogens (reverse/protective isolation). Contact precautions protect others FROM the client. Know which direction protection flows.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client on chemotherapy has an ANC of 450/mm³. The nursing priority is to:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Oncology and Hematology', 'sata', 'A client develops chills, fever, low back pain, and hypotension 20 minutes into a transfusion. The nurse takes which actions? Select all that apply.', '[{"id":"a","text":"Stop the transfusion immediately"},{"id":"b","text":"Slow the rate and continue monitoring"},{"id":"c","text":"Keep IV open with normal saline"},{"id":"d","text":"Notify the blood bank and provider"},{"id":"e","text":"Send the blood bag and tubing to the lab"}]'::jsonb, '{"ids":["a","c","d","e"]}'::jsonb, 'Acute hemolytic transfusion reaction (blood type mismatch): STOP immediately, maintain IV with NS using new tubing, notify provider and blood bank, send blood bag + tubing for analysis. Never slow and continue.', 'Hemolytic reaction = STOP — KEEP LINE WITH NS — NOTIFY — SEND BAG. Never slow and continue. The bag must return to the blood bank. This is a life-threatening reaction.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client develops chills, fever, low back pain, and hypotension 20 minutes into a transfusion. The nurse takes which actions? Select all that apply.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Perioperative Care', 'sata', 'A nurse completes a pre-operative assessment. Which findings require notifying the provider? Select all that apply.', '[{"id":"a","text":"Client takes warfarin 5 mg daily"},{"id":"b","text":"Client has a latex allergy"},{"id":"c","text":"Hemoglobin 14.2 g/dL"},{"id":"d","text":"Client takes St. John''s Wort herbal supplement"},{"id":"e","text":"BP 128/76 mmHg"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Report: warfarin (bleeding risk — may need to be held); latex allergy (OR must be latex-free, anaphylaxis risk); St. John''s Wort (interacts with anesthesia — must stop 2 weeks pre-op). Normal Hgb and BP do not require reporting.', 'Pre-op safety flags: anticoagulants, allergies (especially latex), herbals. Normal labs and vital signs within range = no notification needed. Herbals that interfere: St. John''s Wort, garlic, ginkgo, ginseng.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse completes a pre-operative assessment. Which findings require notifying the provider? Select all that apply.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medication Administration', 'mcq', 'Which situation requires the nurse to withhold the medication and contact the provider?', '[{"id":"a","text":"Client on digoxin has apical pulse of 54 bpm"},{"id":"b","text":"Client on metformin has BG of 210 mg/dL"},{"id":"c","text":"Client on lisinopril has BP 142/88 mmHg"},{"id":"d","text":"Client on ferrous sulfate reports dark-colored stools"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Hold digoxin when apical pulse < 60 bpm. Digoxin further slows the heart — bradycardia below 60 is a contraindication. Dark stools with iron are expected. Metformin at BG 210 is within management range. Lisinopril is given for hypertension — BP 142/88 does not warrant withholding.', 'Digoxin rule: apical pulse < 60 = hold and notify. Always count apical for a full minute before giving digoxin. One of the most tested medication safety rules on NCLEX. Know the hold parameters.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'Which situation requires the nurse to withhold the medication and contact the provider?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Cardiovascular', 'mcq', 'A client with heart failure reports new shortness of breath while lying flat and has crackles halfway up both lung fields. Which prescription should the nurse question?', '[{"id":"a","text":"Furosemide 40 mg IV now"},{"id":"b","text":"Restrict fluids to 1.5 L/day"},{"id":"c","text":"Infuse 0.9% saline at 150 mL/hr"},{"id":"d","text":"Obtain daily weights each morning"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Rapid isotonic fluid infusion can worsen pulmonary congestion in heart failure. Diuretics, fluid restriction, and daily weights are expected management.', 'In heart failure, new crackles plus orthopnea means fluid is already in the lungs. Do not add more fluid unless there is a compelling reason.', 'Physiological Integrity', 'Analyze Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with heart failure reports new shortness of breath while lying flat and has crackles halfway up both lung fields. Which prescription should the nurse question?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Cardiovascular', 'mcq', 'A client develops chest pain after walking to the bathroom. Which action should the nurse take first?', '[{"id":"a","text":"Call the provider"},{"id":"b","text":"Obtain a 12-lead ECG"},{"id":"c","text":"Stop activity and assist the client to rest"},{"id":"d","text":"Administer morphine as prescribed"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'The first action is to decrease myocardial oxygen demand by stopping activity and placing the client at rest. ECG and medications follow rapid assessment and stabilization.', 'For angina questions, first reduce oxygen demand: stop activity, rest, then assess and treat.', 'Physiological Integrity', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'A client develops chest pain after walking to the bathroom. Which action should the nurse take first?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Cardiovascular', 'mcq', 'Which finding is most concerning after femoral cardiac catheterization?', '[{"id":"a","text":"Blood pressure 118/74 mmHg"},{"id":"b","text":"Pedal pulse weaker than baseline"},{"id":"c","text":"Client reports needing to void"},{"id":"d","text":"Small bruise at the insertion site"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A weaker distal pulse may indicate arterial occlusion or impaired perfusion after catheterization and requires immediate action. A small bruise and urinary urgency can be expected.', 'After cath, think circulation below the insertion site: pulse, color, temperature, sensation, movement.', 'Physiological Integrity', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'Which finding is most concerning after femoral cardiac catheterization?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Cardiovascular', 'mcq', 'A client taking warfarin has an INR of 6.2 and bleeding gums. Which order should the nurse anticipate?', '[{"id":"a","text":"Vitamin K"},{"id":"b","text":"Protamine sulfate"},{"id":"c","text":"Aspirin"},{"id":"d","text":"Additional warfarin"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Vitamin K reverses warfarin. Protamine reverses heparin. Aspirin and more warfarin increase bleeding risk.', 'Match antidotes: warfarin = vitamin K; heparin = protamine.', 'Physiological Integrity', 'Generate Solutions', 'published'
where not exists (select 1 from public.questions where prompt = 'A client taking warfarin has an INR of 6.2 and bleeding gums. Which order should the nurse anticipate?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Respiratory', 'mcq', 'A client with COPD is receiving oxygen at 6 L/min by nasal cannula and becomes increasingly drowsy. Which action should the nurse take first?', '[{"id":"a","text":"Increase oxygen to 10 L/min"},{"id":"b","text":"Assess respiratory rate and oxygen saturation"},{"id":"c","text":"Encourage oral fluids"},{"id":"d","text":"Place the client flat in bed"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Increasing drowsiness may reflect carbon dioxide retention or worsening respiratory failure. The nurse first assesses ventilation and oxygenation.', 'Change in level of consciousness in COPD can mean CO2 retention. Assess breathing before changing therapy.', 'Physiological Integrity', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with COPD is receiving oxygen at 6 L/min by nasal cannula and becomes increasingly drowsy. Which action should the nurse take first?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Respiratory', 'mcq', 'Which arterial blood gas result requires the most immediate follow-up?', '[{"id":"a","text":"pH 7.39, PaCO2 40, HCO3 24"},{"id":"b","text":"pH 7.31, PaCO2 60, HCO3 26"},{"id":"c","text":"pH 7.45, PaCO2 36, HCO3 24"},{"id":"d","text":"pH 7.36, PaCO2 42, HCO3 23"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A low pH with elevated PaCO2 indicates respiratory acidosis, which may signal hypoventilation and respiratory failure.', 'ROME: pH low and CO2 high move opposite, so respiratory acidosis.', 'Physiological Integrity', 'Analyze Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'Which arterial blood gas result requires the most immediate follow-up?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Respiratory', 'mcq', 'A client with pneumonia has SpO2 86%, respiratory rate 32/min, and confusion. Which action is priority?', '[{"id":"a","text":"Collect sputum culture"},{"id":"b","text":"Apply oxygen as prescribed"},{"id":"c","text":"Teach incentive spirometry"},{"id":"d","text":"Document expected findings"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Hypoxemia with confusion requires immediate oxygenation support. Cultures and teaching can occur after stabilizing airway and breathing.', 'ABC priority: low oxygen plus confusion means the brain is not getting oxygen.', 'Physiological Integrity', 'Prioritize Hypotheses', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with pneumonia has SpO2 86%, respiratory rate 32/min, and confusion. Which action is priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Respiratory', 'mcq', 'Which instruction is most important for a client using an albuterol inhaler before a corticosteroid inhaler?', '[{"id":"a","text":"Use albuterol first, wait several minutes, then use the corticosteroid"},{"id":"b","text":"Use the corticosteroid first to open the airways"},{"id":"c","text":"Do not rinse the mouth after corticosteroid use"},{"id":"d","text":"Use both inhalers only when symptoms are severe"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'A bronchodilator is used first to open airways, improving delivery of the corticosteroid. The client should rinse the mouth after inhaled steroids.', 'Bronchodilator before steroid: open the airway, then deliver the anti-inflammatory medication.', 'Physiological Integrity', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'Which instruction is most important for a client using an albuterol inhaler before a corticosteroid inhaler?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Renal and Urinary', 'mcq', 'A client with chronic kidney disease has potassium 6.1 mEq/L. Which assessment finding is most important?', '[{"id":"a","text":"Dry skin"},{"id":"b","text":"Peaked T waves"},{"id":"c","text":"Poor appetite"},{"id":"d","text":"Mild ankle edema"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Hyperkalemia can cause life-threatening dysrhythmias. Peaked T waves are a classic ECG sign requiring urgent intervention.', 'High potassium hurts the heart first. ECG changes are the danger cue.', 'Physiological Integrity', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with chronic kidney disease has potassium 6.1 mEq/L. Which assessment finding is most important?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Renal and Urinary', 'mcq', 'Which client statement about hemodialysis access needs correction?', '[{"id":"a","text":"I will avoid blood pressure readings in the access arm"},{"id":"b","text":"I will check for a thrill every day"},{"id":"c","text":"I can sleep with my access arm under my body"},{"id":"d","text":"I will report redness or drainage"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Pressure on the access arm can impair blood flow and clot the fistula or graft. The other statements are appropriate.', 'Protect the access: no pressure, no sticks, no BP, check thrill/bruit.', 'Physiological Integrity', 'Evaluate Outcomes', 'published'
where not exists (select 1 from public.questions where prompt = 'Which client statement about hemodialysis access needs correction?');
