-- Adds 192 unique NCLEX draft questions: 64 clinical concepts x 3 reasoning tasks.
-- Idempotent by prompt. Items require clinical review before publication.
with concepts (
  slug, topic, condition_name, clinical_cue, priority_action, key_teaching,
  danger_finding, wrong_one, wrong_two, wrong_three, client_need
) as (
  values
  -- Medical-Surgical (8)
  ('acute-pulmonary-edema','Medical-Surgical','acute pulmonary edema','sudden dyspnea, crackles, and pink frothy sputum','Position the client upright, apply oxygen, and activate rapid response support','Report increasing breathlessness early and take prescribed heart-failure medicines consistently','New confusion with an oxygen saturation of 82%','Encourage oral fluids rapidly','Place the client flat with the legs elevated','Delay reassessment until the next routine vital-sign round','Physiological Integrity'),
  ('upper-gi-bleed','Medical-Surgical','an upper gastrointestinal bleed','coffee-ground emesis with tachycardia and falling blood pressure','Keep the client NPO, obtain large-bore IV access, and notify the rapid response team','Avoid NSAIDs and report black stools, dizziness, or vomiting blood immediately','Cool clammy skin with systolic blood pressure of 84 mm Hg','Offer a regular meal to assess tolerance','Administer an IM injection for pain','Encourage the client to walk to the bathroom alone','Physiological Integrity'),
  ('acute-stroke','Medical-Surgical','an acute ischemic stroke','new facial droop, arm weakness, and slurred speech','Activate the stroke protocol and determine the exact last-known-well time','Call emergency services immediately for any sudden FAST symptoms','A decreasing level of consciousness with new vomiting','Give food and fluids before a swallow screen','Lower blood pressure rapidly without a prescription','Allow the client to sleep before reassessment','Physiological Integrity'),
  ('dka','Medical-Surgical','diabetic ketoacidosis','polyuria, Kussmaul respirations, glucose 520 mg/dL, and positive ketones','Begin isotonic IV fluid replacement and monitor potassium closely','Use sick-day rules, continue basal insulin as directed, and check glucose and ketones frequently','Potassium of 2.9 mEq/L during insulin therapy','Restrict all fluids until glucose normalizes','Stop insulin whenever the client cannot eat','Give sodium bicarbonate routinely before fluids','Physiological Integrity'),
  ('siadh','Medical-Surgical','SIADH','confusion, low serum sodium, concentrated urine, and low urine output','Institute seizure precautions and follow the prescribed fluid restriction','Measure all fluids and recognize headache or confusion as possible worsening hyponatremia','A seizure with a sodium level of 116 mEq/L','Encourage several liters of free water daily','Provide hypotonic IV fluid rapidly','Use salt-free foods exclusively','Physiological Integrity'),
  ('addisonian-crisis','Medical-Surgical','an Addisonian crisis','severe weakness, vomiting, hypotension, hyponatremia, and hyperkalemia','Administer prescribed IV hydrocortisone and isotonic fluids promptly','Never stop corticosteroids abruptly and increase doses during illness as prescribed','Persistent hypotension despite initial fluid resuscitation','Restrict sodium and fluids','Withhold corticosteroids until potassium normalizes','Encourage strenuous exercise during acute illness','Physiological Integrity'),
  ('compartment-syndrome','Medical-Surgical','acute compartment syndrome','severe pain out of proportion after a leg fracture with pain on passive stretch','Notify the surgeon immediately and keep the extremity at heart level','Report escalating pain, numbness, or tightness that is not relieved by medication','New paresthesia with a tense swollen compartment','Elevate the limb well above the heart','Apply a heating pad tightly over the cast','Wait for loss of the pulse before reporting','Physiological Integrity'),
  ('hepatic-encephalopathy','Medical-Surgical','hepatic encephalopathy','cirrhosis with confusion, asterixis, and elevated ammonia','Administer prescribed lactulose and institute safety precautions','Take lactulose to achieve the prescribed number of soft stools and avoid sedatives unless approved','Increasing somnolence with inability to protect the airway','Give a high-protein supplement immediately','Administer an opioid for restlessness','Restrict bowel movements to prevent dehydration','Physiological Integrity'),

  -- Pharmacology (8)
  ('lithium','Pharmacology','lithium therapy','tremor, diarrhea, ataxia, and recent dehydration','Hold lithium and obtain an urgent serum lithium level','Maintain consistent sodium and fluid intake and call for vomiting or diarrhea','Coarse tremor with confusion and unsteady gait','Begin a low-sodium diet suddenly','Double the next dose after a missed dose','Take ibuprofen daily without consulting the prescriber','Physiological Integrity'),
  ('warfarin','Pharmacology','warfarin therapy','anticoagulation for atrial fibrillation with a rising INR','Hold the dose when prescribed parameters are exceeded and notify the prescriber','Keep vitamin K intake consistent and report bleeding or black stools','INR 6.2 with new hematuria','Use aspirin for minor headaches routinely','Eliminate every green vegetable from the diet','Receive IM injections whenever possible','Physiological Integrity'),
  ('digoxin','Pharmacology','digoxin therapy','heart failure treatment with nausea and yellow-green visual halos','Withhold digoxin, assess the apical pulse, and notify the prescriber','Check the pulse before each dose and report nausea, vision changes, or marked bradycardia','Apical pulse 48/min with new confusion','Take an extra dose when ankle edema appears','Use antacids at the same time as digoxin','Increase the dose after any missed tablet','Physiological Integrity'),
  ('aminoglycoside','Pharmacology','gentamicin therapy','treatment of a serious gram-negative infection','Review trough level and renal function before the next dose','Report tinnitus, hearing changes, reduced urine output, or imbalance promptly','New tinnitus with a rising serum creatinine','Limit oral fluids despite normal cardiac function','Expect permanent hearing changes as harmless','Take the medication with an over-the-counter NSAID daily','Physiological Integrity'),
  ('ace-inhibitor','Pharmacology','ACE inhibitor therapy','new lisinopril prescription for hypertension','Assess blood pressure, potassium, renal function, and signs of angioedema','Rise slowly, avoid potassium salt substitutes, and seek emergency help for lip or tongue swelling','Swelling of the tongue with difficulty swallowing','Treat a dry cough by doubling the dose','Use potassium supplements without approval','Continue the drug throughout pregnancy','Physiological Integrity'),
  ('metformin-contrast','Pharmacology','metformin use around iodinated contrast','scheduled contrast-enhanced CT with reduced renal function','Hold metformin as ordered and verify renal function before restarting it','Tell every imaging provider about metformin and follow instructions for stopping and restarting','Malaise, rapid breathing, and rising lactate after renal injury','Take extra metformin before the scan','Avoid all carbohydrates for 48 hours','Restart metformin immediately before renal results return','Physiological Integrity'),
  ('opioid-overdose','Pharmacology','opioid-induced respiratory depression','postoperative client difficult to arouse with respirations of 6/min','Support ventilation and administer prescribed naloxone','Avoid alcohol and sedatives, and have someone seek help for slow or stopped breathing','Cyanosis with minimal response to painful stimulation','Allow uninterrupted sleep for two hours','Give another opioid dose for restlessness','Place the client prone and leave the room','Physiological Integrity'),
  ('phenytoin','Pharmacology','phenytoin therapy','long-term seizure treatment','Review the serum level, neurologic status, and medication interactions','Perform meticulous oral hygiene and do not stop the medicine abruptly','Nystagmus, ataxia, and slurred speech','Use alcohol to reduce gingival swelling','Skip dental care because gums may bleed','Crush extended-release capsules into tube feeding','Physiological Integrity'),

  -- Fundamentals (8)
  ('c-difficile','Fundamentals','Clostridioides difficile infection','frequent watery diarrhea after antibiotic therapy','Use contact precautions and wash hands with soap and water','Finish prescribed treatment and clean high-touch surfaces with a sporicidal product','Increasing abdominal distention with fever and absent bowel sounds','Use alcohol hand rub as the only hand hygiene','Share a bathroom with an immunocompromised client','Administer an antidiarrheal without an order','Safe and Effective Care Environment'),
  ('blood-transfusion-reaction','Fundamentals','an acute blood transfusion reaction','fever, chills, flank pain, and dyspnea shortly after blood starts','Stop the transfusion and keep the IV line open with new normal-saline tubing','Report chills, itching, breathing difficulty, or back pain immediately during transfusion','Hypotension with wheezing and facial swelling','Slow the transfusion and reassess in thirty minutes','Flush the blood tubing with dextrose solution','Discard the blood bag before notifying the blood bank','Physiological Integrity'),
  ('fall-prevention','Fundamentals','high fall risk','older adult with delirium, urgency, and an unsteady gait','Keep the bed low, activate appropriate alarms, and schedule assisted toileting','Use the call light and wait for help before standing','Repeated attempts to climb over side rails despite redirection','Apply four raised side rails as routine restraint','Place frequently used objects out of reach','Encourage independent walking during confusion','Safe and Effective Care Environment'),
  ('pressure-injury','Fundamentals','pressure-injury prevention','immobile client with moisture and poor nutrition','Reposition on an individualized schedule and offload the heels','Inspect skin daily, manage moisture, and consume adequate protein and fluids','Nonblanchable deep purple tissue over the sacrum','Massage reddened bony prominences vigorously','Use a donut-shaped cushion under the sacrum','Keep damp linens in place to reduce friction','Physiological Integrity'),
  ('sterile-field','Fundamentals','sterile technique','preparing a sterile field for a central-line dressing change','Discard and replace any item when sterility is uncertain','Keep sterile supplies above waist level and within view','A sterile glove touching the bedrail before catheter contact','Reach across the sterile field with a bare arm','Consider the outer one inch of a wrapper sterile','Turn away from the open field while gathering supplies','Safe and Effective Care Environment'),
  ('enteral-feeding-aspiration','Fundamentals','enteral-feeding aspiration prevention','continuous tube feeding in a client with impaired consciousness','Elevate the head of bed 30 to 45 degrees and verify tube placement per policy','Remain upright during feeding and report coughing, choking, or breathing difficulty','Sudden coughing with oxygen desaturation during feeding','Place the client flat to prevent tube movement','Add blue dye to detect aspiration','Increase the rate when gastric discomfort occurs','Physiological Integrity'),
  ('restraint-safety','Fundamentals','safe restraint use','confused client pulling at life-sustaining tubing','Try least-restrictive alternatives and obtain the required time-limited order','Restraints require frequent assessment and are removed as soon as safely possible','Cool pale fingers distal to a wrist restraint','Tie the restraint to a movable side rail','Use restraints for staff convenience','Leave restraints continuously in place for a full shift','Safe and Effective Care Environment'),
  ('seizure-safety','Fundamentals','seizure precautions','hospitalized client with recurrent generalized seizures','Protect the head, turn the client to the side, and time the seizure','Do not place anything in the mouth and take antiseizure medicines consistently','A seizure lasting longer than five minutes','Restrain the arms and legs firmly','Insert an oral airway during jaw clenching','Offer water immediately while the client is drowsy','Safe and Effective Care Environment'),

  -- Pediatrics (8)
  ('epiglottitis','Pediatrics','suspected epiglottitis','drooling, tripod positioning, high fever, and muffled voice','Keep the child calm, provide oxygen, and prepare for controlled airway management','Seek emergency care for drooling with difficulty breathing or a muffled voice','Increasing stridor with decreasing air movement','Inspect the throat with a tongue blade','Force the child to lie flat for examination','Obtain a throat culture before airway support','Physiological Integrity'),
  ('croup','Pediatrics','viral croup','barking cough and inspiratory stridor that worsens at night','Keep the child calm and administer prescribed dexamethasone or nebulized epinephrine','Use cool comfort measures and seek help for stridor at rest or retractions','Stridor at rest with fatigue and cyanosis','Examine the pharynx repeatedly with a tongue blade','Give aspirin for fever','Encourage crying to assess the airway','Physiological Integrity'),
  ('pediatric-dehydration','Pediatrics','severe pediatric dehydration','sunken eyes, delayed capillary refill, tachycardia, and minimal urine','Begin prescribed isotonic fluid bolus and reassess perfusion','Give frequent oral rehydration solution for mild losses and track wet diapers','Lethargy with weak pulses and capillary refill of five seconds','Offer plain water only to an infant','Give undiluted fruit juice after each stool','Delay fluids until vomiting stops completely','Physiological Integrity'),
  ('tetralogy-spell','Pediatrics','a hypercyanotic spell in tetralogy of Fallot','sudden deep cyanosis and irritability after crying','Place the child in the knee-chest position and administer oxygen','Reduce prolonged crying and use the knee-chest position while seeking help for a spell','Cyanosis that does not improve with knee-chest positioning','Lay the child flat with legs extended','Encourage vigorous activity to improve circulation','Give a large feeding during the spell','Physiological Integrity'),
  ('meningitis-child','Pediatrics','bacterial meningitis in a child','fever, nuchal rigidity, photophobia, and altered behavior','Initiate droplet precautions and administer prescribed antibiotics promptly','Complete prophylactic antibiotics if prescribed for close contacts','Purpuric rash with delayed capillary refill','Keep the room brightly lit for neurologic checks','Share eating utensils after the first antibiotic dose','Delay antibiotics until every culture result is final','Safe and Effective Care Environment'),
  ('nephrotic-syndrome-child','Pediatrics','pediatric nephrotic syndrome','generalized edema, proteinuria, and low albumin','Monitor daily weight, urine protein, skin integrity, and infection signs','Use prescribed sodium limits and report fever or increasing swelling','Fever with abdominal pain in an immunosuppressed child','Encourage high-sodium packaged foods','Limit prescribed corticosteroids when edema improves','Massage fragile edematous skin','Physiological Integrity'),
  ('type1-sick-day','Pediatrics','type 1 diabetes sick-day management','child with influenza, poor intake, and hyperglycemia','Continue basal insulin, check glucose and ketones, and maintain hydration','Never omit basal insulin during illness and call for persistent ketones or vomiting','Moderate ketones with repeated vomiting and deep respirations','Stop all insulin until normal meals resume','Give sugar-free fluids only despite hypoglycemia','Avoid checking glucose to let the child rest','Physiological Integrity'),
  ('child-abuse','Pediatrics','suspected child maltreatment','injuries in different healing stages with an inconsistent history','Ensure immediate safety and report objective findings through mandated channels','Caregivers should know that the team must report reasonable suspicion for child safety','The caregiver attempting to leave with an unstable injured child','Promise the caregiver the report will remain secret','Confront the suspected person aggressively in front of the child','Wait for proof beyond doubt before documenting','Safe and Effective Care Environment'),

  -- Maternal and Newborn (8)
  ('postpartum-hemorrhage','Maternal and Newborn','postpartum hemorrhage from uterine atony','a boggy uterus with heavy lochia and falling blood pressure','Massage the fundus, call for help, and administer prescribed uterotonics','Report soaking a pad in an hour, large clots, dizziness, or faintness','Continued heavy bleeding with tachycardia after fundal massage','Place the client alone in the bathroom','Delay fundal assessment until pain medicine works','Encourage ambulation before stabilizing circulation','Physiological Integrity'),
  ('preeclampsia-severe','Maternal and Newborn','preeclampsia with severe features','severe headache, visual changes, right-upper-quadrant pain, and hypertension','Reduce stimulation, initiate seizure precautions, and administer prescribed magnesium sulfate','Report severe headache, vision changes, breathing difficulty, or epigastric pain immediately','Respiratory rate 10/min during magnesium infusion','Encourage unrestricted ambulation','Give an NSAID for persistent epigastric pain','Increase environmental light and visitors','Physiological Integrity'),
  ('placental-abruption','Maternal and Newborn','placental abruption','painful vaginal bleeding, rigid tender uterus, and fetal distress','Activate obstetric emergency support and prepare for rapid birth and hemorrhage management','Seek immediate care for bleeding, constant abdominal pain, or reduced fetal movement','Late fetal decelerations with maternal hypotension','Perform repeated digital vaginal examinations','Encourage the client to walk to assess labor','Delay IV access until ultrasound confirmation','Physiological Integrity'),
  ('umbilical-cord-prolapse','Maternal and Newborn','umbilical cord prolapse','fetal bradycardia after membrane rupture with a palpable cord','Lift the presenting part off the cord and call for emergency cesarean birth','Call for help immediately if something protrudes from the vagina after membranes rupture','Persistent fetal bradycardia despite relieving cord pressure','Attempt to push the cord back into the uterus','Leave the client supine and unattended','Apply pressure to the uterine fundus','Physiological Integrity'),
  ('newborn-hypoglycemia','Maternal and Newborn','newborn hypoglycemia','jitteriness, poor feeding, hypothermia, and glucose 32 mg/dL','Feed promptly or administer prescribed dextrose and recheck glucose','Use early frequent feeds and recognize jitteriness or poor feeding as warning signs','Apnea or seizure activity with persistent low glucose','Delay feeding to avoid aspiration for six hours','Warm the infant without checking glucose again','Give sterile water instead of breast milk or formula','Physiological Integrity'),
  ('mastitis','Maternal and Newborn','lactational mastitis','unilateral breast pain, fever, and a wedge-shaped red area','Continue breast emptying and administer prescribed antibiotics and analgesia','Continue breastfeeding or pumping, hydrate, rest, and complete antibiotics','A fluctuant breast mass with persistent fever','Stop emptying the affected breast completely','Apply a tight binding wrap around both breasts','Discard all breast milk for the entire antibiotic course','Physiological Integrity'),
  ('ectopic-pregnancy','Maternal and Newborn','a rupturing ectopic pregnancy','unilateral pelvic pain, shoulder pain, dizziness, and spotting','Treat as an emergency, establish IV access, and prepare for surgical management','Seek emergency care for one-sided pain, shoulder pain, faintness, or heavy bleeding','Syncope with a rigid abdomen and hypotension','Apply heat and reassess the next day','Perform vigorous abdominal palpation repeatedly','Encourage oral fluids before possible surgery','Physiological Integrity'),
  ('newborn-jaundice','Maternal and Newborn','significant newborn jaundice','jaundice in the first 24 hours with a rapidly rising bilirubin','Notify the neonatal provider promptly and prepare prescribed phototherapy or evaluation','Feed frequently and keep all bilirubin follow-up appointments','Lethargy, high-pitched cry, and poor suck','Place the infant in direct sunlight unattended','Give plain water between feeds','Stop breastfeeding without provider guidance','Physiological Integrity'),

  -- Mental Health (8)
  ('suicide-risk','Mental Health','acute suicide risk','client states a specific plan and has access to the method','Stay with the client, remove hazards, and initiate constant observation per policy','Ask directly about suicidal thoughts and seek immediate help for a plan or intent','Sudden calmness after giving away possessions','Leave the client alone to build trust','Promise to keep suicidal thoughts confidential','Challenge the client to prove the threat is serious','Psychosocial Integrity'),
  ('mania','Mental Health','acute mania','minimal sleep, pressured speech, intrusive behavior, and constant activity','Reduce stimuli, set concise limits, and offer portable high-calorie foods','Maintain sleep routines and report escalating energy or reduced need for sleep early','Exhaustion with refusal of fluids for an entire shift','Encourage competitive group activities','Debate grandiose beliefs at length','Offer multiple complex choices at once','Psychosocial Integrity'),
  ('alcohol-withdrawal','Mental Health','severe alcohol withdrawal','tremor, diaphoresis, agitation, hallucinations, and hypertension','Initiate seizure precautions and administer symptom-triggered benzodiazepines as prescribed','Do not stop heavy alcohol use abruptly without medical guidance','Disorientation with fever and generalized seizure','Use physical confrontation to stop hallucinations','Give caffeinated drinks for fatigue','Place the client in a stimulating shared room','Physiological Integrity'),
  ('panic-attack','Mental Health','a panic attack','hyperventilation, chest tightness, trembling, and fear of dying','Stay with the client, use short calm statements, and guide slow breathing','Practice paced breathing when calm and reduce caffeine and stimulant use','Chest pain with syncope or new focal neurologic deficits','Teach detailed coping theory during peak panic','Leave the client alone to regain control','Ask rapid open-ended questions','Psychosocial Integrity'),
  ('ptsd-flashback','Mental Health','a PTSD flashback','client appears terrified and says the traumatic event is happening now','Use grounding, identify the present place and time, and offer simple choices','Use sensory grounding and seek support when nightmares or avoidance worsen','New suicidal intent associated with traumatic memories','Touch the client unexpectedly from behind','Demand a detailed trauma narrative immediately','Tell the client the event should be forgotten','Psychosocial Integrity'),
  ('anorexia-refeeding','Mental Health','refeeding syndrome risk in anorexia nervosa','severe malnutrition beginning nutritional rehabilitation','Increase nutrition gradually and monitor phosphate, potassium, magnesium, and cardiac status','Follow the structured meal plan and report weakness, swelling, or palpitations','Phosphate 1.2 mg/dL with new dysrhythmia','Begin unrestricted high-calorie feeding immediately','Weigh the client repeatedly throughout each day','Allow exercise after every meal','Physiological Integrity'),
  ('serotonin-syndrome','Mental Health','serotonin syndrome','agitation, fever, diaphoresis, hyperreflexia, and clonus after medication changes','Stop serotonergic agents and obtain emergency medical treatment','Check before combining antidepressants with supplements or cough medicines','Rapidly rising temperature with muscle rigidity and clonus','Give the next antidepressant dose early','Use an electric blanket for chills','Encourage strenuous walking to reduce agitation','Physiological Integrity'),
  ('delirium','Mental Health','acute delirium','fluctuating attention and confusion after infection and hospitalization','Identify and treat the cause while providing safety and frequent reorientation','Use clocks, glasses, hearing aids, hydration, and familiar routines','New decreased responsiveness with oxygen desaturation','Use restraints before trying alternatives','Move the client to a different room each day','Administer sedatives routinely for nighttime wakefulness','Psychosocial Integrity'),

  -- Leadership and Delegation (8)
  ('delegate-ambulation','Leadership and Delegation','delegating routine ambulation','stable postoperative client already assessed and cleared to walk','Delegate ambulation to trained assistive personnel with clear distance and safety instructions','Staff should report dizziness, pain, or intolerance immediately','New chest pain during delegated ambulation','Delegate the initial postoperative assessment','Ask assistive personnel to decide whether the client is stable','Provide no follow-up because the task was delegated','Safe and Effective Care Environment'),
  ('delegate-feeding','Leadership and Delegation','delegating feeding assistance','stable client with an established diet and completed swallow evaluation','Delegate feeding while specifying positioning, aspiration precautions, and intake reporting','Stop feeding and report coughing, pocketing, or a wet voice','Coughing with oxygen desaturation during the meal','Delegate the initial swallow assessment','Allow feeding while the client lies flat','Ask family to change the prescribed diet texture','Safe and Effective Care Environment'),
  ('lpn-assignment','Leadership and Delegation','an appropriate LPN assignment','team caring for stable and unstable medical clients','Assign the LPN a stable client needing routine medications and a sterile dressing change','The RN retains assessment, teaching, and evaluation for unstable or newly admitted clients','A previously stable client developing acute respiratory distress','Assign initial triage of a client with chest pain to the LPN','Delegate creation of the nursing care plan','Ask the LPN to provide initial discharge teaching for a complex new diagnosis','Safe and Effective Care Environment'),
  ('change-of-condition','Leadership and Delegation','escalating a change in condition','client deteriorates and the first provider notification does not produce action','Use the chain of command and activate rapid response when clinically indicated','Document objective findings, notifications, responses, and continued reassessment','Worsening hypotension with altered mental status','Wait until the next shift to avoid conflict','Change prescribed treatment independently','Document criticism instead of objective clinical facts','Safe and Effective Care Environment'),
  ('medication-error','Leadership and Delegation','responding to a medication error','wrong dose discovered immediately after administration','Assess the client first, notify appropriate clinicians, and follow reporting policy','Report errors promptly; incident reports improve systems and are not part of the medical record','New hypotension or respiratory depression after the error','Alter the medication record to hide the dose','Complete an incident report before assessing the client','Ask the client not to discuss the event','Safe and Effective Care Environment'),
  ('disaster-triage','Leadership and Delegation','mass-casualty triage','limited resources with multiple injured clients','Prioritize clients likely to survive with immediate, resource-efficient intervention','Disaster triage focuses on the greatest good for the greatest number','An airway obstruction that can be corrected rapidly','Use normal first-come first-served order','Spend all resources on one expectant client','Treat minor walking-wounded clients before airway emergencies','Safe and Effective Care Environment'),
  ('impaired-colleague','Leadership and Delegation','suspected clinician impairment','nurse has slurred speech and unsafe medication handling','Remove the clinician from patient care and notify the supervisor per policy','Report objective safety concerns through confidential organizational channels','The impaired clinician attempting to administer a high-alert medication','Confront the colleague publicly at the bedside','Ignore the behavior unless a patient is injured','Drive the colleague home without notifying leadership','Safe and Effective Care Environment'),
  ('confidentiality','Leadership and Delegation','protecting client confidentiality','staff discussing an identifiable client in a public elevator','Stop the conversation and move any necessary discussion to a private setting','Access and share only the minimum information needed for assigned care','Posting a recognizable clinical image on a personal social account','Discuss cases quietly in a crowded cafeteria','Open a neighbor’s chart out of concern','Share login credentials during a busy shift','Safe and Effective Care Environment'),

  -- Safety and Infection Control (8)
  ('tuberculosis','Safety and Infection Control','pulmonary tuberculosis','persistent cough, weight loss, night sweats, and upper-lobe cavitation','Place the client in airborne isolation and use a fit-tested N95 respirator','Take every dose of therapy and follow instructions about masks and follow-up sputum tests','Increasing hemoptysis with respiratory distress','Use only a surgical mask when entering the room','Place the client in a positive-pressure room','Discontinue isolation after the first medication dose','Safe and Effective Care Environment'),
  ('meningococcal','Safety and Infection Control','meningococcal meningitis','fever, severe headache, neck stiffness, and petechial rash','Initiate droplet precautions and give prescribed antibiotics without delay','Close contacts may need prompt prophylaxis and should seek guidance immediately','Purpuric rash with hypotension and delayed capillary refill','Use airborne isolation as the only precaution','Delay treatment until lumbar-puncture results return','Share respiratory equipment after wiping it dry','Safe and Effective Care Environment'),
  ('neutropenia','Safety and Infection Control','severe neutropenia','absolute neutrophil count of 300/mm3 after chemotherapy','Monitor temperature closely and evaluate fever as an emergency','Avoid sick contacts and raw high-risk foods, and report temperature of 100.4°F (38°C) or higher','A single oral temperature of 100.4°F (38°C)','Use rectal thermometers for accurate readings','Keep fresh flowers and standing water in the room','Wait for chills before reporting fever','Safe and Effective Care Environment'),
  ('latex-allergy','Safety and Infection Control','latex allergy','history of reactions to bananas and gloves before surgery','Create a latex-safe environment and clearly communicate the allergy','Check labels and tell every healthcare professional about the latex allergy','Wheezing and facial swelling after glove exposure','Schedule the procedure after rooms with heavy latex use','Use powdered latex gloves briefly','Keep latex equipment at the bedside for emergencies','Safe and Effective Care Environment'),
  ('needlestick','Safety and Infection Control','occupational needlestick exposure','hollow-bore needle injury after blood collection','Wash the site, report immediately, and begin exposure evaluation promptly','Do not squeeze the wound; obtain timely testing and prophylaxis when indicated','A source known to have transmissible infection with delayed reporting','Scrub the wound with bleach','Wait for symptoms before reporting','Recap the needle to preserve it for testing','Safe and Effective Care Environment'),
  ('fire-response','Safety and Infection Control','a fire in a client room','smoke coming from equipment near a bedbound client','Rescue anyone in immediate danger, activate the alarm, contain, then extinguish or evacuate','Know facility fire routes and keep exits and oxygen areas clear','Fire involving oxygen equipment beside a client','Use the elevator for rapid evacuation','Open doors and windows to clear smoke','Fight the fire before moving the endangered client','Safe and Effective Care Environment'),
  ('chemo-spill','Safety and Infection Control','a chemotherapy spill','antineoplastic medication leaking onto the floor','Restrict the area and use the designated chemotherapy spill kit and PPE','Do not clean chemotherapy with ordinary supplies; notify trained personnel immediately','Medication contacting unprotected skin or eyes','Wipe the spill with paper towels and bare hands','Place contaminated items in regular trash','Use a household vacuum on dried residue','Safe and Effective Care Environment'),
  ('radiation-implant','Safety and Infection Control','sealed internal radiation therapy','client receiving brachytherapy','Limit time, maximize distance, use shielding, and follow dosimeter precautions','Visitors must follow time and distance limits and pregnant visitors should avoid exposure','The radioactive source found outside the client','Pick up a dislodged source with bare hands','Keep pregnant staff at the bedside for routine care','Store the source in an open trash container','Safe and Effective Care Environment')
),
numbered as (
  select *, row_number() over (order by topic, slug) as concept_number
  from concepts
),
variants as (
  select * from (values
    (1, 'priority', 'Which action should the nurse take first?', 'priority_action'),
    (2, 'teaching', 'Which statement should the nurse include in teaching?', 'key_teaching'),
    (3, 'danger', 'Which finding requires immediate follow-up?', 'danger_finding')
  ) v(variant_number, variant_name, question_suffix, answer_field)
),
prepared as (
  select
    n.*,
    v.*,
    case v.answer_field
      when 'priority_action' then n.priority_action
      when 'key_teaching' then n.key_teaching
      else n.danger_finding
    end as correct_text,
    ((n.concept_number + v.variant_number - 2) % 4) as correct_position
  from numbered n cross join variants v
),
questions_to_insert as (
  select
    topic,
    'mcq'::text as question_type,
    case variant_name
      when 'priority' then 'A nurse is caring for a client with ' || condition_name || ' who has ' || clinical_cue || '. ' || question_suffix
      when 'teaching' then 'A nurse is teaching a client or caregiver about ' || condition_name || '. ' || question_suffix
      else 'A nurse is monitoring a client with ' || condition_name || '. ' || question_suffix
    end as prompt,
    jsonb_build_array(
      jsonb_build_object('id','a','text',case when correct_position=0 then correct_text else wrong_one end),
      jsonb_build_object('id','b','text',case when correct_position=1 then correct_text when correct_position=0 then wrong_one else wrong_two end),
      jsonb_build_object('id','c','text',case when correct_position=2 then correct_text when correct_position=0 then wrong_two when correct_position=1 then wrong_two else wrong_three end),
      jsonb_build_object('id','d','text',case when correct_position=3 then correct_text else wrong_three end)
    ) as choices,
    jsonb_build_object('ids', jsonb_build_array(chr((97 + correct_position)::integer))) as correct_answer,
    case variant_name
      when 'priority' then priority_action || ' is the priority because it addresses the most immediate threat shown by ' || clinical_cue || '. The other options delay effective care or introduce avoidable risk.'
      when 'teaching' then key_teaching || ' is accurate, safety-focused teaching for ' || condition_name || '. The other statements could delay treatment, worsen the condition, or conflict with the plan of care.'
      else danger_finding || ' signals possible deterioration and requires immediate nursing assessment and escalation. The other options are unsafe responses rather than findings to normalize.'
    end as rationale,
    case variant_name
      when 'priority' then 'Identify the immediate threat, then choose the action that stabilizes airway, breathing, circulation, neurologic status, or safety first.'
      when 'teaching' then 'Choose teaching that prevents harm, supports adherence, and gives the client a clear threshold for seeking help.'
      else 'Separate expected findings from cues of instability; acute changes in airway, breathing, circulation, or consciousness require rapid follow-up.'
    end as strategy,
    client_need,
    case variant_name when 'priority' then 'Take Action' when 'teaching' then 'Generate Solutions' else 'Recognize Cues' end as clinical_judgment
  from prepared
)
insert into public.questions (
  topic, question_type, prompt, choices, correct_answer, rationale, strategy,
  client_need, clinical_judgment, status, minimum_plan
)
select
  q.topic, q.question_type, q.prompt, q.choices, q.correct_answer, q.rationale,
  q.strategy, q.client_need, q.clinical_judgment, 'draft', 'starter'
from questions_to_insert q
where not exists (
  select 1 from public.questions existing
  where lower(trim(existing.prompt)) = lower(trim(q.prompt))
);
