-- Safe seed Yingoh NCLEX question bank, part 3.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is administering IV potassium chloride 40 mEq. Which action is most important?', '[{"id":"a","text":"Administer by IV push over 2 minutes"},{"id":"b","text":"Dilute and infuse no faster than 10 mEq/hour peripherally"},{"id":"c","text":"Add to a 50 mL bag and give over 15 minutes"},{"id":"d","text":"Give orally instead to reduce cardiac risk"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'IV potassium must NEVER be given as a bolus — this causes fatal cardiac dysrhythmias. Maximum peripheral rate is 10 mEq/hr; central line max is 20 mEq/hr. Always dilute and monitor cardiac rhythm.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is administering IV potassium chloride 40 mEq. Which action is most important?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient on isoniazid (INH) for tuberculosis reports numbness and tingling in the feet. Which supplement should the nurse anticipate administering?', '[{"id":"a","text":"Vitamin C"},{"id":"b","text":"Pyridoxine (Vitamin B6)"},{"id":"c","text":"Folate"},{"id":"d","text":"Vitamin D"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'INH causes peripheral neuropathy by interfering with pyridoxine (B6) metabolism. Vitamin B6 supplementation is given prophylactically or to treat neuropathy in patients on INH, especially malnourished patients and the elderly.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient on isoniazid (INH) for tuberculosis reports numbness and tingling in the feet. Which supplement should the nurse anticipate administering?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'sata', 'A nurse is reviewing medications for a patient prescribed MAOIs. Which substances should the patient avoid? (Select all that apply)', '[{"id":"a","text":"Aged cheeses"},{"id":"b","text":"Red wine"},{"id":"c","text":"Pseudoephedrine"},{"id":"d","text":"Fresh fruits"},{"id":"e","text":"Meperidine"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'MAOIs + tyramine-rich foods (aged cheese, red wine) → hypertensive crisis. MAOIs + sympathomimetics (pseudoephedrine) → hypertensive crisis. MAOIs + meperidine (Demerol) → serotonin syndrome or hyperpyrexic coma. Fresh fruits are safe.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is reviewing medications for a patient prescribed MAOIs. Which substances should the patient avoid? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is giving furosemide 40 mg IV. Which assessment finding requires immediate follow-up after administration?', '[{"id":"a","text":"Urine output 200 mL in the first hour"},{"id":"b","text":"Blood pressure decreased from 158/92 to 138/84"},{"id":"c","text":"Serum potassium dropped from 3.8 to 2.9 mEq/L"},{"id":"d","text":"Weight decreased by 0.5 kg"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Furosemide is a loop diuretic that wastes potassium. A drop to 2.9 mEq/L indicates hypokalemia (normal 3.5–5.0), which risks dangerous dysrhythmias. Potassium replacement should be initiated and the provider notified.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is giving furosemide 40 mg IV. Which assessment finding requires immediate follow-up after administration?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient taking methotrexate for rheumatoid arthritis calls to report mouth sores and a temperature of 38.6°C. What is the priority nursing response?', '[{"id":"a","text":"Advise the patient to use salt water rinses and monitor temperature"},{"id":"b","text":"Instruct the patient to go to the emergency department immediately"},{"id":"c","text":"Tell the patient to skip the next methotrexate dose"},{"id":"d","text":"Recommend acetaminophen and call back if temperature exceeds 39°C"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Methotrexate is an immunosuppressant. Fever with mucositis in an immunocompromised patient is a medical emergency — signs of severe bone marrow suppression and infection. The patient needs immediate evaluation and CBC.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient taking methotrexate for rheumatoid arthritis calls to report mouth sores and a temperature of 38.6°C. What is the priority nursing response?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'Which antidote should a nurse have available when administering IV magnesium sulfate?', '[{"id":"a","text":"Naloxone (Narcan)"},{"id":"b","text":"Protamine sulfate"},{"id":"c","text":"Calcium gluconate"},{"id":"d","text":"Flumazenil"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Calcium gluconate is the antidote for magnesium toxicity. Magnesium sulfate toxicity presents with absent reflexes, respiratory depression, and cardiac arrest. Calcium antagonizes magnesium''s CNS and neuromuscular effects.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'Which antidote should a nurse have available when administering IV magnesium sulfate?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient prescribed spironolactone asks what foods to limit. What should the nurse teach?', '[{"id":"a","text":"High-sodium foods"},{"id":"b","text":"High-potassium foods such as bananas and oranges"},{"id":"c","text":"High-fat foods"},{"id":"d","text":"Dairy products"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Spironolactone is a potassium-sparing diuretic. It retains potassium, so patients should limit high-potassium foods to prevent hyperkalemia (K+ >5.0 mEq/L), which causes dangerous dysrhythmias.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient prescribed spironolactone asks what foods to limit. What should the nurse teach?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'sata', 'A nurse is reviewing a patient''s medication list before administering the morning dose. Which medications require the nurse to take an apical pulse for one full minute before administration? (Select all that apply)', '[{"id":"a","text":"Digoxin"},{"id":"b","text":"Metoprolol"},{"id":"c","text":"Diltiazem"},{"id":"d","text":"Amlodipine"},{"id":"e","text":"Lisinopril"}]'::jsonb, '{"ids":["a","b","c"]}'::jsonb, 'Digoxin (cardiac glycoside), metoprolol (beta-blocker), and diltiazem (calcium channel blocker) all reduce heart rate — hold if apical pulse <60 bpm. Amlodipine (CCB) primarily reduces BP, not HR. Lisinopril (ACE inhibitor) does not significantly affect HR.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is reviewing a patient''s medication list before administering the morning dose. Which medications require the nurse to take an apical pulse for one full minute before administration? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is preparing insulin. The order reads: "Regular insulin 10 units and NPH insulin 20 units subcutaneously." What is the correct preparation sequence?', '[{"id":"a","text":"Draw NPH first, then regular"},{"id":"b","text":"Draw regular first, then NPH"},{"id":"c","text":"Mix both in separate syringes and give two injections"},{"id":"d","text":"The order does not matter"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Memory aid: "Clear before cloudy." Regular insulin is clear; draw it first to prevent contaminating the regular vial with NPH (which is cloudy/modified). NPH contamination changes the action profile of regular insulin.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preparing insulin. The order reads: "Regular insulin 10 units and NPH insulin 20 units subcutaneously." What is the correct preparation sequence?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with chronic kidney disease has a serum potassium of 6.2 mEq/L and peaked T waves on ECG. Which intervention is the highest priority?', '[{"id":"a","text":"Administer sodium polystyrene sulfonate (Kayexalate) by mouth"},{"id":"b","text":"Prepare for emergent hemodialysis"},{"id":"c","text":"Administer IV calcium gluconate"},{"id":"d","text":"Start a low-potassium diet"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Peaked T waves with K+ 6.2 mEq/L indicates cardiac danger. IV calcium gluconate is given first to stabilize the cardiac membrane (does not lower K+ but prevents fatal arrhythmias). Then insulin/dextrose, Kayexalate, or dialysis to actually remove potassium.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with chronic kidney disease has a serum potassium of 6.2 mEq/L and peaked T waves on ECG. Which intervention is the highest priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A nurse is caring for a patient with a pulmonary embolism (PE). Which findings are consistent with this diagnosis? (Select all that apply)', '[{"id":"a","text":"Sudden onset dyspnea"},{"id":"b","text":"Pleuritic chest pain"},{"id":"c","text":"Hemoptysis"},{"id":"d","text":"Bradycardia"},{"id":"e","text":"SpO2 88%"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Classic PE triad: dyspnea, pleuritic chest pain, hemoptysis. Hypoxia (low SpO2) and tachycardia (not bradycardia) are expected. Bradycardia is not a PE finding — the compensatory response is tachycardia.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with a pulmonary embolism (PE). Which findings are consistent with this diagnosis? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient returns from cardiac catheterization via the right femoral artery. Which assessment finding requires immediate action?', '[{"id":"a","text":"Pedal pulse 2+ in right foot"},{"id":"b","text":"Small bruise at insertion site"},{"id":"c","text":"Right groin hematoma expanding rapidly"},{"id":"d","text":"Patient reports needing to void"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'A rapidly expanding hematoma at the femoral access site indicates arterial bleeding — a vascular emergency. Apply firm manual pressure and notify the provider immediately. The patient may need emergent intervention.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient returns from cardiac catheterization via the right femoral artery. Which assessment finding requires immediate action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with COPD is admitted with exacerbation. ABGs show pH 7.32, PaCO2 58, PaO2 62, HCO3 26. Which interpretation is correct?', '[{"id":"a","text":"Respiratory alkalosis"},{"id":"b","text":"Metabolic acidosis"},{"id":"c","text":"Respiratory acidosis, partially compensated"},{"id":"d","text":"Metabolic alkalosis"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'pH 7.32 (acidosis), PaCO2 58 (elevated → respiratory cause), HCO3 26 (slightly elevated → renal compensation). This is respiratory acidosis with partial metabolic compensation — classic COPD exacerbation with CO2 retention.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with COPD is admitted with exacerbation. ABGs show pH 7.32, PaCO2 58, PaO2 62, HCO3 26. Which interpretation is correct?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A nurse is caring for a patient following a total hip replacement. Which actions help prevent hip dislocation? (Select all that apply)', '[{"id":"a","text":"Keep an abduction pillow between legs"},{"id":"b","text":"Avoid hip flexion beyond 90 degrees"},{"id":"c","text":"Encourage the patient to cross their legs when sitting"},{"id":"d","text":"Use a raised toilet seat"},{"id":"e","text":"Avoid internal rotation of the operative leg"}]'::jsonb, '{"ids":["a","b","d","e"]}'::jsonb, 'Hip dislocation precautions: abduction pillow to keep hips apart, no flexion >90°, use raised toilet seat, avoid internal rotation and adduction. Crossing legs causes adduction and internal rotation — strictly prohibited.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient following a total hip replacement. Which actions help prevent hip dislocation? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with a nasogastric tube connected to low intermittent suction develops muscle cramps and positive Chvostek''s sign. Which electrolyte imbalance should the nurse suspect?', '[{"id":"a","text":"Hyperkalemia"},{"id":"b","text":"Hypocalcemia"},{"id":"c","text":"Hypernatremia"},{"id":"d","text":"Hypomagnesemia"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Chvostek''s sign (facial twitching when tapping facial nerve) and Trousseau''s sign indicate hypocalcemia. NG suction removes gastric acid (HCl), causing metabolic alkalosis, which decreases ionized calcium. Monitor calcium levels.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with a nasogastric tube connected to low intermittent suction develops muscle cramps and positive Chvostek''s sign. Which electrolyte imbalance should the nurse suspect?');
