-- Seed Yingoh NCLEX question bank, part 6.
-- Inserts only prompts that do not already exist, so it is safe to rerun.

insert into public.questions (
  topic,
  question_type,
  prompt,
  choices,
  correct_answer,
  rationale,
  strategy,
  client_need,
  clinical_judgment,
  status
)
select *
from (values
  ('Complex Care', 'mcq', 'A client in septic shock is on norepinephrine. Which finding best indicates treatment is working?', '[{"id":"a","text":"Serum lactate falling from 6.2 to 2.1 mmol/L"},{"id":"b","text":"Temperature falling from 39.8°C to 37.1°C"},{"id":"c","text":"HR falling from 118 to 98 bpm"},{"id":"d","text":"WBC falling from 22,000 to 14,000/mm³"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Falling serum lactate = gold standard for improving tissue perfusion in septic shock. Lactate rises during anaerobic metabolism. Falling lactate = cells are receiving oxygen = perfusion is restored.', 'Septic shock goal = restore tissue perfusion. Lactate is the direct cellular oxygen marker. Temperature and WBC reflect infection control, not perfusion. Falling lactate = treatment working.', '', '', 'published'),
  ('Oncology and Hematology', 'mcq', 'A client on chemotherapy has an ANC of 450/mm³. The nursing priority is to:', '[{"id":"a","text":"Administer a platelet transfusion"},{"id":"b","text":"Initiate neutropenic precautions and monitor for infection"},{"id":"c","text":"Restrict all visitors from the room"},{"id":"d","text":"Place the client on contact precautions"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'ANC < 500/mm³ = severe neutropenia = highest infection risk. Neutropenic precautions protect the immunocompromised client from the environment (reverse isolation). Platelets address thrombocytopenia. Not all visitors restricted — healthy visitors with good hand hygiene may visit.', 'ANC < 500 = neutropenic precautions. These protect the client FROM pathogens (reverse/protective isolation). Contact precautions protect others FROM the client. Know which direction protection flows.', '', '', 'published'),
  ('Oncology and Hematology', 'sata', 'A client develops chills, fever, low back pain, and hypotension 20 minutes into a transfusion. The nurse takes which actions? Select all that apply.', '[{"id":"a","text":"Stop the transfusion immediately"},{"id":"b","text":"Slow the rate and continue monitoring"},{"id":"c","text":"Keep IV open with normal saline"},{"id":"d","text":"Notify the blood bank and provider"},{"id":"e","text":"Send the blood bag and tubing to the lab"}]'::jsonb, '{"ids":["a","c","d","e"]}'::jsonb, 'Acute hemolytic transfusion reaction (blood type mismatch): STOP immediately, maintain IV with NS using new tubing, notify provider and blood bank, send blood bag + tubing for analysis. Never slow and continue.', 'Hemolytic reaction = STOP — KEEP LINE WITH NS — NOTIFY — SEND BAG. Never slow and continue. The bag must return to the blood bank. This is a life-threatening reaction.', '', '', 'published'),
  ('Perioperative Care', 'sata', 'A nurse completes a pre-operative assessment. Which findings require notifying the provider? Select all that apply.', '[{"id":"a","text":"Client takes warfarin 5 mg daily"},{"id":"b","text":"Client has a latex allergy"},{"id":"c","text":"Hemoglobin 14.2 g/dL"},{"id":"d","text":"Client takes St. John''s Wort herbal supplement"},{"id":"e","text":"BP 128/76 mmHg"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Report: warfarin (bleeding risk — may need to be held); latex allergy (OR must be latex-free, anaphylaxis risk); St. John''s Wort (interacts with anesthesia — must stop 2 weeks pre-op). Normal Hgb and BP do not require reporting.', 'Pre-op safety flags: anticoagulants, allergies (especially latex), herbals. Normal labs and vital signs within range = no notification needed. Herbals that interfere: St. John''s Wort, garlic, ginkgo, ginseng.', '', '', 'published'),
  ('Medication Administration', 'mcq', 'Which situation requires the nurse to withhold the medication and contact the provider?', '[{"id":"a","text":"Client on digoxin has apical pulse of 54 bpm"},{"id":"b","text":"Client on metformin has BG of 210 mg/dL"},{"id":"c","text":"Client on lisinopril has BP 142/88 mmHg"},{"id":"d","text":"Client on ferrous sulfate reports dark-colored stools"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Hold digoxin when apical pulse < 60 bpm. Digoxin further slows the heart — bradycardia below 60 is a contraindication. Dark stools with iron are expected. Metformin at BG 210 is within management range. Lisinopril is given for hypertension — BP 142/88 does not warrant withholding.', 'Digoxin rule: apical pulse < 60 = hold and notify. Always count apical for a full minute before giving digoxin. One of the most tested medication safety rules on NCLEX. Know the hold parameters.', '', '', 'published'),
  ('Cardiovascular', 'mcq', 'A client with heart failure reports new shortness of breath while lying flat and has crackles halfway up both lung fields. Which prescription should the nurse question?', '[{"id":"a","text":"Furosemide 40 mg IV now"},{"id":"b","text":"Restrict fluids to 1.5 L/day"},{"id":"c","text":"Infuse 0.9% saline at 150 mL/hr"},{"id":"d","text":"Obtain daily weights each morning"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Rapid isotonic fluid infusion can worsen pulmonary congestion in heart failure. Diuretics, fluid restriction, and daily weights are expected management.', 'In heart failure, new crackles plus orthopnea means fluid is already in the lungs. Do not add more fluid unless there is a compelling reason.', 'Physiological Integrity', 'Analyze Cues', 'published'),
  ('Cardiovascular', 'mcq', 'A client develops chest pain after walking to the bathroom. Which action should the nurse take first?', '[{"id":"a","text":"Call the provider"},{"id":"b","text":"Obtain a 12-lead ECG"},{"id":"c","text":"Stop activity and assist the client to rest"},{"id":"d","text":"Administer morphine as prescribed"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'The first action is to decrease myocardial oxygen demand by stopping activity and placing the client at rest. ECG and medications follow rapid assessment and stabilization.', 'For angina questions, first reduce oxygen demand: stop activity, rest, then assess and treat.', 'Physiological Integrity', 'Take Action', 'published'),
  ('Cardiovascular', 'mcq', 'Which finding is most concerning after femoral cardiac catheterization?', '[{"id":"a","text":"Blood pressure 118/74 mmHg"},{"id":"b","text":"Pedal pulse weaker than baseline"},{"id":"c","text":"Client reports needing to void"},{"id":"d","text":"Small bruise at the insertion site"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A weaker distal pulse may indicate arterial occlusion or impaired perfusion after catheterization and requires immediate action. A small bruise and urinary urgency can be expected.', 'After cath, think circulation below the insertion site: pulse, color, temperature, sensation, movement.', 'Physiological Integrity', 'Recognize Cues', 'published'),
  ('Cardiovascular', 'mcq', 'A client taking warfarin has an INR of 6.2 and bleeding gums. Which order should the nurse anticipate?', '[{"id":"a","text":"Vitamin K"},{"id":"b","text":"Protamine sulfate"},{"id":"c","text":"Aspirin"},{"id":"d","text":"Additional warfarin"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Vitamin K reverses warfarin. Protamine reverses heparin. Aspirin and more warfarin increase bleeding risk.', 'Match antidotes: warfarin = vitamin K; heparin = protamine.', 'Physiological Integrity', 'Generate Solutions', 'published'),
  ('Respiratory', 'mcq', 'A client with COPD is receiving oxygen at 6 L/min by nasal cannula and becomes increasingly drowsy. Which action should the nurse take first?', '[{"id":"a","text":"Increase oxygen to 10 L/min"},{"id":"b","text":"Assess respiratory rate and oxygen saturation"},{"id":"c","text":"Encourage oral fluids"},{"id":"d","text":"Place the client flat in bed"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Increasing drowsiness may reflect carbon dioxide retention or worsening respiratory failure. The nurse first assesses ventilation and oxygenation.', 'Change in level of consciousness in COPD can mean CO2 retention. Assess breathing before changing therapy.', 'Physiological Integrity', 'Recognize Cues', 'published'),
  ('Respiratory', 'mcq', 'Which arterial blood gas result requires the most immediate follow-up?', '[{"id":"a","text":"pH 7.39, PaCO2 40, HCO3 24"},{"id":"b","text":"pH 7.31, PaCO2 60, HCO3 26"},{"id":"c","text":"pH 7.45, PaCO2 36, HCO3 24"},{"id":"d","text":"pH 7.36, PaCO2 42, HCO3 23"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A low pH with elevated PaCO2 indicates respiratory acidosis, which may signal hypoventilation and respiratory failure.', 'ROME: pH low and CO2 high move opposite, so respiratory acidosis.', 'Physiological Integrity', 'Analyze Cues', 'published'),
  ('Respiratory', 'mcq', 'A client with pneumonia has SpO2 86%, respiratory rate 32/min, and confusion. Which action is priority?', '[{"id":"a","text":"Collect sputum culture"},{"id":"b","text":"Apply oxygen as prescribed"},{"id":"c","text":"Teach incentive spirometry"},{"id":"d","text":"Document expected findings"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Hypoxemia with confusion requires immediate oxygenation support. Cultures and teaching can occur after stabilizing airway and breathing.', 'ABC priority: low oxygen plus confusion means the brain is not getting oxygen.', 'Physiological Integrity', 'Prioritize Hypotheses', 'published'),
  ('Respiratory', 'mcq', 'Which instruction is most important for a client using an albuterol inhaler before a corticosteroid inhaler?', '[{"id":"a","text":"Use albuterol first, wait several minutes, then use the corticosteroid"},{"id":"b","text":"Use the corticosteroid first to open the airways"},{"id":"c","text":"Do not rinse the mouth after corticosteroid use"},{"id":"d","text":"Use both inhalers only when symptoms are severe"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'A bronchodilator is used first to open airways, improving delivery of the corticosteroid. The client should rinse the mouth after inhaled steroids.', 'Bronchodilator before steroid: open the airway, then deliver the anti-inflammatory medication.', 'Physiological Integrity', 'Take Action', 'published'),
  ('Renal and Urinary', 'mcq', 'A client with chronic kidney disease has potassium 6.1 mEq/L. Which assessment finding is most important?', '[{"id":"a","text":"Dry skin"},{"id":"b","text":"Peaked T waves"},{"id":"c","text":"Poor appetite"},{"id":"d","text":"Mild ankle edema"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Hyperkalemia can cause life-threatening dysrhythmias. Peaked T waves are a classic ECG sign requiring urgent intervention.', 'High potassium hurts the heart first. ECG changes are the danger cue.', 'Physiological Integrity', 'Recognize Cues', 'published'),
  ('Renal and Urinary', 'mcq', 'Which client statement about hemodialysis access needs correction?', '[{"id":"a","text":"I will avoid blood pressure readings in the access arm"},{"id":"b","text":"I will check for a thrill every day"},{"id":"c","text":"I can sleep with my access arm under my body"},{"id":"d","text":"I will report redness or drainage"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Pressure on the access arm can impair blood flow and clot the fistula or graft. The other statements are appropriate.', 'Protect the access: no pressure, no sticks, no BP, check thrill/bruit.', 'Physiological Integrity', 'Evaluate Outcomes', 'published'),
  ('Renal and Urinary', 'mcq', 'A client with acute kidney injury has urine output of 18 mL/hr for 4 hours. Which action is priority?', '[{"id":"a","text":"Encourage high-protein foods"},{"id":"b","text":"Notify the provider"},{"id":"c","text":"Restrict all fluids permanently"},{"id":"d","text":"Document as normal"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Urine output below 30 mL/hr indicates oliguria and may reflect worsening renal perfusion or injury. Prompt follow-up is needed.', 'Minimum urine output is 30 mL/hr. Below that is a perfusion problem until proven otherwise.', 'Physiological Integrity', 'Take Action', 'published'),
  ('Endocrine', 'mcq', 'A client with diabetes is shaky, diaphoretic, and has blood glucose 48 mg/dL. The client is awake and able to swallow. What should the nurse give first?', '[{"id":"a","text":"Regular insulin"},{"id":"b","text":"15 g fast-acting carbohydrate"},{"id":"c","text":"A high-fat meal"},{"id":"d","text":"Metformin"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'An awake client with hypoglycemia should receive 15 g of rapid carbohydrate, then glucose is rechecked. Insulin would worsen hypoglycemia.', 'Conscious hypoglycemia = oral fast sugar. Unconscious = IV dextrose or glucagon.', 'Physiological Integrity', 'Take Action', 'published'),
  ('Endocrine', 'mcq', 'Which finding in a client with syndrome of inappropriate antidiuretic hormone secretion is expected?', '[{"id":"a","text":"Serum sodium 124 mEq/L"},{"id":"b","text":"Dilute urine"},{"id":"c","text":"Signs of dehydration"},{"id":"d","text":"Increased urine output"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'SIADH causes water retention and dilutional hyponatremia. Urine is concentrated and output is often low.', 'SIADH = too much water held in the body, so sodium becomes diluted.', 'Physiological Integrity', 'Analyze Cues', 'published'),
  ('Endocrine', 'mcq', 'A client after thyroidectomy reports tingling around the mouth and muscle cramps. Which complication does the nurse suspect?', '[{"id":"a","text":"Hypocalcemia"},{"id":"b","text":"Hyperglycemia"},{"id":"c","text":"Fluid overload"},{"id":"d","text":"Thyroid storm"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Parathyroid injury after thyroidectomy can cause hypocalcemia, producing tingling, cramps, tetany, or positive Chvostek/Trousseau signs.', 'After thyroid surgery, tingling and cramps point to low calcium from parathyroid disturbance.', 'Physiological Integrity', 'Recognize Cues', 'published'),
  ('Gastrointestinal', 'mcq', 'A client with cirrhosis becomes confused and has asterixis. Which lab value is most relevant?', '[{"id":"a","text":"Ammonia"},{"id":"b","text":"Troponin"},{"id":"c","text":"Creatine kinase"},{"id":"d","text":"Potassium"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Confusion and asterixis in cirrhosis suggest hepatic encephalopathy from elevated ammonia.', 'Liver failure plus mental status changes equals ammonia until proven otherwise.', 'Physiological Integrity', 'Analyze Cues', 'published'),
  ('Gastrointestinal', 'mcq', 'Which diet instruction is best for a client with dumping syndrome after gastric surgery?', '[{"id":"a","text":"Drink large amounts of fluid with meals"},{"id":"b","text":"Lie down after meals"},{"id":"c","text":"Eat high-sugar foods between meals"},{"id":"d","text":"Eat three large meals daily"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Lying down after meals can slow gastric emptying. Clients should eat small frequent meals, avoid high sugar, and limit fluids with meals.', 'Dumping syndrome = food moves too fast. Slow it with small meals, low sugar, and lying down after eating.', 'Physiological Integrity', 'Generate Solutions', 'published'),
  ('Gastrointestinal', 'mcq', 'A client with acute pancreatitis has severe epigastric pain radiating to the back. Which order should the nurse question?', '[{"id":"a","text":"NPO status"},{"id":"b","text":"IV opioid analgesic"},{"id":"c","text":"Low-fat solid meal tray"},{"id":"d","text":"IV fluids"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Oral intake stimulates pancreatic enzyme secretion and can worsen acute pancreatitis. NPO, fluids, and pain control are expected.', 'Pancreatitis care rests the pancreas: NPO, fluids, pain control.', 'Physiological Integrity', 'Evaluate Outcomes', 'published'),
  ('Neurological', 'mcq', 'A client has a sudden severe headache, vomiting, and decreased level of consciousness. Which condition is most concerning?', '[{"id":"a","text":"Migraine"},{"id":"b","text":"Subarachnoid hemorrhage"},{"id":"c","text":"Sinus infection"},{"id":"d","text":"Tension headache"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A sudden severe headache with vomiting and decreased consciousness suggests hemorrhagic stroke/subarachnoid hemorrhage and requires emergency care.', 'Worst headache plus neuro decline is bleeding until proven otherwise.', 'Physiological Integrity', 'Prioritize Hypotheses', 'published'),
  ('Neurological', 'mcq', 'A client with myasthenia gravis has increasing difficulty swallowing and shallow respirations. What is the priority?', '[{"id":"a","text":"Offer a full meal"},{"id":"b","text":"Assess respiratory status and prepare for ventilatory support"},{"id":"c","text":"Encourage ambulation"},{"id":"d","text":"Delay medications until bedtime"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Myasthenic crisis can cause respiratory muscle weakness and airway compromise. Breathing is the priority.', 'Weakness disorders become emergencies when they affect swallowing or breathing.', 'Physiological Integrity', 'Take Action', 'published'),
  ('Neurological', 'mcq', 'Which action is appropriate for a client after a tonic-clonic seizure ends?', '[{"id":"a","text":"Place the client in a side-lying position"},{"id":"b","text":"Insert a padded tongue blade"},{"id":"c","text":"Restrain the arms"},{"id":"d","text":"Give oral fluids immediately"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'After a seizure, side-lying positioning helps maintain airway and allows secretions to drain. Nothing should be placed in the mouth.', 'Seizure care after: airway, side-lying, assess, document. Nothing in the mouth.', 'Safe and Effective Care Environment', 'Take Action', 'published'),
  ('Acid-Base Balance', 'mcq', 'A client has pH 7.50, PaCO2 30 mmHg, HCO3 24 mEq/L. How should the nurse interpret this?', '[{"id":"a","text":"Respiratory alkalosis"},{"id":"b","text":"Respiratory acidosis"},{"id":"c","text":"Metabolic acidosis"},{"id":"d","text":"Metabolic alkalosis"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'High pH indicates alkalosis. Low PaCO2 causes alkalosis by blowing off acid. HCO3 is normal, so this is respiratory alkalosis.', 'ROME: respiratory problems move opposite. pH high, CO2 low = respiratory alkalosis.', 'Physiological Integrity', 'Analyze Cues', 'published'),
  ('Acid-Base Balance', 'mcq', 'Which client is at highest risk for metabolic alkalosis?', '[{"id":"a","text":"Client with prolonged vomiting"},{"id":"b","text":"Client with diabetic ketoacidosis"},{"id":"c","text":"Client with renal failure and acidosis"},{"id":"d","text":"Client with severe diarrhea"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Vomiting causes loss of gastric acid, leading to metabolic alkalosis. DKA, renal failure, and diarrhea commonly cause metabolic acidosis.', 'Lose acid from the stomach, become alkalotic. Lose bicarbonate from diarrhea, become acidotic.', 'Physiological Integrity', 'Recognize Cues', 'published'),
  ('Acid-Base Balance', 'mcq', 'A client with anxiety is hyperventilating. Which ABG change is expected first?', '[{"id":"a","text":"PaCO2 decreases"},{"id":"b","text":"HCO3 increases immediately"},{"id":"c","text":"pH decreases"},{"id":"d","text":"Potassium rises sharply"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Hyperventilation blows off CO2, causing PaCO2 to fall and pH to rise. Renal compensation takes longer.', 'Breathing changes CO2 quickly. Kidneys change bicarbonate slowly.', 'Physiological Integrity', 'Analyze Cues', 'published'),
  ('Nutrition', 'mcq', 'Which meal choice is best for a client with iron-deficiency anemia?', '[{"id":"a","text":"Spinach salad with grilled chicken and orange slices"},{"id":"b","text":"White rice with tea"},{"id":"c","text":"Plain gelatin and cola"},{"id":"d","text":"Toast with coffee"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Iron-rich foods with vitamin C improve iron absorption. Tea and coffee can reduce absorption.', 'Pair iron with vitamin C. Avoid tea/coffee around iron.', 'Health Promotion and Maintenance', 'Generate Solutions', 'published'),
  ('Nutrition', 'mcq', 'A client receiving total parenteral nutrition suddenly has diaphoresis and tremors after the bag runs empty. What should the nurse suspect?', '[{"id":"a","text":"Rebound hypoglycemia"},{"id":"b","text":"Fluid overload"},{"id":"c","text":"Hypercalcemia"},{"id":"d","text":"Allergic reaction"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Abrupt discontinuation of TPN can cause rebound hypoglycemia because the client was receiving high glucose continuously.', 'Never stop TPN abruptly. If interrupted, hang dextrose per policy.', 'Physiological Integrity', 'Recognize Cues', 'published'),
  ('Nutrition', 'mcq', 'Which instruction is appropriate for a client with dysphagia?', '[{"id":"a","text":"Use thin liquids freely"},{"id":"b","text":"Sit upright during meals"},{"id":"c","text":"Tilt the head back to swallow"},{"id":"d","text":"Eat quickly before tiring"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Upright positioning reduces aspiration risk. Thickened liquids, slow pacing, and chin-tuck may be used depending on swallow evaluation.', 'Dysphagia safety = upright, slow, small bites, prescribed texture.', 'Safe and Effective Care Environment', 'Take Action', 'published'),
  ('Integumentary', 'mcq', 'Which pressure injury finding should the nurse stage as stage 2?', '[{"id":"a","text":"Intact purple area over the heel"},{"id":"b","text":"Full-thickness tissue loss with bone visible"},{"id":"c","text":"Partial-thickness skin loss with a shallow open blister"},{"id":"d","text":"Nonblanchable intact redness"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Stage 2 pressure injury involves partial-thickness skin loss, often appearing as a shallow open ulcer or blister.', 'Stage 1 intact red; Stage 2 partial skin loss/blister; Stage 4 bone/tendon.', 'Physiological Integrity', 'Analyze Cues', 'published'),
  ('Integumentary', 'mcq', 'A client has a new burn injury. Which assessment is the nurse''s priority?', '[{"id":"a","text":"Airway patency"},{"id":"b","text":"Body image concerns"},{"id":"c","text":"Long-term scar care"},{"id":"d","text":"Diet preferences"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Airway injury is the immediate life threat after burns, especially with facial burns, smoke exposure, or enclosed-space fire.', 'Burn priority: airway first, then fluids, then wound care.', 'Physiological Integrity', 'Prioritize Hypotheses', 'published'),
  ('Immune System', 'mcq', 'Which finding suggests anaphylaxis after antibiotic administration?', '[{"id":"a","text":"Wheezing and swelling of the lips"},{"id":"b","text":"Mild nausea only"},{"id":"c","text":"Dry mouth"},{"id":"d","text":"Temporary headache"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Wheezing and lip/tongue swelling indicate airway involvement and systemic allergic reaction requiring emergency treatment.', 'Allergy becomes anaphylaxis when airway, breathing, or circulation is involved.', 'Physiological Integrity', 'Recognize Cues', 'published'),
  ('Immune System', 'mcq', 'A client with HIV has a CD4 count of 180 cells/mm3. Which teaching is most important?', '[{"id":"a","text":"Report fever or new cough promptly"},{"id":"b","text":"Stop antiretroviral therapy when feeling better"},{"id":"c","text":"Avoid all exercise"},{"id":"d","text":"Share razors only with family"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'A CD4 count below 200 increases risk for opportunistic infections. Fever or respiratory symptoms need prompt evaluation.', 'CD4 under 200 = high infection risk. Infection symptoms matter fast.', 'Health Promotion and Maintenance', 'Take Action', 'published'),
  ('Eye and Ear', 'mcq', 'Which instruction is most important after cataract surgery?', '[{"id":"a","text":"Avoid bending at the waist"},{"id":"b","text":"Rub the eye if it itches"},{"id":"c","text":"Sleep on the operative side"},{"id":"d","text":"Lift heavy objects to resume activity"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Bending, rubbing, heavy lifting, and pressure on the operative eye can increase intraocular pressure and disrupt healing.', 'Eye surgery teaching: protect the eye and avoid pressure increases.', 'Safe and Effective Care Environment', 'Take Action', 'published'),
  ('Eye and Ear', 'mcq', 'A client reports sudden painless vision loss described as a curtain coming down. Which problem is suspected?', '[{"id":"a","text":"Retinal detachment"},{"id":"b","text":"Conjunctivitis"},{"id":"c","text":"Otitis media"},{"id":"d","text":"Cataract"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Retinal detachment may present with sudden painless vision loss, flashes, floaters, or a curtain-like shadow.', 'Curtain over vision = retina emergency.', 'Physiological Integrity', 'Recognize Cues', 'published'),
  ('Musculoskeletal', 'mcq', 'Which finding after total hip arthroplasty requires immediate action?', '[{"id":"a","text":"Leg internally rotated and shortened"},{"id":"b","text":"Pain rated 4/10 with movement"},{"id":"c","text":"Mild swelling near incision"},{"id":"d","text":"Use of abduction pillow"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Internal rotation and shortening suggest hip prosthesis dislocation. This requires immediate provider notification and immobilization.', 'After hip replacement, shortening plus rotation equals dislocation.', 'Physiological Integrity', 'Recognize Cues', 'published'),
  ('Musculoskeletal', 'mcq', 'A client with osteoporosis asks how to reduce fracture risk. Which instruction is best?', '[{"id":"a","text":"Perform weight-bearing exercise as tolerated"},{"id":"b","text":"Avoid calcium foods"},{"id":"c","text":"Stay in bed to prevent falls"},{"id":"d","text":"Take extra sedatives at night"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Weight-bearing exercise, calcium/vitamin D, fall prevention, and medication adherence reduce fracture risk.', 'Osteoporosis prevention is load the bones safely and prevent falls.', 'Health Promotion and Maintenance', 'Generate Solutions', 'published'),
  ('Medication Administration', 'mcq', 'Before administering an IV push opioid, which assessment is priority?', '[{"id":"a","text":"Respiratory rate"},{"id":"b","text":"Hair color"},{"id":"c","text":"Last bowel movement only"},{"id":"d","text":"Diet preference"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Opioids can depress respirations. Respiratory rate and sedation level must be assessed before administration.', 'Opioid safety: pain score matters, but breathing comes first.', 'Safe and Effective Care Environment', 'Recognize Cues', 'published'),
  ('Medication Administration', 'mcq', 'Which action follows the three checks of medication administration?', '[{"id":"a","text":"Check medication label against MAR when removing, preparing, and at bedside"},{"id":"b","text":"Check only after giving"},{"id":"c","text":"Ask another client to confirm"},{"id":"d","text":"Skip checks for familiar medications"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'The medication label is checked against the MAR when retrieving, preparing, and before administration to reduce errors.', 'Three checks are built to catch errors before the medication reaches the client.', 'Safe and Effective Care Environment', 'Take Action', 'published'),
  ('Perioperative Care', 'mcq', 'A postoperative client has stridor and restlessness after neck surgery. What is the priority action?', '[{"id":"a","text":"Assess airway and call for help"},{"id":"b","text":"Offer ice chips"},{"id":"c","text":"Encourage ambulation"},{"id":"d","text":"Place in Trendelenburg position"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Stridor indicates airway obstruction and is an emergency. Airway assessment and rapid help are priorities.', 'Stridor is airway narrowing. Treat it as an emergency every time.', 'Physiological Integrity', 'Prioritize Hypotheses', 'published'),
  ('Perioperative Care', 'mcq', 'Which instruction helps prevent postoperative atelectasis?', '[{"id":"a","text":"Use incentive spirometer regularly"},{"id":"b","text":"Avoid coughing completely"},{"id":"c","text":"Remain flat in bed"},{"id":"d","text":"Limit turning for 48 hours"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Incentive spirometry, coughing, deep breathing, turning, and early ambulation help re-expand alveoli and prevent atelectasis.', 'Post-op lungs need expansion: cough, deep breathe, incentive spirometer, move.', 'Physiological Integrity', 'Take Action', 'published'),
  ('Complex Care', 'mcq', 'A client with suspected sepsis has BP 84/48, temp 39.4 C, HR 128, and lactate 5.2. Which action is priority?', '[{"id":"a","text":"Begin ordered fluid resuscitation"},{"id":"b","text":"Delay antibiotics until fever resolves"},{"id":"c","text":"Place on a regular diet"},{"id":"d","text":"Limit vital signs to once daily"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Hypotension and elevated lactate indicate poor tissue perfusion in sepsis. Fluid resuscitation and rapid sepsis protocol care are priorities.', 'Sepsis priority is perfusion: fluids, cultures/antibiotics per protocol, lactate trends.', 'Physiological Integrity', 'Take Action', 'published'),
  ('Complex Care', 'mcq', 'Which client should the emergency nurse see first?', '[{"id":"a","text":"Client with chest pain and diaphoresis"},{"id":"b","text":"Client with ankle sprain and swelling"},{"id":"c","text":"Client requesting a work note"},{"id":"d","text":"Client with mild sore throat for 3 days"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Chest pain with diaphoresis suggests possible acute coronary syndrome and takes priority over stable, non-life-threatening concerns.', 'Triage asks: who may die soon? Chest pain plus diaphoresis wins.', 'Safe and Effective Care Environment', 'Prioritize Hypotheses', 'published')
) as seed(topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
where not exists (
  select 1
  from public.questions q
  where q.prompt = seed.prompt
);
