-- Safe seed Yingoh NCLEX question bank, part 7.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse is caring for a patient with MRSA in a wound. Which PPE should be donned before entering the room?', '[{"id":"a","text":"N95 respirator and gloves"},{"id":"b","text":"Gown and gloves"},{"id":"c","text":"Surgical mask, gown, and gloves"},{"id":"d","text":"Gloves only for direct wound contact"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'MRSA requires contact precautions: gown and gloves upon room entry. A mask is not required for MRSA wound infections (MRSA is not airborne). A mask would be added for procedures generating respiratory secretions. Gloves alone are insufficient — gown prevents clothing contamination.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with MRSA in a wound. Which PPE should be donned before entering the room?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse is assessing a patient''s fall risk using the Morse Fall Scale. Which factor contributes most to a high score?', '[{"id":"a","text":"Age over 65"},{"id":"b","text":"History of a fall in the past 3 months"},{"id":"c","text":"Impaired gait requiring a walker"},{"id":"d","text":"Use of diuretic medication"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'The Morse Fall Scale scores: history of falling (25 points — highest single item), secondary diagnosis, ambulatory aid, IV or heparin lock, gait, and mental status. A prior fall is the strongest predictor of future falls. Implement high-risk fall precautions for scores ≥45.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is assessing a patient''s fall risk using the Morse Fall Scale. Which factor contributes most to a high score?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse has four patients. Which patient should be assessed first?', '[{"id":"a","text":"A patient with chronic back pain requesting pain medication"},{"id":"b","text":"A post-op patient with oxygen saturation of 90% reported by the UAP"},{"id":"c","text":"A stable patient with diabetes asking about diet instructions"},{"id":"d","text":"A patient awaiting discharge with prescription questions"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Airway/oxygenation is always priority. SpO2 90% is below normal (95–100%) and may indicate respiratory compromise — assess immediately. Chronic pain, diet teaching, and discharge questions are lower acuity. Apply ABC (Airway, Breathing, Circulation) and Maslow''s hierarchy to prioritize.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse has four patients. Which patient should be assessed first?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'sata', 'A charge nurse is delegating tasks to a UAP. Which tasks are within the UAP''s scope of practice? (Select all that apply)', '[{"id":"a","text":"Measuring and recording urine output"},{"id":"b","text":"Ambulating a stable post-op patient"},{"id":"c","text":"Administering a PRN enema"},{"id":"d","text":"Obtaining vital signs on stable patients"},{"id":"e","text":"Performing a focused respiratory assessment"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'UAPs may perform: vital signs on stable patients, measuring I&O, feeding, ambulating stable patients, hygiene, positioning. UAPs may NOT: assessments (physical, focused, or otherwise), medication administration, IV care, or care requiring clinical judgment. Enemas require RN order and assessment of response.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A charge nurse is delegating tasks to a UAP. Which tasks are within the UAP''s scope of practice? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse discovers a medication error made by the previous shift. The patient is unharmed. What is the nurse''s priority action?', '[{"id":"a","text":"Confront the nurse who made the error"},{"id":"b","text":"Assess the patient, notify the provider, and complete an incident report"},{"id":"c","text":"Document the error in the patient''s chart in detail"},{"id":"d","text":"Report the error to the state board of nursing immediately"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Medication error response: 1) Assess patient, 2) Notify the provider of the error and patient status, 3) Complete an internal incident/variance report (this is NOT documented in the patient''s medical record in detail). State board reporting is for patterns of unsafe practice, not individual unharmed errors.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse discovers a medication error made by the previous shift. The patient is unharmed. What is the nurse''s priority action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse is using SBAR to communicate with a physician. What information is included in the "B" (Background) component?', '[{"id":"a","text":"The nurse''s recommendation for treatment"},{"id":"b","text":"Current vital signs and what changed recently"},{"id":"c","text":"Pertinent medical history and reason for admission"},{"id":"d","text":"The patient''s name, age, and why the nurse is calling"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'SBAR: S=Situation (who, what, why calling), B=Background (diagnosis, history, relevant labs/meds), A=Assessment (what the nurse thinks is happening), R=Recommendation (what the nurse is requesting). Background provides clinical context for the current situation.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is using SBAR to communicate with a physician. What information is included in the "B" (Background) component?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'sata', 'A nurse manager is addressing staff burnout. Which evidence-based strategies are effective? (Select all that apply)', '[{"id":"a","text":"Implement consistent scheduling with adequate days off"},{"id":"b","text":"Provide mandatory overtime to increase unit staffing"},{"id":"c","text":"Create a culture of psychological safety for reporting concerns"},{"id":"d","text":"Offer access to employee assistance programs"},{"id":"e","text":"Conduct regular team debriefs after difficult patient events"}]'::jsonb, '{"ids":["a","c","d","e"]}'::jsonb, 'Burnout prevention: adequate rest (consistent scheduling), psychological safety (reduces moral injury), EAP access (mental health resources), and debriefing after critical incidents. Mandatory overtime is a primary CAUSE of burnout and has been shown to increase errors and turnover.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse manager is addressing staff burnout. Which evidence-based strategies are effective? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse receives an order to administer a medication that the nurse believes is inappropriate for the patient. What is the correct sequence of actions?', '[{"id":"a","text":"Administer the medication because the provider is ultimately responsible"},{"id":"b","text":"Refuse to give the medication and document the refusal without notifying anyone"},{"id":"c","text":"Question the order with the provider, and if unresolved, follow the chain of command"},{"id":"d","text":"Give the medication but document the nurse''s concerns"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Nurses are legally and ethically accountable for every medication they administer. If a medication seems inappropriate: question the provider, seek clarification. If unresolved, follow the chain of command (charge nurse → supervisor → medical director). Document the process. "I was just following orders" is not a legal defense.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse receives an order to administer a medication that the nurse believes is inappropriate for the patient. What is the correct sequence of actions?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A newly licensed nurse is overwhelmed and makes a medication error. The charge nurse''s best response is:', '[{"id":"a","text":"Report the nurse to the nursing board for endangering patient safety"},{"id":"b","text":"Publicly address the error at the nurses'' station to deter future mistakes"},{"id":"c","text":"Conduct a private conversation focused on learning and system improvements"},{"id":"d","text":"Document the error in the nurse''s personnel file without discussion"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'A just culture approach: address errors privately, focus on learning not blame, examine systems that contributed (staffing, distractions, process gaps). Public shaming and immediate punitive action without context worsen psychological safety and increase future error rates. Support from preceptors reduces new-nurse turnover.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A newly licensed nurse is overwhelmed and makes a medication error. The charge nurse''s best response is:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'mcq', 'A nurse is caring for a 68-year-old with heart failure. The patient reports weight gain of 4 pounds in 2 days, increased ankle swelling, and cannot lie flat without "air hunger." Which nursing action is the highest priority?', '[{"id":"a","text":"Administer scheduled furosemide and reassess in 2 hours"},{"id":"b","text":"Elevate legs to reduce ankle edema"},{"id":"c","text":"Notify the provider immediately — patient is decompensating"},{"id":"d","text":"Obtain daily weight and compare to baseline"}]'::jsonb, '{"ids":["c"]}'::jsonb, '4-pound weight gain in 2 days + orthopnea + edema = acute decompensated heart failure. This requires immediate provider notification for possible IV diuresis, BNP, echo, or hospitalization. Orthopnea (inability to lie flat due to dyspnea) indicates significant pulmonary congestion.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a 68-year-old with heart failure. The patient reports weight gain of 4 pounds in 2 days, increased ankle swelling, and cannot lie flat without "air hunger." Which nursing action is the highest priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'sata', 'A nurse reviews a patient''s chart: 55-year-old, 3 days post-op colectomy, T 39.1°C, HR 108, BP 88/56, RR 24, WBC 18,000. Which findings indicate the patient may be developing sepsis? (Select all that apply)', '[{"id":"a","text":"Temperature 39.1°C"},{"id":"b","text":"HR 108 bpm"},{"id":"c","text":"BP 88/56 mmHg"},{"id":"d","text":"WBC 18,000"},{"id":"e","text":"RR 24 breaths/min"}]'::jsonb, '{"ids":["a","b","c","d","e"]}'::jsonb, 'qSOFA/SIRS criteria for sepsis: temp >38 or <36°C, HR >90, RR >20, WBC >12,000 or <4,000. This patient meets all criteria with hypotension (BP 88/56) suggesting septic shock. Activate rapid response/sepsis protocol immediately. Time is critical — 1-hour bundle.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse reviews a patient''s chart: 55-year-old, 3 days post-op colectomy, T 39.1°C, HR 108, BP 88/56, RR 24, WBC 18,000. Which findings indicate the patient may be developing sepsis? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient with peptic ulcer disease is prescribed omeprazole. When should this medication be administered?', '[{"id":"a","text":"30–60 minutes before breakfast"},{"id":"b","text":"With meals to reduce gastric upset"},{"id":"c","text":"At bedtime for maximum effect"},{"id":"d","text":"With antacids to enhance absorption"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Proton pump inhibitors (omeprazole) must be taken 30–60 minutes before the first meal of the day to be activated by the actively secreting proton pumps. Taking with food reduces effectiveness. They should not be crushed or chewed.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with peptic ulcer disease is prescribed omeprazole. When should this medication be administered?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is administering IV phenytoin. Which action is most important?', '[{"id":"a","text":"Administer in dextrose solution at 100 mg/min"},{"id":"b","text":"Mix with normal saline and infuse no faster than 50 mg/min"},{"id":"c","text":"Give IV push undiluted over 2 minutes"},{"id":"d","text":"Administer intramuscularly for fastest absorption"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'IV phenytoin: use normal saline ONLY (precipitates in dextrose), infuse ≤50 mg/min (cardiac monitoring required — hypotension and dysrhythmias). IM administration is erratic and painful. Purple glove syndrome can occur at infusion sites.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is administering IV phenytoin. Which action is most important?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'sata', 'A patient started on amiodarone for atrial fibrillation needs teaching about adverse effects. Which should the nurse include? (Select all that apply)', '[{"id":"a","text":"Pulmonary toxicity — report new cough or dyspnea"},{"id":"b","text":"Photosensitivity — use sunscreen and cover skin"},{"id":"c","text":"Thyroid dysfunction — monitor TSH periodically"},{"id":"d","text":"Constipation is expected and no treatment is needed"},{"id":"e","text":"Corneal microdeposits — routine eye exams recommended"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Amiodarone toxicities: pulmonary toxicity (most dangerous), photosensitivity (bluish discoloration), thyroid dysfunction (contains iodine), corneal deposits. It also causes hepatotoxicity. LFTs, TFTs, CXR, and eye exams are required for monitoring. Diarrhea (not constipation) can occur.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient started on amiodarone for atrial fibrillation needs teaching about adverse effects. Which should the nurse include? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient with HIV is prescribed tenofovir/emtricitabine (Truvada). Which laboratory test requires monitoring?', '[{"id":"a","text":"Serum creatinine and GFR"},{"id":"b","text":"PT/INR"},{"id":"c","text":"Serum ammonia"},{"id":"d","text":"Serum calcium and phosphate"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Tenofovir (NRTI) is nephrotoxic — monitor kidney function (creatinine, GFR, urine protein) regularly. Tenofovir can cause Fanconi syndrome (proximal tubular injury). HIV medications also require CD4 count and viral load monitoring.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with HIV is prescribed tenofovir/emtricitabine (Truvada). Which laboratory test requires monitoring?');
