-- Safe seed Yingoh NCLEX question bank, part 11.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient is receiving gentamicin. Which pair of assessments is most critical to monitor for drug toxicity?', '[{"id":"a","text":"Blood pressure and heart rate"},{"id":"b","text":"Hearing and kidney function"},{"id":"c","text":"Liver function tests and bilirubin"},{"id":"d","text":"Blood glucose and HbA1c"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Aminoglycosides (gentamicin, tobramycin, amikacin) are ototoxic (irreversible hearing loss, tinnitus, vestibular damage) and nephrotoxic. Monitor: peak and trough drug levels, BUN/creatinine, urine output, and audiometric testing. Keep trough levels low to minimize toxicity.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is receiving gentamicin. Which pair of assessments is most critical to monitor for drug toxicity?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient taking prednisone long-term for Crohn''s disease asks why they need to increase the dose during a surgery. The nurse explains:', '[{"id":"a","text":"Surgery requires stronger anti-inflammatory coverage"},{"id":"b","text":"Long-term steroids suppress the adrenal glands — \"stress dosing\" prevents adrenal crisis"},{"id":"c","text":"Prednisone prevents surgical site infections"},{"id":"d","text":"Higher doses reduce post-operative nausea"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Chronic exogenous corticosteroids suppress the HPA axis — the adrenal glands atrophy and cannot mount a cortisol stress response. "Stress dosing" (increasing steroid dose perioperatively) prevents adrenal insufficiency/Addisonian crisis during the physical stress of surgery. Abrupt steroid withdrawal is dangerous.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient taking prednisone long-term for Crohn''s disease asks why they need to increase the dose during a surgery. The nurse explains:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'sata', 'A nurse is reviewing contraindications for NSAIDs. Which conditions should alert the nurse to question the order? (Select all that apply)', '[{"id":"a","text":"Active peptic ulcer disease"},{"id":"b","text":"Chronic kidney disease stage 4"},{"id":"c","text":"Hypertension controlled with lisinopril"},{"id":"d","text":"History of asthma"},{"id":"e","text":"Type 2 diabetes on oral agents"}]'::jsonb, '{"ids":["a","b","c","d"]}'::jsonb, 'NSAID cautions/contraindications: GI ulcers (NSAIDs inhibit prostaglandins protecting gastric mucosa), CKD (NSAIDs reduce renal prostaglandins and GFR), HTN with ACE inhibitors (dangerous hyperkalemia, reduced antihypertensive effect), aspirin-sensitive asthma (Samter''s triad — bronchospasm). Diabetes alone is not a contraindication.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is reviewing contraindications for NSAIDs. Which conditions should alert the nurse to question the order? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient is prescribed ciprofloxacin for a UTI. Which instruction is most important?', '[{"id":"a","text":"Take with milk to reduce stomach upset"},{"id":"b","text":"Avoid sun exposure and use sunscreen"},{"id":"c","text":"Take with antacids to improve absorption"},{"id":"d","text":"Limit water intake to 1 L/day"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Fluoroquinolones (ciprofloxacin, levofloxacin) cause photosensitivity — sunscreen and sun-protective clothing are essential. Do NOT take with antacids, calcium, iron, or dairy (chelation reduces absorption by up to 90%). Increase fluid intake (2–3 L/day) to prevent crystalluria.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is prescribed ciprofloxacin for a UTI. Which instruction is most important?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with sickle cell disease is admitted during a vaso-occlusive crisis. Which interventions are the highest priority? (Select all that apply)', '[{"id":"a","text":"Aggressive IV hydration"},{"id":"b","text":"Opioid analgesia for pain management"},{"id":"c","text":"Supplemental oxygen"},{"id":"d","text":"Incentive spirometry"},{"id":"e","text":"Encourage outdoor activity"}]'::jsonb, '{"ids":["a","b","c","d"]}'::jsonb, 'Sickle cell crisis management: IV fluids (dilute sickled cells, restore circulation), opioid analgesia (severe pain), supplemental O2 (prevent further sickling), incentive spirometry (prevent acute chest syndrome). Avoid cold, stress, dehydration, and high-altitude activity — all trigger sickling.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with sickle cell disease is admitted during a vaso-occlusive crisis. Which interventions are the highest priority? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with peripheral arterial disease (PAD) asks how to care for their feet. Which instruction is correct?', '[{"id":"a","text":"Soak feet in hot water daily to improve circulation"},{"id":"b","text":"Walk barefoot at home to toughen the skin"},{"id":"c","text":"Wear well-fitting shoes, inspect feet daily, and avoid crossing legs"},{"id":"d","text":"Apply heating pads to legs to relieve pain"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'PAD foot care: daily inspection (impaired sensation masks injury), well-fitting shoes (prevent trauma), avoid crossing legs (further reduces blood flow), avoid extremes of temperature (decreased sensation → burns/frostbite). Heating pads and hot soaks can cause burns in patients with decreased sensation.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with peripheral arterial disease (PAD) asks how to care for their feet. Which instruction is correct?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient newly diagnosed with multiple sclerosis asks about the disease. Which explanation is most accurate?', '[{"id":"a","text":"MS is caused by a bacterial infection and is curable with antibiotics"},{"id":"b","text":"MS involves demyelination of axons in the CNS, causing varied neurological symptoms"},{"id":"c","text":"MS primarily affects the peripheral nervous system and muscles"},{"id":"d","text":"MS consistently progresses in all patients and always leads to complete disability"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'MS is an autoimmune disease causing demyelination of CNS axons, disrupting nerve signal transmission. Symptoms vary based on lesion location: optic neuritis, weakness, spasticity, bladder dysfunction, fatigue. MS course is variable — many patients maintain function for years with disease-modifying therapies.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient newly diagnosed with multiple sclerosis asks about the disease. Which explanation is most accurate?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A patient is being discharged after coronary artery bypass graft (CABG) surgery. Which discharge teaching points are essential? (Select all that apply)', '[{"id":"a","text":"No lifting >5–10 lbs until sternal healing is complete (6–8 weeks)"},{"id":"b","text":"Avoid driving until approved by surgeon (typically 4–6 weeks)"},{"id":"c","text":"Take aspirin and prescribed medications as directed"},{"id":"d","text":"Resume all normal activities within 2 weeks"},{"id":"e","text":"Report fever >38°C, increased wound drainage, or new chest pain"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'CABG discharge: sternum heals in 6–8 weeks (no heavy lifting, sternal precautions), driving restriction (reaction time, sternal stress), antiplatelet therapy compliance critical for graft patency, warning signs of infection/rejection. Full activity resumption takes weeks to months — not 2 weeks.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is being discharged after coronary artery bypass graft (CABG) surgery. Which discharge teaching points are essential? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient develops a fever of 39.2°C on postoperative day 1. What is the most likely cause?', '[{"id":"a","text":"Wound infection"},{"id":"b","text":"Pneumonia"},{"id":"c","text":"Atelectasis"},{"id":"d","text":"Deep vein thrombosis"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'The "5 W''s" of post-op fever by day: Wind (day 1–2 = atelectasis), Water (day 3 = UTI), Wound (day 5–7 = infection), Walking (day 5+ = DVT), Wonder drugs (any day = drug fever). Day 1 fever is almost always atelectasis — encourage deep breathing and incentive spirometry.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient develops a fever of 39.2°C on postoperative day 1. What is the most likely cause?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient is receiving total parenteral nutrition (TPN). Which electrolyte is at the greatest risk for refeeding syndrome when restarting nutrition?', '[{"id":"a","text":"Sodium"},{"id":"b","text":"Phosphorus"},{"id":"c","text":"Calcium"},{"id":"d","text":"Chloride"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Refeeding syndrome: after starvation, reintroducing carbohydrates triggers insulin release → cells take up phosphate, potassium, and magnesium from blood → severe hypophosphatemia. Phosphorus is the key electrolyte to monitor. Hypophosphatemia causes respiratory failure, cardiac arrest, and seizures.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is receiving total parenteral nutrition (TPN). Which electrolyte is at the greatest risk for refeeding syndrome when restarting nutrition?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient with major depressive disorder asks, "What is the point of going on?" How should the nurse respond?', '[{"id":"a","text":"\"You have so much to live for. Think about your family.\""},{"id":"b","text":"\"It sounds like you''re really struggling. Are you thinking about harming yourself?\""},{"id":"c","text":"\"The antidepressants will kick in soon and you''ll feel better.\""},{"id":"d","text":"\"Let me call your doctor so they can adjust your medication.\""}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A statement like "what''s the point of going on?" requires a direct, empathic response and immediate safety assessment. Asking directly about suicidal ideation is therapeutic — it does not plant the idea. Minimizing feelings or deflecting to medication change avoids the safety assessment, which is the priority.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with major depressive disorder asks, "What is the point of going on?" How should the nurse respond?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A nurse is caring for a woman at 16 weeks gestation who has just been told her fetus has Down syndrome (trisomy 21) confirmed by amniocentesis. The patient is crying. The nurse''s priority response is:', '[{"id":"a","text":"Provide information about Down syndrome resources and support groups"},{"id":"b","text":"Explain all options including termination of the pregnancy"},{"id":"c","text":"Sit with the patient, offer presence, and provide emotional support"},{"id":"d","text":"Assure the patient that children with Down syndrome live fulfilling lives"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'In crisis and acute grief, the therapeutic priority is emotional presence and support — not information, reassurance, or option review. The patient cannot process information while acutely distressed. Sit quietly, offer tissues, use therapeutic silence. Information and options come later when the patient is ready.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a woman at 16 weeks gestation who has just been told her fetus has Down syndrome (trisomy 21) confirmed by amniocentesis. The patient is crying. The nurse''s priority response is:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A 10-month-old is receiving oral rehydration therapy for diarrhea. The parent asks when to call the doctor. What is the most important warning sign to report?', '[{"id":"a","text":"One or two loose stools"},{"id":"b","text":"No wet diapers in 8 hours and sunken fontanelle"},{"id":"c","text":"Mild fussiness"},{"id":"d","text":"Decreased appetite for solid foods"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Signs of severe dehydration in an infant: no wet diapers >8 hours (oliguria), sunken fontanelle, sunken eyes, dry mucous membranes, absent tears, skin tenting, lethargy. These require immediate medical evaluation. Mild symptoms (loose stool, fussiness, decreased appetite) are expected and manageable at home with ORT.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 10-month-old is receiving oral rehydration therapy for diarrhea. The parent asks when to call the doctor. What is the most important warning sign to report?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse is preparing to remove a patient from contact isolation. Which is the correct order for doffing PPE?', '[{"id":"a","text":"Mask → gown → gloves → hand hygiene"},{"id":"b","text":"Gloves → hand hygiene → gown → hand hygiene → mask → hand hygiene"},{"id":"c","text":"Gown → gloves → mask → hand hygiene"},{"id":"d","text":"All PPE can be removed in any order as long as hand hygiene is performed last"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Correct doffing (removal) sequence: gloves (most contaminated) → hand hygiene → gown → hand hygiene → mask/respirator (if worn) → hand hygiene. Always perform hand hygiene after each step. The order is designed to prevent self-contamination from the most to least contaminated items.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preparing to remove a patient from contact isolation. Which is the correct order for doffing PPE?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse learns that a co-worker is consistently coming to work smelling of alcohol. What is the most appropriate first action?', '[{"id":"a","text":"Ignore it — the co-worker''s personal life is their own business"},{"id":"b","text":"Cover for the co-worker to protect their license"},{"id":"c","text":"Report the concern to the charge nurse or supervisor immediately"},{"id":"d","text":"Confront the co-worker privately and threaten to report them"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'A nurse impaired by alcohol on duty is an immediate patient safety threat. Report to the supervisor or charge nurse immediately. This is a professional and ethical obligation. Most state nursing boards have confidential peer assistance programs for nurses with substance use disorders. Covering for the nurse is enabling behavior that endangers patients.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse learns that a co-worker is consistently coming to work smelling of alcohol. What is the most appropriate first action?');
