-- Safe seed Yingoh NCLEX question bank, part 6.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A patient at 32 weeks gestation reports sudden, painless, bright red vaginal bleeding. Which condition does the nurse suspect?', '[{"id":"a","text":"Placental abruption"},{"id":"b","text":"Placenta previa"},{"id":"c","text":"Preterm labor"},{"id":"d","text":"Ruptured uterus"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Placenta previa: painless, bright red bleeding (placenta covers the cervical os, bleeds as cervix dilates). Placental abruption: sudden, painful, dark red bleeding. NEVER perform a vaginal exam in placenta previa — can cause massive hemorrhage. Immediate bedrest and notify provider.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient at 32 weeks gestation reports sudden, painless, bright red vaginal bleeding. Which condition does the nurse suspect?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A nurse notices a newborn has a bluish-purple bruise-like discoloration on the lower back and buttocks. What is this finding?', '[{"id":"a","text":"Sign of child abuse requiring immediate reporting"},{"id":"b","text":"Mongolian spot — a normal finding in darker-skinned newborns"},{"id":"c","text":"Hemangioma requiring dermatology consultation"},{"id":"d","text":"Port-wine stain associated with Sturge-Weber syndrome"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Mongolian spots (congenital dermal melanocytosis) are blue-gray pigmented areas on the sacral/lumbar region, common in Asian, Hispanic, Native American, and Black newborns. They are benign and typically fade by school age. Important to document to prevent later confusion with bruising.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse notices a newborn has a bluish-purple bruise-like discoloration on the lower back and buttocks. What is this finding?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A nurse is caring for a 4-year-old post-tonsillectomy. Which assessment finding requires immediate action?', '[{"id":"a","text":"Reports throat pain rated 5/10"},{"id":"b","text":"Frequent swallowing and restlessness"},{"id":"c","text":"Refuses to drink cold fluids"},{"id":"d","text":"Low-grade temperature of 37.8°C"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Frequent swallowing in a post-tonsillectomy child is a classic early sign of hemorrhage — the child is swallowing blood. Assess the throat immediately. This is a surgical emergency. Throat pain, fluid refusal, and low-grade fever are expected post-tonsillectomy findings.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a 4-year-old post-tonsillectomy. Which assessment finding requires immediate action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'sata', 'A nurse is educating parents on preventing sudden infant death syndrome (SIDS). Which recommendations should be included? (Select all that apply)', '[{"id":"a","text":"Place baby on their back to sleep"},{"id":"b","text":"Use a firm, flat sleep surface"},{"id":"c","text":"Keep the sleep area free of soft objects and loose bedding"},{"id":"d","text":"Allow the baby to sleep in the parents'' bed for warmth"},{"id":"e","text":"Offer a pacifier at sleep time after breastfeeding is established"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Safe sleep (AAP): back to sleep, firm flat surface, no soft objects/bedding. Pacifier use reduces SIDS risk — offer after breastfeeding is established (3–4 weeks). Bed-sharing (co-sleeping) increases SIDS risk significantly and is NOT recommended.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is educating parents on preventing sudden infant death syndrome (SIDS). Which recommendations should be included? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A 2-year-old is brought to the ED with inspiratory stridor, a barking cough, and low-grade fever. Which condition is most likely?', '[{"id":"a","text":"Epiglottitis"},{"id":"b","text":"Croup (laryngotracheobronchitis)"},{"id":"c","text":"Bronchiolitis"},{"id":"d","text":"Asthma"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Croup: barking/seal-like cough, inspiratory stridor, low-grade fever in children 6 months–3 years, often worsens at night. Epiglottitis: "tripod position," drooling, high fever, NO barking cough — do not examine throat. Bronchiolitis: expiratory wheezing, RSV, <2 years.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 2-year-old is brought to the ED with inspiratory stridor, a barking cough, and low-grade fever. Which condition is most likely?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'The parent of a 9-month-old asks when to introduce solid foods. The nurse''s best response is:', '[{"id":"a","text":"\"Start solids at 4 months to help the baby sleep longer.\""},{"id":"b","text":"\"Solids should be introduced between 4–6 months, and your baby appears ready.\""},{"id":"c","text":"\"Wait until 12 months to reduce allergy risk.\""},{"id":"d","text":"\"Single-grain iron-fortified cereals are introduced around 6 months with developmental readiness signs.\""}]'::jsonb, '{"ids":["d"]}'::jsonb, 'AAP recommends introducing solid foods around 6 months with signs of readiness: sitting with support, good head control, interest in food, loss of tongue-thrust reflex. Iron-fortified single-grain cereals and pureed vegetables/fruits are appropriate first foods.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'The parent of a 9-month-old asks when to introduce solid foods. The nurse''s best response is:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A 6-year-old with acute asthma exacerbation has SpO2 of 91%, is using accessory muscles, and speaks in short phrases. What is the priority intervention?', '[{"id":"a","text":"Administer a short-acting beta2 agonist (albuterol) via nebulizer"},{"id":"b","text":"Obtain a chest X-ray to rule out pneumonia"},{"id":"c","text":"Apply supplemental oxygen and complete full nursing assessment"},{"id":"d","text":"Administer oral corticosteroids"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Priority in acute asthma: bronchodilator first (albuterol via nebulizer/MDI) to reverse bronchoconstriction. SpO2 91% with accessory muscle use and limited speech indicates moderate-severe exacerbation. Oxygen, corticosteroids follow, but bronchodilation is the urgent intervention.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 6-year-old with acute asthma exacerbation has SpO2 of 91%, is using accessory muscles, and speaks in short phrases. What is the priority intervention?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'sata', 'A nurse suspects child abuse in a 3-year-old admitted with multiple bruises. Which findings increase this suspicion? (Select all that apply)', '[{"id":"a","text":"Bruises in various stages of healing"},{"id":"b","text":"Bruises on the shins and knees of an ambulatory child"},{"id":"c","text":"Patterned bruising (shape of belt buckle, cord)"},{"id":"d","text":"Inconsistent story between caregiver and child"},{"id":"e","text":"Bruising over bony prominences"}]'::jsonb, '{"ids":["a","c","d"]}'::jsonb, 'Red flags for abuse: bruises in multiple healing stages (different-colored), patterned injuries (burns, bite marks, belt shapes), inconsistent history. Bruises on shins/knees and bony prominences are normal in active toddlers. Mandated reporters must report ALL suspected abuse.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse suspects child abuse in a 3-year-old admitted with multiple bruises. Which findings increase this suspicion? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A 7-year-old with type 1 diabetes has a blood glucose of 380 mg/dL, is vomiting, and has Kussmaul breathing. What is the priority nursing action?', '[{"id":"a","text":"Give a rapidly absorbed carbohydrate snack"},{"id":"b","text":"Establish IV access and prepare for IV insulin and fluids"},{"id":"c","text":"Administer glucagon IM"},{"id":"d","text":"Place in Trendelenburg to increase cerebral perfusion"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'DKA in a child: hyperglycemia + vomiting + Kussmaul breathing (metabolic acidosis compensation) = pediatric emergency. IV access for fluid resuscitation (normal saline) and continuous IV insulin are priorities. Oral carbs worsen hyperglycemia; glucagon treats hypoglycemia.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 7-year-old with type 1 diabetes has a blood glucose of 380 mg/dL, is vomiting, and has Kussmaul breathing. What is the priority nursing action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A 12-month-old has not yet said "mama" or "dada" specifically. What is the nurse''s response?', '[{"id":"a","text":"Reassure the parents this is within normal limits"},{"id":"b","text":"Refer for developmental evaluation — should have 2–4 words by 12 months"},{"id":"c","text":"Recommend speech therapy immediately"},{"id":"d","text":"Advise recheck at 15 months if no words develop"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'By 12 months, children should have 2–4 meaningful words (not just babbling). Absence of these words is a developmental red flag. Early referral for evaluation is preferred — early speech therapy intervention has the best outcomes. Do not wait until 15 months.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 12-month-old has not yet said "mama" or "dada" specifically. What is the nurse''s response?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse is preparing to insert a urinary catheter. Which action best prevents catheter-associated urinary tract infections (CAUTI)?', '[{"id":"a","text":"Change the catheter every 7 days"},{"id":"b","text":"Use strict sterile technique during insertion"},{"id":"c","text":"Irrigate the catheter daily with normal saline"},{"id":"d","text":"Apply antibiotic ointment to the urethral meatus daily"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Strict sterile technique during catheter insertion is the most effective CAUTI prevention strategy. Also: use smallest gauge catheter, remove as soon as possible, maintain closed drainage system, keep bag below bladder. Routine catheter changes, irrigation, and meatal ointment are not evidence-based for CAUTI prevention.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preparing to insert a urinary catheter. Which action best prevents catheter-associated urinary tract infections (CAUTI)?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'sata', 'A patient is placed on neutropenic precautions after chemotherapy. Which actions are appropriate? (Select all that apply)', '[{"id":"a","text":"Provide a low-microbial (neutropenic) diet avoiding raw fruits and vegetables"},{"id":"b","text":"Place patient in a private room with positive-pressure air flow"},{"id":"c","text":"Restrict all visitors"},{"id":"d","text":"Monitor temperature every 4 hours"},{"id":"e","text":"Perform meticulous hand hygiene before entering room"}]'::jsonb, '{"ids":["a","b","d","e"]}'::jsonb, 'Neutropenic precautions: low-microbial diet, positive-pressure private room (protects patient FROM environment), frequent temperature monitoring (fever = infection emergency in neutropenic patient), meticulous hand hygiene. Visitors are restricted (no ill visitors) but not eliminated entirely.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is placed on neutropenic precautions after chemotherapy. Which actions are appropriate? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse sustains a needlestick from a patient with unknown HIV status. What is the priority action?', '[{"id":"a","text":"Complete an incident report and see occupational health within 72 hours"},{"id":"b","text":"Immediately wash the site thoroughly with soap and water, then report to employee health"},{"id":"c","text":"Squeeze the wound to expel blood and apply antiseptic"},{"id":"d","text":"Begin prophylactic antibiotics immediately"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Immediate action after needlestick: wash site with soap and water thoroughly. Then report immediately to employee health for exposure assessment, testing of source patient (if available), and decision on post-exposure prophylaxis (PEP) — must start within 72 hours of exposure for HIV. Do NOT squeeze wound (increases tissue trauma).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse sustains a needlestick from a patient with unknown HIV status. What is the priority action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A patient with active pulmonary tuberculosis (TB) requires which type of precautions?', '[{"id":"a","text":"Contact precautions: gown and gloves"},{"id":"b","text":"Droplet precautions: surgical mask within 3 feet"},{"id":"c","text":"Airborne precautions: negative-pressure room and N95 respirator"},{"id":"d","text":"Standard precautions only"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'TB is transmitted via airborne droplet nuclei (<5 microns) that remain suspended in air. Requires: negative-pressure isolation room, N95 (not surgical mask) for all who enter, door kept closed. Patient transport: have patient wear surgical mask. Standard masks do NOT filter TB particles.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with active pulmonary tuberculosis (TB) requires which type of precautions?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'sata', 'A nurse is preparing to change a central line dressing using the CLABSI bundle. Which interventions are included? (Select all that apply)', '[{"id":"a","text":"Hand hygiene before the procedure"},{"id":"b","text":"Use chlorhexidine gluconate for skin antisepsis"},{"id":"c","text":"Use sterile technique with mask, gown, and sterile gloves"},{"id":"d","text":"Change tubing every 24 hours"},{"id":"e","text":"Daily assessment of whether the central line is still needed"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'CLABSI bundle: hand hygiene, maximal sterile barrier precautions, chlorhexidine (CHG) skin antisepsis, optimal site selection, daily review of line necessity. Standard IV tubing is changed every 72–96 hours (not 24h). Lipid tubing changes every 24 hours.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preparing to change a central line dressing using the CLABSI bundle. Which interventions are included? (Select all that apply)');
