-- Batch 11: targeted balance for four underrepresented categories.

-- Management of Care
select public.seed_structured_concept('expansion-batch-11','care-conference','Leadership and Delegation','an interdisciplinary care conference','a complex client has conflicting goals across disciplines','Center the client’s goals, clarify responsibilities, resolve conflicts, and document the shared plan','Prepare priorities and questions and identify the person coordinating follow-up','Disciplines implement contradictory plans that create immediate harm','Exclude the client','Use the meeting only to assign blame','Leave decisions undocumented','Management of Care');
select public.seed_structured_concept('expansion-batch-11','critical-result-readback','Leadership and Delegation','communication of a critical laboratory result','the laboratory reports a life-threatening value by telephone','Write and read back the result, identify the client, assess promptly, and notify the responsible clinician','Expect urgent results to be repeated and linked to a clear response plan','A critical value is acknowledged but no client assessment occurs','Record it in the wrong chart','Wait for routine rounds','Ask unlicensed staff to interpret it','Management of Care');
select public.seed_structured_concept('expansion-batch-11','medication-access','Leadership and Delegation','medication access at discharge','a client cannot afford several essential prescriptions','Notify the team before discharge and coordinate formulary alternatives, assistance, and a feasible plan','Explain cost barriers honestly rather than rationing medicines without guidance','The client leaves without insulin or a safe access plan','Tell the client to halve every dose','Assume samples provide permanent access','Delay discussion until medicines run out','Management of Care');
select public.seed_structured_concept('expansion-batch-11','home-health-safety','Leadership and Delegation','home-health admission planning','a medically complex client lives alone in an unsafe environment','Assess immediate hazards, caregiver capacity, medicine management, emergency access, and ordered services','Keep emergency numbers and an updated care plan accessible and report inability to meet essential needs','No electricity is available for life-sustaining equipment','Ignore environmental hazards','Promise daily care not ordered','Leave supplies where they cannot be reached','Management of Care');
select public.seed_structured_concept('expansion-batch-11','quality-improvement','Leadership and Delegation','a recurring medication-safety event','several similar near misses occur on one unit','Protect current clients and use nonpunitive system analysis to identify and test process improvements','Report near misses because they reveal hazards before harm occurs','Leadership suppresses reports and the same error reaches a client','Discipline one person without system review','Change many processes without measurement','Hide near misses','Management of Care');
select public.seed_structured_concept('expansion-batch-11','continuity-referral','Leadership and Delegation','a time-sensitive outpatient referral','an abnormal finding requires specialist evaluation after discharge','Confirm the referral, responsible clinician, timeframe, records, and process for tracking completion','Know whom to call if an appointment is not received within the stated timeframe','A suspected malignancy referral is never transmitted or tracked','Hand the client an illegible phone number','Assume another office will follow up','Close the result before completion','Management of Care');

-- Safety and Infection Prevention
select public.seed_structured_concept('expansion-batch-11','multidose-vial','Safety and Infection Control','multidose-vial safety','a multidose vial is used in a patient-care area','Dedicate it to one client when it enters the immediate treatment area and access it aseptically','Check storage, dating, contamination, and facility policy before each use','A contaminated vial is reused for several clients','Leave a needle in the stopper','Store beside used syringes','Use beyond the labeled date','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-11','linen-handling','Safety and Infection Control','handling contaminated linen','bedding is heavily soiled with body fluid','Use appropriate PPE, contain at the point of use, and avoid shaking or contact with clothing','Place soiled linen directly into the designated container','Linen is shaken and aerosolizes contaminated material','Carry it against the uniform','Sort it on the floor','Rinse it in a handwashing sink','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-11','respiratory-equipment','Safety and Infection Control','shared respiratory-equipment safety','several clients require reusable respiratory devices','Dedicate equipment or clean and disinfect it according to device and pathogen requirements','Do not share masks, nebulizers, or suction equipment before proper reprocessing','A visibly contaminated nebulizer is moved directly to another client','Wipe only the outside','Store wet equipment in a closed bag','Reuse single-client tubing','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-11','blood-spill','Safety and Infection Control','environmental blood-spill cleanup','blood spills across a treatment-room floor','Restrict the area, wear appropriate PPE, remove material safely, and use an approved disinfectant','Report splashes to eyes, mouth, nonintact skin, or sharps injuries immediately','An unprotected worker sustains mucous-membrane exposure','Clean with bare hands','Use an unapproved household product','Leave sharps hidden in towels','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-11','employee-exposure','Safety and Infection Control','occupational blood exposure','a clinician sustains a percutaneous injury from a used needle','Wash the site, report immediately, assess source and worker, and begin time-sensitive prophylaxis when indicated','Prompt reporting improves access to testing and prophylaxis','The worker delays reporting until after the prophylaxis window','Squeeze and bleach the wound','Hide the injury','Wait for symptoms','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-11','isolation-transport','Safety and Infection Control','transport under transmission precautions','a client on isolation requires urgent imaging','Coordinate with the destination, contain infectious material, use source control, and clean transport equipment','Leave the room only when necessary and follow masking and hygiene instructions','Uncontained drainage contaminates common hallways','Remove every precaution during transport','Make unnecessary stops','Return equipment without disinfection','Safety and Infection Prevention and Control');

-- Psychosocial Integrity
select public.seed_structured_concept('expansion-batch-11','insomnia-cbt','Mental Health','chronic insomnia','a client spends long periods awake in bed and fears not sleeping','Assess causes and support stimulus control, consistent wake time, and cognitive-behavioral treatment','Use the bed for sleep, leave briefly when unable to sleep, and limit late caffeine and alcohol','Severe sleepiness causes repeated driving near misses','Stay in bed worrying for hours','Use alcohol nightly','Drive while unable to remain awake','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-11','social-anxiety','Mental Health','social anxiety disorder','fear of scrutiny causes avoidance of school and work','Assess function and support gradual exposure and evidence-based therapy without forcing abrupt immersion','Practice planned graded steps and coping rather than avoiding every feared setting','The client becomes suicidal because of isolation and perceived failure','Force a public speech immediately','Use alcohol before interactions','Mock the fear','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-11','hoarding','Mental Health','hoarding disorder','clutter blocks exits and creates fire and fall risk','Assess immediate hazards and capacity and use collaborative gradual harm-reduction treatment','Prioritize clear exits, cooking safety, sanitation, and small agreed sorting goals','Blocked exits prevent emergency evacuation','Discard everything secretly','Shame the client','Add more storage without reducing hazards','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-11','postpartum-psychosis','Maternal and Newborn','postpartum psychosis','days after birth a client is sleepless, disorganized, and hears commands about the infant','Ensure constant safety for parent and infant and obtain emergency psychiatric treatment','Psychosis after birth is an emergency, especially with confusion, mania, or harmful commands','The client states a divine command requires harming the infant','Leave parent and infant alone','Treat as normal adjustment','Delay care until the routine visit','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-11','opioid-grief-family','Mental Health','family response to substance-use disorder','family members alternate between rescue, anger, and fear after overdoses','Provide overdose education, naloxone, boundaries, support, and treatment resources','Support recovery without financing unsafe use and seek counseling for family stress','A family member threatens suicide after another overdose','Use blame as motivation','Hide naloxone','Give cash during active unsafe use','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-11','terminal-anxiety','Mental Health','anxiety near end of life','a dying client expresses fear, breathlessness, and unfinished concerns','Assess physical causes and goals and provide presence, symptom relief, spiritual or psychosocial support as desired','Discuss fears openly and identify preferred people and comfort practices','Severe uncontrolled distress with new reversible airway compromise','Dismiss fear with false reassurance','Force unwanted spiritual care','Withhold symptom medicine','Psychosocial Integrity');

-- Basic Care and Comfort
select public.seed_structured_concept('expansion-batch-11','oral-hydration','Fundamentals','supporting oral hydration','a stable older adult has low intake and no fluid restriction','Offer preferred accessible fluids regularly and address swallowing, toileting, and assistance barriers','Use frequent small amounts and monitor urine, mouth dryness, dizziness, and weight','New inability to swallow with coughing and hypoxemia','Force thin liquids despite dysphagia','Leave fluids out of reach','Offer only at meals','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-11','fever-comfort','Fundamentals','comfort care during fever','a stable client has fever, chills, and diaphoresis','Assess the cause and hydration and use light clothing, fluids, and prescribed antipyretic measures','Avoid overbundling and report confusion, breathing difficulty, rash, or dehydration','Fever with stiff neck, purpura, and hypotension','Use ice-water immersion routinely','Pile on heavy blankets throughout fever','Give aspirin to a child','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-11','pruritus-care','Fundamentals','comfort management of pruritus','a client has dry itchy skin without an emergency reaction','Assess cause and use lukewarm bathing, moisturizer, cool environment, and prescribed therapy','Keep nails short and report jaundice, breathing difficulty, infection, or a spreading blistering rash','Itching progresses to facial swelling and wheezing','Use very hot showers','Scratch with sharp objects','Apply unapproved irritants','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-11','edema-skin','Fundamentals','skin care with severe edema','fragile stretched skin leaks clear fluid','Elevate as prescribed, protect and moisturize skin, reposition, and manage the cause','Inspect daily and report redness, warmth, wounds, sudden asymmetry, or breathlessness','One leg becomes acutely red, painful, and much larger','Massage the painful calf','Apply tight bands','Leave wet linens against skin','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-11','fatigue-energy','Fundamentals','energy conservation during chronic illness','a client becomes exhausted before completing basic activities','Prioritize tasks, alternate activity and rest, sit when possible, and use adaptive help','Plan demanding tasks for the best-energy time and report sudden worsening fatigue','Fatigue suddenly accompanies chest pain and dyspnea','Stay on bed rest indefinitely','Rush every task','Skip nutrition and hydration','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-11','communication-aphasia','Fundamentals','communication with expressive aphasia','a stroke survivor understands but struggles to produce words','Use simple questions, allow time, verify meaning, and offer communication aids','Reduce distractions and avoid pretending to understand unclear messages','A sudden worsening of speech occurs with new weakness','Finish every sentence immediately','Speak as if the client is a child','Exclude the client from decisions','Basic Care and Comfort');

-- Retained for subsequent held batches.
