-- Batch 05: 288 drafts; six concepts in each official Client Needs category.

-- Management of Care
select public.seed_structured_concept('expansion-batch-05','sbar-escalation','Leadership and Delegation','urgent SBAR communication','a client with new hypoxemia and falling blood pressure','Assess immediate stability, then report situation, background, assessment, and a clear recommendation','Use current objective data and read back urgent orders to close the communication loop','The receiving clinician does not respond while the client continues to deteriorate','Report only that the client looks bad','Delay contact until all routine charting is complete','Omit the recommendation because only providers make decisions','Management of Care');
select public.seed_structured_concept('expansion-batch-05','ed-triage-priority','Leadership and Delegation','emergency department triage','several clients arrive simultaneously with different acuity','Immediately prioritize the client with airway compromise or shock before stable clients','Triage is based on threat to life and required resources rather than arrival order','A client with stridor, drooling, and decreasing air movement waits in the lobby','Treat minor injuries before an unstable airway','Use age alone to determine priority','Delay reassessment after a long wait','Management of Care');
select public.seed_structured_concept('expansion-batch-05','delegate-vital-signs','Leadership and Delegation','delegating vital-sign measurement','a stable client needs routine postoperative observations','Delegate measurement with exact reporting parameters and personally interpret abnormal results','Assistive personnel collect data; the nurse assesses meaning and decides the response','The assistant reports blood pressure 78/40 and the nurse does not reassess','Ask the assistant to diagnose shock','Delegate evaluation of treatment effectiveness','Provide no parameters for reporting','Management of Care');
select public.seed_structured_concept('expansion-batch-05','float-nurse-assignment','Leadership and Delegation','assigning a float nurse','a medical-surgical nurse floats to an unfamiliar specialty unit','Assign clients with predictable care within demonstrated competency and provide unit support','State competency limits immediately and request guidance for unfamiliar equipment or treatments','The float nurse is assigned an unstable client requiring an unfamiliar titrated medication','Assume licensure means competency in every specialty','Withhold orientation because the shift is busy','Assign by convenience without reviewing acuity','Management of Care');
select public.seed_structured_concept('expansion-batch-05','treatment-refusal','Leadership and Delegation','informed treatment refusal','a competent adult declines a recommended lifesaving intervention','Assess understanding and capacity, explain consequences, notify the provider, and respect the decision','A capable client may refuse after receiving understandable information about risks and alternatives','Staff initiate treatment by force despite valid refusal and no emergency incapacity','Ask family to override the capable client','Threaten withdrawal of all care','Document the client as noncompliant without discussion','Management of Care');
select public.seed_structured_concept('expansion-batch-05','adverse-event-disclosure','Leadership and Delegation','response to an adverse event','a preventable error has caused client harm','Stabilize the client, notify leadership and providers, document facts, and follow disclosure policy','Expect honest communication about known facts and the plan for ongoing care','Staff alter the record or conceal the event from the care team','Speculate about blame in the medical record','Delay treatment while completing reports','Promise an outcome that cannot be guaranteed','Management of Care');

-- Safety and Infection Prevention and Control
select public.seed_structured_concept('expansion-batch-05','norovirus','Safety and Infection Control','norovirus gastroenteritis','abrupt vomiting and watery diarrhea affecting multiple clients','Initiate contact precautions, isolate or cohort, and use effective environmental disinfection','Wash hands with soap and water and avoid preparing food while ill','Continued vomiting contaminates a shared unit without isolation','Rely only on alcohol hand rub after stool contact','Clean vomit with an ineffective routine wipe','Allow symptomatic food handlers to work','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-05','c-diff-environment','Safety and Infection Control','environmental control of C. difficile','a room previously occupied by a client with infectious diarrhea','Use sporicidal terminal cleaning and dedicated or disinfected equipment','Soap-and-water hand hygiene and prescribed environmental cleaning help prevent spread','Shared equipment leaves the room without sporicidal disinfection','Use alcohol gel as the only hand cleaning','Place clean supplies on contaminated surfaces','Discontinue precautions while uncontrolled diarrhea continues','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-05','mrsa-draining-wound','Safety and Infection Control','a draining MRSA wound','uncontained purulent drainage contaminating linens','Use contact precautions and contain drainage with an appropriate dressing','Perform hand hygiene and do not share personal items or wound supplies','Drainage saturates the dressing and contaminates the environment','Use the same equipment for multiple clients without cleaning','Handle soiled dressings with bare hands','Place contaminated linen on the floor','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-05','scabies','Safety and Infection Control','scabies infestation','intense nocturnal itching with burrows and affected close contacts','Use contact precautions and administer prescribed treatment to the client and contacts','Wash clothing and bedding as directed and treat close contacts simultaneously','New crusted scabies in an immunocompromised client with extensive exposure','Share untreated clothing between family members','Stop treatment after itching persists one day','Use droplet precautions alone','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-05','ppe-removal','Safety and Infection Control','safe PPE removal','gown and gloves visibly contaminated after isolation care','Remove the most contaminated items without touching skin and perform hand hygiene at required steps','Follow the facility sequence and avoid touching the front of contaminated PPE','A contaminated glove touches the nurse’s face during removal','Snap the gown forcefully in the hallway','Carry used PPE to another room','Skip hand hygiene because gloves were worn','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-05','sterilization-spore','Safety and Infection Control','sterilization monitoring','a surgical service reviews sterilizer quality controls','Use physical, chemical, and biological monitoring and quarantine loads when required after failure','A failed biological indicator requires immediate reporting and investigation before instruments are used','Implantable instruments from a failed load are released for surgery','Assume a clean wrapper proves sterility','Ignore monitoring records after a cycle','Use high-level disinfection for critical surgical instruments','Safety and Infection Prevention and Control');

-- Health Promotion and Maintenance
select public.seed_structured_concept('expansion-batch-05','prenatal-warning-signs','Maternal and Newborn','prenatal warning-sign education','a pregnant client asks when to call the maternity unit','Teach immediate reporting of bleeding, fluid leakage, severe headache, reduced fetal movement, or regular preterm contractions','Keep scheduled care and seek prompt evaluation for danger signs rather than waiting for the next visit','Heavy bleeding with abdominal pain and decreased fetal movement','Treat fluid leakage as normal urine without assessment','Wait several days after fetal movement stops','Self-treat severe headache with unapproved medicine','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-05','postpartum-contraception','Maternal and Newborn','postpartum contraceptive counseling','a breastfeeding client wants to space future pregnancies','Discuss goals, breastfeeding, medical risks, effectiveness, and timing of available methods','Ovulation can return before the first period, so contraception planning should occur early','The client assumes breastfeeding always prevents pregnancy','Choose a method without reviewing contraindications','Delay all counseling until menstruation returns','Use another person’s prescription','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-05','newborn-car-seat','Health Promotion','newborn car-seat safety','parents preparing to take a healthy newborn home','Use a rear-facing seat in the back seat with correct harness fit and installation','Avoid bulky clothing under straps and obtain a fit check when installation is uncertain','The rear-facing seat is placed in front of an active airbag','Turn the infant forward-facing for easier observation','Add unapproved padding behind the infant','Leave harness straps loose over a thick coat','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-05','toddler-poisoning','Health Promotion','household poison prevention','a family has a curious mobile toddler','Lock medicines and chemicals in original containers and keep poison-control information accessible','Do not induce vomiting unless poison specialists direct it','The child is found drowsy beside an open medication bottle','Store cleaners in beverage containers','Call only after symptoms appear','Refer to medicine as candy','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-05','school-obesity','Health Promotion','family-centered childhood obesity prevention','a school-age child has increasing BMI and sedentary habits','Assess growth pattern and family routines and set achievable nutrition, sleep, and activity goals','Use regular meals, water, active family time, and non-stigmatizing language','The child develops exertional chest pain and syncope','Use severe calorie restriction without supervision','Shame the child at family meals','Eliminate all enjoyable activity as punishment','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-05','adult-prevention-visit','Health Promotion','an adult preventive-health visit','an asymptomatic adult has not received care for several years','Review age and risk-based screening, immunizations, substance use, mental health, and lifestyle','Screening schedules depend on age, history, anatomy, risk, and shared decision-making','The client reports a new breast mass while requesting routine screening','Order every test regardless of risk','Treat new symptoms as routine screening issues','Skip vaccine review because the client feels well','Health Promotion and Maintenance');

-- Psychosocial Integrity
select public.seed_structured_concept('expansion-batch-05','bipolar-depression','Mental Health','bipolar depression','profound depression with a history of mania','Assess suicide risk and mood history and monitor carefully during treatment changes','Track sleep and mood and report suicidal thoughts or emerging decreased need for sleep','The client develops agitation, no sleep, and impulsive spending after an antidepressant change','Use antidepressant monotherapy without reviewing mania history','Encourage sleep deprivation to improve energy','Dismiss new activation as recovery','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-05','negative-symptoms','Mental Health','negative symptoms of schizophrenia','flat affect, low motivation, reduced speech, and social withdrawal','Use simple goals, structured activity, and consistent supportive engagement','Small routines and rehabilitation support function even when emotional expression remains limited','The client stops eating and drinking because of worsening withdrawal','Demand enthusiastic emotional responses','Interpret reduced expression as deliberate rudeness','Use complex group tasks initially','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-05','opioid-use-treatment','Mental Health','opioid use disorder treatment','a client requests help after repeated nonfatal overdoses','Assess withdrawal and safety and offer evidence-based medication treatment and naloxone access','Medication treatment reduces overdose risk and should be combined with ongoing support','The client uses again after abstinence and becomes difficult to arouse','Require detoxification before offering any treatment','Withhold naloxone to discourage use','Discharge the client for relapse','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-05','bulimia-complications','Mental Health','bulimia nervosa','recurrent binge-purge behavior with dental erosion and weakness','Assess electrolytes, cardiac status, suicidality, and compensatory behaviors','Regular nutrition and therapy are essential; report fainting, palpitations, or blood in vomit','Potassium 2.6 mEq/L with ventricular ectopy','Praise weight loss to build rapport','Allow unsupervised bathroom use immediately after meals','Recommend additional exercise after purging','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-05','autism-communication','Mental Health','supportive communication with an autistic client','sensory distress and difficulty processing rapid verbal instructions','Reduce sensory load and use concrete language, visual supports, and extra response time','Care preferences differ; ask the client or caregiver what communication and sensory supports help','Escalating self-injury during overwhelming stimulation','Use figurative language and rapid questions','Touch the client without warning','Remove every familiar object','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-05','stimulant-intoxication','Mental Health','severe stimulant intoxication','agitation, paranoia, hyperthermia, chest pain, and hypertension','Reduce stimulation, monitor cardiac and temperature status, and give prescribed emergency treatment','Seek emergency care for chest pain, severe agitation, overheating, seizure, or collapse','Temperature 104°F with ventricular dysrhythmia','Encourage vigorous exercise','Use confrontation to challenge paranoia','Leave the client unmonitored in a hot room','Psychosocial Integrity');

-- Basic Care and Comfort
select public.seed_structured_concept('expansion-batch-05','unconscious-oral-care','Fundamentals','oral care for an unconscious client','an unresponsive client with pooled secretions and dry mucosa','Position laterally when appropriate, use suction, and provide gentle frequent oral care','Regular oral care protects comfort and reduces secretion and infection complications','Gurgling respirations with oxygen desaturation during care','Pour a large volume of fluid into the mouth','Place the client flat and supine','Leave loose swabs in the mouth','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-05','hearing-aid-care','Fundamentals','hearing-aid communication','an older client cannot follow instructions after hearing aids were removed','Reduce background noise, face the client, check device function, and speak clearly','Keep devices dry, clean as directed, and replace batteries when sound weakens','Sudden unilateral hearing loss with vertigo','Shout from behind the client','Cover the mouth while speaking','Immerse the device in water','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-05','bowel-training','Fundamentals','bowel retraining','a stable client has chronic functional constipation after immobility','Establish regular toileting after meals with fluids, fiber, activity, and privacy as appropriate','Respond to the urge to defecate and use laxatives only as directed','Severe pain, vomiting, distention, and absent bowel sounds','Use frequent enemas without assessment','Ignore the urge until bedtime','Remain on prolonged bed rest','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-05','urge-incontinence','Fundamentals','urge urinary incontinence','sudden urgency and leakage without urinary retention','Assess reversible causes and use scheduled voiding, bladder training, and pelvic-floor strategies','Limit bladder irritants and gradually extend time between planned voids','New incontinence with fever, flank pain, and acute confusion','Restrict all fluid throughout the day','Insert a chronic catheter for convenience','Punish episodes by delaying toileting','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-05','palliative-dyspnea','Fundamentals','palliative management of dyspnea','an end-stage client reports air hunger despite acceptable oxygen saturation','Position for comfort, provide airflow, reduce anxiety, and give prescribed symptom-relief medication','Comfort treatment is guided by distress and goals, not oxygen saturation alone','New severe distress inconsistent with the established comfort plan','Force the client to lie flat','Withhold prescribed opioid solely because it is used for pain','Require burdensome tests against documented goals','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-05','prosthesis-skin-care','Fundamentals','residual-limb and prosthesis care','a new amputee beginning prosthetic training','Inspect skin, shape the limb as prescribed, and ensure gradual properly fitted prosthesis use','Wash and dry the limb daily and report persistent redness, blistering, or drainage','Skin breakdown that remains red after the prosthesis is removed','Wear the prosthesis over open wounds','Adjust the socket with household materials','Skip daily skin inspection','Basic Care and Comfort');

-- Pharmacological and Parenteral Therapies
select public.seed_structured_concept('expansion-batch-05','mixing-insulins','Pharmacology','mixing regular and NPH insulin','both insulins are prescribed in one syringe','Verify doses and draw clear regular insulin before cloudy NPH using aseptic technique','Do not mix glargine with other insulins and follow the exact prescribed timing with meals','The prepared syringe contains an unverified dose after insulin types were confused','Draw NPH before regular insulin','Mix glargine with regular insulin','Estimate the dose without a second check when required','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-05','enoxaparin','Pharmacology','enoxaparin therapy','subcutaneous anticoagulation after orthopedic surgery','Assess bleeding and renal function and inject into abdominal tissue without expelling the air bubble when supplied','Avoid NSAIDs unless approved and report bleeding, black stool, or severe headache','New severe headache with unilateral weakness while anticoagulated','Massage the injection site vigorously','Inject into bruised tissue','Take aspirin freely for soreness','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-05','prednisone-longterm','Pharmacology','long-term systemic corticosteroid therapy','prednisone prescribed for chronic inflammatory disease','Monitor infection, glucose, blood pressure, bone health, and adrenal suppression','Take with food and never stop abruptly after prolonged use','Fever with hypotension after suddenly stopping prednisone','Receive live vaccines without review','Stop immediately when symptoms improve','Ignore black tarry stool','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-05','carbamazepine','Pharmacology','carbamazepine therapy','treatment for focal seizures and trigeminal neuralgia','Monitor blood counts, sodium, liver function, rash, and interactions','Report fever, sore throat, mouth ulcers, severe rash, or confusion promptly','Blistering rash with mucosal lesions','Use grapefruit without checking interactions','Stop abruptly after one seizure-free week','Ignore progressive unsteadiness','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-05','linezolid','Pharmacology','linezolid therapy','treatment of resistant gram-positive infection in a client taking serotonergic medicine','Review interactions and monitor blood counts, blood pressure, and serotonin-toxicity signs','Avoid unapproved serotonergic or high-tyramine products and report agitation, fever, or unusual bruising','Clonus, hyperreflexia, fever, and severe agitation','Combine with an MAOI without review','Ignore falling platelets','Use large amounts of aged fermented food','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-05','vesicant-extravasation','Pharmacology','chemotherapy vesicant extravasation','burning, swelling, and absent blood return during a vesicant infusion','Stop the infusion, leave the catheter for aspiration or antidote, and follow the drug-specific protocol','Report burning, pain, tightness, swelling, or leakage at the infusion site immediately','Blistering and progressive tissue discoloration at the site','Flush the vesicant forcefully through the vein','Remove the catheter before attempting aspiration','Apply pressure and massage the site','Pharmacological and Parenteral Therapies');

-- Reduction of Risk Potential
select public.seed_structured_concept('expansion-batch-05','postop-hemorrhage','Medical-Surgical','early postoperative hemorrhage','restlessness, tachycardia, cool skin, and increasing sanguineous drainage','Assess circulation, reinforce monitoring, notify the surgical team, and prepare resuscitation support','Report rapidly saturating dressings, dizziness, palpitations, or faintness immediately','Falling blood pressure with a rapidly expanding wound swelling','Remove the original dressing to inspect repeatedly','Encourage walking to raise blood pressure','Delay reporting until hemoglobin results return','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-05','hip-arthroplasty-dislocation','Medical-Surgical','hip dislocation after posterior hip arthroplasty','shortened internally rotated leg with sudden severe hip pain','Keep the client still, maintain precautions, and notify the surgeon immediately','Avoid hip flexion beyond prescribed limits, adduction, and internal rotation','A sudden pop with inability to move the operative leg','Cross the legs at the knees','Use a low soft chair','Bend forward to tie shoes','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-05','turp-syndrome','Medical-Surgical','TURP syndrome','confusion, hypertension, bradycardia, nausea, and hyponatremia during irrigation','Stop or reduce irrigation as directed, notify the surgeon, and assess sodium and cardiopulmonary status','Report confusion, severe headache, breathing difficulty, or reduced catheter drainage','Seizure with sodium 116 mEq/L','Increase hypotonic irrigation pressure','Encourage free-water intake rapidly','Treat confusion as expected anesthesia recovery','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-05','cataract-postop','Medical-Surgical','complications after cataract surgery','a client recovering after intraocular lens placement','Protect the eye and monitor pain, vision, drainage, nausea, and intraocular-pressure symptoms','Avoid bending, heavy lifting, rubbing the eye, and straining as instructed','Severe eye pain with nausea and sudden vision loss','Sleep directly on the operative eye','Lift heavy groceries the next morning','Rub the eye when itching occurs','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-05','colonoscopy-perforation','Medical-Surgical','perforation after colonoscopy','increasing abdominal pain, rigid distention, fever, and tachycardia','Keep the client NPO, notify the provider urgently, and prepare diagnostic and surgical management','Mild gas may occur, but severe pain, fever, bleeding, or a firm swollen abdomen requires urgent care','Rigid abdomen with hypotension and shoulder pain','Give a laxative for increasing pain','Encourage a large meal','Delay reporting until the next bowel movement','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-05','renal-biopsy','Medical-Surgical','bleeding after renal biopsy','a client returning from percutaneous kidney biopsy','Maintain prescribed bed rest and monitor vital signs, urine, flank pain, and hemoglobin','Avoid heavy activity and report bright-red urine, clots, dizziness, or increasing flank pain','Hypotension with gross hematuria and worsening flank pain','Encourage immediate stair climbing','Administer an anticoagulant before reassessment','Treat large clots as expected','Reduction of Risk Potential');

-- Physiological Adaptation
select public.seed_structured_concept('expansion-batch-05','cardiogenic-shock','Emergency and Critical Care','cardiogenic shock after myocardial infarction','hypotension, cool clammy skin, crackles, jugular venous distention, and low urine output','Support oxygenation, activate shock care, and give prescribed vasoactive therapy while avoiding indiscriminate fluids','Report recurrent chest pain, severe breathlessness, faintness, or reduced urine immediately','Worsening pulmonary edema with mean arterial pressure below target','Give repeated large fluid boluses without reassessment','Encourage ambulation during hypotension','Delay cardiac monitoring','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-05','hemorrhagic-shock','Emergency and Critical Care','hemorrhagic shock','active bleeding, tachycardia, narrow pulse pressure, cool skin, and confusion','Control bleeding, establish rapid vascular access, and begin prescribed blood and fluid resuscitation','Seek emergency help for major bleeding and do not remove deeply embedded objects','Declining consciousness with persistent hypotension despite initial support','Give oral fluids to an unstable client','Delay blood preparation until complete laboratory results','Apply heat directly to uncontrolled bleeding','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-05','dic','Emergency and Critical Care','disseminated intravascular coagulation','oozing from lines, petechiae, organ ischemia, low platelets, and prolonged clotting','Treat the cause, minimize trauma, monitor bleeding and perfusion, and administer prescribed blood products','Report unexpected bruising, bleeding, reduced urine, chest pain, or confusion promptly','Uncontrolled bleeding with new mottled ischemic digits','Give IM injections for analgesia','Use rectal temperatures','Apply vigorous pressure massage to bruised tissue','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-05','acute-pancreatitis','Medical-Surgical','severe acute pancreatitis','epigastric pain radiating to the back, vomiting, and rising lipase','Keep the client NPO initially as prescribed, provide IV fluid and analgesia, and monitor organ function','Avoid alcohol and report severe recurrent pain, vomiting, fever, or jaundice','Increasing respiratory distress with hypotension and falling urine output','Offer a high-fat meal during severe pain','Place the client flat after eating','Delay fluid resuscitation','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-05','bowel-obstruction','Medical-Surgical','mechanical bowel obstruction','colicky pain, vomiting, distention, and high-pitched sounds followed by silence','Keep NPO, decompress as prescribed, replace fluids and electrolytes, and monitor for strangulation','Seek care for persistent vomiting, severe distention, inability to pass stool or gas, or constant pain','Constant severe pain with fever, rigidity, and absent bowel sounds','Give a bulk-forming laxative','Encourage a solid meal','Delay evaluation until flatus returns','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-05','status-epilepticus','Emergency and Critical Care','convulsive status epilepticus','continuous seizure activity lasting at least five minutes without recovery','Protect the airway, give oxygen, check glucose, and administer prescribed rapid antiseizure therapy','Use rescue medicine exactly as directed and call emergency services for a seizure lasting five minutes','Persistent seizure with cyanosis despite first-line medication','Restrain all extremities','Insert an object between the teeth','Delay medication until thirty minutes have passed','Physiological Adaptation');

-- Retained for subsequent held batches.
