-- Batch 06: 288 drafts; six additional concepts in every official category.

-- Management of Care
select public.seed_structured_concept('expansion-batch-06','bedside-handoff','Leadership and Delegation','safe bedside handoff','a shift change involving a client with several high-risk treatments','Verify identity, lines, infusions, orders, allergies, safety risks, and immediate priorities with the client involved when appropriate','Speak up during handoff when information conflicts with the current condition or medication record','A high-alert infusion rate differs from the order and neither nurse verifies it','Discuss unrelated clients in the room','Skip line tracing to save time','Rely entirely on memory','Management of Care');
select public.seed_structured_concept('expansion-batch-06','delegate-specimen','Leadership and Delegation','delegating specimen collection','a stable client needs a routine clean-catch urine specimen','Give clear collection, labeling, timing, and transport instructions and verify completion','Label specimens at the bedside with required identifiers and report collection problems','An unlabeled specimen is sent to the laboratory','Ask assistive personnel to interpret results','Prelabel containers away from the client','Leave the specimen at room temperature indefinitely','Management of Care');
select public.seed_structured_concept('expansion-batch-06','unsafe-staffing','Leadership and Delegation','an unsafe staffing assignment','a nurse receives more unstable clients than can be safely monitored','Notify the charge nurse promptly, describe specific risks, request help, and continue essential care without abandoning clients','Use the chain of command and document objective safety concerns according to policy','The nurse accepts silently and a deteriorating client is left unmonitored','Walk out before transferring responsibility','Refuse every task without identifying risk','Alter acuity documentation to force reassignment','Management of Care');
select public.seed_structured_concept('expansion-batch-06','organ-donation-referral','Leadership and Delegation','potential organ donation','a client meets facility triggers for referral after catastrophic neurologic injury','Notify the designated organ-procurement organization according to law and policy','Trained donation specialists discuss options; bedside staff should provide support without promising eligibility','Staff approach the family with inaccurate promises before referral','Delay referral until after withdrawal of support','Pressure the family to consent','Assume age alone excludes donation','Management of Care');
select public.seed_structured_concept('expansion-batch-06','hospice-goals','Leadership and Delegation','hospice plan-of-care coordination','a terminally ill client prioritizes comfort at home','Clarify goals, anticipate symptoms, coordinate equipment and medicines, and teach whom to call','Hospice supports comfort and family needs; emergency plans should match documented goals','Care is repeatedly sent to emergency services contrary to documented wishes without reassessment','Promise that all symptoms will disappear','Stop every beneficial comfort medicine','Exclude family chosen by the client','Management of Care');
select public.seed_structured_concept('expansion-batch-06','medical-interpreter','Leadership and Delegation','language-access services','a client with limited English proficiency must consent to complex care','Use a qualified medical interpreter and speak directly to the client','Request an interpreter for important discussions rather than relying on children or untrained visitors','A minor child translates high-risk consent information','Speak only to the interpreter','Use gestures for medication teaching','Ask family to omit distressing information','Management of Care');

-- Safety and Infection Prevention and Control
select public.seed_structured_concept('expansion-batch-06','influenza-droplet','Safety and Infection Control','seasonal influenza precautions','fever, myalgia, cough, and a positive influenza test','Use droplet precautions plus standard precautions and limit unnecessary transport','Wear a mask as instructed and practice respiratory hygiene and hand cleaning','An unmasked symptomatic client enters a crowded oncology waiting room','Use contact precautions alone','Share respiratory equipment without disinfection','Discontinue precautions immediately after one antiviral dose','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-06','tb-transport','Safety and Infection Control','transport of a client with pulmonary tuberculosis','a medically necessary test outside the airborne-isolation room','Place a surgical mask on the client, cover coughs, notify the receiving area, and limit transport','Keep the room door closed and leave isolation only for essential care','The client is transported unmasked through public corridors','Place an N95 on the client instead of source-control masking','Leave the isolation door open','Schedule nonessential group activities','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-06','protective-environment','Safety and Infection Control','a protective environment after stem-cell transplant','profound immunosuppression with high risk from environmental mold','Follow protective-environment airflow and construction controls and exclude fresh plants and standing water','Perform meticulous hand hygiene and avoid sick visitors, soil, and unapproved raw foods','Construction dust enters the positive-pressure room','Use negative pressure for routine protection','Bring fresh flowers to improve mood','Allow a coughing visitor without screening','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-06','safe-injection','Safety and Infection Control','safe injection practice','preparation of parenteral medicine for several clients','Use a new sterile needle and syringe for every injection and enter single-dose vials for one client only','Never reuse a syringe, even when the needle is changed','One syringe is used to access a shared vial for multiple clients','Prepare injections beside a contaminated sink','Reuse a syringe after changing the needle','Combine leftover single-dose vials','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-06','surgical-site-prevention','Safety and Infection Control','surgical-site infection prevention','a client preparing for elective surgery','Use indicated antimicrobial prophylaxis timing, appropriate hair removal, glucose control, and aseptic skin preparation','Follow bathing and wound-care instructions and report fever, spreading redness, or drainage','Purulent drainage and wound separation with fever','Shave the site with a razor the night before','Continue unnecessary antibiotics indefinitely','Touch the prepared site with unsterile gloves','Safety and Infection Prevention and Control');
select public.seed_structured_concept('expansion-batch-06','foodborne-prevention','Safety and Infection Control','food safety for severe immunosuppression','a client receiving intensive chemotherapy','Use safe food handling, avoid unpasteurized and undercooked high-risk foods, and refrigerate promptly','Separate raw foods, cook thoroughly, and wash produce and hands','Fever and bloody diarrhea after eating undercooked meat','Thaw meat on the counter all day','Drink unpasteurized milk','Use the same board for raw meat and salad without cleaning','Safety and Infection Prevention and Control');

-- Health Promotion and Maintenance
select public.seed_structured_concept('expansion-batch-06','breast-awareness','Health Promotion','breast health awareness','an adult notices a new breast change','Assess the change and arrange diagnostic evaluation rather than waiting for routine screening','Report a new lump, skin dimpling, nipple inversion, or bloody discharge promptly','A hard fixed mass with skin retraction','Assume a painless lump is harmless','Massage a new mass daily','Wait for the next annual visit despite change','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-06','pregnancy-vaccines','Maternal and Newborn','vaccination during pregnancy','a pregnant client asks about recommended vaccines','Review gestational timing and administer recommended inactivated vaccines while avoiding contraindicated live vaccines','Vaccination helps protect parent and infant; discuss influenza, Tdap, and other risk-based recommendations','A live vaccine is prepared without reviewing pregnancy status','Avoid every vaccine during pregnancy','Receive a live vaccine without consultation','Delay indicated influenza protection until after delivery','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-06','child-immunization-catchup','Pediatrics','catch-up childhood immunization','a child has incomplete records after moving','Verify available records and use the recommended catch-up schedule without restarting valid series','Bring immunization records to visits and continue from documented valid doses','The child has signs of anaphylaxis after a vaccine dose','Restart every vaccine series automatically','Count undocumented verbal dates as verified records','Give contraindicated live vaccine during severe immunosuppression','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-06','osteoporosis-prevention','Health Promotion','osteoporosis prevention','an older adult has low activity and fracture risk','Promote weight-bearing and resistance activity, adequate calcium and vitamin D, fall prevention, and risk-based screening','Avoid tobacco, limit excess alcohol, and discuss medicines that affect bone health','New severe back pain with height loss after minimal strain','Remain sedentary to protect bones','Take excessive calcium without review','Ignore home fall hazards','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-06','smoking-cessation','Health Promotion','tobacco cessation','a client is willing to make a quit attempt','Assess dependence and preferences and offer counseling plus approved medication options','Set a quit plan, identify triggers, use support, and treat lapses as opportunities to resume','Chest pain and hemoptysis in a long-term smoker','Use shame to motivate quitting','Recommend unverified products as harmless','Stop prescribed cessation medicine for mild cravings','Health Promotion and Maintenance');
select public.seed_structured_concept('expansion-batch-06','sti-prevention','Health Promotion','sexually transmitted infection prevention','a young adult requests confidential prevention counseling','Provide risk-based testing, vaccination, barrier-method education, partner services, and prevention options','Use barriers correctly and seek testing because many infections have no symptoms','Pelvic pain, fever, and syncope with possible pregnancy','Rely on appearance to identify infection','Share prescribed antibiotics with partners','Avoid testing when asymptomatic','Health Promotion and Maintenance');

-- Psychosocial Integrity
select public.seed_structured_concept('expansion-batch-06','generalized-anxiety','Mental Health','generalized anxiety disorder','persistent excessive worry, muscle tension, and impaired sleep','Assess function and safety and support evidence-based psychotherapy, relaxation, and prescribed treatment','Practice scheduled coping skills and limit caffeine and nonprescribed stimulants','Anxiety escalates with suicidal thoughts and inability to function','Tell the client to stop worrying','Use alcohol nightly for sleep','Avoid every anxiety-provoking activity permanently','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-06','borderline-crisis','Mental Health','borderline personality disorder in crisis','intense fear of abandonment, self-injury urges, and staff splitting','Assess self-harm risk, use consistent boundaries, validate emotion, and coordinate one team plan','Use crisis skills and contact supports early when urges intensify','The client hides a sharp object and states intent to self-injure','Make exceptions to limits for preferred staff','Threaten discharge for emotional expression','Argue about whether feelings are rational','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-06','aggressive-escalation','Mental Health','escalating aggressive behavior','pacing, clenched fists, loud threats, and increasing proximity','Maintain distance and exit access, reduce stimulation, set clear limits, and summon help early','Use calm words, offer space and choices, and seek staff before losing control','The client reaches for a weapon while blocking the exit','Stand within arm’s reach','Match the client’s volume','Turn away and leave others unprotected','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-06','psychiatric-seclusion','Mental Health','seclusion or restraint in behavioral care','imminent violence persists after less-restrictive measures fail','Use only the least restrictive emergency measure with an order, monitoring, basic care, and earliest release','Restrictive measures are never punishment and end when immediate danger resolves','Respiratory distress or altered consciousness develops while restrained','Use restraint for verbal annoyance','Tie restraints to movable rails','Skip circulation and breathing checks','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-06','postpartum-depression','Maternal and Newborn','postpartum depression','persistent sadness, guilt, poor bonding, insomnia, and intrusive thoughts','Assess suicide and infant-harm risk and connect the client with urgent perinatal mental-health care','Postpartum depression is treatable; seek help for persistent symptoms or frightening thoughts','A stated plan to harm self or the infant','Reassure that all symptoms are normal baby blues','Leave the client alone with the infant during active intent','Advise stopping all treatment while breastfeeding','Psychosocial Integrity');
select public.seed_structured_concept('expansion-batch-06','gambling-disorder','Mental Health','gambling disorder','debt, concealment, chasing losses, and family crisis','Assess suicide risk, finances, comorbidity, and readiness for treatment and support','Limit access to money and gambling platforms and use specialized therapy and peer support','The client has a suicide plan after a major loss','Loan money to recover losses','Encourage one final large bet','Keep financial harm secret from the treatment team','Psychosocial Integrity');

-- Basic Care and Comfort
select public.seed_structured_concept('expansion-batch-06','chemotherapy-mucositis','Fundamentals','oral mucositis','painful oral ulcers during chemotherapy','Assess severity and infection and provide frequent gentle oral care and prescribed pain relief','Use a soft brush and bland rinses and avoid alcohol mouthwash, tobacco, and irritating foods','Ulcers prevent all fluid intake and fever develops','Use lemon-glycerin swabs repeatedly','Scrub bleeding tissue','Choose spicy acidic foods','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-06','enteral-medications','Fundamentals','medication administration through a feeding tube','several medicines are due during continuous enteral feeding','Verify placement, review drug-feed interactions, give medicines separately, and flush appropriately','Do not crush enteric-coated or extended-release medicines and follow tube-specific instructions','The tube becomes occluded after crushed extended-release medication','Mix all medicines into the formula bag','Crush every tablet regardless of formulation','Use carbonated beverage as routine unclogging treatment','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-06','nausea-comfort','Fundamentals','nonpharmacologic nausea management','a stable client has treatment-related nausea','Reduce odors, provide oral care, offer small tolerated portions, and give prescribed antiemetic before triggers','Use small frequent bland meals and sip fluids between meals as tolerated','Vomiting blood with dizziness and hypotension','Serve a large fatty meal','Lie flat immediately after eating','Force strong-smelling food','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-06','diarrhea-skin','Fundamentals','skin protection during frequent diarrhea','an incontinent client has repeated liquid stool and perineal redness','Clean gently after episodes, dry carefully, use barrier protection, and treat the cause','Avoid harsh rubbing and report open skin, bleeding, fever, or dehydration','Rapidly spreading denuded skin with severe pain and fever','Scrub with hot water and strong soap','Leave wet briefs in place','Apply powder that cakes into moist skin','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-06','hemiplegic-positioning','Fundamentals','positioning after stroke with hemiplegia','a client has a flaccid affected arm and limited mobility','Support the shoulder and joints in alignment and reposition while protecting sensation and skin','Never pull on the affected arm and inspect numb skin daily','New shoulder pain with visible subluxation after transfer','Lift by the affected arm','Leave the hand tightly clenched','Place pressure directly on the weak shoulder','Basic Care and Comfort');
select public.seed_structured_concept('expansion-batch-06','dry-eye-comfort','Fundamentals','eye protection with impaired eyelid closure','an unconscious client cannot fully close the eyelids','Assess corneal exposure and use prescribed lubrication and eyelid protection','Protect eyes from drying and report redness, cloudiness, drainage, or injury','A cloudy cornea with new purulent drainage','Tape directly across the cornea','Use unprescribed vasoconstrictor drops','Leave the eyes open under direct airflow','Basic Care and Comfort');

-- Pharmacological and Parenteral Therapies
select public.seed_structured_concept('expansion-batch-06','acetaminophen','Pharmacology','acetaminophen safety','a client uses several combination cold and pain products','Calculate the total daily dose from every product and assess liver and alcohol risk','Read ingredient labels and avoid taking multiple acetaminophen-containing products','Right-upper-quadrant pain, vomiting, and markedly elevated liver enzymes after overdose','Combine products without counting doses','Use heavy alcohol with daily high doses','Wait for jaundice before reporting overdose','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-06','nsaid-bleeding','Pharmacology','NSAID therapy','an older client with kidney disease and anticoagulant use requests ibuprofen','Review renal, gastrointestinal, cardiovascular, and bleeding risks before administration','Take only as approved and report black stool, vomiting blood, swelling, or reduced urine','Black tarry stool with dizziness and falling hemoglobin','Take two NSAIDs together','Use during acute kidney injury','Ignore new edema and reduced urine','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-06','statin-myopathy','Pharmacology','statin therapy','a high-intensity statin is started for vascular risk reduction','Review interactions and liver history and assess unexplained muscle symptoms','Report severe muscle pain, weakness, or dark urine and avoid pregnancy during therapy','Diffuse weakness with dark urine and markedly elevated creatine kinase','Double doses after missed tablets','Use interacting medicines without review','Stop permanently for mild transient soreness without consultation','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-06','bisphosphonate','Pharmacology','oral bisphosphonate therapy','alendronate prescribed for osteoporosis','Give with plain water on an empty stomach and keep the client upright for the required interval','Remain upright and delay food and other medicines according to product instructions','New painful swallowing with severe retrosternal pain','Take at bedtime while lying down','Chew with calcium supplements','Use despite inability to remain upright','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-06','albuterol-overuse','Pharmacology','short-acting beta agonist use','an asthma client empties an albuterol inhaler every week','Assess current respiratory status and notify the prescriber because frequent rescue use signals poor control','Track rescue use and seek review when it is needed more often or stops relieving symptoms','Minimal air movement and exhaustion despite repeated rescue doses','Use albuterol as the only long-term controller','Delay emergency help while taking unlimited doses','Ignore marked tachycardia and chest pain','Pharmacological and Parenteral Therapies');
select public.seed_structured_concept('expansion-batch-06','inhaled-steroid','Pharmacology','inhaled corticosteroid therapy','a controller inhaler is prescribed for persistent asthma','Teach daily use, correct sequencing, spacer use when indicated, and mouth rinsing','This controller does not replace a rescue inhaler; rinse and spit after use','White oral plaques with painful swallowing and worsening asthma control','Use only during acute attacks','Stop whenever symptoms improve for one day','Swallow rinse water after every dose','Pharmacological and Parenteral Therapies');

-- Reduction of Risk Potential
select public.seed_structured_concept('expansion-batch-06','femoral-cath','Medical-Surgical','care after femoral cardiac catheterization','a client returns after arterial access closure','Monitor the site, distal circulation, vital signs, rhythm, and prescribed positioning','Keep the leg as directed and report warmth, bleeding, numbness, severe pain, or back pain','Hypotension with flank pain and a firm groin swelling','Flex the affected hip repeatedly','Walk before the prescribed bed-rest interval','Apply heat to active bleeding','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-06','contrast-aki','Medical-Surgical','contrast-associated kidney injury risk','a client with chronic kidney disease needs iodinated contrast','Review renal function and nephrotoxins and use prescribed hydration and lowest appropriate contrast exposure','Follow instructions about fluids and medicines and report reduced urine or swelling','Creatinine rises sharply with oliguria after contrast','Give additional nephrotoxic medicine','Ignore metformin instructions','Restrict all fluids without indication','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-06','spine-surgery','Medical-Surgical','neurologic compromise after spinal surgery','a postoperative client needs frequent motor and sensory checks','Maintain alignment and assess strength, sensation, pain, bladder function, and wound drainage','Use logrolling and report new weakness, numbness, saddle anesthesia, or loss of bladder control','New bilateral leg weakness with urinary retention','Twist at the waist during transfer','Place pillows causing spinal rotation','Delay reporting new paralysis','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-06','mastectomy-arm','Medical-Surgical','arm care after axillary lymph-node surgery','a client is at risk for lymphedema and shoulder limitation','Protect the affected side, promote prescribed range of motion, and monitor swelling and infection','Avoid constriction and skin injury and report persistent swelling, redness, or heaviness','Rapid arm swelling with redness and fever','Use tight jewelry on the affected arm','Allow routine blood pressures on that side when alternatives exist','Avoid all shoulder movement indefinitely','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-06','peritoneal-dialysis','Medical-Surgical','peritoneal dialysis peritonitis','cloudy effluent with abdominal pain and fever','Save the effluent sample, notify the dialysis team, and administer prescribed antimicrobial therapy','Use meticulous aseptic connection technique and report cloudy drainage immediately','Cloudy outflow with rebound tenderness and hypotension','Warm dialysate in a microwave','Continue exchanges without reporting cloudy fluid','Touch sterile connectors with bare hands','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-06','chest-tube-air-leak','Medical-Surgical','a new chest-tube air leak','continuous bubbling appears in the water-seal chamber','Assess the client and system and locate loose connections according to policy','Keep the system upright and below the chest and report new continuous bubbling or dyspnea','Sudden distress with no tidaling and absent breath sounds','Strip tubing forcefully','Clamp routinely during transport','Ignore continuous bubbling','Reduction of Risk Potential');

-- Physiological Adaptation
select public.seed_structured_concept('expansion-batch-06','stemi','Emergency and Critical Care','acute ST-elevation myocardial infarction','crushing chest pressure, diaphoresis, ST elevation, and nausea','Activate reperfusion protocol, obtain rapid ECG-based care, and give prescribed antiplatelet and supportive therapy','Call emergency services for persistent chest pressure and do not drive yourself','Recurrent pain with ventricular tachycardia and hypotension','Delay care to finish household tasks','Walk to relieve chest pressure','Take an interacting erectile-dysfunction drug with nitrate','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-06','acute-heart-failure','Medical-Surgical','acute decompensated heart failure','orthopnea, crackles, edema, hypoxemia, and jugular venous distention','Sit upright, support oxygenation, give prescribed diuretic and vasodilator therapy, and monitor response','Track daily weight and report rapid gain, swelling, or increasing breathlessness','Pink frothy sputum with severe hypoxemia','Give a large unmonitored fluid bolus','Place the client flat','Encourage high-sodium food','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-06','acute-kidney-injury','Medical-Surgical','acute kidney injury','rising creatinine, oliguria, edema, and electrolyte disturbance','Identify the cause, stop nephrotoxins, monitor fluid and electrolytes, and treat urgent complications','Avoid unapproved NSAIDs and report reduced urine, swelling, weakness, or breathlessness','Potassium 6.7 mEq/L with widening QRS complexes','Give potassium supplements','Force excessive fluid despite pulmonary edema','Continue nephrotoxic contrast without review','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-06','variceal-bleed','Medical-Surgical','bleeding esophageal varices','cirrhosis with massive hematemesis, hypotension, and altered consciousness','Protect the airway, establish large-bore access, and prepare prescribed vasoactive and endoscopic therapy','Avoid alcohol and NSAIDs and seek emergency care for vomiting blood or black stool','Ongoing hematemesis with inability to protect the airway','Insert a nasogastric tube without an order','Offer food and oral fluids','Delay blood preparation','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-06','major-burn','Emergency and Critical Care','a major thermal burn','large partial- and full-thickness burns with facial soot and hoarseness','Secure the airway early, begin calculated fluid resuscitation, prevent hypothermia, and assess associated trauma','Cool minor burns with running water but seek emergency care for large, deep, facial, airway, electrical, or chemical burns','Increasing hoarseness and stridor after an enclosed-space fire','Apply ice directly to extensive burns','Break intact blisters','Delay airway assessment until edema is obvious','Physiological Adaptation');
select public.seed_structured_concept('expansion-batch-06','bacterial-meningitis-adult','Medical-Surgical','acute bacterial meningitis','fever, severe headache, neck stiffness, photophobia, and altered consciousness','Initiate droplet precautions and give prescribed antibiotics promptly after appropriate cultures','Close contacts may need prophylaxis and urgent evaluation is required for fever with stiff neck or confusion','Purpuric rash with shock and declining consciousness','Delay antibiotics for final culture results','Place in a bright noisy room','Use standard precautions alone initially','Physiological Adaptation');

-- Retained for subsequent held batches.
