-- Safe seed Yingoh NCLEX question bank, part 5.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient threatens to leave the hospital against medical advice. The nurse restrains the patient without consent. This constitutes:', '[{"id":"a","text":"Battery"},{"id":"b","text":"False imprisonment"},{"id":"c","text":"Negligence"},{"id":"d","text":"Malpractice"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'False imprisonment is unlawful restraint or restriction of a person''s freedom of movement without consent or legal justification. Patients who are competent and have decision-making capacity have the right to leave AMA. The nurse should document the AMA discussion.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient threatens to leave the hospital against medical advice. The nurse restrains the patient without consent. This constitutes:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'sata', 'A nurse is assessing suicide risk. Which factors significantly increase risk? (Select all that apply)', '[{"id":"a","text":"Previous suicide attempt"},{"id":"b","text":"Access to lethal means such as firearms"},{"id":"c","text":"Strong religious beliefs against suicide"},{"id":"d","text":"Recent significant loss or humiliation"},{"id":"e","text":"Stated desire for revenge"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Highest risk factors: prior attempt (strongest predictor), access to means (especially firearms), recent loss/humiliation. Strong religious beliefs and social support are protective factors that reduce risk. Expressed desire for revenge alone is insufficient for elevated risk categorization.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is assessing suicide risk. Which factors significantly increase risk? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient in the manic phase of bipolar disorder refuses to eat because "eating takes too much time." What is the most therapeutic nursing response?', '[{"id":"a","text":"Sit with the patient during structured mealtimes and encourage eating"},{"id":"b","text":"Offer high-calorie finger foods and snacks the patient can eat while moving"},{"id":"c","text":"Restrict activities until the patient agrees to sit and eat a full meal"},{"id":"d","text":"Notify the provider that the patient is refusing meals"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Manic patients are hyperactive and cannot sit still for meals. Provide portable, high-calorie finger foods (sandwiches, crackers, fruit) so they can eat while moving. This meets nutritional needs within the patient''s behavioral capacity during mania.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient in the manic phase of bipolar disorder refuses to eat because "eating takes too much time." What is the most therapeutic nursing response?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient prescribed clozapine (Clozaril) requires monitoring for which serious adverse effect?', '[{"id":"a","text":"QT prolongation"},{"id":"b","text":"Agranulocytosis"},{"id":"c","text":"Tardive dyskinesia"},{"id":"d","text":"Neuroleptic malignant syndrome"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Clozapine has a BLACK BOX WARNING for agranulocytosis (life-threatening drop in WBC/neutrophils). Weekly then bi-weekly ANC monitoring is mandatory. The drug is only available through a restricted REMS program. Hold if ANC <1500.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient prescribed clozapine (Clozaril) requires monitoring for which serious adverse effect?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient experiencing alcohol withdrawal on day 2 develops tremors, diaphoresis, and a seizure. Which medication does the nurse anticipate?', '[{"id":"a","text":"Haloperidol (Haldol)"},{"id":"b","text":"Lorazepam (Ativan)"},{"id":"c","text":"Naltrexone (Vivitrol)"},{"id":"d","text":"Disulfiram (Antabuse)"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Benzodiazepines (lorazepam, diazepam) are first-line for alcohol withdrawal seizures and delirium tremens. They cross-react with GABA receptors to prevent CNS hyperexcitability. CIWA-Ar protocol guides dosing. Haloperidol lowers seizure threshold.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient experiencing alcohol withdrawal on day 2 develops tremors, diaphoresis, and a seizure. Which medication does the nurse anticipate?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'sata', 'A nurse is applying therapeutic communication with a patient who is grieving. Which responses are therapeutic? (Select all that apply)', '[{"id":"a","text":"\"I understand exactly how you feel.\""},{"id":"b","text":"\"Tell me what you''re experiencing right now.\""},{"id":"c","text":"\"This must be a very difficult time for you.\""},{"id":"d","text":"\"Everything happens for a reason.\""},{"id":"e","text":"Sitting silently with the patient for several minutes"}]'::jsonb, '{"ids":["b","c","e"]}'::jsonb, 'Therapeutic: open-ended questions, empathy, and therapeutic silence. Non-therapeutic: "I know how you feel" (impossible to know another''s experience — blocks communication) and clichés like "everything happens for a reason" (minimizes feelings).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is applying therapeutic communication with a patient who is grieving. Which responses are therapeutic? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient with anorexia nervosa has a BMI of 15.2 and serum potassium of 2.8 mEq/L. What is the priority concern?', '[{"id":"a","text":"Cardiac dysrhythmias from electrolyte imbalance"},{"id":"b","text":"Impaired body image and self-esteem"},{"id":"c","text":"Risk of refeeding syndrome from rapid nutritional replacement"},{"id":"d","text":"Social isolation related to disordered eating behaviors"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'With K+ 2.8 mEq/L, the priority is physiologic safety — hypokalemia causes life-threatening cardiac dysrhythmias including ventricular fibrillation. The body can only address psychosocial needs once the patient is medically stabilized.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with anorexia nervosa has a BMI of 15.2 and serum potassium of 2.8 mEq/L. What is the priority concern?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient with PTSD wakes up screaming and is disoriented. What is the nurse''s therapeutic response?', '[{"id":"a","text":"\"You''re safe. I''m your nurse. You''re in the hospital.\""},{"id":"b","text":"\"Calm down. It was just a dream.\""},{"id":"c","text":"Leave the room to give the patient space"},{"id":"d","text":"Ask the patient to describe the nightmare in detail"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'During a PTSD nightmare/flashback, orient the patient with calm, simple statements about safety and present reality. "You''re safe, you''re in the hospital" grounds the patient. Dismissing the experience or leaving is non-therapeutic; detail-seeking during acute distress is re-traumatizing.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with PTSD wakes up screaming and is disoriented. What is the nurse''s therapeutic response?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient receiving an SSRI for 10 days reports feeling more energetic and has made end-of-life phone calls to family. What is the priority nursing concern?', '[{"id":"a","text":"The SSRI is working — energy returning is a positive sign"},{"id":"b","text":"The patient may be at increased risk for suicide"},{"id":"c","text":"The SSRI needs to be increased as the patient still seems sad"},{"id":"d","text":"Teach the patient it takes 4–6 weeks for full effect"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'SSRIs restore energy before improving mood — patients may now have enough motivation to act on suicidal thoughts. "End-of-life" calls (saying goodbye) and increased energy in the first 2 weeks = HIGH RISK for suicide. Perform a complete safety assessment immediately.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient receiving an SSRI for 10 days reports feeling more energetic and has made end-of-life phone calls to family. What is the priority nursing concern?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A nurse is monitoring a patient in active labor. Which fetal heart rate pattern requires immediate intervention?', '[{"id":"a","text":"Early decelerations beginning and ending with contractions"},{"id":"b","text":"Accelerations with fetal movement"},{"id":"c","text":"Late decelerations occurring after each contraction"},{"id":"d","text":"Variable decelerations that resolve quickly"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Late decelerations (FHR drops after the peak of a contraction and recovers late) indicate uteroplacental insufficiency — fetal hypoxia. Immediate actions: left lateral position, O2 via mask, IV fluids, stop oxytocin, notify provider. Early decelerations are benign (head compression). Accelerations are reassuring.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is monitoring a patient in active labor. Which fetal heart rate pattern requires immediate intervention?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'sata', 'A nurse is caring for a patient at 38 weeks gestation with severe preeclampsia (BP 168/112). Which interventions are priority? (Select all that apply)', '[{"id":"a","text":"Administer magnesium sulfate IV as ordered"},{"id":"b","text":"Maintain a quiet, low-stimulation environment"},{"id":"c","text":"Monitor reflexes, LOC, and respiratory rate hourly"},{"id":"d","text":"Encourage ambulation in the hallway to lower BP"},{"id":"e","text":"Keep calcium gluconate at bedside"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Severe preeclampsia: mag sulfate prevents seizures (eclampsia), low-stimulation prevents seizure triggers, close monitoring of mag toxicity signs (absent reflexes, RR <12, LOC), calcium gluconate is the mag sulfate antidote. Ambulation is contraindicated — bedrest.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient at 38 weeks gestation with severe preeclampsia (BP 168/112). Which interventions are priority? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A breastfeeding mother asks the nurse when her milk will "come in" after birth. What is the most accurate response?', '[{"id":"a","text":"Within 2–4 hours of delivery"},{"id":"b","text":"Day 3–5 postpartum"},{"id":"c","text":"At 2 weeks postpartum"},{"id":"d","text":"Only after the placenta is delivered"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Colostrum (thick, yellow, antibody-rich) is produced for the first 2–3 days. Mature breast milk transitions in at 3–5 days postpartum. Teach the mother this is normal and that colostrum alone adequately nourishes the newborn in the first days.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A breastfeeding mother asks the nurse when her milk will "come in" after birth. What is the most accurate response?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A nurse assesses a postpartum patient 1 hour after delivery and finds the fundus boggy and displaced to the right. What is the priority action?', '[{"id":"a","text":"Document and continue monitoring"},{"id":"b","text":"Have the patient void and then reassess the fundus"},{"id":"c","text":"Perform firm uterine massage immediately"},{"id":"d","text":"Administer oxytocin (Pitocin) as ordered"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A full bladder displaces the uterus (usually to the right) and prevents proper contraction, causing uterine atony and bleeding. First: have the patient void or catheterize, then reassess. A boggy fundus = uterine atony = risk of postpartum hemorrhage.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse assesses a postpartum patient 1 hour after delivery and finds the fundus boggy and displaced to the right. What is the priority action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A newborn is born at 35 weeks gestation. Which finding is most expected compared to a term newborn?', '[{"id":"a","text":"Strong suck and swallow reflex"},{"id":"b","text":"Lanugo covering most of the body"},{"id":"c","text":"Abundant vernix only in skin folds"},{"id":"d","text":"Well-developed plantar creases"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Lanugo (fine hair covering) is abundant in preterm infants and diminishes as gestation advances. At 35 weeks: poor suck/swallow (weak), abundant lanugo, decreased vernix (it builds up then decreases), and few plantar creases (those develop in the 3rd trimester).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A newborn is born at 35 weeks gestation. Which finding is most expected compared to a term newborn?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'sata', 'A nurse is caring for a newborn receiving phototherapy for jaundice. Which interventions are appropriate? (Select all that apply)', '[{"id":"a","text":"Cover the newborn''s eyes with opaque shields"},{"id":"b","text":"Remove eye shields during feedings for bonding"},{"id":"c","text":"Monitor temperature frequently"},{"id":"d","text":"Apply lotion to skin to prevent drying"},{"id":"e","text":"Increase feeding frequency to promote bilirubin excretion"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Phototherapy: opaque eye shields protect retinas, remove during feedings for parent bonding, frequent temp monitoring (lights cause hyperthermia/hypothermia), frequent feedings promote GI transit and bilirubin excretion. Do NOT apply lotions — increases risk of burns under lights.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a newborn receiving phototherapy for jaundice. Which interventions are appropriate? (Select all that apply)');
