-- Safe seed Yingoh NCLEX question bank, part 13.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A nurse is assessing a patient for dehydration. Which findings are consistent? (Select all that apply)', '[{"id":"a","text":"Decreased skin turgor (tenting over sternum or hand)"},{"id":"b","text":"Urine specific gravity 1.030"},{"id":"c","text":"Bounding peripheral pulses"},{"id":"d","text":"Dry mucous membranes"},{"id":"e","text":"Orthostatic hypotension"}]'::jsonb, '{"ids":["a","b","d","e"]}'::jsonb, 'Dehydration: poor skin turgor, concentrated urine (SG >1.025), dry mucous membranes, orthostatic hypotension (BP drop >20 systolic when standing), weak/thready pulse (not bounding). Bounding pulses indicate fluid overload or high cardiac output states.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is assessing a patient for dehydration. Which findings are consistent? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with a colostomy is concerned because the stoma output is liquid. The nurse assesses that the colostomy is located in the ascending colon. What is the most appropriate response?', '[{"id":"a","text":"\"Liquid output is abnormal — report this to your surgeon.\""},{"id":"b","text":"\"Liquid output is expected from a right-sided (ascending) colostomy because absorption is incomplete.\""},{"id":"c","text":"\"Increase dietary fiber to solidify the stool output.\""},{"id":"d","text":"\"Irrigate the colostomy daily to regulate output.\""}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Colostomy output consistency depends on location: right-sided (ascending) = liquid (less water absorbed), transverse = semi-formed, sigmoid/descending = formed. Liquid output from a right colostomy is expected and normal. Irrigation is only appropriate for sigmoid colostomies.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with a colostomy is concerned because the stoma output is liquid. The nurse assesses that the colostomy is located in the ascending colon. What is the most appropriate response?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient takes St. John''s Wort for mild depression and is prescribed indinavir for HIV. What is the nurse''s concern?', '[{"id":"a","text":"St. John''s Wort has no significant drug interactions"},{"id":"b","text":"St. John''s Wort induces CYP3A4, reducing indinavir plasma levels and risk of treatment failure"},{"id":"c","text":"Combining these causes serotonin syndrome"},{"id":"d","text":"St. John''s Wort enhances indinavir causing toxicity"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'St. John''s Wort is a potent CYP3A4 inducer — it increases drug metabolism and reduces plasma levels of many medications including antiretrovirals (indinavir, efavirenz), oral contraceptives, warfarin, and cyclosporine. For HIV medications, this can cause sub-therapeutic levels and treatment failure/resistance.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient takes St. John''s Wort for mild depression and is prescribed indinavir for HIV. What is the nurse''s concern?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'sata', 'A nurse is preparing to perform a time-out before a surgical procedure. Which elements are confirmed? (Select all that apply)', '[{"id":"a","text":"Patient identity using two identifiers"},{"id":"b","text":"Correct surgical site marked by the surgeon"},{"id":"c","text":"Procedure to be performed"},{"id":"d","text":"Patient''s insurance coverage"},{"id":"e","text":"Required equipment and implants are available"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Universal Protocol time-out (Joint Commission): correct patient identity, correct procedure, correct surgical site (marked), positioning, required implants/equipment available. All team members must agree before proceeding. Insurance information is administrative and is NOT part of the clinical time-out.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preparing to perform a time-out before a surgical procedure. Which elements are confirmed? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'mcq', 'A nurse is triaging 4 patients. Which patient has the highest priority?', '[{"id":"a","text":"A 45-year-old with a migraine, vomiting, and pain 8/10"},{"id":"b","text":"A 70-year-old with new onset slurred speech and right-sided arm weakness that started 45 minutes ago"},{"id":"c","text":"A 30-year-old with an ankle sprain, swelling, and pain 5/10"},{"id":"d","text":"A 55-year-old with a chronic back pain exacerbation"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Sudden onset neurological symptoms (slurred speech, unilateral weakness) within 4.5 hours = possible ischemic stroke — time-critical. "Time is brain" — every minute of delay kills neurons. Activate the stroke team immediately. FAST: Face drooping, Arm weakness, Speech difficulty, Time to call. The 30-min window for CT and 60-min window for tPA are benchmarks.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is triaging 4 patients. Which patient has the highest priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'sata', 'A nurse is teaching a pregnant patient about danger signs requiring immediate medical evaluation. Which symptoms are included? (Select all that apply)', '[{"id":"a","text":"Sudden severe headache with visual changes"},{"id":"b","text":"Decreased fetal movement"},{"id":"c","text":"Vaginal bleeding at any gestational age"},{"id":"d","text":"Mild ankle swelling at 36 weeks"},{"id":"e","text":"Severe upper right quadrant pain"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Obstetric danger signs: severe headache + visual changes (preeclampsia/eclampsia), decreased fetal movement (possible fetal distress), any vaginal bleeding, RUQ pain (HELLP syndrome/hepatic capsule distension). Mild ankle edema at 36 weeks is normal. "HELLP": Hemolysis, Elevated Liver enzymes, Low Platelets.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is teaching a pregnant patient about danger signs requiring immediate medical evaluation. Which symptoms are included? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A nurse is performing a pain assessment on a 3-year-old who cannot verbalize pain. Which scale is most appropriate?', '[{"id":"a","text":"Numeric Rating Scale (0–10)"},{"id":"b","text":"FLACC scale (Face, Legs, Activity, Cry, Consolability)"},{"id":"c","text":"Visual Analog Scale"},{"id":"d","text":"McGill Pain Questionnaire"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'FLACC is a behavioral pain assessment tool validated for non-verbal children 2 months–7 years. It scores 5 behavioral indicators (0–2 each, total 0–10). Numeric scales require verbal/cognitive ability (appropriate for ≥6–8 years). The Wong-Baker FACES scale is appropriate for ≥3 years who can point to a face.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is performing a pain assessment on a 3-year-old who cannot verbalize pain. Which scale is most appropriate?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient receives tissue plasminogen activator (tPA) for DVT. Which finding 1 hour later requires immediate provider notification?', '[{"id":"a","text":"A mild headache rated 2/10"},{"id":"b","text":"Blood oozing from IV sites"},{"id":"c","text":"Sudden confusion and left-sided arm weakness"},{"id":"d","text":"Temperature increase of 0.5°C"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'New neurological deficits (confusion, focal weakness) after thrombolytic therapy (tPA) = intracranial hemorrhage until proven otherwise — a life-threatening emergency. Stop the tPA infusion immediately and notify the provider. Order emergent CT scan. IV site oozing is expected and managed with pressure.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient receives tissue plasminogen activator (tPA) for DVT. Which finding 1 hour later requires immediate provider notification?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient on continuous cardiac monitoring develops a rhythm with no discernible P waves, an irregularly irregular pattern, and a ventricular rate of 110 bpm. The nurse identifies this as:', '[{"id":"a","text":"Atrial flutter with 2:1 conduction"},{"id":"b","text":"Atrial fibrillation with rapid ventricular response"},{"id":"c","text":"Third-degree (complete) heart block"},{"id":"d","text":"Ventricular tachycardia"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Atrial fibrillation: chaotic atrial activity (no true P waves, "fibrillatory baseline"), irregularly irregular R-R intervals, variable ventricular rate. A-fib with RVR (rate >100) requires rate control (beta-blockers, calcium channel blockers, digoxin). Anticoagulation is needed for stroke prevention.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient on continuous cardiac monitoring develops a rhythm with no discernible P waves, an irregularly irregular pattern, and a ventricular rate of 110 bpm. The nurse identifies this as:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A patient requires wound irrigation with a large volume of saline. Which equipment provides the most effective irrigation pressure to remove debris?', '[{"id":"a","text":"Gentle pour from a saline bottle"},{"id":"b","text":"Bulb syringe irrigation"},{"id":"c","text":"35 mL syringe with a 19-gauge angiocath at 8–12 psi"},{"id":"d","text":"Whirlpool hydrotherapy"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Effective wound irrigation requires 8–12 psi to remove bacteria and debris without damaging tissue. A 35 mL syringe with a 19-gauge angiocath delivers approximately 8–10 psi. Bulb syringes deliver <1 psi (inadequate). High-pressure devices (>15 psi) can drive bacteria into tissue.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient requires wound irrigation with a large volume of saline. Which equipment provides the most effective irrigation pressure to remove debris?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'sata', 'A nurse is caring for a patient with Type 1 DM admitted for hypoglycemia unawareness. Which teaching points are essential for discharge? (Select all that apply)', '[{"id":"a","text":"Check blood glucose more frequently, especially before driving"},{"id":"b","text":"Keep fast-acting glucose sources available at all times"},{"id":"c","text":"Wear or carry medical ID indicating diabetic status"},{"id":"d","text":"Eat only when blood glucose is above 180 mg/dL"},{"id":"e","text":"Teach family members how to administer glucagon"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Hypoglycemia unawareness (absent warning symptoms): frequent glucose monitoring (CGM strongly recommended), always carry glucose (15g fast carbs), medical ID for emergencies, family glucagon training for severe episodes. Eating only when glucose >180 encourages chronic hyperglycemia — incorrect. Target pre-meal glucose per provider plan.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with Type 1 DM admitted for hypoglycemia unawareness. Which teaching points are essential for discharge? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient with dementia becomes agitated and combative every evening (sundowning). Which nursing intervention is most effective?', '[{"id":"a","text":"Administer haloperidol routinely at 1600 hours to prevent agitation"},{"id":"b","text":"Restrain the patient during evening hours for safety"},{"id":"c","text":"Increase meaningful activity in the afternoon and ensure adequate lighting in the evening"},{"id":"d","text":"Move the patient to a quiet room with no stimulation"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Sundowning management: non-pharmacological first. Meaningful daytime activity (prevents boredom and sleep during day), adequate evening lighting (reduces shadows that trigger confusion), consistent routine, calming music, caregiver presence. Routine antipsychotics increase fall risk and are not first-line. Restraints worsen agitation.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with dementia becomes agitated and combative every evening (sundowning). Which nursing intervention is most effective?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A 2-year-old child is seen for a well-child visit. The nurse notes the child says 50 words and uses 2-word phrases. What is the nurse''s assessment?', '[{"id":"a","text":"Delayed — refer for speech evaluation immediately"},{"id":"b","text":"Advanced — most 2-year-olds say fewer words"},{"id":"c","text":"Within normal limits — 50+ words and 2-word combinations are expected at age 2"},{"id":"d","text":"Slightly delayed — typical 2-year-olds use only 10–15 words"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Expected language development at 24 months: vocabulary of ≥50 words, 2-word phrases ("more milk"), and beginning of short sentences. Red flags at 2 years: <50 words, no 2-word phrases, loss of previously acquired language (regression). This child''s development is appropriate.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 2-year-old child is seen for a well-child visit. The nurse notes the child says 50 words and uses 2-word phrases. What is the nurse''s assessment?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse is discharging a patient who speaks limited English. The patient''s adult child offers to interpret. What is the most appropriate action?', '[{"id":"a","text":"Allow the family member to interpret — it is more comfortable for the patient"},{"id":"b","text":"Use a professional medical interpreter (in-person, video, or phone)"},{"id":"c","text":"Speak slowly and use gestures to convey information"},{"id":"d","text":"Provide only written discharge instructions in English"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Federal law (Title VI, Civil Rights Act) requires healthcare facilities receiving federal funding to provide meaningful access to language services. Family interpreters risk inaccuracy, omission, and HIPAA violations. A certified medical interpreter ensures accuracy and maintains confidentiality. Ask the patient if they prefer a professional interpreter.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is discharging a patient who speaks limited English. The patient''s adult child offers to interpret. What is the most appropriate action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient with bipolar disorder taking lithium has the following levels on two consecutive days: 1.8 mEq/L and 2.3 mEq/L. The patient has coarse tremors and is confused. What is the priority action?', '[{"id":"a","text":"Administer the next lithium dose and recheck levels in 12 hours"},{"id":"b","text":"Hold lithium, notify provider, prepare for IV hydration and monitoring"},{"id":"c","text":"Administer activated charcoal for detoxification"},{"id":"d","text":"Increase fluid intake to 2 L orally and recheck level tomorrow"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Lithium toxicity: level 2.3 mEq/L with coarse tremor and confusion = severe toxicity (>2.0 mEq/L). Immediately: HOLD lithium, notify provider, IV saline (promotes renal lithium excretion), monitor neurological status, cardiac rhythm. Severe cases require hemodialysis. There is NO specific antidote for lithium.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with bipolar disorder taking lithium has the following levels on two consecutive days: 1.8 mEq/L and 2.3 mEq/L. The patient has coarse tremors and is confused. What is the priority action?');
