-- Safe seed Yingoh NCLEX question bank, part 14.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with heart failure has jugular venous distension (JVD), 3+ pitting edema, and bilateral crackles. Which position is most therapeutic?', '[{"id":"a","text":"Flat supine to maximize preload"},{"id":"b","text":"Trendelenburg to increase venous return"},{"id":"c","text":"High Fowler''s (90 degrees) with legs dependent"},{"id":"d","text":"Left lateral with head of bed elevated 15 degrees"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'High Fowler''s with legs dependent (dangling): reduces preload (fluid shifts from central to peripheral circulation), decreases pulmonary congestion, improves diaphragmatic excursion and breathing. Supine and Trendelenburg increase venous return (increase preload) — contraindicated in fluid overload. This is the first-line non-pharmacologic intervention for acute decompensated heart failure.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with heart failure has jugular venous distension (JVD), 3+ pitting edema, and bilateral crackles. Which position is most therapeutic?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A nurse is assessing a 2-hour-old newborn. Which finding requires immediate intervention?', '[{"id":"a","text":"Respiratory rate of 48 breaths per minute"},{"id":"b","text":"Acrocyanosis (blue hands and feet)"},{"id":"c","text":"Central cyanosis (blue lips and trunk)"},{"id":"d","text":"Molding of the skull from vaginal delivery"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Central cyanosis (lips, tongue, trunk) in a newborn indicates systemic hypoxia — possible congenital heart defect, respiratory distress, or sepsis. This is NEVER normal and requires immediate assessment and intervention. Acrocyanosis (peripheral) is normal in the first 24–48 hours. RR 40–60 and molding are normal newborn findings.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is assessing a 2-hour-old newborn. Which finding requires immediate intervention?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse is administering a blood transfusion. Which action is most important to ensure patient safety?', '[{"id":"a","text":"Prime the tubing with dextrose solution before connecting blood"},{"id":"b","text":"Verify blood product with another licensed nurse using two patient identifiers and blood bank information"},{"id":"c","text":"Administer the entire unit as quickly as possible to prevent bacterial growth"},{"id":"d","text":"Start the transfusion and return to check in 2 hours"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Blood transfusion safety: two licensed nurses verify the blood product at the bedside — patient name, DOB, MRN, blood type, expiration date, and unit number match between the patient, wristband, and blood bank label. Fatal hemolytic transfusion reactions occur from wrong-patient errors. Use only 0.9% NS (never dextrose — causes hemolysis).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is administering a blood transfusion. Which action is most important to ensure patient safety?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'mcq', 'A nurse is reviewing morning labs for a patient on day 3 of broad-spectrum antibiotics: WBC 24,000, temperature 39.4°C, new onset diarrhea (5–6 loose stools), crampy abdominal pain. Which pathogen is most likely responsible?', '[{"id":"a","text":"Staphylococcus aureus (MRSA)"},{"id":"b","text":"Clostridioides difficile (C. diff)"},{"id":"c","text":"Pseudomonas aeruginosa"},{"id":"d","text":"Candida albicans"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'C. difficile colitis: antibiotic use (disrupts normal flora), new-onset diarrhea (≥3 loose stools/day), crampy pain, leukocytosis, fever. Contact precautions immediately. Diagnosis: C. diff toxin assay. Treatment: oral vancomycin or fidaxomicin. Metronidazole is second-line. ALWAYS wash hands with soap and water (alcohol-based sanitizer does not kill C. diff spores).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is reviewing morning labs for a patient on day 3 of broad-spectrum antibiotics: WBC 24,000, temperature 39.4°C, new onset diarrhea (5–6 loose stools), crampy abdominal pain. Which pathogen is most likely responsible?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'sata', 'A nurse is caring for a patient taking warfarin. Which substances significantly increase the anticoagulant effect and bleeding risk? (Select all that apply)', '[{"id":"a","text":"Aspirin"},{"id":"b","text":"Cranberry juice in large amounts"},{"id":"c","text":"Vitamin K-rich foods (kale, spinach)"},{"id":"d","text":"Fluconazole (antifungal)"},{"id":"e","text":"Rifampin (antibiotic)"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Warfarin interactions: aspirin (adds antiplatelet effect), cranberry juice (inhibits CYP2C9, increases warfarin), fluconazole (inhibits CYP2C9, significantly increases INR). Vitamin K-rich foods DECREASE anticoagulant effect. Rifampin INDUCES CYP enzymes, DECREASING warfarin effect. Consistency of Vit K intake is key — not elimination.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient taking warfarin. Which substances significantly increase the anticoagulant effect and bleeding risk? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with acute gout asks why they should increase fluid intake. The nurse explains:', '[{"id":"a","text":"Fluid dilutes uric acid in the blood and promotes renal excretion"},{"id":"b","text":"Fluids increase uric acid production to stimulate excretion"},{"id":"c","text":"Dehydration has no effect on gout attacks"},{"id":"d","text":"Fluid intake prevents the need for allopurinol"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Gout results from hyperuricemia and urate crystal deposition in joints. Increased fluid intake (2–3 L/day) dilutes uric acid and promotes renal excretion, reducing serum urate levels. Also avoid: purine-rich foods (organ meats, shellfish), alcohol (especially beer), and dehydration. Colchicine is for acute attacks; allopurinol for prevention.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with acute gout asks why they should increase fluid intake. The nurse explains:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A nurse is floated to a unit outside their usual practice area. Which action best protects patient safety?', '[{"id":"a","text":"Accept any patient assignment without question to demonstrate flexibility"},{"id":"b","text":"Communicate competency limitations to the charge nurse and only accept assignments within the nurse''s skill level"},{"id":"c","text":"Refuse the float assignment entirely"},{"id":"d","text":"Handle all assigned patients independently without asking for help to avoid appearing incompetent"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Nurses practice within their scope and competency. When floated, communicate honestly about skill limitations (e.g., "I''m not experienced with PICC line care"). Request appropriate orientation and avoid taking high-acuity patients outside your expertise. This protects patients AND the nurse legally. Silence about incompetence is negligence.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is floated to a unit outside their usual practice area. Which action best protects patient safety?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A patient is in active labor and requests an epidural. Before administering the epidural, the nurse should:', '[{"id":"a","text":"Obtain verbal consent only since it is an emergency"},{"id":"b","text":"Pre-hydrate with IV fluids, verify platelet count, and obtain informed consent"},{"id":"c","text":"Administer the epidural immediately to reduce maternal stress"},{"id":"d","text":"Check fetal station — epidurals are contraindicated before 8 cm dilation"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Pre-epidural: IV fluid bolus (reduces hypotension risk — common side effect), informed consent, platelet count >80,000 (thrombocytopenia contraindication), baseline FHR documentation. Epidurals are NOT contraindicated at any cervical dilation — this is a common misconception. Maternal hypotension post-epidural → fetal bradycardia; left lateral positioning helps.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is in active labor and requests an epidural. Before administering the epidural, the nurse should:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'mcq', 'A nurse is caring for a patient post-kidney transplant on day 5. Labs show: creatinine 3.8 (up from 1.2 yesterday), decreased urine output, weight gain of 2 kg, and the patient reports tenderness over the graft site. Which complication is most likely?', '[{"id":"a","text":"Acute rejection of the transplanted kidney"},{"id":"b","text":"Calcineurin inhibitor nephrotoxicity"},{"id":"c","text":"Urinary tract infection"},{"id":"d","text":"Fluid overload from IV therapy"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Acute rejection (days to months post-transplant): rising creatinine, decreased urine output, weight gain (fluid retention), fever, hypertension, and graft site tenderness. Treatment: high-dose IV corticosteroids, anti-thymocyte globulin. Calcineurin inhibitor toxicity causes gradual rising creatinine without graft tenderness. Notify provider immediately — early treatment preserves the graft.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient post-kidney transplant on day 5. Labs show: creatinine 3.8 (up from 1.2 yesterday), decreased urine output, weight gain of 2 kg, and the patient reports tenderness over the graft site. Which complication is most likely?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'highlight', 'A nurse reviews the following nursing note for a 72-year-old client admitted for a right hip replacement performed this morning. Highlight all findings that require immediate follow-up.', '[]'::jsonb, '{"ids":[]}'::jsonb, 'Immediate follow-up required: SpO₂ 88% on room air (below acceptable threshold, risk of hypoxia), urine output of 15 mL/hr for 3 hours (oliguria, less than 0.5 mL/kg/hr — indicates hypovolemia or AKI), and right calf pain and warmth (classic signs of DVT, a major post-op complication of hip replacement). Temperature 38.1°C and mild incision oozing are expected within first 24 hours post-op and require monitoring, not immediate intervention. HR 88 is within normal limits for a post-op client.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse reviews the following nursing note for a 72-year-old client admitted for a right hip replacement performed this morning. Highlight all findings that require immediate follow-up.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Cardiovascular', 'mcq', 'A client admitted with an acute MI has BP 88/50 mmHg, HR 118 bpm, cool clammy skin, and urine output 15 mL/hr. Which complication does the nurse suspect?', '[{"id":"a","text":"Hypertensive urgency"},{"id":"b","text":"Cardiogenic shock"},{"id":"c","text":"Pulmonary embolism"},{"id":"d","text":"Pericardial tamponade"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Cardiogenic shock: post-MI hypotension + tachycardia + cool/clammy skin + oliguria = the heart cannot pump. Tamponade = Beck''s triad (JVD, muffled sounds, hypotension). PE = pleuritic chest pain + hypoxia.', 'Triad after MI: hypotension + tachy + cold/clammy + low urine = cardiogenic shock. The pump has failed. Peripheral circulation shuts down to preserve core organs.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client admitted with an acute MI has BP 88/50 mmHg, HR 118 bpm, cool clammy skin, and urine output 15 mL/hr. Which complication does the nurse suspect?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Cardiovascular', 'sata', 'A client has left-sided heart failure. Which assessment findings does the nurse expect? Select all that apply.', '[{"id":"a","text":"Bilateral crackles in the lung bases"},{"id":"b","text":"Jugular venous distension"},{"id":"c","text":"Pink frothy sputum"},{"id":"d","text":"Dependent pitting ankle edema"},{"id":"e","text":"S3 gallop heart sound"}]'::jsonb, '{"ids":["a","c","e"]}'::jsonb, 'Left HF backs up into the lungs: crackles, pink frothy sputum (severe pulmonary edema), S3 gallop. JVD and peripheral edema = right HF (backs up into systemic circulation).', 'Left = Lungs. Right = Rest of body. Apply this spatial rule instantly. Left HF = pulmonary. Right HF = peripheral/systemic.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client has left-sided heart failure. Which assessment findings does the nurse expect? Select all that apply.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Cardiovascular', 'mcq', 'A client on IV heparin for DVT has an aPTT of 120 seconds. What is the nurse''s priority action?', '[{"id":"a","text":"Increase the infusion rate"},{"id":"b","text":"Administer protamine sulfate"},{"id":"c","text":"Contact the provider to adjust the rate"},{"id":"d","text":"Repeat the aPTT in 2 hours without changes"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Therapeutic aPTT: 60–100 seconds. At 120 the client is supratherapeutic — high bleeding risk. Notify the provider. Protamine reverses heparin but needs an order. Never independently adjust an infusion.', 'Therapeutic aPTT = 1.5–2.5x normal = 60–100 sec. Above 100 = too much heparin → notify provider. Never adjust an IV infusion without an order.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client on IV heparin for DVT has an aPTT of 120 seconds. What is the nurse''s priority action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Respiratory', 'mcq', 'A client with COPD has ABG: pH 7.32, PaCO₂ 58 mmHg, HCO₃ 28 mEq/L. The nurse interprets this as:', '[{"id":"a","text":"Respiratory alkalosis with metabolic compensation"},{"id":"b","text":"Metabolic acidosis, uncompensated"},{"id":"c","text":"Respiratory acidosis with partial metabolic compensation"},{"id":"d","text":"Mixed respiratory and metabolic alkalosis"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'pH 7.32 = acidosis. PaCO₂ 58 = elevated → respiratory cause. HCO₃ 28 = elevated → kidneys compensating. pH still abnormal = partial compensation. Classic COPD CO₂ retention.', 'ROME: Respiratory Opposite — pH low + PaCO₂ high = respiratory acidosis. Then HCO₃ elevated = kidney compensation. pH still abnormal = partial.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with COPD has ABG: pH 7.32, PaCO₂ 58 mmHg, HCO₃ 28 mEq/L. The nurse interprets this as:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Respiratory', 'sata', 'A client is placed on airborne precautions. Which actions does the nurse take? Select all that apply.', '[{"id":"a","text":"Place the client in a negative pressure room"},{"id":"b","text":"Wear a surgical mask when entering"},{"id":"c","text":"Wear an N95 respirator before entering"},{"id":"d","text":"Keep the client door closed at all times"},{"id":"e","text":"Client wears a surgical mask during transport"}]'::jsonb, '{"ids":["a","c","d","e"]}'::jsonb, 'Airborne (TB, measles, varicella): negative pressure room, door closed, N95 for staff (NOT surgical mask), client wears surgical mask during transport.', 'Airborne = N95 + negative pressure room. Surgical mask wrong-answer trap: it is used for DROPLET, not airborne. N95 filters tiny airborne particles — surgical masks do not.', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A client is placed on airborne precautions. Which actions does the nurse take? Select all that apply.');
