-- Safe seed Yingoh NCLEX question bank, part 17.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Renal and Urinary', 'mcq', 'A client with acute kidney injury has urine output of 18 mL/hr for 4 hours. Which action is priority?', '[{"id":"a","text":"Encourage high-protein foods"},{"id":"b","text":"Notify the provider"},{"id":"c","text":"Restrict all fluids permanently"},{"id":"d","text":"Document as normal"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Urine output below 30 mL/hr indicates oliguria and may reflect worsening renal perfusion or injury. Prompt follow-up is needed.', 'Minimum urine output is 30 mL/hr. Below that is a perfusion problem until proven otherwise.', 'Physiological Integrity', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with acute kidney injury has urine output of 18 mL/hr for 4 hours. Which action is priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Endocrine', 'mcq', 'A client with diabetes is shaky, diaphoretic, and has blood glucose 48 mg/dL. The client is awake and able to swallow. What should the nurse give first?', '[{"id":"a","text":"Regular insulin"},{"id":"b","text":"15 g fast-acting carbohydrate"},{"id":"c","text":"A high-fat meal"},{"id":"d","text":"Metformin"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'An awake client with hypoglycemia should receive 15 g of rapid carbohydrate, then glucose is rechecked. Insulin would worsen hypoglycemia.', 'Conscious hypoglycemia = oral fast sugar. Unconscious = IV dextrose or glucagon.', 'Physiological Integrity', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with diabetes is shaky, diaphoretic, and has blood glucose 48 mg/dL. The client is awake and able to swallow. What should the nurse give first?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Endocrine', 'mcq', 'Which finding in a client with syndrome of inappropriate antidiuretic hormone secretion is expected?', '[{"id":"a","text":"Serum sodium 124 mEq/L"},{"id":"b","text":"Dilute urine"},{"id":"c","text":"Signs of dehydration"},{"id":"d","text":"Increased urine output"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'SIADH causes water retention and dilutional hyponatremia. Urine is concentrated and output is often low.', 'SIADH = too much water held in the body, so sodium becomes diluted.', 'Physiological Integrity', 'Analyze Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'Which finding in a client with syndrome of inappropriate antidiuretic hormone secretion is expected?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Endocrine', 'mcq', 'A client after thyroidectomy reports tingling around the mouth and muscle cramps. Which complication does the nurse suspect?', '[{"id":"a","text":"Hypocalcemia"},{"id":"b","text":"Hyperglycemia"},{"id":"c","text":"Fluid overload"},{"id":"d","text":"Thyroid storm"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Parathyroid injury after thyroidectomy can cause hypocalcemia, producing tingling, cramps, tetany, or positive Chvostek/Trousseau signs.', 'After thyroid surgery, tingling and cramps point to low calcium from parathyroid disturbance.', 'Physiological Integrity', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'A client after thyroidectomy reports tingling around the mouth and muscle cramps. Which complication does the nurse suspect?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Gastrointestinal', 'mcq', 'A client with cirrhosis becomes confused and has asterixis. Which lab value is most relevant?', '[{"id":"a","text":"Ammonia"},{"id":"b","text":"Troponin"},{"id":"c","text":"Creatine kinase"},{"id":"d","text":"Potassium"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Confusion and asterixis in cirrhosis suggest hepatic encephalopathy from elevated ammonia.', 'Liver failure plus mental status changes equals ammonia until proven otherwise.', 'Physiological Integrity', 'Analyze Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with cirrhosis becomes confused and has asterixis. Which lab value is most relevant?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Gastrointestinal', 'mcq', 'Which diet instruction is best for a client with dumping syndrome after gastric surgery?', '[{"id":"a","text":"Drink large amounts of fluid with meals"},{"id":"b","text":"Lie down after meals"},{"id":"c","text":"Eat high-sugar foods between meals"},{"id":"d","text":"Eat three large meals daily"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Lying down after meals can slow gastric emptying. Clients should eat small frequent meals, avoid high sugar, and limit fluids with meals.', 'Dumping syndrome = food moves too fast. Slow it with small meals, low sugar, and lying down after eating.', 'Physiological Integrity', 'Generate Solutions', 'published'
where not exists (select 1 from public.questions where prompt = 'Which diet instruction is best for a client with dumping syndrome after gastric surgery?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Gastrointestinal', 'mcq', 'A client with acute pancreatitis has severe epigastric pain radiating to the back. Which order should the nurse question?', '[{"id":"a","text":"NPO status"},{"id":"b","text":"IV opioid analgesic"},{"id":"c","text":"Low-fat solid meal tray"},{"id":"d","text":"IV fluids"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Oral intake stimulates pancreatic enzyme secretion and can worsen acute pancreatitis. NPO, fluids, and pain control are expected.', 'Pancreatitis care rests the pancreas: NPO, fluids, pain control.', 'Physiological Integrity', 'Evaluate Outcomes', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with acute pancreatitis has severe epigastric pain radiating to the back. Which order should the nurse question?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Neurological', 'mcq', 'A client has a sudden severe headache, vomiting, and decreased level of consciousness. Which condition is most concerning?', '[{"id":"a","text":"Migraine"},{"id":"b","text":"Subarachnoid hemorrhage"},{"id":"c","text":"Sinus infection"},{"id":"d","text":"Tension headache"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'A sudden severe headache with vomiting and decreased consciousness suggests hemorrhagic stroke/subarachnoid hemorrhage and requires emergency care.', 'Worst headache plus neuro decline is bleeding until proven otherwise.', 'Physiological Integrity', 'Prioritize Hypotheses', 'published'
where not exists (select 1 from public.questions where prompt = 'A client has a sudden severe headache, vomiting, and decreased level of consciousness. Which condition is most concerning?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Neurological', 'mcq', 'A client with myasthenia gravis has increasing difficulty swallowing and shallow respirations. What is the priority?', '[{"id":"a","text":"Offer a full meal"},{"id":"b","text":"Assess respiratory status and prepare for ventilatory support"},{"id":"c","text":"Encourage ambulation"},{"id":"d","text":"Delay medications until bedtime"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Myasthenic crisis can cause respiratory muscle weakness and airway compromise. Breathing is the priority.', 'Weakness disorders become emergencies when they affect swallowing or breathing.', 'Physiological Integrity', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with myasthenia gravis has increasing difficulty swallowing and shallow respirations. What is the priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Neurological', 'mcq', 'Which action is appropriate for a client after a tonic-clonic seizure ends?', '[{"id":"a","text":"Place the client in a side-lying position"},{"id":"b","text":"Insert a padded tongue blade"},{"id":"c","text":"Restrain the arms"},{"id":"d","text":"Give oral fluids immediately"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'After a seizure, side-lying positioning helps maintain airway and allows secretions to drain. Nothing should be placed in the mouth.', 'Seizure care after: airway, side-lying, assess, document. Nothing in the mouth.', 'Safe and Effective Care Environment', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'Which action is appropriate for a client after a tonic-clonic seizure ends?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Acid-Base Balance', 'mcq', 'A client has pH 7.50, PaCO2 30 mmHg, HCO3 24 mEq/L. How should the nurse interpret this?', '[{"id":"a","text":"Respiratory alkalosis"},{"id":"b","text":"Respiratory acidosis"},{"id":"c","text":"Metabolic acidosis"},{"id":"d","text":"Metabolic alkalosis"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'High pH indicates alkalosis. Low PaCO2 causes alkalosis by blowing off acid. HCO3 is normal, so this is respiratory alkalosis.', 'ROME: respiratory problems move opposite. pH high, CO2 low = respiratory alkalosis.', 'Physiological Integrity', 'Analyze Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'A client has pH 7.50, PaCO2 30 mmHg, HCO3 24 mEq/L. How should the nurse interpret this?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Acid-Base Balance', 'mcq', 'Which client is at highest risk for metabolic alkalosis?', '[{"id":"a","text":"Client with prolonged vomiting"},{"id":"b","text":"Client with diabetic ketoacidosis"},{"id":"c","text":"Client with renal failure and acidosis"},{"id":"d","text":"Client with severe diarrhea"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Vomiting causes loss of gastric acid, leading to metabolic alkalosis. DKA, renal failure, and diarrhea commonly cause metabolic acidosis.', 'Lose acid from the stomach, become alkalotic. Lose bicarbonate from diarrhea, become acidotic.', 'Physiological Integrity', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'Which client is at highest risk for metabolic alkalosis?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Acid-Base Balance', 'mcq', 'A client with anxiety is hyperventilating. Which ABG change is expected first?', '[{"id":"a","text":"PaCO2 decreases"},{"id":"b","text":"HCO3 increases immediately"},{"id":"c","text":"pH decreases"},{"id":"d","text":"Potassium rises sharply"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Hyperventilation blows off CO2, causing PaCO2 to fall and pH to rise. Renal compensation takes longer.', 'Breathing changes CO2 quickly. Kidneys change bicarbonate slowly.', 'Physiological Integrity', 'Analyze Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with anxiety is hyperventilating. Which ABG change is expected first?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Nutrition', 'mcq', 'Which meal choice is best for a client with iron-deficiency anemia?', '[{"id":"a","text":"Spinach salad with grilled chicken and orange slices"},{"id":"b","text":"White rice with tea"},{"id":"c","text":"Plain gelatin and cola"},{"id":"d","text":"Toast with coffee"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Iron-rich foods with vitamin C improve iron absorption. Tea and coffee can reduce absorption.', 'Pair iron with vitamin C. Avoid tea/coffee around iron.', 'Health Promotion and Maintenance', 'Generate Solutions', 'published'
where not exists (select 1 from public.questions where prompt = 'Which meal choice is best for a client with iron-deficiency anemia?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Nutrition', 'mcq', 'A client receiving total parenteral nutrition suddenly has diaphoresis and tremors after the bag runs empty. What should the nurse suspect?', '[{"id":"a","text":"Rebound hypoglycemia"},{"id":"b","text":"Fluid overload"},{"id":"c","text":"Hypercalcemia"},{"id":"d","text":"Allergic reaction"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Abrupt discontinuation of TPN can cause rebound hypoglycemia because the client was receiving high glucose continuously.', 'Never stop TPN abruptly. If interrupted, hang dextrose per policy.', 'Physiological Integrity', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'A client receiving total parenteral nutrition suddenly has diaphoresis and tremors after the bag runs empty. What should the nurse suspect?');
