-- Safe seed Yingoh NCLEX question bank, part 9.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient is admitted voluntarily for depression. They now want to leave against medical advice. The nurse understands that:', '[{"id":"a","text":"Voluntary patients can be held involuntarily if they pose a danger to themselves"},{"id":"b","text":"Voluntary patients have the absolute right to leave at any time"},{"id":"c","text":"The patient must be physically restrained until a psychiatrist arrives"},{"id":"d","text":"The patient cannot leave until 72 hours of treatment are complete"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Voluntary patients generally have the right to leave. However, if the patient is assessed as a danger to self or others, the nurse can initiate the process for involuntary detention (5150/hold) while arranging psychiatric evaluation. This overrides the right to leave.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is admitted voluntarily for depression. They now want to leave against medical advice. The nurse understands that:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'sata', 'A nurse is caring for a patient with borderline personality disorder. Which behaviors does the nurse expect? (Select all that apply)', '[{"id":"a","text":"Unstable intense relationships — idealization followed by devaluation"},{"id":"b","text":"Self-mutilation or suicidal gestures"},{"id":"c","text":"Auditory hallucinations telling the patient to harm others"},{"id":"d","text":"Intense fear of abandonment"},{"id":"e","text":"Impulsive behaviors (spending, substance use, self-harm)"}]'::jsonb, '{"ids":["a","b","d","e"]}'::jsonb, 'BPD hallmarks: splitting (idealize/devalue), fear of abandonment, identity disturbance, impulsivity, self-harm, emotional dysregulation. Auditory command hallucinations are characteristic of psychotic disorders (schizophrenia), not BPD. Set consistent limits and use dialectical behavior therapy (DBT) approach.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with borderline personality disorder. Which behaviors does the nurse expect? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient is brought to the ER agitated, diaphoretic, with a temperature of 40.2°C, HR 128, clonus, and has taken an antidepressant overdose in combination with tramadol. The nurse suspects:', '[{"id":"a","text":"Neuroleptic malignant syndrome"},{"id":"b","text":"Serotonin syndrome"},{"id":"c","text":"Anticholinergic toxidrome"},{"id":"d","text":"Opioid toxicity"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Serotonin syndrome triad: altered mental status + autonomic instability (tachycardia, hyperthermia, diaphoresis) + neuromuscular abnormalities (clonus, hyperreflexia, tremor). Caused by serotonergic drug combinations (SSRI + tramadol, linezolid, etc.). NMS also causes hyperthermia but has "lead-pipe" rigidity and bradykinesia, not clonus.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is brought to the ER agitated, diaphoretic, with a temperature of 40.2°C, HR 128, clonus, and has taken an antidepressant overdose in combination with tramadol. The nurse suspects:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A nurse is using motivational interviewing with a patient who is ambivalent about quitting smoking. Which response best demonstrates this technique?', '[{"id":"a","text":"\"Smoking causes lung cancer. You really should quit for your health.\""},{"id":"b","text":"\"What concerns you most about your smoking right now?\""},{"id":"c","text":"\"Have you tried nicotine patches? Many patients find them helpful.\""},{"id":"d","text":"\"On a scale of 1–10, how ready are you to quit smoking today?\""}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Motivational interviewing (MI) uses open-ended questions to explore the patient''s own concerns and motivations (elicit-provide-elicit). Option B evokes the patient''s perspective. Option D uses a readiness ruler (also MI), but B is more open-ended and exploratory. Direct advice ("you should quit") is confrontational and reduces autonomy.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is using motivational interviewing with a patient who is ambivalent about quitting smoking. Which response best demonstrates this technique?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A nurse is assessing a patient at 10 weeks gestation. Fundal height measurement is appropriate starting at which gestational age?', '[{"id":"a","text":"10 weeks"},{"id":"b","text":"20 weeks"},{"id":"c","text":"28 weeks"},{"id":"d","text":"32 weeks"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Fundal height (McDonald''s rule) measurement begins at 20 weeks gestation. After 20 weeks, fundal height in centimeters approximates gestational age in weeks (±2 cm). Before 20 weeks, the uterus is too small to measure reliably via tape measure from symphysis pubis to fundus.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is assessing a patient at 10 weeks gestation. Fundal height measurement is appropriate starting at which gestational age?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A nurse is caring for a patient in the second stage of labor. The patient is pushing effectively. Which fetal heart rate finding requires immediate action?', '[{"id":"a","text":"FHR 145 bpm between contractions"},{"id":"b","text":"Accelerations with fetal movement"},{"id":"c","text":"Prolonged deceleration to 80 bpm for 3 minutes"},{"id":"d","text":"Variable decelerations with rapid recovery to baseline"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'A prolonged deceleration (>2 min, <10 min) to 80 bpm for 3 minutes indicates significant fetal compromise. Interventions: stop pushing, reposition, O2 by mask, IV bolus, notify provider — possible emergency delivery. Accelerations are reassuring. Brief variable decelerations with quick recovery are common in second stage.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient in the second stage of labor. The patient is pushing effectively. Which fetal heart rate finding requires immediate action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'sata', 'A nurse is caring for a patient with gestational diabetes. Which teaching points are correct? (Select all that apply)', '[{"id":"a","text":"Monitor blood glucose before meals and at bedtime"},{"id":"b","text":"Gestational diabetes resolves immediately after delivery in all cases"},{"id":"c","text":"The newborn is at risk for hypoglycemia after birth"},{"id":"d","text":"Dietary modifications are the first-line management"},{"id":"e","text":"A postpartum glucose tolerance test is recommended at 6–12 weeks"}]'::jsonb, '{"ids":["a","c","d","e"]}'::jsonb, 'GDM teaching: monitor glucose regularly, diet/exercise first-line, newborn monitored for hypoglycemia (fetal hyperinsulinism), and postpartum GTT at 6–12 weeks (GDM increases lifetime risk of type 2 diabetes — does NOT always resolve; 50% develop T2DM within 10 years).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with gestational diabetes. Which teaching points are correct? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A newborn has a positive Ortolani and Barlow test. What does this indicate?', '[{"id":"a","text":"Normal hip development"},{"id":"b","text":"Developmental dysplasia of the hip (DDH)"},{"id":"c","text":"Talipes equinovarus (clubfoot)"},{"id":"d","text":"Cerebral palsy"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Ortolani (reduction "clunk") and Barlow (dislocation with pressure) tests assess for hip instability/DDH. A positive finding requires urgent orthopedic referral. DDH is more common in females, first-born, breech presentation. Treatment: Pavlik harness if diagnosed early.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A newborn has a positive Ortolani and Barlow test. What does this indicate?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A nurse is caring for a patient who delivered 30 minutes ago and lost an estimated 600 mL of blood. Vital signs are stable. What is the correct classification of this blood loss?', '[{"id":"a","text":"Normal blood loss for vaginal delivery"},{"id":"b","text":"Primary postpartum hemorrhage — requires immediate intervention"},{"id":"c","text":"Secondary postpartum hemorrhage"},{"id":"d","text":"Expected blood loss for a cesarean section"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Primary PPH: ≥500 mL blood loss within 24 hours of vaginal delivery (≥1000 mL for cesarean). 600 mL qualifies as primary PPH. Assess the "4 T''s": Tone (atony), Tissue (retained placenta), Trauma (lacerations), Thrombin (coagulopathy). Most common cause is uterine atony.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient who delivered 30 minutes ago and lost an estimated 600 mL of blood. Vital signs are stable. What is the correct classification of this blood loss?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A 5-year-old with acute lymphocytic leukemia (ALL) has a platelet count of 18,000/mm³. Which activity should the nurse avoid?', '[{"id":"a","text":"Reading books quietly in bed"},{"id":"b","text":"Taking an oral temperature"},{"id":"c","text":"Administering rectal suppositories"},{"id":"d","text":"Age-appropriate play therapy"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'With thrombocytopenia (platelets <20,000), avoid any invasive rectal procedures — suppositories, enemas, rectal temperatures — due to severe bleeding risk. Also avoid IM injections, aspirin, flossing, contact sports. Use only oral or axillary temperatures.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 5-year-old with acute lymphocytic leukemia (ALL) has a platelet count of 18,000/mm³. Which activity should the nurse avoid?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A nurse is caring for a child with epiglottitis. Which action is the priority?', '[{"id":"a","text":"Examine the throat using a tongue depressor to assess swelling"},{"id":"b","text":"Keep the child calm and allow the parent to hold the child in a comfortable position"},{"id":"c","text":"Administer nebulized racemic epinephrine immediately"},{"id":"d","text":"Place a nasogastric tube for medication administration"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Epiglottitis is a life-threatening emergency. NEVER examine the throat or use a tongue depressor — this can cause complete airway obstruction by triggering laryngospasm. Keep the child calm (crying worsens obstruction). Allow parent holding, minimize invasive procedures. Airway equipment and anesthesia should be immediately available.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a child with epiglottitis. Which action is the priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'sata', 'A child with nephrotic syndrome is admitted. Which findings does the nurse expect? (Select all that apply)', '[{"id":"a","text":"Massive proteinuria (frothy urine)"},{"id":"b","text":"Periorbital and generalized edema"},{"id":"c","text":"Hypoalbuminemia"},{"id":"d","text":"Hematuria and hypertension"},{"id":"e","text":"Hyperlipidemia and lipiduria"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Nephrotic syndrome: massive proteinuria (>3.5g/day → frothy urine), hypoalbuminemia (protein lost), edema (low oncotic pressure), hyperlipidemia (liver compensates by making lipids). Hematuria and hypertension are hallmarks of NEPHRITIC syndrome, not nephrotic.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A child with nephrotic syndrome is admitted. Which findings does the nurse expect? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A 3-year-old ingests an unknown household chemical. What is the nurse''s initial action?', '[{"id":"a","text":"Induce vomiting with syrup of ipecac"},{"id":"b","text":"Call Poison Control (1-800-222-1222) immediately"},{"id":"c","text":"Give the child milk to dilute the chemical"},{"id":"d","text":"Administer activated charcoal at home before arriving at the hospital"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Call Poison Control immediately — they provide specific guidance based on the substance. Ipecac is NO LONGER recommended (risk of aspiration, delayed decontamination). Do not give milk (may enhance absorption of some substances). Activated charcoal requires medical supervision.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 3-year-old ingests an unknown household chemical. What is the nurse''s initial action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A nurse is assessing a 6-week-old infant who is vomiting forcefully after every feeding. The vomit is non-bilious and projectile. The nurse palpates an olive-shaped mass in the epigastric area. What condition does the nurse suspect?', '[{"id":"a","text":"Intussusception"},{"id":"b","text":"Hirschsprung''s disease"},{"id":"c","text":"Pyloric stenosis"},{"id":"d","text":"Gastroesophageal reflux"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Pyloric stenosis: 2–6 week old infant, projectile non-bilious vomiting after feeding, palpable "olive" mass in right epigastrium, hungry after vomiting. Leads to metabolic alkalosis with hypokalemia. Treatment: surgical pyloromyotomy. Intussusception: "currant jelly" stool, colicky pain, sausage-shaped mass.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is assessing a 6-week-old infant who is vomiting forcefully after every feeding. The vomit is non-bilious and projectile. The nurse palpates an olive-shaped mass in the epigastric area. What condition does the nurse suspect?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse is doing medication reconciliation on admission. Which is the most complete and accurate source for obtaining the medication history?', '[{"id":"a","text":"The patient''s family member"},{"id":"b","text":"The emergency department physician''s notes"},{"id":"c","text":"A brown bag review of all medications the patient brings from home"},{"id":"d","text":"The patient''s pharmacy records only"}]'::jsonb, '{"ids":["c"]}'::jsonb, '"Brown bag" medication review (patient brings all medications) is the most complete source — includes prescriptions, OTCs, supplements, and herbals that patients often omit when asked verbally. Discrepancies trigger clarification. Pharmacy records miss PRN and recently changed medications.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is doing medication reconciliation on admission. Which is the most complete and accurate source for obtaining the medication history?');
