-- Safe seed Yingoh NCLEX question bank, part 2.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A nurse assesses a patient 24 hours post-thyroidectomy. Which finding requires the most immediate action?', '[{"id":"a","text":"Serum calcium 7.2 mg/dL with positive Trousseau sign"},{"id":"b","text":"Hoarseness when speaking"},{"id":"c","text":"Incision pain rated 5/10"},{"id":"d","text":"Temperature of 37.8°C"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Post-thyroidectomy hypocalcemia from parathyroid damage can progress to tetany, laryngospasm, and seizures. Calcium 7.2 mg/dL with positive Trousseau sign requires immediate IV calcium gluconate.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse assesses a patient 24 hours post-thyroidectomy. Which finding requires the most immediate action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'sata', 'A patient is admitted after a suicide attempt. Which nursing interventions are appropriate? (Select all that apply)', '[{"id":"a","text":"Remove all potentially harmful items from the environment"},{"id":"b","text":"Maintain 1:1 supervision at all times"},{"id":"c","text":"Ask the patient directly about suicidal ideation"},{"id":"d","text":"Avoid discussing the attempt to prevent distress"},{"id":"e","text":"Establish a therapeutic nurse–patient relationship"},{"id":"f","text":"Document the patient''s statements and behaviors"}]'::jsonb, '{"ids":["a","b","c","e","f"]}'::jsonb, 'Suicide precautions include environmental safety, 1:1 supervision, and direct assessment — asking directly does NOT increase risk. Therapeutic relationship and thorough documentation are essential. Avoiding discussion (D) is incorrect.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is admitted after a suicide attempt. Which nursing interventions are appropriate? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'sata', 'A nurse is preparing to administer heparin subcutaneously. Which actions should the nurse take? (Select all that apply)', '[{"id":"a","text":"Verify the aPTT before administration"},{"id":"b","text":"Administer in the abdomen, rotating sites"},{"id":"c","text":"Massage the injection site after administration"},{"id":"d","text":"Have protamine sulfate available as an antidote"},{"id":"e","text":"Use a 1-inch 21-gauge needle"},{"id":"f","text":"Monitor platelet count for HIT"}]'::jsonb, '{"ids":["a","b","d","f"]}'::jsonb, 'Monitor aPTT; rotate abdominal sites; keep protamine sulfate available; monitor platelets for HIT (day 5–10). Do NOT massage (causes bruising). Use 5/8-inch, 25–27 gauge needle for subcutaneous injection.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preparing to administer heparin subcutaneously. Which actions should the nurse take? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with a bowel obstruction has an NG tube on low intermittent suction. Labs: Na 138, K 2.9, Cl 88, HCO3 32. Which acid-base imbalance is present?', '[{"id":"a","text":"Metabolic acidosis"},{"id":"b","text":"Metabolic alkalosis"},{"id":"c","text":"Respiratory acidosis"},{"id":"d","text":"Respiratory alkalosis"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'NG suction removes gastric HCl, causing loss of H+ and Cl−. Result: elevated HCO3 (32), low Cl (88), and hypokalemia (2.9). This is metabolic alkalosis.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with a bowel obstruction has an NG tube on low intermittent suction. Labs: Na 138, K 2.9, Cl 88, HCO3 32. Which acid-base imbalance is present?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'sata', 'A nurse is delegating tasks to unlicensed assistive personnel (UAP). Which tasks can be safely delegated? (Select all that apply)', '[{"id":"a","text":"Measuring and recording urinary output"},{"id":"b","text":"Assessing a patient who reports increased pain"},{"id":"c","text":"Obtaining vital signs on a stable patient"},{"id":"d","text":"Teaching a patient how to use an incentive spirometer"},{"id":"e","text":"Reporting urine output of 20 mL/hr to the nurse"},{"id":"f","text":"Ambulating a post-stroke patient independently"}]'::jsonb, '{"ids":["a","c","e"]}'::jsonb, 'UAPs can measure and record I&O, obtain vital signs on stable patients, and report objective measurements. Assessment, teaching, and ambulating post-stroke patients require nursing judgment and cannot be delegated.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is delegating tasks to unlicensed assistive personnel (UAP). Which tasks can be safely delegated? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'bow_tie', 'A 68-year-old client is admitted to the ICU with a 3-day history of productive cough, fever of 39.2°C, and confusion. Oxygen saturation is 88% on room air. BP is 88/54 mmHg. The client''s family reports he lives alone and has type 2 diabetes and COPD. ABGs: pH 7.28, PaCO2 52, HCO3 22. WBC 22,000. Chest X-ray shows bilateral infiltrates.', '[]'::jsonb, '{"ids":[]}'::jsonb, 'This client meets criteria for septic shock secondary to pneumonia with concurrent respiratory acidosis and hypoxemia. Priority actions: administer supplemental oxygen and position HOB 30–45°, initiate broad-spectrum antibiotics within the first hour, and establish IV access for fluid resuscitation. Key parameters to monitor: oxygen saturation and ABGs (respiratory status), blood pressure and MAP (hemodynamic stability), and blood cultures (source identification). Avoid vasopressors before adequate fluid resuscitation.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A 68-year-old client is admitted to the ICU with a 3-day history of productive cough, fever of 39.2°C, and confusion. Oxygen saturation is 88% on room air. BP is 88/54 mmHg. The client''s family reports he lives alone and has type 2 diabetes and COPD. ABGs: pH 7.28, PaCO2 52, HCO3 22. WBC 22,000. Chest X-ray shows bilateral infiltrates.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'matrix', 'A nurse is caring for a 54-year-old client admitted for acute decompensated heart failure. Vitals: BP 156/98, HR 108, RR 26, SpO₂ 90%, temp 37.1°C. The client has 3+ pitting edema in bilateral lower extremities, JVD, and audible crackles bilaterally. Orders include: IV furosemide 40 mg, continuous cardiac monitoring, daily weights, sodium restriction 2g/day, and supplemental oxygen. For each nursing intervention, indicate whether it is Indicated, Contraindicated, or Not Applicable.', '[]'::jsonb, '{"ids":[]}'::jsonb, 'In acute decompensated HF: IV furosemide reduces fluid overload (Indicated); positioning HOB 45° reduces preload and improves oxygenation (Indicated); daily weights monitor fluid status (Indicated). Encouraging oral fluid intake worsens fluid overload (Contraindicated). Sodium restriction is already ordered and would be managed by dietary team, not a direct nursing intervention in this context (Not Applicable as a nursing action; it is a dietary order). Ambulating in the acute decompensated phase with SpO₂ 90% is Contraindicated.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a 54-year-old client admitted for acute decompensated heart failure. Vitals: BP 156/98, HR 108, RR 26, SpO₂ 90%, temp 37.1°C. The client has 3+ pitting edema in bilateral lower extremities, JVD, and audible crackles bilaterally. Orders include: IV furosemide 40 mg, continuous cardiac monitoring, daily weights, sodium restriction 2g/day, and supplemental oxygen. For each nursing intervention, indicate whether it is Indicated, Contraindicated, or Not Applicable.');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'ordered_response', 'A nurse receives a shift report on a client who had an emergency appendectomy 6 hours ago. On assessment, the nurse notes sudden onset of tachycardia (HR 128), diaphoresis, abdominal rigidity, and temperature 38.9°C. The client states the pain has changed from 4/10 to 9/10 and feels "different." Place the following nursing actions in the correct order of priority (1 = first action, 5 = last action).', '[{"id":"a","text":"Notify the surgeon immediately of assessment findings"},{"id":"b","text":"Assess the client''s airway, breathing, and circulation"},{"id":"c","text":"Obtain vital signs and oxygen saturation"},{"id":"d","text":"Prepare the client for potential return to the OR"},{"id":"e","text":"Document all findings and interventions in the medical record"}]'::jsonb, '{"ids":[],"order":["b","c","a","d","e"]}'::jsonb, 'Use the nursing process and ABCs. First: assess ABCs (B) — immediate threat identification. Second: obtain full vital signs and SpO₂ to quantify deterioration (C). Third: notify the surgeon with complete SBAR — these findings suggest peritonitis from anastomotic leak (A). Fourth: prepare client for surgical intervention which may be imminent (D). Finally: document all findings and the chain of communication (E).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse receives a shift report on a client who had an emergency appendectomy 6 hours ago. On assessment, the nurse notes sudden onset of tachycardia (HR 128), diaphoresis, abdominal rigidity, and temperature 38.9°C. The client states the pain has changed from 4/10 to 9/10 and feels "different." Place the following nursing actions in the correct order of priority (1 = first action, 5 = last action).');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is administering warfarin. Which laboratory value should be monitored to evaluate therapeutic effectiveness?', '[{"id":"a","text":"aPTT"},{"id":"b","text":"PT/INR"},{"id":"c","text":"Platelet count"},{"id":"d","text":"Bleeding time"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Warfarin (a vitamin K antagonist) effectiveness is monitored with PT/INR. Therapeutic INR for most indications is 2.0–3.0. aPTT monitors heparin therapy.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is administering warfarin. Which laboratory value should be monitored to evaluate therapeutic effectiveness?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient is receiving IV vancomycin. The nurse notices flushing, erythema, and hypotension developing during the infusion. What is the priority action?', '[{"id":"a","text":"Administer diphenhydramine IV push"},{"id":"b","text":"Stop the infusion and notify the provider"},{"id":"c","text":"Slow the infusion rate and monitor"},{"id":"d","text":"Obtain a vancomycin trough level"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Red Man Syndrome is a rate-related reaction to vancomycin, not a true allergy. Slowing the infusion rate (over 60–90 min) resolves symptoms. It is not an IgE-mediated hypersensitivity reaction requiring stopping the drug.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is receiving IV vancomycin. The nurse notices flushing, erythema, and hypotension developing during the infusion. What is the priority action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'sata', 'A nurse is teaching a patient newly prescribed atorvastatin. Which instructions should be included? (Select all that apply)', '[{"id":"a","text":"Report unexplained muscle pain or weakness"},{"id":"b","text":"Avoid grapefruit juice"},{"id":"c","text":"Take the medication in the morning for best effect"},{"id":"d","text":"Monitor LFTs periodically"},{"id":"e","text":"Expect a rash during the first week"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'Statins can cause myopathy/rhabdomyolysis (report muscle pain). Grapefruit inhibits CYP3A4 increasing statin levels. Liver function should be monitored. Statins are given at any time of day (not only morning). A rash is not expected.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is teaching a patient newly prescribed atorvastatin. Which instructions should be included? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is preparing to give morphine 4 mg IV to a post-op patient. Respirations are 10/min. What should the nurse do first?', '[{"id":"a","text":"Give the medication as prescribed — pain increases respiratory rate"},{"id":"b","text":"Withhold the medication and notify the provider"},{"id":"c","text":"Give half the dose and reassess in 15 minutes"},{"id":"d","text":"Administer oxygen before giving morphine"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Opioids are withheld when respirations are <12/min due to the risk of respiratory depression. The nurse should hold the dose and notify the provider immediately. Naloxone (Narcan) should be available.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preparing to give morphine 4 mg IV to a post-op patient. Respirations are 10/min. What should the nurse do first?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'Which electrolyte imbalance increases a patient''s risk of digoxin toxicity?', '[{"id":"a","text":"Hypernatremia"},{"id":"b","text":"Hypokalemia"},{"id":"c","text":"Hypermagnesemia"},{"id":"d","text":"Hypercalcemia"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Hypokalemia potentiates digoxin toxicity because potassium and digoxin compete for the same receptor (Na-K ATPase pump). Low potassium increases digoxin binding and effect. Monitor and maintain K+ 3.5–5.0 mEq/L.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'Which electrolyte imbalance increases a patient''s risk of digoxin toxicity?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'sata', 'A nurse is caring for a patient receiving heparin infusion. Which findings indicate possible heparin-induced thrombocytopenia (HIT)? (Select all that apply)', '[{"id":"a","text":"Platelet count dropped from 280,000 to 90,000 on day 8 of therapy"},{"id":"b","text":"New thrombus formation despite heparin therapy"},{"id":"c","text":"aPTT supratherapeutic at 130 seconds"},{"id":"d","text":"Skin necrosis at heparin injection sites"},{"id":"e","text":"Serum potassium of 3.2 mEq/L"}]'::jsonb, '{"ids":["a","b","d"]}'::jsonb, 'HIT: >50% platelet drop on days 5–14, paradoxical new clotting, and skin necrosis at injection sites. Supratherapeutic aPTT reflects dosing, not HIT. Hypokalemia is unrelated. If HIT suspected, stop heparin immediately.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient receiving heparin infusion. Which findings indicate possible heparin-induced thrombocytopenia (HIT)? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient with a penicillin allergy (hives) is prescribed cefazolin. What is the most appropriate nursing action?', '[{"id":"a","text":"Administer as prescribed — cephalosporins are unrelated to penicillin"},{"id":"b","text":"Hold the medication and verify the order with the provider"},{"id":"c","text":"Give a test dose and observe for 30 minutes"},{"id":"d","text":"Substitute oral amoxicillin instead"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'There is a small but real cross-reactivity between penicillins and cephalosporins (~1–2%). A penicillin allergy warrants clarification before administering a cephalosporin. The nurse should hold and verify. Amoxicillin is also a penicillin.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with a penicillin allergy (hives) is prescribed cefazolin. What is the most appropriate nursing action?');
