-- Batch 09: medication-safety catalog. Each row generates seven review-gated items.
select public.seed_structured_concept(
  'expansion-batch-09', slug, 'Pharmacology', medicine, cue, action, teaching,
  danger, wrong1, wrong2, wrong3, 'Pharmacological and Parenteral Therapies'
)
from (values
('hydralazine','IV hydralazine therapy','severe hypertension requiring controlled reduction','Monitor blood pressure and heart rate closely and give at the prescribed rate','Rise slowly and report chest pain, palpitations, faintness, or severe headache','Marked hypotension with reflex tachycardia and chest pain','Give repeated doses without reassessment','Lower pressure to normal immediately','Encourage unassisted walking'),
('clonidine','clonidine therapy','chronic hypertension treated with a central alpha agonist','Check pressure and pulse and assess sedation and adherence','Do not stop abruptly because rebound hypertension can occur','Severe headache and blood pressure 226/120 after abrupt withdrawal','Stop suddenly when pressure improves','Double a missed dose','Combine with alcohol for sleep'),
('verapamil','verapamil therapy','rate control in a client with cardiac disease','Check heart rate, blood pressure, conduction, heart failure signs, and interactions','Report fainting, slow pulse, swelling, or worsening breathlessness','Complete heart block with hypotension','Give with severe bradycardia','Crush extended-release tablets','Ignore new pulmonary edema'),
('adenosine','rapid IV adenosine','stable regular narrow-complex supraventricular tachycardia','Give as a rapid IV push followed immediately by flush with continuous ECG monitoring','A brief flushing or chest sensation may occur; report persistent symptoms','Persistent instability or ventricular rhythm after administration','Infuse slowly over thirty minutes','Give without rhythm monitoring','Use for an irregular wide-complex rhythm without evaluation'),
('atropine','atropine for symptomatic bradycardia','bradycardia with hypotension and poor perfusion','Give the prescribed dose while preparing pacing if ineffective','Report severe vision change, urinary retention, confusion, or palpitations','Worsening instability despite atropine','Delay pacing preparation','Give for asymptomatic normal-rate rhythm','Ignore acute confusion'),
('norepinephrine','norepinephrine vasopressor therapy','septic shock with persistent hypotension after fluid resuscitation','Use central access when possible, titrate to perfusion target, and monitor the site and extremities','Report burning or swelling at the infusion site and new chest or limb pain','Extravasation with pale cool tissue or progressive digital ischemia','Infuse without blood-pressure monitoring','Give through infiltrated access','Stop abruptly during profound shock'),
('dobutamine','dobutamine in low-output heart failure','poor cardiac output with adequate pressure and congestion','Monitor rhythm, blood pressure, urine output, perfusion, and response continuously','Report chest pain, palpitations, or worsening breathlessness','New rapid ventricular dysrhythmia with ischemic pain','Give as an unmonitored IV push','Use despite uncontrolled tachydysrhythmia','Increase for chest pain without assessment'),
('sacubitril-valsartan','sacubitril-valsartan therapy','heart failure treatment after prior ACE inhibitor use','Verify the required ACE-inhibitor washout and monitor pressure, potassium, renal function, and angioedema','Avoid potassium salt substitutes and seek emergency care for facial or tongue swelling','Angioedema with airway difficulty','Give simultaneously with an ACE inhibitor','Use during pregnancy','Ignore rising potassium'),
('sglt2-inhibitor','SGLT2 inhibitor therapy','diabetes or heart failure treatment with dapagliflozin','Monitor renal status, hydration, genital infection, and ketoacidosis symptoms','Maintain hydration and report nausea, abdominal pain, rapid breathing, or genital symptoms even with normal glucose','Euglycemic ketoacidosis with rapid breathing and positive ketones','Continue during severe dehydration without review','Ignore genital infection','Use extra doses after high-carbohydrate meals'),
('glargine','insulin glargine therapy','basal insulin prescribed once daily','Verify the dose and administer consistently without mixing it with other insulin','Take at the same time daily and treat hypoglycemia promptly','Nocturnal hypoglycemia with seizure','Mix with NPH in one syringe','Use as the only treatment for acute ketoacidosis','Skip whenever a meal is missed'),
('iv-regular-insulin','IV regular insulin infusion','diabetic ketoacidosis after initial fluid resuscitation','Verify potassium, use an infusion pump, and monitor glucose and electrolytes frequently','Expect frequent blood tests and report weakness or palpitations','Potassium falls to 2.8 mEq/L during infusion','Start before checking potassium','Give IV glargine instead','Stop all insulin as soon as glucose reaches 250'),
('glucagon','emergency glucagon','severe hypoglycemia in a client unable to swallow','Administer by the prescribed route, position to prevent aspiration, and give carbohydrate after awakening','Teach household members administration and call emergency services after use','Failure to awaken or recurrent hypoglycemia after glucagon','Give oral liquid during unconsciousness','Leave the client supine while vomiting','Skip follow-up glucose'),
('propylthiouracil','propylthiouracil therapy','hyperthyroidism requiring antithyroid treatment','Monitor thyroid response, liver injury, and agranulocytosis symptoms','Report fever, sore throat, jaundice, dark urine, or severe abdominal symptoms immediately','Fever with neutropenia or acute liver failure','Stop and restart doses randomly','Double doses for palpitations','Ignore sore throat'),
('desmopressin','desmopressin therapy','central diabetes insipidus with excessive dilute urine','Monitor sodium, fluid balance, weight, and urine response','Use only prescribed fluid intake and report headache, confusion, or sudden weight gain','Hyponatremic seizure after excessive water intake','Encourage unlimited free water','Give repeated extra doses for thirst','Ignore rapid weight gain'),
('octreotide','octreotide therapy','variceal bleeding or severe secretory diarrhea','Monitor glucose, heart rate, abdominal symptoms, and gallbladder effects','Report severe abdominal pain, faintness, or major glucose changes','Bradycardia with severe abdominal pain and hyperglycemia','Give without glucose monitoring','Ignore gallstone symptoms','Stop during active variceal bleeding without an order'),
('omeprazole','proton-pump inhibitor therapy','long-term acid suppression','Confirm indication and monitor for interactions and long-term magnesium, infection, and bone risks','Take as directed before meals and report persistent diarrhea or swallowing difficulty','Severe watery diarrhea with hypomagnesemic dysrhythmia','Crush delayed-release granules incorrectly','Continue indefinitely without indication review','Use to mask gastrointestinal bleeding'),
('sucralfate','sucralfate therapy','mucosal protection for ulcer disease','Give on an empty stomach and separate it from interacting medicines','Follow timing instructions and maintain fluids and fiber if appropriate','Bezoar or severe constipation with obstruction signs','Give simultaneously with every oral medicine','Mix into tube feeding without review','Use as emergency treatment for perforation'),
('ondansetron','ondansetron therapy','antiemetic use in a client with cardiac risk','Review QT risk, electrolytes, bowel function, and interacting serotonergic medicines','Report fainting, palpitations, severe constipation, agitation, or fever','QT prolongation with syncope and ventricular dysrhythmia','Give repeated doses despite prolonged QT','Ignore absent bowel sounds','Combine interacting drugs without review'),
('metoclopramide','metoclopramide therapy','gastroparesis treatment','Assess bowel obstruction risk and monitor for acute dystonia and tardive dyskinesia','Report involuntary facial or body movements, severe restlessness, or muscle spasm','Oculogyric crisis with neck spasm','Give during mechanical obstruction','Continue after tardive movements','Use indefinitely without reassessment'),
('flumazenil','flumazenil administration','benzodiazepine reversal in a high-risk client','Assess seizure and mixed-overdose risk and maintain airway and continuous monitoring','Re-sedation can occur and emergency observation remains necessary','Generalized seizure after reversal in a dependent client','Give routinely for unknown mixed overdose','Leave immediately after awakening','Assume reversal replaces ventilation'),
('acetylcysteine','acetylcysteine for acetaminophen overdose','a potentially toxic ingestion with uncertain timing','Obtain the needed level and liver tests and begin antidote promptly when indicated','Complete the full antidote protocol and report vomiting, rash, or breathing difficulty','Acute liver failure or anaphylactoid reaction during infusion','Delay until jaundice develops','Stop after one dose','Use activated charcoal days later as the only treatment'),
('calcium-gluconate','IV calcium gluconate','symptomatic hypocalcemia or membrane stabilization in hyperkalemia','Use a secure IV line, cardiac monitoring, and the prescribed rate','Report burning at the site, chest discomfort, or palpitations','Extravasation with tissue injury or severe bradycardia','Give rapidly without ECG monitoring','Mix with incompatible bicarbonate solution','Treat hyperkalemia without addressing potassium'),
('sodium-bicarbonate','IV sodium bicarbonate therapy','a specific severe acid-base or toxicologic indication','Verify the indication and monitor pH, sodium, potassium, volume, and ventilation','This medicine is not routine for every acidosis and requires repeated laboratory monitoring','Worsening alkalosis, hypernatremia, and fluid overload','Give routinely for respiratory acidosis','Mix with incompatible calcium solution','Ignore falling potassium'),
('ipratropium','inhaled ipratropium therapy','bronchodilator treatment for COPD','Assess breathing and anticholinergic effects and use correct device technique','Avoid spraying into the eyes and report urinary retention or eye pain','Acute eye pain with halos or severe urinary retention','Use as the sole rescue for life-threatening asthma','Spray directly into open eyes','Swallow nebulizer solution'),
('montelukast','montelukast therapy','leukotriene-modifier treatment for asthma','Clarify that it is maintenance therapy and monitor neuropsychiatric symptoms','Continue controller use as prescribed and report mood, behavior, or suicidal changes','New suicidal thoughts after starting therapy','Use for immediate rescue during status asthmaticus','Stop other controllers without instruction','Ignore major behavior change'),
('ceftriaxone','ceftriaxone therapy','parenteral cephalosporin treatment','Review allergy history, cultures, biliary effects, diarrhea, and neonatal calcium risks','Complete therapy and report breathing difficulty or severe persistent diarrhea','Anaphylaxis or suspected C. difficile colitis','Mix with IV calcium in a neonate','Ignore immediate wheezing','Stop after fever improves'),
('doxycycline','doxycycline therapy','tetracycline treatment','Review pregnancy, age, photosensitivity, esophageal injury, and mineral interactions','Take with water, remain upright, use sun protection, and separate from antacids or iron','Severe swallowing pain or blistering photosensitivity','Take immediately before lying down','Combine with antacid','Use during pregnancy without review'),
('metronidazole','metronidazole therapy','anaerobic or protozoal infection treatment','Review alcohol use, neurologic symptoms, liver status, and warfarin interaction','Avoid alcohol during therapy and for the instructed period afterward','Severe neuropathy, seizure, or major anticoagulant bleeding','Drink alcohol to reduce nausea','Ignore new numbness','Double warfarin without monitoring'),
('acyclovir','IV acyclovir therapy','severe herpesvirus infection','Ensure appropriate hydration, renal dosing, and IV-site and kidney monitoring','Maintain prescribed hydration and report reduced urine, confusion, or infusion pain','Crystalluria with acute kidney injury and neurotoxicity','Give rapidly without hydration','Ignore rising creatinine','Use an unadjusted dose in renal failure'),
('amphotericin-b','amphotericin B therapy','systemic fungal infection','Premedicate as prescribed and monitor renal function, potassium, magnesium, blood counts, and infusion reaction','Report severe chills, breathing difficulty, reduced urine, or weakness','Anaphylaxis or severe hypokalemia with ventricular dysrhythmia','Infuse without baseline electrolytes','Ignore falling renal function','Give as a rapid IV push'),
('isoniazid','isoniazid therapy','tuberculosis treatment containing isoniazid','Monitor liver injury and neuropathy risk and administer pyridoxine when indicated','Avoid alcohol and report jaundice, dark urine, numbness, or severe fatigue','Acute hepatitis with marked transaminase rise','Stop companion drugs independently','Use alcohol daily','Ignore tingling feet'),
('ethambutol','ethambutol therapy','multidrug tuberculosis treatment containing ethambutol','Obtain baseline and ongoing visual acuity and color-vision assessment','Report blurred vision or red-green color change immediately','New optic neuritis with loss of visual acuity','Continue despite vision loss','Skip eye testing','Use as tuberculosis monotherapy'),
('pyrazinamide','pyrazinamide therapy','multidrug tuberculosis treatment containing pyrazinamide','Monitor liver function, uric acid, and joint symptoms','Report jaundice or severe joint pain and keep all liver tests','Acute hepatitis with severe hyperuricemic arthritis','Drink alcohol during therapy','Ignore jaundice','Stop all drugs for mild expected urine color change')
) as c(slug,medicine,cue,action,teaching,danger,wrong1,wrong2,wrong3);

-- Retained for subsequent held batches.
