-- Safe seed Yingoh NCLEX question bank, part 8.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is about to give levothyroxine (Synthroid) 100 mcg PO. The patient just had breakfast. What should the nurse do?', '[{"id":"a","text":"Give the medication with food to prevent gastric upset"},{"id":"b","text":"Hold the medication and reschedule for 30–60 minutes before the next meal"},{"id":"c","text":"Administer at any time — timing doesn''t affect absorption"},{"id":"d","text":"Crush and mix with juice for easier administration"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Levothyroxine is best absorbed on an empty stomach, 30–60 minutes before breakfast. Food, calcium, iron, and antacids significantly reduce absorption. Always given at the same time each day. If the patient has eaten, give as soon as possible and separate from food by 30–60 minutes.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is about to give levothyroxine (Synthroid) 100 mcg PO. The patient just had breakfast. What should the nurse do?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is caring for a patient receiving tissue plasminogen activator (tPA) for ischemic stroke. Which finding requires the nurse to stop the infusion immediately?', '[{"id":"a","text":"Blood pressure 148/90 mmHg"},{"id":"b","text":"New onset of severe headache, vomiting, and neurological deterioration"},{"id":"c","text":"Mild bruising at the IV site"},{"id":"d","text":"Improvement in facial droop after 30 minutes of infusion"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'During tPA infusion: severe headache + vomiting + neuro deterioration = hemorrhagic transformation (intracerebral bleeding) — STOP infusion immediately and notify provider. tPA carries a risk of potentially fatal intracranial hemorrhage. Mild bruising at IV site is expected. BP 148/90 requires monitoring but not stopping infusion.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient receiving tissue plasminogen activator (tPA) for ischemic stroke. Which finding requires the nurse to stop the infusion immediately?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'sata', 'A nurse is reviewing medications for an elderly patient. Which medications increase fall risk and require extra caution? (Select all that apply)', '[{"id":"a","text":"Lorazepam (benzodiazepine)"},{"id":"b","text":"Metoprolol (beta-blocker)"},{"id":"c","text":"Lisinopril (ACE inhibitor)"},{"id":"d","text":"Diphenhydramine (antihistamine)"},{"id":"e","text":"Oxycodone (opioid)"}]'::jsonb, '{"ids":["a","b","c","d","e"]}'::jsonb, 'All five increase fall risk: benzodiazepines (sedation), beta-blockers (bradycardia, orthostatic hypotension), ACE inhibitors (orthostatic hypotension), diphenhydramine (anticholinergic confusion/sedation — Beers Criteria), and opioids (sedation, dizziness). High-risk fall precautions warranted.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is reviewing medications for an elderly patient. Which medications increase fall risk and require extra caution? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A patient is prescribed sildenafil (Viagra) and asks if it interacts with any of their current medications. The nurse''s greatest concern would be if the patient is also taking:', '[{"id":"a","text":"Aspirin 81 mg daily"},{"id":"b","text":"Isosorbide mononitrate (nitrate)"},{"id":"c","text":"Metformin 500 mg twice daily"},{"id":"d","text":"Lisinopril 10 mg daily"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Sildenafil (PDE-5 inhibitor) + nitrates = CONTRAINDICATED — causes severe, potentially fatal hypotension. Both dilate blood vessels through different mechanisms with additive effect. This is an absolute contraindication. ACE inhibitors and metformin have no significant interaction.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is prescribed sildenafil (Viagra) and asks if it interacts with any of their current medications. The nurse''s greatest concern would be if the patient is also taking:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with chronic obstructive pulmonary disease (COPD) is receiving supplemental oxygen. The nurse understands that oxygen should be titrated to maintain an SpO2 of:', '[{"id":"a","text":"98–100%"},{"id":"b","text":"94–98%"},{"id":"c","text":"88–92%"},{"id":"d","text":"82–85%"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'COPD patients retain CO2 and rely on hypoxic drive (low O2) to breathe. Target SpO2 88–92% — keeping it in this range avoids suppressing the respiratory drive. High-flow oxygen in COPD can cause CO2 retention and respiratory failure (the "COPD oxygen paradox").', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with chronic obstructive pulmonary disease (COPD) is receiving supplemental oxygen. The nurse understands that oxygen should be titrated to maintain an SpO2 of:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A patient is diagnosed with hypothyroidism. Which clinical findings does the nurse expect? (Select all that apply)', '[{"id":"a","text":"Weight gain despite decreased appetite"},{"id":"b","text":"Cold intolerance"},{"id":"c","text":"Constipation"},{"id":"d","text":"Tachycardia and heat intolerance"},{"id":"e","text":"Dry skin, hair loss, and fatigue"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'Hypothyroidism (low thyroid hormone) = slowed metabolism: weight gain, cold intolerance, constipation, dry skin, hair loss, fatigue, bradycardia, depression, myxedema. Tachycardia and heat intolerance are signs of HYPER-thyroidism (excessive thyroid hormone).', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is diagnosed with hypothyroidism. Which clinical findings does the nurse expect? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient is admitted with a hemoglobin of 5.8 g/dL. The patient is symptomatic with dizziness and shortness of breath. What is the priority nursing intervention?', '[{"id":"a","text":"Administer oral iron supplementation"},{"id":"b","text":"Initiate a high-iron diet consultation"},{"id":"c","text":"Prepare for blood transfusion per order"},{"id":"d","text":"Obtain blood cultures before starting iron"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Hgb 5.8 with symptomatic anemia (dizziness, dyspnea) requires transfusion — oral iron takes weeks to raise hemoglobin and cannot correct acute symptomatic anemia. Normal Hgb: women 12–16 g/dL, men 14–18 g/dL. Transfusion is typically considered for symptomatic patients with Hgb <7–8 g/dL.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is admitted with a hemoglobin of 5.8 g/dL. The patient is symptomatic with dizziness and shortness of breath. What is the priority nursing intervention?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with rheumatoid arthritis reports morning stiffness lasting more than 2 hours. What is the most appropriate nursing advice?', '[{"id":"a","text":"Avoid activity until stiffness resolves to prevent joint damage"},{"id":"b","text":"Apply heat before activity and engage in gentle range-of-motion exercises"},{"id":"c","text":"Apply ice packs to all affected joints for 30 minutes"},{"id":"d","text":"Increase doses of ibuprofen to 800 mg every 4 hours"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'For RA morning stiffness: moist heat (warm shower, heating pad) reduces stiffness and increases joint mobility before activity. Gentle ROM exercises maintain function. Ice is used during acute inflammatory flares (swelling/heat). Avoid self-increasing NSAIDs without provider guidance.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with rheumatoid arthritis reports morning stiffness lasting more than 2 hours. What is the most appropriate nursing advice?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient who had a cystectomy and ileal conduit asks the nurse what to expect from the stoma output. What is correct?', '[{"id":"a","text":"Stool-like output will be present for several days"},{"id":"b","text":"Urine drains continuously through the stoma — no ability to control output"},{"id":"c","text":"Output will be intermittent every 4–6 hours"},{"id":"d","text":"The stoma output will not have mucus"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'An ileal conduit (urinary diversion) drains urine continuously — there is no sphincter, so the patient cannot control output. A pouching system is worn at all times. Mucus is present in the urine (normal — from the bowel segment used). Stool is NOT present — the conduit carries urine only.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient who had a cystectomy and ileal conduit asks the nurse what to expect from the stoma output. What is correct?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A patient is diagnosed with neutropenia (ANC <500) after chemotherapy. Which findings require the nurse to notify the provider immediately? (Select all that apply)', '[{"id":"a","text":"Oral temperature of 38.3°C (100.9°F)"},{"id":"b","text":"Alopecia (hair loss)"},{"id":"c","text":"New chills without fever"},{"id":"d","text":"Redness and warmth at the IV site"},{"id":"e","text":"Mild nausea after chemotherapy"}]'::jsonb, '{"ids":["a","c","d"]}'::jsonb, 'In neutropenia: fever ≥38.3°C = febrile neutropenia (oncologic emergency — broad-spectrum antibiotics within 1 hour). Chills without fever can precede bacteremia. IV site infection in an immunocompromised patient is serious. Alopecia and mild nausea are expected chemo side effects.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is diagnosed with neutropenia (ANC <500) after chemotherapy. Which findings require the nurse to notify the provider immediately? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A nurse is caring for a patient 4 hours post-nephrectomy. Which finding is most concerning?', '[{"id":"a","text":"Pain at incision site rated 6/10"},{"id":"b","text":"Urine output of 15 mL in the past hour"},{"id":"c","text":"Serosanguineous drainage on the dressing"},{"id":"d","text":"Temperature of 37.8°C"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Urine output 15 mL/hr is oliguria (<30 mL/hr) after nephrectomy — especially critical because the remaining kidney must now do 100% of filtration. This may indicate hemorrhage, shock, or acute kidney injury. Immediate provider notification is required.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient 4 hours post-nephrectomy. Which finding is most concerning?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient is admitted with Guillain-Barré syndrome. Which assessment is the highest priority?', '[{"id":"a","text":"Lower extremity motor strength and sensation"},{"id":"b","text":"Respiratory rate and tidal volume"},{"id":"c","text":"Cranial nerve function for facial weakness"},{"id":"d","text":"Deep tendon reflexes"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'GBS causes ascending paralysis that can progress to respiratory muscle failure — the primary cause of death. Monitor respiratory rate, tidal volume, vital capacity, and SpO2 frequently. Patients may require mechanical ventilation. Respiratory assessment is the priority life-threatening concern.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is admitted with Guillain-Barré syndrome. Which assessment is the highest priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient with a hip fracture is in Buck''s traction preoperatively. The purpose of this traction is:', '[{"id":"a","text":"To correct the bone fracture permanently"},{"id":"b","text":"To reduce muscle spasm and maintain alignment until surgery"},{"id":"c","text":"To increase blood supply to the fracture site"},{"id":"d","text":"To prevent deep vein thrombosis from immobility"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Buck''s traction (skin traction) is temporary, used preoperatively to reduce pain by decreasing muscle spasm and maintaining femoral alignment. It does NOT reduce or set the fracture — surgery does. Neurovascular checks, skin assessment, and comfort are key nursing priorities.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with a hip fracture is in Buck''s traction preoperatively. The purpose of this traction is:');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A nurse is completing a post-operative assessment on a patient following abdominal surgery. Which findings indicate a return of bowel function? (Select all that apply)', '[{"id":"a","text":"Patient passes flatus"},{"id":"b","text":"Bowel sounds present in all four quadrants"},{"id":"c","text":"Patient has a bowel movement"},{"id":"d","text":"Abdomen is soft and non-distended"},{"id":"e","text":"Patient requests their first meal"}]'::jsonb, '{"ids":["a","b","c"]}'::jsonb, 'Return of bowel function after surgery: bowel sounds (peristalsis resuming), passing flatus, and bowel movement. Absence of distension and patient hunger are positive signs but not definitive indicators of bowel function. Advancing diet without bowel function risks ileus.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is completing a post-operative assessment on a patient following abdominal surgery. Which findings indicate a return of bowel function? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient with obsessive-compulsive disorder (OCD) spends 3 hours per day washing their hands. The nurse''s initial therapeutic approach should be:', '[{"id":"a","text":"Prevent the patient from engaging in hand washing during therapy sessions"},{"id":"b","text":"Discuss the underlying anxiety driving the compulsion and set small limits over time"},{"id":"c","text":"Tell the patient the hand washing is unnecessary and irrational"},{"id":"d","text":"Encourage the patient to substitute a less harmful compulsion"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'For OCD, the nurse acknowledges the anxiety driving the compulsion and works collaboratively to gradually limit compulsive behaviors (exposure and response prevention is the gold standard). Abruptly preventing compulsions causes extreme anxiety and damages the therapeutic relationship. Never tell the patient their fears are irrational.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient with obsessive-compulsive disorder (OCD) spends 3 hours per day washing their hands. The nurse''s initial therapeutic approach should be:');
