-- Safe seed Yingoh NCLEX question bank, part 18.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Nutrition', 'mcq', 'Which instruction is appropriate for a client with dysphagia?', '[{"id":"a","text":"Use thin liquids freely"},{"id":"b","text":"Sit upright during meals"},{"id":"c","text":"Tilt the head back to swallow"},{"id":"d","text":"Eat quickly before tiring"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Upright positioning reduces aspiration risk. Thickened liquids, slow pacing, and chin-tuck may be used depending on swallow evaluation.', 'Dysphagia safety = upright, slow, small bites, prescribed texture.', 'Safe and Effective Care Environment', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'Which instruction is appropriate for a client with dysphagia?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Integumentary', 'mcq', 'Which pressure injury finding should the nurse stage as stage 2?', '[{"id":"a","text":"Intact purple area over the heel"},{"id":"b","text":"Full-thickness tissue loss with bone visible"},{"id":"c","text":"Partial-thickness skin loss with a shallow open blister"},{"id":"d","text":"Nonblanchable intact redness"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Stage 2 pressure injury involves partial-thickness skin loss, often appearing as a shallow open ulcer or blister.', 'Stage 1 intact red; Stage 2 partial skin loss/blister; Stage 4 bone/tendon.', 'Physiological Integrity', 'Analyze Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'Which pressure injury finding should the nurse stage as stage 2?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Integumentary', 'mcq', 'A client has a new burn injury. Which assessment is the nurse''s priority?', '[{"id":"a","text":"Airway patency"},{"id":"b","text":"Body image concerns"},{"id":"c","text":"Long-term scar care"},{"id":"d","text":"Diet preferences"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Airway injury is the immediate life threat after burns, especially with facial burns, smoke exposure, or enclosed-space fire.', 'Burn priority: airway first, then fluids, then wound care.', 'Physiological Integrity', 'Prioritize Hypotheses', 'published'
where not exists (select 1 from public.questions where prompt = 'A client has a new burn injury. Which assessment is the nurse''s priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Immune System', 'mcq', 'Which finding suggests anaphylaxis after antibiotic administration?', '[{"id":"a","text":"Wheezing and swelling of the lips"},{"id":"b","text":"Mild nausea only"},{"id":"c","text":"Dry mouth"},{"id":"d","text":"Temporary headache"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Wheezing and lip/tongue swelling indicate airway involvement and systemic allergic reaction requiring emergency treatment.', 'Allergy becomes anaphylaxis when airway, breathing, or circulation is involved.', 'Physiological Integrity', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'Which finding suggests anaphylaxis after antibiotic administration?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Immune System', 'mcq', 'A client with HIV has a CD4 count of 180 cells/mm3. Which teaching is most important?', '[{"id":"a","text":"Report fever or new cough promptly"},{"id":"b","text":"Stop antiretroviral therapy when feeling better"},{"id":"c","text":"Avoid all exercise"},{"id":"d","text":"Share razors only with family"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'A CD4 count below 200 increases risk for opportunistic infections. Fever or respiratory symptoms need prompt evaluation.', 'CD4 under 200 = high infection risk. Infection symptoms matter fast.', 'Health Promotion and Maintenance', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with HIV has a CD4 count of 180 cells/mm3. Which teaching is most important?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Eye and Ear', 'mcq', 'Which instruction is most important after cataract surgery?', '[{"id":"a","text":"Avoid bending at the waist"},{"id":"b","text":"Rub the eye if it itches"},{"id":"c","text":"Sleep on the operative side"},{"id":"d","text":"Lift heavy objects to resume activity"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Bending, rubbing, heavy lifting, and pressure on the operative eye can increase intraocular pressure and disrupt healing.', 'Eye surgery teaching: protect the eye and avoid pressure increases.', 'Safe and Effective Care Environment', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'Which instruction is most important after cataract surgery?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Eye and Ear', 'mcq', 'A client reports sudden painless vision loss described as a curtain coming down. Which problem is suspected?', '[{"id":"a","text":"Retinal detachment"},{"id":"b","text":"Conjunctivitis"},{"id":"c","text":"Otitis media"},{"id":"d","text":"Cataract"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Retinal detachment may present with sudden painless vision loss, flashes, floaters, or a curtain-like shadow.', 'Curtain over vision = retina emergency.', 'Physiological Integrity', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'A client reports sudden painless vision loss described as a curtain coming down. Which problem is suspected?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Musculoskeletal', 'mcq', 'Which finding after total hip arthroplasty requires immediate action?', '[{"id":"a","text":"Leg internally rotated and shortened"},{"id":"b","text":"Pain rated 4/10 with movement"},{"id":"c","text":"Mild swelling near incision"},{"id":"d","text":"Use of abduction pillow"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Internal rotation and shortening suggest hip prosthesis dislocation. This requires immediate provider notification and immobilization.', 'After hip replacement, shortening plus rotation equals dislocation.', 'Physiological Integrity', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'Which finding after total hip arthroplasty requires immediate action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Musculoskeletal', 'mcq', 'A client with osteoporosis asks how to reduce fracture risk. Which instruction is best?', '[{"id":"a","text":"Perform weight-bearing exercise as tolerated"},{"id":"b","text":"Avoid calcium foods"},{"id":"c","text":"Stay in bed to prevent falls"},{"id":"d","text":"Take extra sedatives at night"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Weight-bearing exercise, calcium/vitamin D, fall prevention, and medication adherence reduce fracture risk.', 'Osteoporosis prevention is load the bones safely and prevent falls.', 'Health Promotion and Maintenance', 'Generate Solutions', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with osteoporosis asks how to reduce fracture risk. Which instruction is best?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medication Administration', 'mcq', 'Before administering an IV push opioid, which assessment is priority?', '[{"id":"a","text":"Respiratory rate"},{"id":"b","text":"Hair color"},{"id":"c","text":"Last bowel movement only"},{"id":"d","text":"Diet preference"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Opioids can depress respirations. Respiratory rate and sedation level must be assessed before administration.', 'Opioid safety: pain score matters, but breathing comes first.', 'Safe and Effective Care Environment', 'Recognize Cues', 'published'
where not exists (select 1 from public.questions where prompt = 'Before administering an IV push opioid, which assessment is priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medication Administration', 'mcq', 'Which action follows the three checks of medication administration?', '[{"id":"a","text":"Check medication label against MAR when removing, preparing, and at bedside"},{"id":"b","text":"Check only after giving"},{"id":"c","text":"Ask another client to confirm"},{"id":"d","text":"Skip checks for familiar medications"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'The medication label is checked against the MAR when retrieving, preparing, and before administration to reduce errors.', 'Three checks are built to catch errors before the medication reaches the client.', 'Safe and Effective Care Environment', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'Which action follows the three checks of medication administration?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Perioperative Care', 'mcq', 'A postoperative client has stridor and restlessness after neck surgery. What is the priority action?', '[{"id":"a","text":"Assess airway and call for help"},{"id":"b","text":"Offer ice chips"},{"id":"c","text":"Encourage ambulation"},{"id":"d","text":"Place in Trendelenburg position"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Stridor indicates airway obstruction and is an emergency. Airway assessment and rapid help are priorities.', 'Stridor is airway narrowing. Treat it as an emergency every time.', 'Physiological Integrity', 'Prioritize Hypotheses', 'published'
where not exists (select 1 from public.questions where prompt = 'A postoperative client has stridor and restlessness after neck surgery. What is the priority action?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Perioperative Care', 'mcq', 'Which instruction helps prevent postoperative atelectasis?', '[{"id":"a","text":"Use incentive spirometer regularly"},{"id":"b","text":"Avoid coughing completely"},{"id":"c","text":"Remain flat in bed"},{"id":"d","text":"Limit turning for 48 hours"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Incentive spirometry, coughing, deep breathing, turning, and early ambulation help re-expand alveoli and prevent atelectasis.', 'Post-op lungs need expansion: cough, deep breathe, incentive spirometer, move.', 'Physiological Integrity', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'Which instruction helps prevent postoperative atelectasis?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Complex Care', 'mcq', 'A client with suspected sepsis has BP 84/48, temp 39.4 C, HR 128, and lactate 5.2. Which action is priority?', '[{"id":"a","text":"Begin ordered fluid resuscitation"},{"id":"b","text":"Delay antibiotics until fever resolves"},{"id":"c","text":"Place on a regular diet"},{"id":"d","text":"Limit vital signs to once daily"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Hypotension and elevated lactate indicate poor tissue perfusion in sepsis. Fluid resuscitation and rapid sepsis protocol care are priorities.', 'Sepsis priority is perfusion: fluids, cultures/antibiotics per protocol, lactate trends.', 'Physiological Integrity', 'Take Action', 'published'
where not exists (select 1 from public.questions where prompt = 'A client with suspected sepsis has BP 84/48, temp 39.4 C, HR 128, and lactate 5.2. Which action is priority?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Complex Care', 'mcq', 'Which client should the emergency nurse see first?', '[{"id":"a","text":"Client with chest pain and diaphoresis"},{"id":"b","text":"Client with ankle sprain and swelling"},{"id":"c","text":"Client requesting a work note"},{"id":"d","text":"Client with mild sore throat for 3 days"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Chest pain with diaphoresis suggests possible acute coronary syndrome and takes priority over stable, non-life-threatening concerns.', 'Triage asks: who may die soon? Chest pain plus diaphoresis wins.', 'Safe and Effective Care Environment', 'Prioritize Hypotheses', 'published'
where not exists (select 1 from public.questions where prompt = 'Which client should the emergency nurse see first?');
