-- Batch 08: 168 drafts focused on laboratory and diagnostic safety.
select public.seed_structured_concept('expansion-batch-08','critical-potassium','Laboratory and Diagnostics','a critical potassium result','potassium 6.9 mEq/L with peaked T waves','Place on cardiac monitoring, verify the result appropriately, and begin prescribed emergency treatment','Avoid potassium supplements and salt substitutes unless prescribed and keep repeat laboratory appointments','Widening QRS complexes with bradycardia','File the result for routine rounds','Give potassium chloride IV push','Encourage a high-potassium snack','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','critical-sodium','Laboratory and Diagnostics','severe hyponatremia','sodium 116 mEq/L with headache and confusion','Institute seizure precautions, assess volume status, and begin carefully prescribed correction','Follow fluid and medicine instructions and report worsening headache, vomiting, or confusion','A generalized seizure during sodium correction','Encourage unrestricted free water','Correct sodium rapidly without monitoring','Leave the confused client unattended','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','critical-calcium','Laboratory and Diagnostics','symptomatic hypocalcemia','perioral tingling, tetany, prolonged QT, and calcium 6.8 mg/dL','Apply seizure and cardiac precautions and administer prescribed calcium replacement','Take calcium and vitamin D as directed and report cramping, tingling, or spasms','Laryngospasm with stridor','Give phosphate supplements','Encourage hyperventilation','Delay ECG monitoring','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','critical-magnesium','Laboratory and Diagnostics','severe hypermagnesemia','weakness, absent reflexes, hypotension, and slow respirations','Stop magnesium sources, support ventilation, and give prescribed calcium and elimination therapy','Avoid magnesium laxatives with kidney disease unless approved','Respirations 7/min with heart block','Give additional magnesium','Encourage unassisted walking','Wait for cardiac arrest before escalation','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','critical-glucose','Laboratory and Diagnostics','critical hypoglycemia','glucose 38 mg/dL with diaphoresis and confusion','Give rapid glucose based on swallowing ability and recheck promptly','Carry fast carbohydrate and review medicine, meals, and activity after an episode','Seizure with inability to swallow','Give long-acting insulin','Use only a high-fat meal','Allow driving before recheck','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','elevated-lactate','Laboratory and Diagnostics','rising serum lactate','suspected infection with lactate 5.2 mmol/L and hypotension','Assess perfusion, activate sepsis treatment, and trend lactate with clinical response','Seek urgent care for infection with confusion, mottling, breathlessness, or very low urine','Lactate continues rising despite resuscitation','Treat the number without reassessing the client','Delay antibiotics for final cultures','Give unmonitored hypotonic fluid','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','troponin-rise','Laboratory and Diagnostics','an acute troponin rise','ischemic chest discomfort with a rising serial troponin','Continue acute coronary assessment and treatment using symptoms, ECG, and serial values','Call emergency services for persistent chest pressure, sweating, nausea, or breathlessness','Recurrent pain with new ST elevation and ventricular dysrhythmia','Dismiss the result because one value was normal','Encourage exercise testing during active pain','Delay ECG acquisition','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','inr-critical','Laboratory and Diagnostics','a critically elevated INR','warfarin use with INR 7.1 and hematuria','Hold warfarin as prescribed, assess bleeding, and prepare reversal based on severity','Keep vitamin K intake consistent and report bleeding, severe headache, or black stool','Sudden severe headache with unilateral weakness','Give an IM injection','Administer aspirin for discomfort','Double the next warfarin dose','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','platelet-critical','Laboratory and Diagnostics','severe thrombocytopenia','platelets 9,000/mm3 with petechiae and oral bleeding','Institute bleeding precautions and notify the provider urgently','Use a soft toothbrush and electric razor and avoid injury and unapproved NSAIDs','New neurologic change with severe headache','Use rectal temperatures','Give intramuscular injections','Floss bleeding gums vigorously','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','anc-critical','Laboratory and Diagnostics','profound neutropenia','absolute neutrophil count 200/mm3 after chemotherapy','Treat fever as an emergency and use protective infection-prevention measures','Check temperature and report 100.4°F (38°C) or higher immediately','Fever with hypotension and shaking chills','Use rectal suppositories','Keep fresh flowers at bedside','Delay cultures and antibiotics','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','hemoglobin-critical','Laboratory and Diagnostics','severe symptomatic anemia','hemoglobin 5.8 g/dL with dyspnea, tachycardia, and chest pressure','Support oxygenation, assess bleeding, and prepare prescribed transfusion or treatment','Report bleeding, faintness, chest discomfort, or worsening breathlessness','Ischemic chest pain with hypotension','Encourage strenuous ambulation','Delay type and screen','Give large IM injections','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','creatinine-rise','Laboratory and Diagnostics','rapidly rising creatinine','creatinine doubles with oliguria after nephrotoxin exposure','Stop or review nephrotoxins, assess volume and obstruction, and monitor urgent electrolytes','Avoid unapproved NSAIDs and report reduced urine, swelling, or breathlessness','Oliguria with potassium 6.5 mEq/L and pulmonary edema','Give contrast again without review','Encourage potassium supplements','Ignore fluid accumulation','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','ammonia-elevated','Laboratory and Diagnostics','hepatic encephalopathy','cirrhosis with confusion, asterixis, and elevated ammonia','Assess airway and triggers and give prescribed lactulose and other therapy','Use lactulose to the prescribed stool target and report confusion or bleeding','Increasing somnolence with inability to protect the airway','Give a sedative for restlessness','Stop bowel therapy after one stool','Provide alcohol','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','lipase-elevated','Laboratory and Diagnostics','acute pancreatitis','severe epigastric pain radiating to the back with elevated lipase','Provide prescribed bowel rest, fluids, analgesia, and organ monitoring','Avoid alcohol and report recurrent severe pain, vomiting, fever, or jaundice','Hypotension with respiratory distress and oliguria','Offer a fatty meal','Delay fluid support','Place flat after eating','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','serum-osmolality','Laboratory and Diagnostics','hyperosmolar dehydration','very high serum osmolality, profound dehydration, hyperglycemia, and neurologic change','Begin controlled isotonic fluid replacement and monitor glucose and electrolytes','Maintain hydration and follow sick-day glucose guidance','Seizure with worsening hypotension during treatment','Correct sodium and glucose instantly','Restrict fluid','Give potassium before urine output is known','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','blood-culture','Laboratory and Diagnostics','blood-culture collection for sepsis','cultures are ordered before urgent antimicrobial therapy','Collect the prescribed sets aseptically from appropriate sites without materially delaying antibiotics','Cultures should be obtained before antibiotics when feasible, but lifesaving treatment must not be postponed','Antibiotics are delayed for hours while repeated collection attempts continue','Draw all bottles from one contaminated line without indication','Touch cleansed stoppers','Refrigerate specimens without instruction','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','urine-culture','Laboratory and Diagnostics','urine-culture collection','a catheterized client has new fever and urinary symptoms','Obtain an aseptic sample from the sampling port after appropriate preparation','A clean specimen prevents contamination; never collect culture from the drainage bag','Culture is collected from old stagnant bag urine','Disconnect the closed system','Pour urine from the bag into a cup','Collect after antibiotics whenever avoidable','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','abg-sampling','Laboratory and Diagnostics','arterial blood-gas sampling','an ABG is needed from a client receiving oxygen','Document oxygen settings, use proper arterial technique, expel air, and transport promptly','Hold firm pressure longer when bleeding risk is increased and report hand numbness or pallor','The hand becomes pale, cool, and pulseless after radial puncture','Leave air bubbles in the syringe','Change oxygen immediately before sampling without documentation','Apply inadequate pressure during anticoagulation','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','qt-prolongation','Laboratory and Diagnostics','marked QT prolongation','QTc 540 ms in a client taking several QT-prolonging medicines','Review offending medicines, correct potassium and magnesium, and maintain rhythm monitoring','Report palpitations, fainting, or seizure and check before adding interacting medicines','Polymorphic ventricular tachycardia with syncope','Give another QT-prolonging dose','Ignore low potassium','Remove cardiac monitoring','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','mri-metal','Laboratory and Diagnostics','MRI safety screening','a client with implanted hardware is scheduled for MRI','Verify the exact device and MRI conditions and remove unsafe metal before entering the controlled area','Report every implant, fragment, patch, pump, and device before scanning','An unknown aneurysm clip is taken into the magnet room','Assume all modern implants are safe','Bring an oxygen cylinder into the magnet room','Hide a retained metal fragment','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','ct-contrast-reaction','Laboratory and Diagnostics','an immediate iodinated-contrast reaction','urticaria, wheezing, and hypotension develop during injection','Stop contrast, activate emergency response, and treat airway and anaphylaxis promptly','Report previous contrast reactions and asthma and seek help for breathing or facial swelling','Progressive stridor with shock','Continue injection to finish imaging','Give oral fluids to an unstable client','Leave the client alone','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','tee-recovery','Laboratory and Diagnostics','recovery after transesophageal echocardiography','a sedated client has topical pharyngeal anesthesia','Monitor airway and sedation and keep NPO until protective reflexes return','Do not eat or drink until throat sensation and swallowing return','Stridor, hematemesis, or severe chest pain','Offer hot coffee immediately','Allow unassisted walking while sedated','Ignore difficulty swallowing','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','bone-marrow-biopsy','Laboratory and Diagnostics','complications after bone-marrow biopsy','a thrombocytopenic client returns after iliac-crest sampling','Apply pressure, monitor the site and vital signs, and follow bleeding precautions','Keep the dressing dry as directed and report persistent bleeding, fever, or increasing pain','Uncontrolled site bleeding with hypotension','Massage the puncture site','Take aspirin for pain','Remove the dressing immediately','Reduction of Risk Potential');
select public.seed_structured_concept('expansion-batch-08','d-dimer-context','Laboratory and Diagnostics','interpretation of an elevated D-dimer','a postoperative client has unilateral swelling and dyspnea','Treat the client’s symptoms urgently and obtain definitive imaging rather than diagnosing from D-dimer alone','D-dimer can be elevated for many reasons and does not by itself confirm a clot','Severe hypoxemia and hypotension while imaging is deferred because the result is nonspecific','Use D-dimer as a stand-alone diagnosis','Massage the swollen leg','Encourage walking before evaluation','Reduction of Risk Potential');

-- Retained for subsequent held batches.
