-- Safe seed Yingoh NCLEX question bank, part 1.
-- Run the whole file. Each question is inserted independently and skipped if its prompt already exists.

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is administering metformin to a patient with type 2 diabetes. Which laboratory finding should the nurse report to the provider immediately before giving this medication?', '[{"id":"a","text":"Blood glucose of 180 mg/dL"},{"id":"b","text":"Serum creatinine of 2.8 mg/dL"},{"id":"c","text":"HbA1c of 7.2%"},{"id":"d","text":"Blood pressure of 130/82 mmHg"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Metformin is contraindicated with significant renal impairment (creatinine >1.4 mg/dL in women, >1.5 in men) due to the risk of lactic acidosis. A creatinine of 2.8 mg/dL requires holding the medication and notifying the provider.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is administering metformin to a patient with type 2 diabetes. Which laboratory finding should the nurse report to the provider immediately before giving this medication?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'sata', 'A nurse is caring for a patient with Clostridioides difficile (C. diff) colitis. Which actions are appropriate? (Select all that apply)', '[{"id":"a","text":"Wear gloves when entering the room"},{"id":"b","text":"Use alcohol-based hand rub after removing gloves"},{"id":"c","text":"Wear a gown when entering the room"},{"id":"d","text":"Wash hands with soap and water"},{"id":"e","text":"Place patient in a negative pressure room"},{"id":"f","text":"Wear an N95 respirator"}]'::jsonb, '{"ids":["a","c","d"]}'::jsonb, 'C. diff requires contact precautions: gown and gloves. Alcohol-based hand rubs do NOT kill C. diff spores — soap and water is required. Negative pressure rooms and N95s are for airborne precautions, not C. diff.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with Clostridioides difficile (C. diff) colitis. Which actions are appropriate? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'mcq', 'A nurse calculates an APGAR score at 5 minutes. The newborn has HR 110/min, slow irregular respirations, some extremity flexion, grimace to stimulation, and acrocyanosis. What is the APGAR score?', '[{"id":"a","text":"4"},{"id":"b","text":"5"},{"id":"c","text":"6"},{"id":"d","text":"7"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'HR >100 = 2, Respiratory slow/irregular = 1, Muscle tone some flexion = 1, Reflex grimace = 1, Color acrocyanosis = 0. Total = 5. Scores 4–6 indicate moderate depression requiring stimulation.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse calculates an APGAR score at 5 minutes. The newborn has HR 110/min, slow irregular respirations, some extremity flexion, grimace to stimulation, and acrocyanosis. What is the APGAR score?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'sata', 'A nurse assesses a patient 12 hours post-abdominal surgery: T 38.9°C, HR 102, BP 118/76, SpO2 95%, urine output 20 mL over 2 hours. Which findings require immediate intervention? (Select all that apply)', '[{"id":"a","text":"Temperature 38.9°C"},{"id":"b","text":"Heart rate 102"},{"id":"c","text":"Urine output 20 mL over 2 hours"},{"id":"d","text":"SpO2 95%"},{"id":"e","text":"Respiratory rate 22"},{"id":"f","text":"Blood pressure 118/76"}]'::jsonb, '{"ids":["a","c"]}'::jsonb, 'Post-op day 0–1 fever (atelectasis) requires incentive spirometry and deep breathing. Urine output 20 mL/2 hr = 10 mL/hr — below the 30 mL/hr minimum, indicating oliguria. Other values are acceptable post-operatively.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse assesses a patient 12 hours post-abdominal surgery: T 38.9°C, HR 102, BP 118/76, SpO2 95%, urine output 20 mL over 2 hours. Which findings require immediate intervention? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is preparing to administer digoxin. Which finding should cause the nurse to withhold the medication and contact the provider?', '[{"id":"a","text":"Apical pulse of 56 beats per minute"},{"id":"b","text":"Blood pressure of 118/72 mmHg"},{"id":"c","text":"Serum potassium of 4.1 mEq/L"},{"id":"d","text":"Serum digoxin level of 0.8 ng/mL"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Withhold digoxin if apical pulse <60 bpm and notify the provider. Digoxin is a negative chronotrope; giving it with a rate of 56 could cause dangerous bradycardia or heart block.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preparing to administer digoxin. Which finding should cause the nurse to withhold the medication and contact the provider?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A nurse is caring for a patient with diabetic ketoacidosis (DKA). Which clinical findings are consistent with this diagnosis? (Select all that apply)', '[{"id":"a","text":"Kussmaul respirations"},{"id":"b","text":"Blood glucose 520 mg/dL"},{"id":"c","text":"Fruity breath odor"},{"id":"d","text":"Bradycardia"},{"id":"e","text":"Polyuria and polydipsia"},{"id":"f","text":"Diaphoresis and pallor"}]'::jsonb, '{"ids":["a","b","c","e"]}'::jsonb, 'DKA: Kussmaul respirations (compensation for metabolic acidosis), hyperglycemia >250 mg/dL, fruity/acetone breath (ketones), polyuria and polydipsia. Bradycardia and diaphoresis/pallor are not DKA findings.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is caring for a patient with diabetic ketoacidosis (DKA). Which clinical findings are consistent with this diagnosis? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Mental Health', 'mcq', 'A patient is prescribed lithium carbonate for bipolar disorder. Which serum level indicates toxicity requiring immediate intervention?', '[{"id":"a","text":"0.6 mEq/L"},{"id":"b","text":"0.9 mEq/L"},{"id":"c","text":"1.2 mEq/L"},{"id":"d","text":"2.1 mEq/L"}]'::jsonb, '{"ids":["d"]}'::jsonb, 'Therapeutic lithium range is 0.6–1.2 mEq/L. Levels >1.5 indicate toxicity; >2.0 is severe toxicity requiring emergency treatment including IV fluids and possible hemodialysis.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient is prescribed lithium carbonate for bipolar disorder. Which serum level indicates toxicity requiring immediate intervention?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pediatrics', 'mcq', 'A nurse is assessing an 18-month-old child. Which developmental milestone should the nurse expect?', '[{"id":"a","text":"Speaking in 4–5 word sentences"},{"id":"b","text":"Walking up stairs with alternating feet"},{"id":"c","text":"Using a spoon and cup with some spilling"},{"id":"d","text":"Drawing a circle"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'At 18 months, toddlers use a spoon and cup with some spilling. Four-to-five word sentences, stair-climbing with alternating feet, and drawing circles are ~3-year milestones.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is assessing an 18-month-old child. Which developmental milestone should the nurse expect?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'sata', 'A nurse teaches a patient prescribed warfarin. Which foods should be eaten in consistent amounts because they may decrease warfarin effectiveness? (Select all that apply)', '[{"id":"a","text":"Spinach"},{"id":"b","text":"Kale"},{"id":"c","text":"Grapefruit"},{"id":"d","text":"Broccoli"},{"id":"e","text":"Bananas"},{"id":"f","text":"Brussels sprouts"}]'::jsonb, '{"ids":["a","b","d","f"]}'::jsonb, 'Vitamin K antagonizes warfarin. High vitamin K foods include spinach, kale, broccoli, and Brussels sprouts. Patients should eat these consistently, not avoid them, to maintain stable INR.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse teaches a patient prescribed warfarin. Which foods should be eaten in consistent amounts because they may decrease warfarin effectiveness? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Pharmacology', 'mcq', 'A nurse is administering morphine sulfate IV post-operatively. Which equipment must be at the bedside before administering?', '[{"id":"a","text":"Blood pressure cuff and stethoscope"},{"id":"b","text":"Naloxone and resuscitation equipment"},{"id":"c","text":"Blood glucose monitor"},{"id":"d","text":"IV calcium gluconate"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Before administering opioids, naloxone (Narcan) and resuscitation equipment must be at bedside. Opioids can cause respiratory depression; naloxone is the required antidote.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is administering morphine sulfate IV post-operatively. Which equipment must be at the bedside before administering?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Safety and Infection Control', 'mcq', 'A nurse is preparing to administer blood. Which action is the priority to prevent a transfusion reaction?', '[{"id":"a","text":"Prime IV tubing with normal saline"},{"id":"b","text":"Verify the blood product with another nurse at the bedside"},{"id":"c","text":"Check vital signs 15 minutes after starting"},{"id":"d","text":"Obtain IV access with an 18-gauge catheter"}]'::jsonb, '{"ids":["b"]}'::jsonb, 'Two licensed nurses must verify blood type, unit number, expiration date, and patient ID at bedside before transfusion. This is the priority action to prevent hemolytic transfusion reactions.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse is preparing to administer blood. Which action is the priority to prevent a transfusion reaction?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Medical-Surgical', 'mcq', 'A patient has a serum potassium of 2.8 mEq/L. Which assessment finding is most consistent with this result?', '[{"id":"a","text":"Muscle weakness and leg cramps"},{"id":"b","text":"Peaked T waves on ECG"},{"id":"c","text":"Bradycardia"},{"id":"d","text":"Paresthesias of the face"}]'::jsonb, '{"ids":["a"]}'::jsonb, 'Hypokalemia (<3.5 mEq/L) causes muscle weakness, cramps, and fatigue. Peaked T waves and bradycardia are hyperkalemia signs. Facial paresthesias are associated with hypocalcemia.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A patient has a serum potassium of 2.8 mEq/L. Which assessment finding is most consistent with this result?');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'NGN Case Studies', 'sata', 'A nurse reviews orders for a patient with acute heart failure. Which orders should be clarified before implementing? (Select all that apply)', '[{"id":"a","text":"0.9% NaCl 500 mL IV bolus over 1 hour"},{"id":"b","text":"Furosemide 40 mg IV push"},{"id":"c","text":"Restrict fluids to 1500 mL/day"},{"id":"d","text":"Morphine sulfate 2 mg IV PRN for air hunger"},{"id":"e","text":"High sodium diet"},{"id":"f","text":"Daily weights"}]'::jsonb, '{"ids":["a","e"]}'::jsonb, 'IV saline bolus worsens fluid overload and pulmonary edema in acute HF. A high sodium diet exacerbates fluid retention. Furosemide, fluid restriction, morphine for dyspnea, and daily weights are all appropriate HF interventions.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse reviews orders for a patient with acute heart failure. Which orders should be clarified before implementing? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Maternal and Newborn', 'sata', 'A nurse assesses a patient in active labor. Which findings require immediate intervention? (Select all that apply)', '[{"id":"a","text":"Fetal heart rate of 90 bpm for 3 minutes"},{"id":"b","text":"Contractions every 3–4 minutes lasting 50 seconds"},{"id":"c","text":"Late decelerations on the fetal monitor"},{"id":"d","text":"Maternal blood pressure of 158/106 mmHg"},{"id":"e","text":"Cervical dilation of 7 cm"},{"id":"f","text":"Clear amniotic fluid"}]'::jsonb, '{"ids":["a","c","d"]}'::jsonb, 'Fetal bradycardia <110 bpm for >3 min requires repositioning, O2, and provider notification. Late decelerations indicate uteroplacental insufficiency. BP 158/106 meets severe hypertension in pregnancy criteria — magnesium sulfate and provider notification required.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A nurse assesses a patient in active labor. Which findings require immediate intervention? (Select all that apply)');

insert into public.questions (topic, question_type, prompt, choices, correct_answer, rationale, strategy, client_need, clinical_judgment, status)
select 'Leadership and Management', 'mcq', 'A charge nurse is making shift assignments. Which patient should be assigned to the most experienced RN?', '[{"id":"a","text":"Patient with COPD requiring chest physiotherapy"},{"id":"b","text":"Patient with new colostomy requiring discharge teaching"},{"id":"c","text":"Patient with septic shock receiving vasopressors"},{"id":"d","text":"Patient with type 2 diabetes preparing for discharge"}]'::jsonb, '{"ids":["c"]}'::jsonb, 'Match patient acuity to nurse competency. Septic shock with vasopressors requires complex hemodynamic monitoring, medication titration, and critical thinking — the most demanding assignment.', '', '', '', 'published'
where not exists (select 1 from public.questions where prompt = 'A charge nurse is making shift assignments. Which patient should be assigned to the most experienced RN?');
